### PR TITLE
tox formatting for python files in `format.sh`

### PR DESCRIPTION
**Pull request by navin772**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

It would be contributor friendly if we can have python formatting in `./scripts/format.sh`.
Currently due to lack of formatting support from `rules_python`, bazel targets were not configurable (Added it as a TODO)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Added Python formatting capabilities to the `format.sh` script using `tox`.
- Installed `tox` and configured it to use the `linting` environment.
- This change aims to improve code consistency and maintainability by applying standard Python formatting tools like `isort`, `black`, `flake8`, and `docformatter`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>format.sh</strong><dd><code>Add Python formatting using tox in format.sh script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

scripts/format.sh

<li>Added a new section for Python formatting.<br> <li> Installed <code>tox</code> and set <code>TOXENV</code> to <code>linting</code>.<br> <li> Executed <code>tox</code> with configuration from <code>py/tox.ini</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14497/files#diff-3a9054a1963ff6cd07b6054d4feecbb4a17b3e4fe87ac71aeb2db3f2524552fb">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This seems to not work on the CI. Can you look into it?

**Comment by navin772** [comment]
I will take a look, from the CI logs it seems like selenium py package failed to build.

For now, I will convert this to draft.

**Comment by navin772** [comment]
@AutomatedTester I have updated the PR, can you please trigger the CI?

**Comment by navin772** [comment]
The RBE test failures are unrelated to the changes.

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
