### PR TITLE
[java] Add updated timeout to ensure correct error message

### LINKED ISSUE #10033: [🐛 Bug]: misleading log message
### What happened?

There is a misleading log message. See steps to reproduce, below.

### How can we reproduce the issue?

I have the following script:

```java
long start = System.currentTimeMillis();
driver.manage().timeouts().scriptTimeout(Duration.ofMillis(10000));
// this will obviously time out!
driver.executeAsyncScript("window.setTimeout(arguments[arguments.length - 1], 20000);");
log.info("Elapsed time: " + (System.currentTimeMillis() - start));
```

### Relevant log output

The above script produces **expected** org.openqa.selenium.ScriptTimeoutException. This is followed by the message:

```shell
Command: [f634c328f5ee0db65e63f424e23f7ef2, executeAsyncScript {script=window.setTimeout(arguments[arguments.length - 1], 20000);, args=[]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 95.0.4638.69, chrome: {chromedriverVersion: 95.0.4638.17 (a9d0719444d4b..., userDataDir: /tmp/.com.google.Chrome.ejxyR3}, goog:chromeOptions: {debuggerAddress: localhost:46805}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:46805/devtoo..., se:cdpVersion: 95.0.4638.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

My question (bug) is specifically about the "timeouts: {script: 30000}" part above. I am expecting to see "script: 10000" in my case.

### Operating System

all

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

all?

### What are the browser driver(s) and version(s) where you see this issue?

all?

### Are you using Selenium Grid?

n/a

### PR DESCRIPTION
**Pull request by pujagani**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add updated timeout to ensure correct error message

### Motivation and Context

Fixes #10033

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
I am not sure if this is the best approach for now. Could I have some time to review this first, please?

**Comment by pujagani** [comment]
> I am not sure if this is the best approach for now. Could I have some time to review this first, please?

I had the same thought, I was not sure either because a few webdriver implementations override `getCapabilities` and few don't. I am definitely missing some context around that. Hence created the PR. This is not an urgent/blocking fix. Have a look as time permits. Thank you!

**Comment by titusfortner** [comment]
Nice work on a solution, but I think we should consider Capabilities immutable.

Capabilities are to negotiate what kind of session gets started. While timeouts can be changed (and are the only capabilities that can be changed), it doesn't change what was negotiated.

Plus the bindings all have getters for the timeouts now if someone needs to query the current state.

**Comment by pujagani** [comment]
Thank you for the explanation. The context is clear now. Closing the pull request. https://github.com/SeleniumHQ/selenium/issues/10033#issuecomment-1001113555

**Pull request closed without merging**
