### PR TITLE
Refactor/sole master directory

### PR DESCRIPTION
**Pull request by luke-hill**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

- Make the sole arbiter `rake_tasks`
- Fix up some minor punctuation

EDIT: I've opted to tidy up the `.rake` files because they were a proper mish-mash. And future PR's will attempt to try unclog these files even further.

It's likely that even though we're moving all the rakes into the one mega `Rakefile` we can unclog it later, but this is a necessary evil for now to fix the `rake_tasks` directory

### CODE REVIEW

**Comment by barancev** [comment]
Can you please rebase it, I've changed rakelib/bazel.rake to fix a Windows-specific issue

**Comment by luke-hill** [comment]
This is rebased and I've done an initial "guess" fix (Maybe the failure was caused by it being massively outdated :man_shrugging: )

My new fixes are to add a temporary second require for all the rake files. However I could not find where they were initially loaded in to memory.

Also calling them `.rake` instead of `.rb` makes them a bit harder to triage. However that might be a bigger change I do later on.

For now we've got the single proper source of truth directory. The next job is to start cleansing more code and namespacing things more.

Next stop after this will be some of the crazy fun code, which is in mega-files. So I'll probably just try breaking those out.

**Comment by luke-hill** [comment]
Ping
Ruby Review: @p0deje 
JVM Issue / Approval: @barancev

**Comment by barancev** [comment]
@luke-hill What JVM issue?

**Comment by luke-hill** [comment]
@p0deje this now begins to start unclogging stuff and putting them in more folder based structures.

I've fixed the conflicts, and the JVM issue from previously was fixed in another branch. So this should pass.

The GCC area has a lot of tabbed fixes, so apologies for that.

**Comment by barancev** [comment]
LGTM, merged as fd1fabe5746b60a7c62aa63ba1f3e2838d368f01

**Pull request closed without merging**
