### PR TITLE
Updates the py api doc build

### PR DESCRIPTION
**Pull request by emanlove**
### Description
These changes regenerate the api stub files - those template files which give the base structure for the api docs - each time instead of using outdated checked in version from previous builds. Essentially we treat these like new builds which need to be regenerated versus updating and storing old build artifacts.

The base API template (py/docs/source/api.rst) has been updated to match current high level python modules which the api doc is built from. Ideally this should be autogenerated itself simply matching the Python codebase. Leaving that for another body of work to do sometime in the future.

Also updated the versions of the documentation tool (sphinx) and template packages (jinja) to more recent version. (Due to using Python 3.8 the latest sphinx version can't be used but this is ok.).

### Motivation and Context
The API changes with each release as it matches the code. So essentially each time a new release comes out a new build of the documentation should be generated.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Updated Sphinx version in `py/docs/requirements.txt` from 1.8.2 to 7.1.2 to support Python 3.8.
- Enhanced `py/docs/source/api.rst` by adding new modules and reordering them alphabetically.
- Modified `py/tox.ini` to use `docs/requirements.txt` for dependencies, added a step to regenerate autodoc stub pages, and set the `PYTHONPATH` environment variable.
- Removed previously generated API doc stub files to ensure they are auto-generated during the build process.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update Sphinx version in documentation requirements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/docs/requirements.txt

- Updated Sphinx version from 1.8.2 to 7.1.2.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14173/files#diff-92834b7f224ddd3ec0dd19af89cb429679ed4a1fea9a0fba6b6a5229355b02d8">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>api.rst</strong><dd><code>Update API documentation structure and modules</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/docs/source/api.rst

<li>Added new modules to the API documentation.<br> <li> Reordered modules alphabetically.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14173/files#diff-7e8f0a6376548281d6c1a5b57121f0a701a76c5f88129fe7def3d89f39b63c43">+36/-14</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tox.ini</strong><dd><code>Update tox configuration for documentation build</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/tox.ini

<li>Updated to use <code>docs/requirements.txt</code> for dependencies.<br> <li> Added command to regenerate autodoc stub pages.<br> <li> Set <code>PYTHONPATH</code> environment variable.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14173/files#diff-27d219400d7f64afbf3d9bceb197e20b299fdd58fb4e84c9b7c2ee7c4e828177">+9/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by emanlove** [comment]
If one wants to easily test or reproduce the steps this is doing, the following commands will setup an virtualenv, grab the latest code and run the doc generation through tox; similar to what the official build does.

```bash
virtualenv test-py38-env
source test-py38-env/bin/activate
pip install tox
git clone git@github.com:emanlove/selenium.git se-api-docs-test
cd se-api-docs-test/
git switch -c py-api-doc-13910 origin/py-api-doc-13910
tox -c py/tox.ini
```

**Comment by titusfortner** [comment]
Oh wow, yeah, this looks great. When looking at the diff I'm seeing several things in the current docs that still reference Selenium 4.17

**Comment by titusfortner** [comment]
@emanlove can you fix the conflict (looks like adding the line from #14171 isn't part of this PR)

**Comment by titusfortner** [comment]
Also can you create another issue for auto-generating the api.rst file so we can track it?

**Comment by emanlove** [comment]
@titusfortner Fixed the conflict. Sorry about that one.

**Review by titusfortner — APPROVED** [review]
I've verified this works and is an improvement on what we have now. Thanks.

**Comment by titusfortner** [comment]
@iampopovich I know you did the work to update the api.rst file here, do you want me to merge your file and rebase this on top of it, or can I just merge this? Also are you in our chat room? (https://www.selenium.dev/support/#ChatRoom) We can discuss more there if you'd like.

**Comment by iampopovich** [comment]
These changes are better than mine. It's fine to use them, no worries. They also include part of my work, so it's all fair 🤝

**Comment by titusfortner** [comment]
Now I just need to see about retroactively generating docs from the 4.22 tag😁

**Pull request merged**
