### PR TITLE
[dotnet] Support GetLog command by Remote Web Driver

### LINKED ISSUE #14545: [🐛 Bug]: Console logs returned as zero using  RemoteDriver (SeleniumGrid) .NET Selenium
### What happened?

This code is not functioning correctly when using RemoteWebDriver with Selenium Grid.

[Test]
public void ConsoleLogsGridRun()
{
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, OpenQA.Selenium.LogLevel.All);
var Driver = new RemoteWebDriver(
new Uri("http://10.0.0.37:8888/"),
new RemoteSessionSettings(options), TimeSpan.FromSeconds(100));
Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

Driver.FindElement(By.Id("consoleLog")).Click();
Driver.FindElement(By.Id("consoleError")).Click();

var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
}

Please advise

### How can we reproduce the issue?

```shell
[Test]
public void ConsoleLogsGridRun()
{
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, OpenQA.Selenium.LogLevel.All);
var Driver = new RemoteWebDriver(
new Uri("http://10.0.0.37:8888/"),
new RemoteSessionSettings(options), TimeSpan.FromSeconds(100));
Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

Driver.FindElement(By.Id("consoleLog")).Click();
Driver.FindElement(By.Id("consoleError")).Click();

var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
}
```

### Relevant log output

```shell
jsErrors returned as null
```

### Operating System

Windows 10

### Selenium version

Selenium Version 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

129.0.6668.71

### Are you using Selenium Grid?

Selenium Grid 4.25.0

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
Now it is possible to `driver.Manage().Logs.GetLog("browser")` where `driver` is remote webdriver.

### Motivation and Context
Fixes #14545 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Added support for the `GetLog` command in the Remote WebDriver, allowing retrieval of logs such as "browser" logs.
- Implemented the `GetAvailableLogTypes` command to fetch available log types.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>W3CWireProtocolCommandInfoRepository.cs</strong><dd><code>Add support for log retrieval commands in Remote WebDriver</code></dd></summary>
<hr>

dotnet/src/webdriver/Remote/W3CWireProtocolCommandInfoRepository.cs

<li>Added support for the <code>GetLog</code> command in the Remote WebDriver.<br> <li> Added support for the <code>GetAvailableLogTypes</code> command.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14549/files#diff-5a0c14b496d71555b1f790082e2841e0a7635be73c3e7055acf08244d8b459cf">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by pujagani — APPROVED** [review]
LGTM. Thank you!

**Comment by pujagani** [comment]
There a bunch of failing tests though I am not sure if they are related to the changes in this PR.

**Comment by nvborisenko** [comment]
Failed tests are not related to this PR. Probably I will be able to look at this later (as separate PR).

**Comment by nvborisenko** [comment]
Tests are failing because of Edge 128 is used, when 129 is expected. https://github.com/SeleniumHQ/selenium/pull/14411 should fix it.

**Comment by sponnusamyneogov** [comment]
Thank you so much!@nvborisenko

**Comment by nvborisenko** [comment]
@sponnusamyneogov, you will be able to test the changes in upcoming nightly build, don't forget to share results.

**Comment by hatemkahil** [comment]
Hi, unfortunately it looks like this change has broken the existing functionality of `driver.Manage().Logs.GetLog("browser")`. 

We were using this for the last 2 years and it was working fine for both our Chrome and Safari (through testingbot.com) tests. After the 4.26 update, we started getting the below exception when we use it on the Safari (through testingbot.com) tests. It's working fine on Chrome.

`System.NotImplementedException: The command 'POST /session/ef0dd34ce41e-3063933af011-5b4c8dca3c44-173394094693-47367542/se/log' was not found.
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Logs.GetLog(String logKind)`

Please let me know if I can provide more info or if we need to change anything to make this work.

Thanks.

**Comment by nvborisenko** [comment]
@hatemkahil you said: "it was working fine for both our Chrome and Safari". It was incorrect, now it is correct. Now it throws exception, instead of returning empty list of log messages. Please submit new issue if you still think it is incorrect.

**Pull request merged**
