### PR TITLE
Added Expected Condition (EC) elements_not_overlapping

### PR DESCRIPTION
**Pull request by shbenzer**
I added a new expected condition called elements_not_overlapping; this should allow for enhanced WebDriverWaits on loading screens, timing element rearrangement, etc. A new pytest called test_expected_condition_elements_not_overlapping was added to support.

### Description
1. Added expected condition elements_not_overlapping
2. Added a pytest called test_expected_condition_elements_not_overlapping to ensure EC works properly
3. Added an Id ("clickToShowParent") to a parent div in JavascriptPage.html

### Motivation and Context
I desired this EC because in some cases, elements move in the dom over time (e.g. a div moves across the screen as the user scrolls) and in other there may be several children in a loading screen or multiple elements may be loading simultaneously, and this will ensure that tests are definitively able to proceed.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by shbenzer** [comment]
Let me know if you have any questions/critics, I appreciate the work y'all do.

**Comment by shbenzer** [comment]
I don't know why the cla agreement thinks I am two authors - shbenzer is Simon Benzer is me.

**Comment by shbenzer** [comment]
needed to update test

**Comment by diemol** [comment]
@shbenzer thanks for this, however we are not adding more methods to the support packages anymore. 

If you are looking for ways to collaborate, please join our chat and we can discuss it.

https://www.selenium.dev/support/#ChatRoom

**Comment by shbenzer** [comment]
@diemol, interesting, what's the reason for that? Also sure, I'll gladly join the community, what channel in the slack should I post in?

**Comment by diemol** [comment]
#selenium-tlc is the channel

**Pull request closed without merging**
