### PR TITLE
[dotnet] Avoid try/catch while working with known types in Selenium Manager

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
This approach is more convenient little bit.

### Motivation and Context
When debugging unit tests, debugger always stops in `try/catch` block.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
The reason for the try/catch is that Selenium Manager is in beta and not fully featured, so we don't want users to get errors related to Selenium Manager, yet, because they can't do anything to fix it. We want the error message to include what they can do something about: "put drivers on path"

I think the next step is a custom Selenium Manager Error and link to how to debug problems (logging, submitting issues, etc)

**Comment by nvborisenko** [comment]
I just reworked small piece of code, logically it still the same, but debugger is happy now. Ah, and performance of this piece became better if it's relevant.

**Comment by titusfortner** [comment]
Where are potential errors getting caught, then?

**Review by diemol — APPROVED** [review]
Thank you, this is a better solution than the one I coded.

**Pull request merged**
