### PR TITLE
Fix clear actions in ActionChains

### LINKED ISSUE #7913: ActionChains does not reset actions
## 🐛 Bug Report

ActionChains does not reset actions.

## To Reproduce

Drag and drop

Detailed steps to reproduce the behavior:

All elements drag and drop every loop iteration

## Expected behavior

Reset actions and do one drag and drop for each iteration

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome()
actions = ActionChains(driver)

driver.get('http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html')

countries = {
    "Italy": "Rome",
    "Spain": "Madrid",
    "Norway": "Oslo",
    "Denmark": "Copenhagen",
    "South Korea": "Seoul",
    "Sweden": "Stockholm",
    "United States": "Washington",
}

for country in countries:
    country_box = driver.find_element_by_xpath(f"//div[.='{country}']")
    capital_box = driver.find_element_by_xpath(f"//div[.='{countries[country]}' and contains(@id, 'box')]")
    actions.drag_and_drop(capital_box, country_box).perform()
    actions.reset_actions()
```

## Environment

**OS**: macOS Catalina Version 10.15.2 
**Language Bindings version**: Python 3.141.0

**Browser**: Chrome
**Browser version**: 79.0.3945.88 (Official Build) (64-bit)
**Browser Driver version**: ChromeDriver 79.0.3945.36

**Browser**: Firefox
**Browser version**: 72.0.1 (64-bit)
**Browser Driver version**: geckodriver v0.26.0, v0.21.0

### PR DESCRIPTION
**Pull request by bayilyas**
Clear actions in ActionChains object after performing

Fixes #7913 

### Description
`ActionChains` assigned to a variable does not clear previous actions after `perform` and  `reset_actions` does not solve the issue.

### Motivation and Context

Assigning ActionChains to a variable and using it in different actions causes a repetition of all previous actions. The example below, in the second drag and drop, actions will be executed for `element1` and `element2` and not only for the `element2`. Clearing `device.action` in the `perform` method solve the issue.

Not: clearing actions on the remote end with `driver.execute(Command.W3C_CLEAR_ACTIONS)` can be also executed in the `pefrom` method.

```
actions = ActionChains(driver)
actions.drag_and_drop(element1, target).perform()
actions.reset_actions()
actions.drag_and_drop(element2, target).perform()
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Dude-X** [comment]
Suppose you run `perform` an action twice. Would this still work?
Example:
```
action = Actions(driver)
action.move_to_element(element)
action.perform()
action.perform()
```

**Comment by bayilyas** [comment]
For the case you want to run `perform` twice, it will do nothing like in Java. Should it be possible to repeat `perform` and is correct? If so, clearing actions can be implemented in `clear_actions`.

**Comment by Dude-X** [comment]
@bayilyas seems like you need to merge master.
@AutomatedTester Can you review and merge this if its acceptable?

**Review by AutomatedTester — APPROVED** [review]

**Review by Proc-64core — COMMENTED** [review]
@@ -53,26 +53,27 @@
    def key_action(self):	    def key_action(self):
        return self._key_action	        return self._key_action
    @property	    @property
    def pointer_action(self):	    def pointer_action(self):
        return self._pointer_action	        return self._pointer_action
    def add_key_input(self, name):	    def add_key_input(self, name):
        new_input = KeyInput(name)	        new_input = KeyInput(name)
        self._add_input(new_input)	        self._add_input(new_input)
        return new_input	        return new_input
    def add_pointer_input(self, kind, name):	    def add_pointer_input(self, kind, name):
        new_input = PointerInput(kind, name)	        new_input = PointerInput(kind, name)
        self._add_input(new_input)	        self._add_input(new_input)
        return new_input	        return new_input
    def perform(self):	    def perform(self):
        enc = {"actions": []}	        enc = {"actions": []}
        for device in self.devices:	        for device in self.devices:
            encoded = device.encode()	            encoded = device.encode()
            if encoded['actions']:	            if encoded['actions']:
                enc["actions"].append(encoded)	                enc["actions"].append(encoded)
                device.actions = []
        self.driver.execute(Command.W3C_ACTIONS, enc)	        self.driver.execute(Command.W3C_ACTIONS, enc)


     def clear_actions(self):	    def clear_actions(self):
[.<pdf>](https://github.com/SeleniumHQ/selenium/files/4208331/default.pdf)

**Comment by TheMakerOfWorlds** [comment]
will the fix be available in v4? and is there any way to get this fix now?

**Comment by TheMakerOfWorlds** [comment]
> will the fix be available in v4? and is there any way to get this fix now?

nvm just added your change in the code thank you so much

**Comment by bayilyas** [comment]
I did commit to clear `actions` after performing actions. With the commit, it will be impossible to reuse the `actions` after perform. 
In Java, there's no such possibility but in Python was and I more than sure that we shouldn't remove this possibility.

Prepared action can be reused several times and `reset_actions` should be used to clear previous actions. Is this correct behavior? I think my commit was a mistake and should be revert. 
@AutomatedTester what do you think?

**Pull request merged**
