### PR TITLE
[rust] Fix Edge management in RPM-based Linux

### LINKED ISSUE #13636: [🐛 Bug]: Selenium Manager should support Edge management using RPM in Linux
### What happened?

Currently, Selenium Manager uses the DEB package in Linux for Edge management. Nevertheless, this package is not compatible with the Red Hat Linux distros (e.g., Fedora). That should be improved in the Selenium Manager logic since Edge is also shipped as RPM: https://www.microsoft.com/en-us/edge/download?form=MA13FJ

### How can we reproduce the issue?

Run this command in a RPM-based Linux system:

```shell
./selenium-manager --trace --browser edge --force-browser-download
```

### Relevant log output

```shell
[2024-02-27T10:56:10.769Z TRACE] Artifacts: [Artifact { artifact_name: "deb", location: "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_122.0.2365.52-1_amd64.deb", hash: "8542F251416132389AADE5EBD734F29F29275727ABB78E4DD07E2247CC28191C", hash_algorithm: "SHA256", size_in_bytes: 165968574 }]
[2024-02-27T10:56:10.769Z DEBUG] Downloading edge 122.0.2365.52 from https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_122.0.2365.52-1_amd64.deb
[2024-02-27T10:56:10.769Z TRACE] Downloading https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_122.0.2365.52-1_amd64.deb to temporal folder "/tmp/selenium-manager9CpqoP"
[2024-02-27T10:56:10.962Z TRACE] File to be downloaded: microsoft-edge-stable_122.0.2365.52-1_amd64.deb
[2024-02-27T10:56:10.962Z TRACE] File downloaded to temporal folder: /tmp/selenium-manager9CpqoP/microsoft-edge-stable_122.0.2365.52-1_amd64.deb
[2024-02-27T10:56:49.706Z TRACE] The detected extension of the compressed file is deb
[2024-02-27T10:56:49.706Z TRACE] Extracting from /tmp/selenium-manager9CpqoP/microsoft-edge-stable_122.0.2365.52-1_amd64.deb to /tmp/selenium-manager9CpqoP
[2024-02-27T10:56:59.294Z TRACE] Moving extracted files and folders from /tmp/selenium-manager9CpqoP/opt/microsoft/msedge to /home/vagrant/.cache/selenium/edge/linux64/122.0.2365.52
[2024-02-27T10:57:00.419Z ERROR] Cross-device link (os error 18)
```

### Operating System

Red Hat Linux (e.g., Fedora)

### Selenium version

4.18+

### What are the browser(s) and version(s) where you see this issue?

Edge

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

No

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
I checked the Edge DEB package can also be used to extract the assets (Edge files and folders) in an RPM-based system (e.g., Fedora). The problem was the way in which the resulting folders was moved from the temporal folder to the cache. This PR changes that, and as a result, Edge can be downloaded in RPM-based systems. I tested it in Fedora:

```
user@fedora:~/dev/selenium/rust$ cat /etc/fedora-release
Fedora release 39 (Thirty Nine)

user@fedora:~/dev/selenium/rust$ cargo run -- --clear-cache --debug --browser edge
   Compiling selenium-manager v0.4.19-nightly (/home/user/dev/selenium/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 6.35s
     Running `target/debug/selenium-manager --clear-cache --debug --browser edge`
[2024-03-18T17:23:52.854Z DEBUG] Clearing cache at: /home/user/.cache/selenium
[2024-03-18T17:23:52.959Z DEBUG] Sending stats to Plausible: Props { browser: "edge", browser_version: "", os: "linux", arch: "x86_64", lang: "", selenium_version: "4.19-nightly" }
[2024-03-18T17:23:52.968Z DEBUG] msedgedriver not found in PATH
[2024-03-18T17:23:52.970Z DEBUG] edge not found in PATH
[2024-03-18T17:23:52.970Z DEBUG] edge not found in the system
[2024-03-18T17:23:52.971Z DEBUG] Checking edge releases on https://edgeupdates.microsoft.com/api/products/
[2024-03-18T17:23:53.051Z DEBUG] Required browser: edge 122.0.2365.92
[2024-03-18T17:23:53.051Z DEBUG] Downloading edge 122.0.2365.92 from https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_122.0.2365.92-1_amd64.deb
[2024-03-18T17:24:26.512Z DEBUG] edge 122.0.2365.92 is available at /home/user/.cache/selenium/edge/linux64/122.0.2365.92/msedge
[2024-03-18T17:24:26.512Z DEBUG] Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_122_LINUX
[2024-03-18T17:24:26.599Z DEBUG] Required driver: msedgedriver 122.0.2365.92
[2024-03-18T17:24:26.599Z DEBUG] Downloading msedgedriver 122.0.2365.92 from https://msedgedriver.azureedge.net/122.0.2365.92/edgedriver_linux64.zip
[2024-03-18T17:24:29.797Z INFO ] Driver path: /home/user/.cache/selenium/msedgedriver/linux64/122.0.2365.92/msedgedriver
[2024-03-18T17:24:29.797Z INFO ] Browser path: /home/user/.cache/selenium/edge/linux64/122.0.2365.92/msedge
```

### Motivation and Context
Fix for #13636.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

___

## **Type**
enhancement

___

## **Description**
- Enhanced support for RPM-based Linux systems in Edge browser file extraction by using shell commands for file movement.
- This change allows the Edge DEB package to be used on RPM-based systems like Fedora, improving compatibility and user experience.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>files.rs</strong><dd><code>Enhance Edge Browser File Extraction for RPM-based Systems</code></dd></summary>
<hr>
      
rust/src/files.rs

<li>Added OS parameter to <code>uncompress_deb</code> function to handle file movement <br>based on OS.<br> <li> Replaced direct file system rename operation with a shell command for <br>moving extracted Edge browser files.<br> <li> Enhanced the way Edge browser files are moved to the cache directory <br>on RPM-based systems.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13705/files#diff-64844fef0537ed5f6fd38575be93920c99efacb3fd4c317ed6ff1ce243c2e1f1">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — APPROVED** [review]

**Review by diemol — COMMENTED** [review]
Now, the build is failing. Could you please have a look when you have time, @bonigarcia?

**Comment by bonigarcia** [comment]
> Now, the build is failing. Could you please have a look when you have time, @bonigarcia?

I have reviewed the failures, but I don't know the causes.

First, the Windows build is failing before starting the tests. The error is:

```
error: linking with `C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/link.exe` failed: exit code: 1181
```

I searched for this problem, and it might be a toolchain issue:

https://stackoverflow.com/questions/57178691/rust-link-failed-with-exit-code-1181
https://stackoverflow.com/questions/55603111/unable-to-compile-rust-hello-world-on-windows-linker-link-exe-not-found/

Second, a couple of tests are failing in macOS: (1) The test that downloads the latest version of Firefox and (2) The test that downloads the late version of Edge.

Unfortunately, I cannot reproduce it in my MacOS VM. Both tests execute correctly.

@diemol: Can you please try the following on your Mac?

```
cd selenium/rust
cargo run -- --debug --browser firefox --force-browser-download
cargo run -- --debug --browser edge --force-browser-download
```

**Comment by bonigarcia** [comment]
Regarding the Windows build, I have bumped the toolchain version, and with PR #13735, it is green again:

https://github.com/SeleniumHQ/selenium/actions/runs/8428684771

But I still don't know why the Firefox and Edge download tests are failing in CI-macOS.

**Comment by diemol** [comment]
This is the command output on my M1
```
❯ cargo run -- --debug --browser firefox --force-browser-download
   Compiling selenium-manager v0.4.19-nightly (/Users/diegomolina/projects/github.com/seleniumhq/selenium/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 3.25s
     Running `target/debug/selenium-manager --debug --browser firefox --force-browser-download`
[2024-03-26T09:36:51.155Z DEBUG] geckodriver not found in PATH
[2024-03-26T09:36:51.156Z DEBUG] Required browser: firefox 124.0.1
[2024-03-26T09:36:51.156Z DEBUG] firefox 124.0.1 already exists
[2024-03-26T09:36:51.156Z DEBUG] firefox 124.0.1 is available at /Users/diegomolina/.cache/selenium/firefox/mac-arm64/124.0.1/Firefox.app/Contents/MacOS/firefox
[2024-03-26T09:36:51.156Z DEBUG] Required driver: geckodriver 0.34.0
[2024-03-26T09:36:51.156Z DEBUG] geckodriver 0.34.0 already in the cache
[2024-03-26T09:36:51.156Z INFO ] Driver path: /Users/diegomolina/.cache/selenium/geckodriver/mac-arm64/0.34.0/geckodriver
[2024-03-26T09:36:51.156Z INFO ] Browser path: /Users/diegomolina/.cache/selenium/firefox/mac-arm64/124.0.1/Firefox.app/Contents/MacOS/firefox
    ~/projects/github.com/seleniumhq/selenium/rust    sm_rpm_fix ············································································································································· 4s 
❯ cargo run -- --debug --browser edge --force-browser-download
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/selenium-manager --debug --browser edge --force-browser-download`
[2024-03-26T09:37:09.316Z DEBUG] Sending stats to Plausible: Props { browser: "edge", browser_version: "", os: "macos", arch: "arm64", lang: "", selenium_version: "4.19-nightly" }
[2024-03-26T09:37:09.329Z DEBUG] msedgedriver not found in PATH
[2024-03-26T09:37:09.330Z DEBUG] Checking edge releases on https://edgeupdates.microsoft.com/api/products/
[2024-03-26T09:37:10.067Z DEBUG] Required browser: edge 122.0.2365.92
[2024-03-26T09:37:10.068Z DEBUG] Downloading edge 122.0.2365.92 from https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/61b13da3-c921-482a-9166-743689310b71/MicrosoftEdge-122.0.2365.92.pkg
[2024-03-26T09:38:39.953Z DEBUG] edge 122.0.2365.92 is available at /Users/diegomolina/.cache/selenium/edge/mac-arm64/122.0.2365.92/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
[2024-03-26T09:38:39.954Z DEBUG] Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_122_MACOS
[2024-03-26T09:38:40.161Z DEBUG] Required driver: msedgedriver 122.0.2365.92
[2024-03-26T09:38:40.161Z DEBUG] Downloading msedgedriver 122.0.2365.92 from https://msedgedriver.azureedge.net/122.0.2365.92/edgedriver_mac64_m1.zip
[2024-03-26T09:38:44.233Z INFO ] Driver path: /Users/diegomolina/.cache/selenium/msedgedriver/mac-arm64/122.0.2365.92/msedgedriver
[2024-03-26T09:38:44.233Z INFO ] Browser path: /Users/diegomolina/.cache/selenium/edge/mac-arm64/122.0.2365.92/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
    ~/projects/github.com/seleniumhq/selenium/rust    sm_rpm_fix ········································································································································· 1m 36s 
❯
```

**Comment by diemol** [comment]
It is worth noting that the Edge download took quite a while, over a minute.

**Comment by bonigarcia** [comment]
Thanks for the test, @diemol. Like me, it seems to work. Now, I need to figure out why it is failing in GHA.

Regarding the minute that lasts, I'm afraid there is nothing we can do. SM needs to download the artifact (around 300 MB) and then extract it. The data compression ratio is high, so extracting all the files/folders takes a bit.

**Comment by bonigarcia** [comment]
> Thanks for the test, @diemol. Like me, it seems to work. Now, I need to figure out why it is failing in GHA.
> 
> Regarding the minute that lasts, I'm afraid there is nothing we can do. SM needs to download the artifact (around 300 MB) and then extract it. The data compression ratio is high, so extracting all the files/folders takes a bit.

**Comment by diemol** [comment]
I don't mind it takes that long, I was only wondering if it was affecting the tests.

**Pull request merged**
