### PR TITLE
Upgrade to JUnit 5 (vintage)

### PR DESCRIPTION
**Pull request by mkurz**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Using JUnit 5 Vintage allows us to run vintage JUnit tests (tests written in the JUnit 4 style) on the new JUnit Platform. Therefore someone doesn't need to upgrade pre-JUnit 5 tests itself yet.

See https://www.baeldung.com/junit-5-migration:
> JUnit Vintage aids in the migration of JUnit tests by running JUnit 3 or JUnit 4 tests within the JUnit 5 context.

Also https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-vintage
> JUnit Vintage test engine implementation that allows to run vintage JUnit tests, i.e. tests written in the JUnit 3 or JUnit 4 style, on the new JUnit Platform.

JUnit 5 releases: https://github.com/junit-team/junit5/releases

Why upgrade?
So frameworks that use selenium can also upgrade to JUnit 5 without conflicting dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6635)

### CODE REVIEW

**Comment by barancev** [comment]
Nope. The build tool we use at the moment (buck) has no support for JUnit 5.

**Comment by barancev** [comment]
There is no ticket yet. You may open one to track the status.

**Comment by mkurz** [comment]
@barancev Don't you think it would be possible to use the JUnit **vintage** artifact?

**Comment by barancev** [comment]
@mkurz Vintage artifact contains an engine that should be run by JUnit 5 runner to handle old-school tests. And the problem is that the build tool can't use this new runner. Or am I missing something?

**Comment by mkurz** [comment]
Hmmm... I am not sure, but probably you are right...

**Pull request closed without merging**
