### PR TITLE
Allow specifying timeouts

### LINKED ISSUE #11158: [🐛 Bug]: Cannot set read timeout value in Local Drivers
### What happened?

Despite setting high timeouts ("{implicit: 10000000, pageLoad: 10000000, script: 10000000}"), calling executeAsyncScript will occasionally time out after exactly 3 minutes. This is using 4.5.0 of Selenium and Java 17 with Firefox 105 on Ubuntu 18. It's also using selenium-http-jdk-client.

### How can we reproduce the issue?

```shell
Download https://github.com/TolstoyDotCom/more-speech and follow the instructions in the "2.1 Notes" section. You might need to use different handles and different numbers of pages to see the issue.

When you click 'Check timeline', the app gets some tweets from the user's profile page then visits each tweet's page.

On an individual tweet page, com.tolstoy.censorship.twitter.checker.app.webdriver.WebDriverFactoryNT first calls executeAsyncScript to load the tweets using the scripts in the stockscripts directory (jquery + suededenim + tweet_retriever).

Then, com.tolstoy.censorship.twitter.checker.app.browserproxy.BrowserProxyHAR calls executeAsyncScript using (jquery + suededenim + har_retriever).

Then, WebDriverFactoryNT calls executeAsyncScript using (jquery + suededenim + json_parser).

So, three calls to executeAsyncScript per page and if one of them takes longer than 3 minutes (likely if there are lots of tweets), it will probably time out.
```

### Relevant log output

```shell
[INFO ] 2022-Oct-21 11:45:18 AM c.t.c.t.c.a.h.SearchRunTimelineBuilder - Loading reply page [...]
[...]
[ERROR] 2022-Oct-21 11:48:18 AM c.t.c.t.c.a.h.SearchRunTimelineBuilder - error logging in or building searchRun org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-125-generic', java.version: '17.0.4'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [c57d3478-3d94-41ae-a991-f4792364f495, get {url=https://twitter.com/[...]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 105.0, moz:accessibilityChecks: false, moz:buildID: 20220915150737, moz:debuggerAddress: 127.0.0.1:36466, moz:geckodriverVersion: 0.32.0, moz:headless: false, moz:platformVersion: 5.4.0-125-generic, moz:processID: 6398, moz:profile: /tmp/rust_mozprofileAhZ2z2, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://127.0.0.1:36466/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 10000000, pageLoad: 10000000, script: 10000000}, unhandledPromptBehavior: dismiss}
Session ID: c57d3478-3d94-41ae-a991-f4792364f495
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at com.tolstoy.censorship.twitter.checker.app.helpers.SearchRunTimelineBuilder.getIndividualPage(SearchRunTimelineBuilder.java:353)
	at com.tolstoy.censorship.twitter.checker.app.helpers.SearchRunTimelineBuilder.getIndividualPages(SearchRunTimelineBuilder.java:323)
	at com.tolstoy.censorship.twitter.checker.app.helpers.SearchRunTimelineBuilder.buildSearchRunTimelineInternal(SearchRunTimelineBuilder.java:282)
	at com.tolstoy.censorship.twitter.checker.app.helpers.SearchRunTimelineBuilder.buildSearchRunTimeline(SearchRunTimelineBuilder.java:185)
	at com.tolstoy.censorship.twitter.checker.app.AppGUI$TimelineWorker.doInBackground(AppGUI.java:210)
	at com.tolstoy.censorship.twitter.checker.app.AppGUI$TimelineWorker.doInBackground(AppGUI.java:187)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 23 more
```

### Operating System

Ubuntu 18

### Selenium version

4.5.0 Java

### What are the browser(s) and version(s) where you see this issue?

Firefox 105

### What are the browser driver(s) and version(s) where you see this issue?

webdrivermanager 5.0.3

### Are you using Selenium Grid?

no

### PR DESCRIPTION
**Pull request by krmahadevan**
Partially Fixes #11158

The client side read and connection timeouts are 
Currently hard coded and there’s no way to change them.

While we are working on creating a proper mechanism To be able to specify timeouts when working with local Drivers, it still will not allow a user to alter the  Read and connection timeouts at the Node end when  Running tests in Grid.

Exposing these two timeouts via JVM arguments so 
that a user may be able to set them when spawning
the node.

* `webdriver.client.connection.timeout.seconds` - for connection timeouts in seconds
* `webdriver.client.read.timeout.minutes` - for read timeouts  in minutes

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
I believe we do not want to follow the approach of using JVM properties to set this values. This has been abused over the years and perhaps the only place where it is ok-ish is the Grid server. 

Moreover, this code is hard to remove in the future because deprecating JVM properties is very tricky.

**Comment by krmahadevan** [comment]
> I believe we do not want to follow the approach of using JVM properties to set this values. This has been abused over the years and perhaps the only place where it is ok-ish is the Grid server.

Sure. I hear you. This PR is ONLY for addressing the scenario of requiring client side timeouts to be set when running in the grid mode, because if I understand the flow correctly eventually a new ChromeDriver|EdgeDriver|FirefoxDriver is instantiated at the node as well, to support the running of the test on the node no ?

**Comment by diemol** [comment]
> > I believe we do not want to follow the approach of using JVM properties to set this values. This has been abused over the years and perhaps the only place where it is ok-ish is the Grid server.
> 
> Sure. I hear you. This PR is ONLY for addressing the scenario of requiring client side timeouts to be set when running in the grid mode, because if I understand the flow correctly eventually a new ChromeDriver|EdgeDriver|FirefoxDriver is instantiated at the node as well, to support the running of the test on the node no ?

For client side timeouts when using Grid, users can rely on the `RemoteWebDriverBuilder` and pass a `ClientConfig`. The requests in the Grid Node are already using the configured timeouts.

**Comment by krmahadevan** [comment]
> For client side timeouts when using Grid, users can rely on the `RemoteWebDriverBuilder` and pass a `ClientConfig`. The requests in the Grid Node are already using the configured timeouts.

This is what I have been searching for. Would it be possible for you to please help point me to the section of the code wherein a `ClientConfig` object set at the RemoteWebDriver level at a testcase, is being deserialised at the node and then used to instantiate a webdriver object at the node ?

**Comment by diemol** [comment]
No, the timeout on the client side is used for HTTP connections started on the client side. So those values are not propagated to the Grid, The Grid has its own timeouts configuration.

**Comment by krmahadevan** [comment]
> No, the timeout on the client side is used for HTTP connections started on the client side. So those values are not propagated to the Grid, The Grid has its own timeouts configuration.

Ok. I think I kind of know what is happening. Please correct me if the below understanding is wrong

* We allow a user to define a `session-timeout` at the node level.
* We use this `session-timeout` as if it was a `readTimeout` as seen here https://github.com/SeleniumHQ/selenium/blob/937cbaa05470fad29e7f2f8e60653039d1a1b8a5/java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java#L138-L142

So whenever a user is dealing with the Selenium grid and when they are handling client timeouts, they also need to ensure that the value they use as a readtimeout matches with what they have specified as a `session-timeout` at the node end.

Question.

The node options is missing connection timeout. Do you think we should add that as a node option as well, so that the parity of being able to configure read timeout and connection timeout exists at both the client and the node ends ?

**Comment by krmahadevan** [comment]
@diemol - I am closing this PR, since this PR no longer makes sense. 

Please do let me know if you think we should add a node configuration option that lets a user to setup a connection timeout as well.

**Comment by titusfortner** [comment]
yeah, so many different timeouts it gets confusing.

Session Timeout is *set on the grid*, and is for when the grid has an active session and hasn't gotten a new command from the client in the provided time. It exists so that the session doesn't hang forever. 

Connection Timeout *set on the Service* is how long to wait to make the initial connection to the server/driver. Typically keep-alive is set, so this only applies on the first connection.

Read Timeout *set on the Service* is how long to wait to hear back on any subsequent connection to the server/driver.

Page Load / Script Timeout - *set on the Options (or driver)* is how the driver should wait to hear back from the browser for a navigation or script execution.

The last two can cause conflicting results because the same action will have different results depending on which value is set higher.

**Pull request closed without merging**
