### PR TITLE
Do not set content length to zero

### LINKED ISSUE #11342: [🐛 Bug]: Dynamic Grid setup fails when the docker images are missing locally
### What happened?

When we attempt at following the documentation of [Dynamic Grid](https://github.com/SeleniumHQ/docker-selenium#dynamic-grid) the docker node does not come up and crashes.

### How can we reproduce the issue?

Ensure that you dont have any of the selenium related docker container images in your machine by running 

1. `docker container prune` to prune the images being used by stopped containers
2. `docker rmi $(docker images | grep selenium | awk '{print $3}')` clean up all selenium images

Create a docker-compose file named `docker-compose-v3-dynamic-grid.yml` that looks like below:

```yaml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.6.0-20221104
    volumes:
      - ./config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub-dynamic
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-dynamic
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5005:5005"
     
  selenium-hub-dynamic:
    image: selenium/hub:4.6.0-20221104
    container_name: selenium-hub-dynamic
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4455:4444"
```

In the same directory create a toml configuration file named `config.toml` with its contents as below:

```toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.6.0-20221104", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.6.0-20221104", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.6.0-20221104", "{\"browserName\": \"MicrosoftEdge\"}"
    ]
    
# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted 
# If var/run/docker.sock is not mounted: 
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
# I am on mac
url =  "http://host.docker.internal:2375"

# Docker image used for video recording
#video-image = "selenium/video:ffmpeg-4.3.1-20220531"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = "10.136.130.15"#<ip-from-node-machine>
#port = "5555"#<port-from-node-machine>
```

Setup socat forwarding (I am on Mac and so I installed `socat` and run the following command, `socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock`

Now bring up the nodes by running `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
```


### Relevant log output

```shell
sunny-node-docker-1   | 10:31:07.650 INFO [PullImage.apply] - Pulling Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.6.0-20221104', digest='null'}
sunny-node-docker-1   | java.lang.reflect.InvocationTargetException
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sunny-node-docker-1   |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sunny-node-docker-1   |         at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
sunny-node-docker-1   |         at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
sunny-node-docker-1   | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
sunny-node-docker-1   |         at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:152)
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:128)
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:239)
sunny-node-docker-1   |         at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
sunny-node-docker-1   |         at org.openqa.selenium.grid.Main.launch(Main.java:83)
sunny-node-docker-1   |         at org.openqa.selenium.grid.Main.go(Main.java:57)
sunny-node-docker-1   |         at org.openqa.selenium.grid.Main.main(Main.java:42)
sunny-node-docker-1   |         ... 6 more
sunny-node-docker-1   | Caused by: java.lang.reflect.InvocationTargetException
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sunny-node-docker-1   |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sunny-node-docker-1   |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sunny-node-docker-1   |         at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
sunny-node-docker-1   |         at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
sunny-node-docker-1   |         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
sunny-node-docker-1   |         at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
sunny-node-docker-1   |         ... 14 more
sunny-node-docker-1   | Caused by: java.lang.IllegalArgumentException: non-positive contentLength: 0
sunny-node-docker-1   |         at java.net.http/java.net.http.HttpRequest$BodyPublishers.fromPublisher(HttpRequest.java:539)
sunny-node-docker-1   |         at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.notChunkingBodyPublisher(JdkHttpMessages.java:124)
sunny-node-docker-1   |         at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.createRequest(JdkHttpMessages.java:76)
sunny-node-docker-1   |         at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
sunny-node-docker-1   |         at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
sunny-node-docker-1   |         at org.openqa.selenium.docker.v1_41.PullImage.apply(PullImage.java:63)
sunny-node-docker-1   |         at org.openqa.selenium.docker.v1_41.V141Docker.getImage(V141Docker.java:80)
sunny-node-docker-1   |         at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
sunny-node-docker-1   |         at java.base/java.util.Optional.map(Optional.java:265)
sunny-node-docker-1   |         at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:260)
sunny-node-docker-1   |         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
sunny-node-docker-1   |         at java.base/java.lang.Thread.run(Thread.java:829)
sunny-node-docker-1   | Exception in thread "Thread-0" java.lang.NullPointerException
sunny-node-docker-1   |         at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:80)
sunny-node-docker-1   |         at java.base/java.lang.Thread.run(Thread.java:829)
sunny-node-docker-1   | 2022-12-01 10:31:08,079 INFO exited: selenium-grid-docker (exit status 1; not expected)
```

### Operating System

macOS

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Not relevant

### What are the browser driver(s) and version(s) where you see this issue?

Not relevant

### Are you using Selenium Grid?

4.6.0

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes: #11342

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@pujagani @diemol - I haven't been able to figure out a proper way to test this functionality manually because I basically need to create `selenium/standalone-firefox` docker image with the newly built jar and then use that. 

I attempted the following but this generates an error saying 

```
grid-node-docker-1    | 06:36:35.008 WARN [SessionSlot.apply] - Unable to create session
grid-node-docker-1    | java.lang.IllegalArgumentException: Assets path must be set
grid-node-docker-1    |         at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.docker.DockerSession.<init>(DockerSession.java:61)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:269)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:90)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:382)
grid-node-docker-1    |         at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
grid-node-docker-1    |         at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
```

Steps:
1. Built the grid jar (`bazel build grid`)
2. cloned the docker selenium project
3. copied the selenium grid jar to the `Base` folder in the docker selenium project
4. Altered the Dockerfile in this directory to refer to the local jar instead of downloading it from Maven central.
5. Built all the images by running `VERSION=local make build`
6. Altered the docker compose file and the `config.toml` (references of them are available in the defect ) to refer to the local images.
7. Started the grid via docker compose
8. Ran a sample test that looks like below

```java
  public static void main(String[] args) throws MalformedURLException {
    RemoteWebDriver driver = null;
    try {
      driver = new RemoteWebDriver(new URL("http://localhost:4444"), new FirefoxOptions());
      driver.get("http://www.google.com");
      System.err.println("Title " + driver.getTitle());
    } finally {
      if (driver != null) {
        driver.quit();
      }
    }
  }
```

**Comment by krmahadevan** [comment]
Ok please ignore the error msg.. That was my mistake...  I didnt add a volume for mapping the assets in my docker compose file.

Once I added it 

```yaml
    volumes:
      - ./config.toml:/opt/bin/config.toml
      - ./assets:/opt/selenium/assets
```
It worked fine.. a test runs fine.. That PR is now tested out.. I am able to run a firefox test inside a dynamic grid without any issues.

**Comment by jsa34** [comment]
Came across this, too, after updating thinking the issue was resolved with latest release.  Could this be reviewed/merged/released ASAP?

**Review by qalinn — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you, @krmahadevan!

**Comment by krmahadevan** [comment]
@diemol @pujagani - Please help re-open this defect. It looks like this is still NOT done.

Here's what I have as analysis:

1. We got rid of all places wherein we are setting the content length explicitly to zero.
2. When starting a container, we use the [Docker container API ](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStart) with a POST message, but it has no body and so its content length now gets evaluated to zero.
3. We are using the JDK client by default for all of our http client needs. 
4. We create a HttpRequest via `org.openqa.selenium.remote.http.jdk.JdkHttpMessages#createRequest`  which internally calls `org.openqa.selenium.remote.http.jdk.JdkHttpMessages#notChunkingBodyPublisher` for a `POST` message.
5. Since as per the docker api spec, there's no payload for this request, we end up getting evaluated to a content length of zero.
6. This in turn triggers the validation check at the JDK HttpClient level saying 

```
grid-node-docker-1    | java.lang.IllegalArgumentException: non-positive contentLength: 0
grid-node-docker-1    |         at java.net.http/java.net.http.HttpRequest$BodyPublishers.fromPublisher(HttpRequest.java:539)
grid-node-docker-1    |         at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.notChunkingBodyPublisher(JdkHttpMessages.java:124)
grid-node-docker-1    |         at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.createRequest(JdkHttpMessages.java:76)
grid-node-docker-1    |         at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:292)
```

Note: 
We cannot set a payload also for this request, since when we do that, I hit an error as below

```
{
    "message": "starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"
}
```
with a `400 BAD REQUEST`

I will raise a new PR for this in a few hours.

**Comment by krmahadevan** [comment]
Here's the new PR https://github.com/SeleniumHQ/selenium/pull/11445

**Comment by pujagani** [comment]
Thank you for the details. I have reopened the associated GitHub issue as requested.

**Pull request merged**
