### PR TITLE
Delete JavascriptEnabled test annotation

### PR DESCRIPTION
**Pull request by asashour**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

The purpose of the change, is to remove `@JavascriptEnabled` test annotation, which was used for only HtmlUnit, and it is not needed anymore.

### CODE REVIEW

**Comment by shs96c** [comment]
Is running without JS support no longer supported by HtmlUnit?

**Comment by asashour** [comment]
Running without JS support is supported, but not the default. In both HtmlUnit and HtmlUnitDriver.

I see almost all the tests in Selenium base, depend on JavaScript ennoblement.

After the deprecation of `Capabilities.isJavaScriptEnabled` (as I remember), a new `JAVASCRIPT_ENABLED` Capabilities was introduced in HtmlUnitDriver, so users can disable it when needed.

If there are test cases related to 'no JS', then it should be bound to only HtmlUnitDriver and HtmlUnit (the latter is tested in HtmlUnit suite).

And since the general tests of selenium seem not to require 'JavaScript off', except in only HtmlUnitDriver, then it makes sense in only HtmlUnitDriver test package, but not for all tests.

**Comment by shs96c** [comment]
Thank you for the thoughtful answers.

**Comment by shs96c** [comment]
Merged as 8ad8daba8c89735a90b8534690fafdb2600708a7. Thank you!

**Pull request closed without merging**
