### PR TITLE
Updating Firefox AddOns for Testing

### PR DESCRIPTION
**Pull request by diemol**
### **User description**
# Merge when Firefox 127 has been released.

___

### **PR Type**
enhancement, tests

___

### **Description**
- Updated extension ID assertions across multiple test files to match the new version (`webextensions-selenium-example-v3@example.com`).
- Modified test metadata for signed directory installation in Ruby specs.
- Removed a skipped test entry for Firefox beta driver.
- Added new `cose.manifest` file for signed extension.
- Updated `manifest.mf` and `mozilla.sf` files with new digest algorithms and entries.
- Updated `manifest.json` files to version 3 and changed extension ID to the new version for both signed and unsigned extensions.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
</strong></td><td><details><summary>4 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>ExtensionsTest.java</strong><dd><code>Update extension ID assertions in Firefox extensions tests</code></dd></summary>
<hr>
      
java/test/org/openqa/selenium/firefox/ExtensionsTest.java

- Updated extension ID assertions to match new version.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-f9cb6222f5c99a506ed1fef5fd203114f7ed1d6b3724c7ff091a346e0b1b2c47">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RemoteFirefoxDriverTest.java</strong><dd><code>Update extension ID assertion in RemoteFirefoxDriverTest</code>&nbsp; </dd></summary>
<hr>
      
java/test/org/openqa/selenium/firefox/RemoteFirefoxDriverTest.java

- Updated extension ID assertion to match new version.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-ceebcc4a4e13c6da623c74774e275bd74db52f53a959b6904721534ece129051">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>driver_spec.rb</strong><dd><code>Update extension ID assertions and test metadata in Firefox driver </code><br><code>specs</code></dd></summary>
<hr>
      
rb/spec/integration/selenium/webdriver/firefox/driver_spec.rb

<li>Updated extension ID assertions to match new version.<br> <li> Modified test metadata for signed directory installation.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-9ec26646751cbee2fac6073dcb7e6bbed145635fe9c9e5f0c5d2c1e2531700fc">+8/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ff_installs_addons_tests.py</strong><dd><code>Update extension ID assertions in Firefox addon installation tests</code></dd></summary>
<hr>
      
py/test/selenium/webdriver/firefox/ff_installs_addons_tests.py

- Updated extension ID assertions to match new version.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-e0886617d0c9b304043b03e1674bd934e3fdb6ac70751fa6e4806ace5d4e6db2">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>.skipped-tests</strong><dd><code>Remove skipped test entry for Firefox beta driver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
.skipped-tests

- Removed a skipped test entry for Firefox beta driver.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-f5b9e26559bdc4671c8a6fd4013e376a76cbdac0a1661ffbe585b7533c4700f7">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Enhancement
</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>cose.manifest</strong><dd><code>Add cose.manifest file for signed extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
common/extensions/webextensions-selenium-example-signed/META-INF/cose.manifest

- Added new cose.manifest file for signed extension.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-5c9beb74cd94f2185093292be9f00e8c7cfa15263b317028be45a7a440d8dbf1">+12/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>manifest.mf</strong><dd><code>Update manifest.mf with new digest algorithms and entries</code></dd></summary>
<hr>
      
common/extensions/webextensions-selenium-example-signed/META-INF/manifest.mf

<li>Updated digest algorithms and added new entries for signed extension.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-91e9e19227b10070ce1f2a6d7555b20a62aff7a26feecc45db5f6bbc71c31d9e">+15/-5</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>mozilla.sf</strong><dd><code>Update mozilla.sf with new digest manifest</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
common/extensions/webextensions-selenium-example-signed/META-INF/mozilla.sf

- Updated digest manifest for signed extension.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-c69be679fa9b1876501b9018dcc463d30aaebe99f8d86551c1d1cba8840bf5ad">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>manifest.json</strong><dd><code>Update manifest version and extension ID for signed extension</code></dd></summary>
<hr>
      
common/extensions/webextensions-selenium-example-signed/manifest.json

<li>Updated manifest version to 3.<br> <li> Changed extension ID to new version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-74a0cce1281b416503898acc485469fccc1c14f31c3ca7d70be7ae13d6611b36">+15/-10</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>manifest.json</strong><dd><code>Update manifest version and extension ID for unsigned extension</code></dd></summary>
<hr>
      
common/extensions/webextensions-selenium-example/manifest.json

<li>Updated manifest version to 3.<br> <li> Changed extension ID to new version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13999/files#diff-b72a975cc05b8de90b47a83cc49a195d494b36d4aba2bd8c5fcb852fa35dc29d">+14/-9</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
Ruby Addon tests are still failing with this PR, and I can't tell what RBE is doing because the BiDi tests started hanging the build on the latest Chrome version.

**Comment by titusfortner** [comment]
Ok, versions weren't updating uniformly and guards were weird, looks good now.

**Comment by diemol** [comment]
I had forgotten entirely about this PR.

**Comment by titusfortner** [comment]
The h1 was memorable to me

# Merge when Firefox 127 has been released.

**Pull request merged**
