### PR TITLE
[py]  Implement add_request_handler 

### PR DESCRIPTION
**Pull request by jman-sketch**
### Description

Implement add_request_handler as described in #13993 . As required, also implemented
* `network.AddIntercept`
* `network.BeforeRequestSent`
* `network.ContinueRequest`
* `network.RemoveRequest`
* `browsingContext.Navigate`
* and all dependencies of objects above.

The dependencies were generated from CDDL entries in [BIDI specs](https://w3c.github.io/webdriver-bidi)

Add an asynchronous navigation function `driver.network.get`

### Motivation and Context
#13993

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Implemented a new feature to handle network requests using BiDi protocol in Selenium.
- Added multiple data classes for network operations with JSON serialization and deserialization.
- Integrated network request handling into the WebDriver class.
- Added tests to verify the functionality of the `add_request_handler` method.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>network.py</strong><dd><code>Implement network request handling and serialization classes</code></dd></summary>
<hr>

py/selenium/webdriver/common/bidi/network.py

<li>Implemented multiple data classes for network operations.<br> <li> Added methods for JSON serialization and deserialization.<br> <li> Introduced event handling for network requests.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14604/files#diff-d04fc5573acd6ca5bcc8167940f134f1a3ead8a5230c066c077a1319a1ffe1d4">+491/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>script.py</strong><dd><code>Add stack trace data classes with serialization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/bidi/script.py

<li>Added <code>StackFrame</code> and <code>StackTrace</code> data classes.<br> <li> Implemented JSON serialization and deserialization methods.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14604/files#diff-c4d141b056a48aff05840758a7591f2d2b86d6c2f6b8f79c7362ddc8b41c7fcc">+46/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>network.py</strong><dd><code>Introduce Network class for request management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/remote/network.py

<li>Created <code>Network</code> class for managing network requests.<br> <li> Implemented <code>add_request_handler</code> method for request interception.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14604/files#diff-46fd53c2cf5a4d87c5ff47cdf75bfecf2e06d5d7888a7c7b1394187c398684e3">+41/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Integrate Network class into WebDriver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/remote/webdriver.py

<li>Integrated <code>Network</code> class into WebDriver.<br> <li> Added <code>network</code> property for network operations.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14604/files#diff-c87c150ed2a08f5293db58a06da8bf7f14c3a5582586c6270c1be661dfdd0985">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>bidi_network_tests.py</strong><dd><code>Add tests for network request handler</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/common/bidi_network_tests.py

<li>Added test for <code>add_request_handler</code> method.<br> <li> Used pytest for testing network request interception.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14604/files#diff-97c8d35b88402ef5de934c8fb95da5f7c7c04039a79baf20cc8fd6c91379dac7">+40/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by jman-sketch** [comment]
Currently, the `add_listener` function is blocking, meaning that page can only be refreshed via the browser itself. However, when navigating using the browser, requests are properly intercepted and modified. I wanted to open the PR for feedback and suggestions.

**Comment by jman-sketch** [comment]
It was `driver.get` that was the blocking operation. Added `network.get` for asynchronous navigation

**Comment by jman-sketch** [comment]
`bidi_network_tests.py` was throwing errors because usage of `|` operator for merging dictionaries was introduced in Python 3.9 while the tests were using 3.8. It has been fixed

**Comment by jman-sketch** [comment]
All local `chrome-` tests are passing

@VietND96 May the workflow be triggered again?

**Comment by jman-sketch** [comment]
@AutomatedTester I would really appreciate your feedback on this. In particular, what are your thoughts on

* Using BiDi objects + websocket vs json + HTTP
   * Ideally, there should be a generic class and each object would only have the type definitions, but I'm not sure where to put the generic class 
* Using trio/nursery vs plain async functions
    * I think being able to call `await add_request_handler` would be a lot more elegant, but I _think_ it would require more changes to existing modules

**Comment by jman-sketch** [comment]
Remote tests were timing out due to requesting external URLs. Changing it to internal ones in `pages` solved it

**Comment by jman-sketch** [comment]
Factored all the repeated functions into `bidi.py` class. Tests are still passing (locally)

**Comment by shbenzer** [comment]
run ./scripts/format.sh to help with your formatting

**Comment by jman-sketch** [comment]
@shbenzer Aha! Thanks!

**Comment by shbenzer** [comment]
bidi_tests.py and upload_tests.py are flaky - I've got PRs up to fix them - so don't worry about those results

**Comment by jman-sketch** [comment]
@shbenzer Perfect! That explains a lot :confetti_ball:

**Comment by jman-sketch** [comment]
While adding support for multiple intercepts, noticed that "paused" cached requests are served without waiting for continue request. Not sure if this is intended (from browser end).

Since bidi `network.setCacheBehavior` is not implemented yet, will disable caching with cdp for now.

**Comment by jman-sketch** [comment]
Closing this PR to open a new one (#14738) from a different account for better access management. Thank you for your feedbacks!

**Pull request closed without merging**
