### PR TITLE
Fix bug: Missing to load the "net/http" library.

### PR DESCRIPTION
**Pull request by dvarrui**
### Description

Get this error 
```
Using the selenium-webdriver v4.11.0 gem results in the following error: selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/default.rb:108:in `new_request_for': uninitialized constant S elenium::WebDriver::Remote::Http::Default::Net (NameError)

             req = Net::HTTP.const_get(verb.to_s.capitalize).new(url.path, headers)
```

### Motivation and Context

Software installed:
* rbenv 1.2.0-48-g6717c62
* ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
* geckodriver v0.33.0
* gem selenium-webdriver (4.11.0)

When running this script:

```
require "selenium-webdriver"

# Initialize webdriver
options = Selenium::WebDriver::Options.firefox
options.page_load_strategy = :normal
driver = Selenium::WebDriver.for :firefox, options: options
driver.manage.timeouts.implicit_wait = 30

# Use webdriver
driver.get "https://www.nba.com"
puts "[Title] #{driver.title}"
driver.quit
```

Obtain this error:

```
selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/default.rb:108:in `new_request_for': uninitialized constant S
elenium::WebDriver::Remote::Http::Default::Net (NameError)

            req = Net::HTTP.const_get(verb.to_s.capitalize).new(url.path, headers)
```

###  Solution

Adding `require 'net/https'` to the `lib/selenium/webdriver/firefox.rb` file.

### Types of changes

[X ] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [X ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
What do you think about the comment I made on the previous PR?

https://github.com/SeleniumHQ/selenium/pull/12493#issuecomment-1665593969

**Comment by dvarrui** [comment]
I think what you propose is a good idea.
:-)

**Comment by titusfortner** [comment]
@dvarrui would you like to make the change and I'll merge it?

**Comment by dvarrui** [comment]
OK

Do I make the modification in the same "fix_dvarrui" branch or should I create a new one?

**Comment by titusfortner** [comment]
this branch is fine. We end up squashing and merging when we accept the PR.

**Comment by dvarrui** [comment]
Done!
Thanks for your help!

**Comment by titusfortner** [comment]
This code does not need to be rebased with trunk, Github will do that automatically when it merges. I can't accept this PR without seeing the completed test run, and the results go away every time it gets rebased. 😂

**Comment by dvarrui** [comment]
Sorry!
😞

**Comment by titusfortner** [comment]
It's all good, I keep forgetting to go back and look at results 😂
All working, thanks!.

**Pull request merged**
