### PR TITLE
[Rust] Refactors

### PR DESCRIPTION
**Pull request by oriongonza**
### Description
General refactors in the selenium manager

### Motivation and Context
I was going to add a new functionality and found some code that could get updated.

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Changes

- Added string interpolation, introduced in version 1.58 https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html
- ran cargo fmt
- refactored the main pipeline. This could be changed to use `if let Err` syntax if this change is not accepted

### CODE REVIEW

**Review by bonigarcia — COMMENTED** [review]
Hi @dev-ardi. Are you using `cargo fmt` to format the code in this PR?

**Comment by oriongonza** [comment]
Buenos días @bonigarcia,

Yes I am, that's the reason behind the commit https://github.com/SeleniumHQ/selenium/pull/11832/commits/ac551af7a41582b4d180ea0732bad3b2addb5cdc
Are you using another formatter?

**Comment by bonigarcia** [comment]
We also use cargo fmt, thanks!

**Review by bonigarcia — APPROVED** [review]

**Comment by diemol** [comment]
@dev-ardi could you please sign the CLA and resolve the conflicts?

**Comment by oriongonza** [comment]
Done

**Review by diemol — COMMENTED** [review]
Seems tests are failing.

**Comment by oriongonza** [comment]
I have no idea how to merge these locally😞

**Comment by diemol** [comment]
You can use the GitHub UI for that...

image

https://github.com/SeleniumHQ/selenium/pull/11832/conflicts

**Comment by AutomatedTester** [comment]
@dev-ardi hey, we have numerous chat services all interconnected if you're interested. 

https://www.selenium.dev/support/

It might mean you get quicker answers as people might not always be watching GitHub notifications. We would love for you to join us and come hang out

**Review by diemol — APPROVED** [review]
Thank you, @dev-ardi!

Congratulations on your first contribution 🎉

**Pull request merged**
