### PR TITLE
[rb] Add macos coverage to Ruby CI Github Action - Feat#12397

### LINKED ISSUE #12397: [🚀 Feature]: Run tests on Mac in CI
### Feature and motivation

Something (maybe Ruby) needs to run on Mac. We don't have any coverage for Safari or for Selenium Manager actually working properly on Mac.

I happened to hit a selenium manager bug trying to do something before the upcoming release; we need CI to catch this.

### Usage example

n/a

### PR DESCRIPTION
**Pull request by dev-velo**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Fixes #12397 
Added a macos runner to Ruby CI yaml file. Unit tests for ruby 3.2.0 will run on macos. I seen ruby 3.2.2 is out and wouldve upgraded the ruby version but not sure how that will affect caching so i left the versions as they were.

Integration-local should now run on mac for chrome, firefox, safari. The Bazel.yaml file also now enables safaridriver given safari as an input. 

**Possibly extra things that might need to get done**

There might be some more bazel work needed for remote execution. I added the proper os but I have seen mention of pinning browsers for hermetic builds in the slack chat, unsure how much work would be needed to pin safari.
I would be fine adding any extra work given some guidance. Also fine with removing macos for remote tests if that proves too difficult
### Motivation and Context

More test coverage!
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
Oops tests are broken. This should fix, verifying - https://github.com/SeleniumHQ/selenium/commit/ce495aca174c7480350412fc26100ad4fd9744b1

**Comment by titusfortner** [comment]
Ok fixed, re-running. I'm guessing there will still be failing tests we need to sort, but at least everything should run.

**Comment by titusfortner** [comment]
So, I suspect that there are a lot of bugs or other things that Safari doesn't have working, or that don't work on mac for some reason. We have guards in RSpec to indicate which tests we expect not to be passing based on bugs and such. Let me know if you'd like to work on that, and if you need help parsing the guarding syntax.

**Comment by dev-velo** [comment]
Yea seems the guards in rspec only covered windows and strictly specific github. Added macos to the list and removed the ci portion since it was reproducible in a local machine and not exclusive to github.

**Comment by dev-velo** [comment]
think I got the local firefox tests all working... now onto safari

**Comment by dev-velo** [comment]
believe local safari tests should be fine with one exception. safari seems to [run chrome driver tests](https://github.com/SeleniumHQ/selenium/actions/runs/5901035299/job/16015190304#step:15:712) <- Line 712 in the run bazel command, not sure why github sends the page to the last line in the logs. It complains about w3c compliance when it comes to headless which I don't think safari has ( which might be why it complains ). My only issue is [chrome driver tests](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/spec/integration/selenium/webdriver/chrome/driver_spec.rb#L25) are exclusive to chrome ```describe Driver, exclusive: {browser: :chrome} ``` so I am not sure why safari is being even triggered. @titusfortner this should be the last hurdle to get safari tests to pass locally.  Hopefully you might have some advice or some solution to not get chrome to not run on safari, I tried a few things with exclusions but couldn't get any to work.

**Comment by titusfortner** [comment]
Thanks for the work on this!
I'll look into it, but this week is a lot.

**Comment by titusfortner** [comment]
I haven't forgotten about this one. Still need to get time to look it over.

**Comment by titusfortner** [comment]
One last error here, and I think I figured it out. 🤞

**Review by titusfortner — APPROVED** [review]

**Comment by titusfortner** [comment]
Thanks @RevealOscar for getting this together!

**Comment by dev-velo** [comment]
whoop whoop! @titusfortner ty for the help! Ill look into open issues and see what else I can help with

**Pull request merged**
