### PR TITLE
[py] Added Common Tests to Edge CI

### PR DESCRIPTION
**Pull request by shbenzer**
### Description
Added "test/selenium/webdriver/common/**/*.py" to edge tests in Bazel.Build

### Motivation and Context
Building off @Delta456 's #14723 . Figured since this will add so many tests it might be best to split into a separate pr.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
enhancement, tests

___

### **Description**
- Added common Selenium WebDriver tests to the Edge CI test suite in the Bazel build configuration.
- This change enhances the test coverage for Edge by including tests from the common directory.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>BUILD.bazel</strong><dd><code>Include common tests in Edge CI test suite</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/BUILD.bazel

<li>Added common test files to the Edge test suite.<br> <li> Updated the <code>srcs</code> attribute to include common tests.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14748/files#diff-3e8ff3a52e8e6c0b195ea328e17c50ba6d90abca1ce1624110607da20691d7a9">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by AutomatedTester — APPROVED** [review]

**Comment by VietND96** [comment]
```
    py_test_suite(
        name = "common-%s" % browser,
        size = "large",
        srcs = glob(
            [
                "test/selenium/webdriver/common/**/*.py",
                "test/selenium/webdriver/support/**/*.py",
            ],
```
@AutomatedTester, I saw this test suite using config from browsers.bzl, should this be duplicated?

**Comment by shbenzer** [comment]
@VietND96 Merge [1de1b40](https://github.com/SeleniumHQ/selenium/pull/14748/commits/1de1b4069735b6d3dda989ffa994ed17095fca34) introduced errors into `//py:test-edge-test/selenium/webdriver/edge/edge_launcher_tests.py ` and `//py:test-edge-test/selenium/webdriver/common/w3c_interaction_tests.py`

**Comment by shbenzer** [comment]
Only the bidi_tests.py had problems in initial commit - those have been marked xfail like safari since problem is on the webdriver side

**Comment by VietND96** [comment]
Yes, I am updating your PR and @Delta456 to merge both

**Comment by VietND96** [comment]
In set of common tests including BiDi test, when running `bazel test //py:test-edge`, it doesn't set args --bidi=true, so there were failed tests
So, the CI keep running 2 command separately
`bazel test //py:common-$browser-bidi` - run tests in /common/*.py and /support/*.py against different browser driver
`bazel test //py:test-$browser` - test of particular browser driver
Also updated README on the list of commands for python tests

**Pull request merged**
