### PR TITLE
[New feature] - 🎉  - Added the initial support for error Handling

### PR DESCRIPTION
**Pull request by 0xvasanth**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

 

### Description:
 * Support for the Base Error Container
 * Support for Custom **Result** to be exposed from each functional / API endpoint 
 * Support for Brief Custom error and CmdError code to make

### Motivation and Context

 * When using Selenium Manager as a library it is mandatory to raise a Handled error from the lib
 * Since there is no support for Error Handling right now, need of that support is required

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bonigarcia** [comment]
Hi @itsparser. Thanks a lot for contributing. I quickly reviewed your PR, and it seems that most changes are related to the formatting style. To track the new code, please revert these formatting changes, and leave only the new changes, thanks.

**Comment by 0xvasanth** [comment]
@bonigarcia I have just used rustfmt which will auto-correct the import order and indentation, I believe this can help for code readability, and I am okay to revert it in this PR 
But I strongly recommend using this in your project [ref](https://github.com/rust-lang/rustfmt)
please suggest your response

**Comment by bonigarcia** [comment]
@itsparser  Thanks for the suggestion, although that should be a separate PR, IMO. For this one, I think is better to consider only the code related to error handling

**Comment by 0xvasanth** [comment]
@bonigarcia it been done review and merge this will send you next PR with rustfmt

**Comment by bonigarcia** [comment]
Selenium Manager handles drivers (chromedriver, geckodriver, etc.) automatically. In other words, it downloads these binaries, matching the browser version, etc. But Selenium Manager does not deal with the W3C Commands. That work is done by the drivers (chromedriver, etc.). Therefore, this code does not work on the right track.

**Comment by diemol** [comment]
@itsparser have you seen the comments above? Perhaps you can chat with us in Slack https://www.selenium.dev/support/ and we find an approach for this PR together?

**Comment by 0xvasanth** [comment]
@diemol  sorry for the late replay was allocated in my professional work, will update the PR and send you back

**Comment by diemol** [comment]
Closing in favor of #11263

**Pull request closed without merging**
