### PR TITLE
Keyword loalization implemention

### PR DESCRIPTION
**Pull request by MathausC**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

This Pull Request contains a implementation of a new way to find Elements using XPath and Keywords presents in properties files. I dynamical replace the keyword text for the equivalent translation to find a element using a generic text content for any language covered at the properties file.

### Description
I implemented a new method By.keyword() and a new internal class ByKeyword();
I Also implemented a list of hash maps at the RemoteWebDriver class so I could store the properties files with the translations.
I Added a method to add this properties files
I modified the findElement and findElements methods so it would replace the keyowrd present at the content of the XPath with the available translations.

### Motivation and Context
I wanted to make a new method so I could find elements in pages where the identifiers are not well written and could use the text content, but it be independent of what language it was written.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
I would like to see this feature in its own small project that Selenium can promote. There are hooks in the code to make it easy to extend the locators without them needing to be in the same module.

Would you be interested in collaborating on this?

**Comment by diemol** [comment]
During the meeting on [25.05.2023](https://www.selenium.dev/meetings/2023/tlc-05-25/) it was decided to not continue adding features to Support classes (in this case extending an existing selector):
- That is the direction we should go because it would set the project to be a base library, rather than something in between. A more clear concept. Also, with the people we have at the moment, we cannot maintain more stuff.
- The standard should be bug fixes only. For new features: please copy & paste/subclass/fork and change whatever you want. 


@MathausC thank you for taking the time to raise this PR, but given the decision taken on the linked meeting, we won't be accepting this PR. If you are interested in contributing more, [please reach out to us](https://www.selenium.dev/support/), and I am sure there are more opportunities to contribute. An alternative is to collaborate as @titusfortner suggests above, for example, a popular framework that might be interested is @asolntsev's Selenide.

**Comment by asolntsev** [comment]
@MathausC Yes, welcome to [Selenide](https://github.com/selenide/selenide) project! It's a testing library built on top of Selenium webdriver. Selenide adds various functionality, including locators a'la "by text", "by attribute" etc. 
It seems we don't yet have locator "by keyword", and we would add it with a pleasure.

**Comment by MathausC** [comment]
> I would like to see this feature in its own small project that Selenium can promote. There are hooks in the code to make it easy to extend the locators without them needing to be in the same module.
> 
> Would you be interested in collaborating on this?

Yes, sure. I'll love to contribute with it.

**Comment by MathausC** [comment]
> @MathausC Yes, welcome to [Selenide](https://github.com/selenide/selenide) project! It's a testing library built on top of Selenium webdriver. Selenide adds various functionality, including locators a'la "by text", "by attribute" etc. It seems we don't yet have locator "by keyword", and we would add it with a pleasure.

Thank you @asolntsev I'll take a look and reach out to you.

**Comment by titusfortner** [comment]
@MathausC if you want to chat with us on Slack, find us in #selenium-tlc channel — https://www.selenium.dev/support/#ChatRoom

**Pull request closed without merging**
