### PR TITLE
[js] fix: return statement in submit()

### PR DESCRIPTION
**Pull request by TamsilAmani**
### Description

The value evaluated by the submit() was not being returned.

### Motivation and Context

Help developers who use selenium to get correct result.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harsha509** [comment]
Makes sense!

Thank you @TamsilAmani !

**Review by harsha509 — DISMISSED** [review]
Thank you @TamsilAmani !

**Comment by titusfortner** [comment]
What result are we expecting from submit? It's an action on the browser, so the return should be `null`

**Comment by swrdfish** [comment]
@titusfortner @harsha509 
Thank you for looking into this.

I stumbled upon this bug while working on [Nightwatch](https://github.com/nightwatchjs/nightwatch). The problem is that `.submit()` is supposed to return a promise, which can be used to wait for the command to complete. Without the promise we cannot ensure that subsequent actions behave deterministically. It is not the value we are interested in but the promise to let us know when the command has finished.

**Pull request merged**
