### PR TITLE
Added new capabilities for safari driver: automaticInspection and automaticProfiling

### LINKED ISSUE #5307: Fix and actualize  SafariOptions class (java)
Please remove fields/capabilities from SafariOptions class:
* `cleanSession`: This property is migrated from old safaridriver by selenium, but it was never used by Apple's safaridriver (Safari always creates clean session). Because current version does not support deprecated driver this capability should be removed.  
* `port` : this deprecated field is not exposed to user and cause the issue #5020 which maked SafaryOption unusable (in grid environment) 

Add new capabilities which are [supported by safaridriver](https://webkit.org/blog/6900/webdriver-support-in-safari-10/)
* `automaticInspection`
* `automaticProfiling`

### PR DESCRIPTION
**Pull request by email2vimalraj**
Fixes #5307

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by lmtierney** [comment]
Is there anywhere these are documented? They don't follow the w3c spec for custom capabilities

**Comment by barancev** [comment]
They are documented here:
https://webkit.org/blog/6900/webdriver-support-in-safari-10/

**Comment by barancev** [comment]
The problem is that these new capabilities don't follow W3C rules for capabilities...

**Comment by email2vimalraj** [comment]
@lmtierney @barancev  I am raising this PR after a discussion on this with @shs96c during the "fix a bug be a committer" workshop that I attended two days back here in SeConf18 in Bangalore. As per my understanding I believe that some exceptions could be allowed. 

@shs96c can you please chime in ?

**Comment by shs96c** [comment]
@barancev all options are added to the `safari.options` capability, which is unchanged for a long time. 

I'm pinging Apple to try and figure out the right place to set this stuff. From the docs, it's not clear.

**Comment by shs96c** [comment]
I've had a conversation with the developer at Apple who's working most on safaridriver. Apparently, the options can be added as normal capabilities prefixed with `safari:`

**Comment by shs96c** [comment]
I'm tempted to merge this in and then make the fixups afterwards. Any objections from anyone?

**Comment by shs96c** [comment]
OK. My plan is to squash and merge this and then fix it up. This is a first commit from the "Fix a Bug, Become a Committer" workshop, so I'd like to thank @email2vimalraj for both attending and committing :)

**Comment by shs96c** [comment]
Congratulations on your first commit, @email2vimalraj!

**Comment by mmerrell** [comment]
+1, awesome!
MM

**Comment by email2vimalraj** [comment]
Thanks a lot for merging this PR. I'll try to contribute more.

**Pull request merged**
