### PR TITLE
Fixing Typo Errors

### PR DESCRIPTION
**Pull request by sruthi25**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Looks good to me!

Thank you @sruthi25 !

**Review by diemol — APPROVED** [review]
Thank you @sruthi25!

**Review by diemol — COMMENTED** [review]
@sruthi25 could you please sign the CLA?

**Comment by sruthi25** [comment]
> @sruthi25 could you please sign the CLA?

I have signed it but changes are not reflecting

**Comment by corevo** [comment]
The email account you've used to make the changes is not connected to your account

**Comment by diemol** [comment]
> > @sruthi25 could you please sign the CLA?
> 
> I have signed it but changes are not reflecting

The problem is that the commit is not associated with your GitHub user. Please double check that the email configured in your local git setup is associated with your GitHub account.
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account

**Comment by sruthi25** [comment]
> > > @sruthi25 could you please sign the CLA?
> > 
> > 
> > I have signed it but changes are not reflecting
> 
> The problem is that the commit is not associated with your GitHub user. Please double check that the email configured in your local git setup is associated with your GitHub account.
> https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account

**Comment by sruthi25** [comment]
> > > > @sruthi25 could you please sign the CLA?
> > > 
> > > 
> > > I have signed it but changes are not reflecting
> > 
> > 
> > The problem is that the commit is not associated with your GitHub user. Please double check that the email configured in your local git setup is associated with your GitHub account.
> > https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account

done

**Comment by sruthi25** [comment]
I have closed  mistakenly, could not reopen it

**Comment by diemol** [comment]
@sruthi25 the commit is still not associated with your GitHub account

Maybe double-check your local git configuration
here is a link that points out all the details https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by sruthi25** [comment]
There is a problem with email configuration, I am deleting this PR and creating new PR

**Comment by diemol** [comment]
Closing in favor of #8609

**Pull request closed without merging**
