### PR TITLE
Add ability to filter log entries by range of log levels

### PR DESCRIPTION
**Pull request by valfirst**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/5667)

### CODE REVIEW

**Comment by shs96c** [comment]
Would it not be nicer to pass in a `Predicate<LogEntry>`? That way you can just use a normal Java streams to deal with these.

**Comment by shs96c** [comment]
Looking closer, `LogEntries.getAll().stream().filter(entry -> true).collect(Collectors.toList())` would allow this, right? And then it becomes easier to add your own filters too.

**Comment by valfirst** [comment]
> Would it not be nicer to pass in a Predicate<LogEntry>? That way you can just use a normal Java streams to deal with these.

I can make `private List<LogEntry> filter(Predicate<LogEntry> logEntryPredicate)` public. Or do you propose to do not add methods filtering by levels at all?

\
The root cause of this PR: I've started using `LogEntries`, applied `filter(Level.WARNING)` and expected to get only warnings (who reads javadocs 😄), but I received warnings, errors and etc. So I thought, that it might be useful to have flexible API to get log entries of specified level or level range only, at least users may try to understand difference between overloaded methods.

**Comment by valfirst** [comment]
Closing: filter functionality was deprecated in `LogEntries`: https://github.com/SeleniumHQ/selenium/commit/c24ac7c1064a982c14b89742eda57219e420f770

**Pull request closed without merging**
