### PR TITLE
Replace calls to console.log with managed loggers

### LINKED ISSUE #12676: [🐛 Bug]: unnecessary console.debug messages in seleniumManager.js
### What happened?

Too many `console.debug` messages are printed when running tests.

I think it will be better if by default only warning/error messages are logged.

Some options to control the log level of NodeJS binding can be also useful.

### How can we reproduce the issue?

```shell
Create a simple project with NodeJS bindings and run the tests.
```

### Relevant log output

```shell
> npx jest tests/e2e

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

 PASS  tests/e2e/browser/screenshot.tests.ts
  ✓ should be able screenshot viewport (1871 ms)

 PASS  tests/e2e/components/grid.tests.ts
  ✓ should render cells (1918 ms)
  ✓ should render headers (233 ms)
  ✓ should be sorted (205 ms)
```

### Operating System

All

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

No

### PR DESCRIPTION
**Pull request by danielrozenberg**
### Description
This PR replaces calls to `console.<loglevel>()` in JS code with (hopefully) appropriate Selenium-managed loggers.

This also removes hardcoded logger names in existing managed logger calls with the referenced names (e.g., replacing `logging.getLogger('webdriver')` with (`logging.getLogger(logging.Type.DRIVER)`)

### Motivation and Context
Fixes #12676
(and related instances of the same logging issue that don't have a reported issue on GH)

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Hey Selenium team! I'm pretty confident about all tests passing, but didn't want to tick that box because I wasn't able to run all of them on my workstation, only by removing `edge` and `firefox` tests from the runner. The changes are in the `node` directory so I don't _think_ they should be affected

When reviewing, please pay extra attention to which loggers I used in each instance. I think my assumptions are grounded, but you never know :D

**Review by harsha509 — APPROVED** [review]
LGTM!

**Comment by titusfortner** [comment]
Sorry, not in a place to parse through the JS right now.

Which of the logging features in our docs - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
does this PR address?

**Comment by danielrozenberg** [comment]
This PR replaces uses of `console.log` (sorta JS's equivalent of `printf` to stdout) with Selenium's proper loggers

**Comment by diemol** [comment]
This is why https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/ was not working in all cases for JS, we were not leveraging the logger library. 

Thanks, @danielrozenberg!

**Review by diemol — APPROVED** [review]

**Comment by titusfortner** [comment]
Thanks!

**Pull request merged**
