### PR TITLE
Allow use of JUnit filters.

### PR DESCRIPTION
**Pull request by joshbruning**
Allow use of JUnit filters.

This change allows the JUnit Filter API to work correctly, and
will fall back to it being broken if some version of JUnit4's
Suite/ParentRunner hierarchy is incompatible with it. I've
verified this should work with at least JUnit 4.10, 4.11, and
4.12.

### CODE REVIEW

**Comment by barancev** [comment]
What's the purpose of this change? We don't use filtering. Well, actually we do filtering, but an alternative flavor of it: https://github.com/joshbruning/selenium/blob/patch-2/java/client/test/org/openqa/selenium/testing/SeleniumTestRunner.java#L80-L84

**Comment by joshbruning** [comment]
This is a bug fix, not a new feature.

bazel defines --test_filter and --test_arg (see http://bazel.io/docs/bazel-user-manual.html)
(buck defines ----test-selectors and -filter). These allow developers (me) to filter (for example a single test method) easily per invocation.

I'm not familiar with buck's implementation; however, bazel's is here: https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/junit/runner/junit4/JUnit4Runner.java

You can see how it uses org.junit.runner.manipulation.Filter for increased parallelization (sharding) as well as for including/excluding tests.

I would be quite surprised if buck is implemented using something other than the standard JUnit mechanism.

Suite and ParentRunner both support Filter correctly; however, Selenium's ParallelSuite does not. ParentRunner.run is not really intended to be overridden (without a super call) as it calls key private methods; it is public so that it can be invoked. ParentRunner implements Filterable (by extending Suite which extends ParentRunner), and it should honor any calls to its "public void filter(Filter filter)".

**Comment by barancev** [comment]
An attempt to apply this PR caused an exception:
```
java.util.Collections$UnmodifiableCollection cannot be cast to java.util.List
java.lang.ClassCastException: java.util.Collections$UnmodifiableCollection cannot be cast to java.util.List
	at org.openqa.selenium.testing.ParallelSuite.getFilteredChildren(ParallelSuite.java:75)
	at org.openqa.selenium.testing.ParallelSuite.run(ParallelSuite.java:55)
```

**Comment by joshbruning** [comment]
Thanks - I was wrong about 4.12. I'll update the code to support that version as well.

**Comment by joshbruning** [comment]
This should be ready for review again.

**Comment by joshbruning** [comment]
Hey, I squashed my commits and sync'd up to head. Would appreciate if someone would take a look so we can get this in, or I can just abandon it and update the Google-fork automation we have to ignore this change locally.

**Comment by shs96c** [comment]
After discussion on the IRC channel, it sounds like we don't need the ParallelSuite at all. I've deleted it, rendering this PR unnecessary.

**Pull request closed without merging**
