### PR TITLE
Update webelement.py

### PR DESCRIPTION
**Pull request by boobear2107**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
There are some `flake8` errors, could you please sort those.

**Comment by AutomatedTester** [comment]
@Dude-X could you check this as it an extension of your initial work

**Comment by Dude-X** [comment]
There are several issues with this PR.
# This code is not Python 2 and 3 compatible.
# EventFiringWebElement is already registered as a WebElement.
# The terminology is wrong. `wrapper_driver` when it's clear that it's a WebElement

There is a possibility that the code to unwrap the element is flawed, but you will have to show a simple test case to demonstrate the issue.

**Comment by AutomatedTester** [comment]
Closing as I don't think this is the way we want to go. I appreciate the effort that you put in to creating this PR. If you would like to discuss it further please feel free to come chat to us on IRC/Slack.

**Pull request closed without merging**
