### PR TITLE
[js] fix docs typos

### PR DESCRIPTION
**Pull request by Marketionist**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by Marketionist** [comment]
@mach6 @lukeis @titusfortner please review

**Comment by Marketionist** [comment]
Currently build in Travis failed with:
```
assert 'bob' == ''
```
(https://travis-ci.org/SeleniumHQ/selenium/jobs/187081577#L1338)

and

```
expected no Exception, got #<Selenium::WebDriver::Error::TimeOutError: timed out after 5 seconds (Unable to locate element: #oneline
```
(https://travis-ci.org/SeleniumHQ/selenium/jobs/187081595#L870)

So, it's definitely not because of the typos fixing in this PR.

**Comment by Marketionist** [comment]
I see your point @cgoldberg, agreed.  Added back extra spaces in license for consistency. Please re-review and merge if ok

**Comment by cgoldberg** [comment]
:+1:  I don't have access to merge though

**Comment by Marketionist** [comment]
Thanks for reviewing!

**Pull request merged**
