### PR TITLE
Add support for ISO 8601 date format for logs

### PR DESCRIPTION
**Pull request by artgo**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Add support for [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date format `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` as well as already converted Date object.

### CODE REVIEW

**Comment by artgo** [comment]
It is being passed by Android from Appium. See https://github.com/appium/appium/issues/6785

**Comment by artgo** [comment]
Lint failures (in appveyor) are unrelated and are in different files.

**Comment by artgo** [comment]
@lukeis FYI :)

**Comment by shs96c** [comment]
This is a bug on the part of Appium. The expectation is that log entry timestamps are (admittedly rather oddly for JSON) numbers representing the UNIX Epoch timestamp at which the log entry was created.

Thank you, however, for taking the time to file this PR!

It should be noted that `SimpleDateFormat` is not thread-safe. Putting it on the `static` field will at some point lead to unusual error cases.

**Pull request closed without merging**
