### PR TITLE
Fix Require.java for #14088

### PR DESCRIPTION
**Pull request by vlad8x8**
### **User description**
Fix for https://github.com/SeleniumHQ/selenium/issues/14088

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Fix for #14088 

### Description
Check if the browser path is Windows app execution alias before checking if it's a file.

### Motivation and Context
Selenium manager is failing on  Windows app execution aliases

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix

___

### **Description**
- Added a new method `isWindowsAppExecutionAlias` to check if the browser path is a Windows app execution alias.
- Modified the `isExecutable` method to use the new alias check before verifying if the file is executable.
- This resolves the issue where Selenium manager fails on Windows app execution aliases.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Require.java</strong><dd><code>Add Windows app execution alias check in Require.java</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/internal/Require.java

<li>Added method <code>isWindowsAppExecutionAlias</code> to check for Windows app <br>execution aliases.<br> <li> Modified <code>isExecutable</code> method to incorporate the new alias check before <br>verifying if the file is executable.<br> <li> Imported necessary classes for file attribute handling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14151/files#diff-f50b7e191924359188430521dce38b2907db5e70cb9939e89a8f8d8c74cf22fc">+21/-2</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by joerg1985** [comment]
This PR does mix the `java.io` and the `java.nio` way of doing things. I would suggest to deprecate the `java.io` stuff (using the File class) and create a new `isExecutable` using the Path, which does not call `isRegularFile`. @vlad8x8 would you like to update the PR or should i do the change?

**Comment by vlad8x8** [comment]
Hi @joerg1985 . Unfortunatelly `Files.isExecutable(path)` and `file.isExecutable()` returns different values for Windows app execution aliases. Feel free to change it as you want, if it works for Windows app execution aliases. 
You can find some aliases on Win10 in folder `<UserFolder>\AppData\Local\Microsoft\WindowsApps`
Targets for those aliases you can find in Windows registry `HKCU:/SOFTWARE/Microsoft/Windows/CurrentVersion/App Paths`

**Comment by joerg1985** [comment]
@vlad8x8 i have pushed a fix in 2a7ddf1fdeb724bb5f4bd6cd64867894aa485add therefore i close this.
Thanks for reporting and helping to locate the issue.

**Comment by vlad8x8** [comment]
@joerg1985 did you test your commit against app execution aliases?
java.nio.file.LinkOption.NOFOLLOW_LINKS is critical for them, but you don't use it in your PR

**Comment by joerg1985** [comment]
I have tested `Files.isExecutable` does return true for `msteams.exe`, but i will double check it tomorrow with the nightly build.

**Pull request closed without merging**
