### PR TITLE
Adding customizable browser_name capability to microsoftedge

### PR DESCRIPTION
**Pull request by stanleyhon**
msedgedriver allows driving of edge based targets such as [WebViews](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2). msedgedriver expects the browserName capability to be provided differently in order to differentiate between driving edge or an edge-based webview.

This change updates the edge variant of `Options` to allow specifying the browserName capability, This overrides what is requested to msedgedriver.

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Are you able to write tests for this change?

**Comment by stanleyhon** [comment]
Would adding something similar to the existing tests in https://github.com/SeleniumHQ/selenium/blob/master/py/test/unit/selenium/webdriver/edge/edge_options_tests.py be enough?

I would verify specifying `options.custom_browser_name = "someTestvalue"` results in the value being outputted when option is asked to produce a capability set with `toCapability`.

**Comment by stanleyhon** [comment]
@AutomatedTester just following up to see if my suggested resolution would be sufficient before I go implement the wrong thing :)

**Comment by AutomatedTester** [comment]
> Would adding something similar to the existing tests in https://github.com/SeleniumHQ/selenium/blob/master/py/test/unit/selenium/webdriver/edge/edge_options_tests.py be enough?
> 
> I would verify specifying `options.custom_browser_name = "someTestvalue"` results in the value being outputted when option is asked to produce a capability set with `to_capabilities`.

That is a good place to put it

**Comment by stanleyhon** [comment]
@AutomatedTester I've added a test as we discussed and the test passes on my local box. Let me know if you notice anything else.

**Pull request merged**
