### PR TITLE
Fixed references to chromedriver website

### LINKED ISSUE #7630: Change chromedriver download links from Google Sites to actual domain link?
## 🐛 Bug Report
In many places in the code, both in comments and in error messages, links are made to https://sites.google.com/a/chromium.org/chromedriver. It seems as though it would be more sensible to link to the actual Chromium website for this at https://chromedriver.chromium.org/, in case the chromedriver host changes and the URL is no longer valid. **I would be more than happy to fix and PR this but I want to check that it wouldn't be better to keep it as it is.**

## To Reproduce
n/a

## Expected behavior
Links should be made to https://chromedriver.chromium.org/, rather than https://sites.google.com/a/chromium.org/chromedriver

## Test script or set of commands reproducing this issue
https://github.com/SeleniumHQ/selenium/search?q=sites.google.com&unscoped_q=sites.google.com

## Environment
n/a

### PR DESCRIPTION
**Pull request by pbeart**
Changed all references to the chromedriver project Google Sites URL
(https://sites.google.com/a/chromium.org/chromedriver/) to be to the
project's actual domain and official site,
https://chromedriver.chromium.org/.

Fixes #7630

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by barancev** [comment]
One more file lost:
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by pbeart** [comment]
Thanks, not sure how that didn't come up in my search. Do I just edit my repo, squash those two commits together then remake the pull request?

**Comment by barancev** [comment]
You can simply add another commit to the PR, we'll squash them before merge.

**Comment by cgoldberg** [comment]
... or just edit your local and push to the same remote branch... that will update the PR.  a maintainer can squash your commits when merging.

**Comment by pbeart** [comment]
I've added that change, not sure if you get notified by commits to branch-to-be-merged in the same way you do for comments

**Comment by barancev** [comment]
Merged as 0d2a9b4844bc0ae6e17cd9d32b344a770f3b4878, thank you for the contribution!

**Pull request closed without merging**
