### PR TITLE
Issue #386 implementing __repr__ for WebElement

### PR DESCRIPTION
**Pull request by aricearice**

### CODE REVIEW

**Comment by lukeis** [comment]
looks good to me. Have you signed the [CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)?

**Comment by aricearice** [comment]
@lukeis yes, I just signed it.

**Comment by AutomatedTester** [comment]
Why are you outputting? I don't think it has value here

**Comment by AutomatedTester** [comment]
Ignore my previous comment.


Why are you outputting w3c? I don't think it has value here

**Comment by santiycr** [comment]
@aricearice thanks for your contribution!! If you're interested in a Sauce swag box, can you share your address and shirt size with me to sso @ saucelabs com please? (and your teammate as well!)

**Comment by santiycr** [comment]
I agree with @AutomatedTester. I would remove the w3c attribute from the output and for parent. 
I think the format of the final string needs some tweaking. Here's what the default `__repr__` looks like:
```python
<selenium.webdriver.remote.webelement.WebElement object at 0x1052aa2d0>
```

Here's what it looks like with the change:
```python
WebElement(parent=<selenium.webdriver.remote.webdriver.WebDriver object at 0x10a4a3950>, id_="0.27372260647825897-1", w3c=False)
```
I think a better looking version would be:
```python
<selenium.webdriver.remote.webelement.WebElement object (session_id=**self.parent.session_id**, id_="0.27372260647825897-1">
```

**Comment by aricearice** [comment]
okay, now the final string looks like: 
```
<class 'selenium.webdriver.remote.webelement.WebElement'>(session="d26385ad17cfce0f4e894b351f12faf3", element="0.999454349745065-1")
```

**Comment by lukeis** [comment]
merged as b2219e10837dd33d9ada49cbe697bb81a5f3aa28

**Comment by santiycr** [comment]
great job, @aricearice! Thanks

**Comment by wongterrencew** [comment]
Hi @santiycr, I was the teammate and a sauce swag box sounds awesome!

**Comment by santiycr** [comment]
awesome @wongterrencew. Please email me as well and I'll make it happen!

**Pull request closed without merging**
