### PR TITLE
UnreachableBrowserException logs the command parameter details only in debug mode

### LINKED ISSUE #11275: [🚀 Feature]: let the UnreachableBrowserException not leak details of the command
### Motivation
If a `UnreachableBrowserException` is raised in a sensitive area there will be sensitive information in the logs.

e.g. the basic-auth infos are leaked here
```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: com.my.company.ta.driver.factory.SeleniumDrivers$2
Command: [4ade0fd2dd7fa0b55833438a7af7386d, get {url=https://user:password@mysavedomain.com/}]
Capabilities ...
Session ID: 4ade0fd2dd7fa0b55833438a7af7386d
Caused by: java.io.UncheckedIOException: java.net.http.HttpTimeoutException: request timed out
Caused by: java.net.http.HttpTimeoutException: request timed out
```

### Feature
There are several options to ensure the parameters are not logged in the CI pipeline:

a) Modify the `UnreachableBrowserException` to only contain the parameter values if `org.openqa.selenium.internal.Debug.IS_DEBUG` is set to true. In other cases it should be enought to know the names of the parameters send.

b) Modify the UnreachableBrowserException to respect a new system property e.g. `org.openqa.selenium.SUPPRESS_COMMAND_PARAMETERS`. If this flag is set only dump the name of the parameters set.

### Usage example

We are using encryption to ensure secrets are not visible to regular users in our continuous integration pipeline.
E.g. a Jenkins user can view the logs & workspace, but there are only encrypted secrets.
The logging will also ensure there are no secrets shown in the build logs.

A UnreachableBrowserException will currently leak this informations to regular users usually not able to read this informations.

### PR DESCRIPTION
**Pull request by debanjanc01**
### Description

This resolves: https://github.com/SeleniumHQ/selenium/issues/11275
In the case when `UnreachableBrowserException` is raised, only the command parameter names will be logged (unless in debug mode) so as to not reveal any sensitive information. 

In order to test the changes, `org.mockito:mockito-inline` has been added as a dependency.
### Motivation and Context

This solves: https://github.com/SeleniumHQ/selenium/issues/11275
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
@debanjanc01 sorry we did not review this in a timely manner, but it needs to be rebased with trunk. Can you update it?

**Comment by debanjanc01** [comment]
> @debanjanc01 sorry we did not review this in a timely manner, but it needs to be rebased with trunk. Can you update it?

Hey @titusfortner sure I'll rebase and update the PR.

**Comment by debanjanc01** [comment]
@titusfortner I've rebased with trunk

**Review by diemol — APPROVED** [review]
Thank you, @debanjanc01!
I made some adjustments, but most of the work was already there.

**Comment by joerg1985** [comment]
@diemol i am to late with my review, but one question, why is there a `toThrow instanceof UnreachableBrowserException && !Debug.isDebugging()` condition and not only a  `!Debug.isDebugging()` condition?

My original issue described it in the case of a `UnreachableBrowserException` but are there no other cases where we could leak infos e.g. by a `NoSuchSessionException`?

**Comment by diemol** [comment]
I did not spend time analyzing the whole range of possibilities. If there is more, let's specify it here, and reopen so we can iterate.

**Comment by debanjanc01** [comment]
@joerg1985 I did think of the possibilities of other Exception cases having the same bug. But since the original issue mentioned UnreachableBrowserException specifically I've added the explicit `instanceof` check. 
I agree with @diemol , we could iterate on this to cover the whole range of possibilities.

**Pull request merged**
