### PR TITLE
selenium-webdriver: update Ruby gem YARD to v0.9.9

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates the API docs gem YARD to its latest release.

- Was fixed at v0.8.7 (released on 26 Oct 2014)
- Is now v0.9.9 (latest)

[YARD releases](https://github.com/lsegal/yard/releases)

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by lmtierney** [comment]
Is there anything specific you were wanting to include from a newer version that we can't currently accomplish?

**Comment by p0deje** [comment]
Do you have any dependency collissions?

**Comment by p0deje** [comment]
Thank you, merged in c39752cedbd0223df8b7bf4cf19bd50cf7706da7.

**Comment by olleolleolle** [comment]
(Mostly I wanted us to avoid any spurious warning outputs, keep it shiny.)

**Pull request closed without merging**
