### PR TITLE
Dot editorconfig

### PR DESCRIPTION
**Pull request by ddavison**
based on the source so far, these are the settings I could see.

IntelliJ 14, as well as [many](https://github.com/sindresorhus/editorconfig-sublime) [other](https://github.com/sindresorhus/atom-editorconfig) [IDEs](https://github.com/ncjones/editorconfig-eclipse)/[editors](https://github.com/editorconfig/editorconfig-notepad-plus-plus) support [this file](http://editorconfig.org/).

screen shot 2015-03-18 at 07 42 13

### CODE REVIEW

**Comment by andreastt** [comment]
I'm -1 on more configurations.

**Comment by nirvdrum** [comment]
I don't have a problem with the changes.  But I don't think I've ever seen an update to the IDEA config files that didn't conflict with my local checkout (I think I always have to change the SDK location), so each update means I need to blow away whatever is working and set up my environment all over.  If we can fix that problem, I'd be more amenable to other IDE config changes.

**Comment by ddavison** [comment]
well the `.editorconfig` file is unique.. there is a `root = true` property that you can add to your workspace folder, (mine is ~ddavison/workspace) and in there, i have an .editorconfig that has `root = true`, then in my `~ddavison/workspace/selenium` folder, I have the .editorconfig overrides (since i usually use 4 spaces for java)

**Comment by barancev** [comment]
Am I right that this config file needs a special plugin to be installed in an IDE?

**Comment by ddavison** [comment]
it *is* technically a plugin, but it does get installed by default when you install IDEA 14.  (also in the Community Edition)

**Comment by barancev** [comment]
IDEA is not a problem as there is .idea/codeStyleSettings.xml file committed to the repository.
What about other IDEs?

**Comment by ddavison** [comment]
Well, the entire premise of the .editorconfig is

> "[EditorConfig] helps developers define and maintain consistent coding styles between different editors and IDEs."

[EditorConfig](https://github.com/editorconfig) has released all kinds of plugins for many IDE's

- IDEA
- [Visual Studio](https://github.com/editorconfig/editorconfig-visualstudio)
- [Emacs](https://github.com/editorconfig/editorconfig-emacs)
- [Vim](https://github.com/editorconfig/editorconfig-vim)
- ...

It's just nice for developers who use editorconfig, that we let the repository tell how the code should be written

**Comment by nirvdrum** [comment]
I'm ambivalent on the change.  I don't really see a problem with it going in, other than maybe some bikeshedding around various styles.  But having a consistent style is a laudable goal.

**Comment by andreastt** [comment]
I agree with that, @nirvdrum. Should we land this then

**Comment by nirvdrum** [comment]
Sure.  At worst, we revert it if it turns out to be problematic.

**Pull request merged**
