### PR TITLE
[java] use the correct base64 decoder

### PR DESCRIPTION
**Pull request by joerg1985**
### Description
Use the correct base64 decoder (RFC4648) as defined by the WebDriver specification.

### Motivation and Context
Selenium should follow the WebDriver specification

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by pujagani — APPROVED** [review]
Thank you @joerg1985 !

**Comment by weikilla** [comment]
hi , why do this change? i am using appium java client, which is depend on this project. but currently, when i call screenshot method, will throw Illegal base64 character xxx, i found the root cause is this change.

**Comment by joerg1985** [comment]
@weikilla the W3C WebDriver specification does specify the Base64 decoder to use, see: https://www.w3.org/TR/webdriver/#index

I think you should open a ticket at appium to get this fixed in the corresponding driver.
Alternatively they could overwrite the selenium implemenation, if they need a none W3C compliant implementation.

Just my two cents, the selenium team might have a different opinion on this 😄

**Comment by mykola-mokhnach** [comment]
This change will break the backward compatibility between following java client versions and existing Appium drivers. We'd have to hack this implementation in Appium java client to workaround it.

Even if we update the thing for multiple drivers, existing versions of them stay unchanged and there would be a mess.

cc @diemol @titusfortner @valfirst @SrinivasanTarget

**Comment by titusfortner** [comment]
@mykola-mokhnach can you please create an issue to make sure we track this? I don't understand the difference in implementations, so I'd vote for reverting it in the next release and figuring out a better path forward if we need to make the change.

**Comment by mykola-mokhnach** [comment]
@titusfortner created https://github.com/SeleniumHQ/selenium/issues/11168

**Pull request merged**
