### PR TITLE
[C#] Fix deselecting options in <select>

### PR DESCRIPTION
**Pull request by glibas**
1. Add NoSuchElementException when deselecting non-existing option
2. Remove check !isMultiple() when selecting/deselecting by index.
3. Add exception when deselecting non-multiselect

### CODE REVIEW

**Comment by glib-briia** [comment]
Hi @lukeis ,

Could you please have a look on this pr.

It is similar to https://github.com/SeleniumHQ/selenium/pull/1623, just mirror the changes in .NET client.

**Comment by jimevans** [comment]
I'll take a look later today.

**Comment by glib-briia** [comment]
Hi @jimevans ,

Thank you

**Comment by glib-briia** [comment]
Forgot to mention: _CLA is signed._

**Comment by jimevans** [comment]
Merged in 6e4dfca. Thank you for your contribution.

**Pull request closed without merging**
