### PR TITLE
[py] add safari service tests

### PR DESCRIPTION
**Pull request by Delta456**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add safari service tests

### Motivation and Context

Add because they were missing 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Tests

___

### **Description**
- Added new test cases for the Safari service to ensure proper functionality.
- Implemented setup and teardown for environment variables in the test suite.
- Verified the service path is correctly set and updated based on environment variables.
- Tested the service's logging capabilities and service URL configuration.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add license header to Safari test init file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/safari/__init__.py

- Added license information and file header.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14700/files#diff-0cf3a88ecb6c72c2c01a7dfa6adab6740c21918231ac8dd2060592b60b3f39e7">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>safari_service_tests.py</strong><dd><code>Add Safari service test cases</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/safari/safari_service_tests.py

<li>Added new test cases for Safari service.<br> <li> Implemented environment variable setup and teardown.<br> <li> Tested service path and logging functionality.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14700/files#diff-2a95e98da6223c7e658c7e61dfd7a0de6380b021736bfd5fb2aa83a6963cd41d">+54/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
I guess the tests are not running in CI

**Comment by Delta456** [comment]
> I guess the tests are not running in CI

Yes, looks like I need to edit the CI to add it to `CI / Python / Safari Tests / Integration Tests (safari) (pull_request)` ?

**Comment by VietND96** [comment]
Let me add full tests of Safari to CI in trunk first. Last few days I added but there were 9 test failures, so I decided to add the launcher tests only.
Probably I mark skip for those failure and we will get back to fix later.

**Comment by Delta456** [comment]
This test passes locally. We can add this test in the CI and get back to the rest later.

**Comment by VietND96** [comment]
While patching 4.26.1 for python, we missed catching a broken for safari webdriver #14699 due to no safari tests in CI.
I also checked other bindings java, rb, there is runner: macOS used there. However, there is no browser: safari is enabled.
So, via this PR, we want to enable safari-test for python. There are few failed tests marked as `xfail_safari` (some of tests are being marked as fail in other browser, remote)
@AutomatedTester, can you review this to see if it is fine?

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
