### PR TITLE
Java: Minor DefaultFieldDecorator improvement 

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
Visibility of the "isDecoratableList" method has been changed to
Protected.

### CODE REVIEW

**Comment by sevaseva** [comment]
LGTM.

Two things:
- have you signed CLA https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla ? (sorry if you indicated so in the past)
- can you please modify the commit message to indicate the intent of this change; describe the issue that it's fixing or otherwise explain why you would like this change to me merged. It is relatively obvious here, but I stating things explicitly in the commit log increases the quality of the codebase. (for example your https://github.com/TikhomirovSergey/selenium/commit/5fc375516ea8779af271fa26efe4ef91606a7c39 does a better job explaining reasons)

**Comment by TikhomirovSergey** [comment]
Hi @sevaseva 
Right now I have signed the Contributor License Agreement. Today I'm going to modify descriptions of both my commits: [this](https://github.com/TikhomirovSergey/selenium/commit/c6bc33b3efc60d3ffcf2ef73925fc6d6ac8f8e71) and [that](https://github.com/TikhomirovSergey/selenium/commit/5fc375516ea8779af271fa26efe4ef91606a7c39). Thank you for remarks :)

**Comment by TikhomirovSergey** [comment]
Comments have been amended.

**Comment by sevaseva** [comment]
Thank you @TikhomirovSergey !
Sorry for the delay (tm).
I merged the new commit of yours as 860ff26abc95d3d49546b0b7f3aec229b4ba4d0a.
For future notice, please keep pull request include exactly one commit (or more if there are more than one logical change and for some reason you have to propose them in one PR). When you need to update the PR, just force-push the new content to the branch that the PR is based on.
Thanks again for contributing. I'll let a bigger PageFactory enthusiast review your "Page Factory enhancement" PR.

**Pull request closed without merging**
