### PR TITLE
[js] download files from remote server

### PR DESCRIPTION
**Pull request by titusfortner**
### Status
In draft because downloadFile does not yet work.

@harsha509 I updated this as best I can figure, but `downloadFile` is a copy/paste from ChatGPT and I'd be shocked if it worked. Can you help me figure out the right implementation for that functionality?

### Description
* adds capability `enableDownloads`
* errors if using method without setting capability
* `getDownloadableFiles` returns direct list of names
* `downloadFIle` — needs help
* downloadFile creates directory if does not exist
* deleteDownloadableFiles deletes all files

### Motivation and Context
implement #11657

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @titusfortner

**Comment by limuyuan** [comment]
Hello @titusfortner , is using JS to download files from Remote WebDriver still not supported?

**Comment by titusfortner** [comment]
It should work. Are you having a problem?

**Comment by limuyuan** [comment]
> It should work. Are you having a problem?

I'm always getting the below error message when trying to `downloadFile`
```
 Uncaught WebDriverError WebDriverError: Cannot find file [[selenium-java-4.21.0.zip]] in directory C:\Users\admin\AppData\Local\Temp\1\uuid13931905917359662002f7930a56-f43c-4f3d-b955-d6cfd9cafa88\download16040450071988999621.
```

I found this PR from changelog and I have noticed you said the `downloadFile` should not work.
After comparing codes with the trunk, there's nothing new, so I believe it's still not working.

**Comment by limuyuan** [comment]
I have submitted an issue: #14111

**Pull request merged**
