### PR TITLE
[java] Webdriver can work with embedded apps without CDP

### PR DESCRIPTION
**Pull request by vlad8x8**
Webdriver for New MS Teams can start only added an argument `remote-debugging-port=<any number>` to EdgeOptions. But Teams is actually staring at random port and ChromiumDriver is failing to create a CDP connection. If the connection is empty, Teams starts well and webdriver can interact with Teams well.

### Description
Connection can be empty if CromiumDriver can not create it

### Motivation and Context
CromiumDriver can't connect to New MS Teams

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Thank you for your PR.

Could you please share more information or a link about this use case? We'd probably be fine with this change, but I would like to document the change after understanding the intent better.

**Comment by vlad8x8** [comment]
> Thank you for your PR.
> 
> Could you please share more information or a link about this use case? We'd probably be fine with this change, but I would like to document the change after understanding the intent better.

As mentioned in the description, the main use case is The New MS Teams (https://adoption.microsoft.com/en-us/new-microsoft-teams/) based on Edge browser.
I'm sorry, but I don't clearly understand how that connection is working, but locally I just set in debugging `connection = empty` and it's running well

**Review by diemol — CHANGES_REQUESTED** [review]
Could you please check? The code is not building. https://github.com/SeleniumHQ/selenium/actions/runs/4859217466/jobs/8661644754

**Comment by vlad8x8** [comment]
> Could you please check? The code is not building. [SeleniumHQ/selenium/actions/runs/4859217466/jobs/8661644754](https://github.com/SeleniumHQ/selenium/actions/runs/4859217466/jobs/8661644754)

fixed

**Comment by vlad8x8** [comment]
Hi @diemol 
Could you please re-review the PR?

**Comment by vlad8x8** [comment]
Hi @diemol 
Could you please review the requested change?

**Comment by titusfortner** [comment]
He's on holiday. Thanks for the PR, but we'll get to it when we can.

**Review by diemol — APPROVED** [review]
Thank you, @vlad8x8!

**Pull request merged**
