### PR TITLE
[dotnet] Json serializer gen context for SM output

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
Use generated json serializer context for Selenium Manager json output.

### Motivation and Context
To be friendly with AOT.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Enhanced JSON deserialization by replacing `JsonNode` with a strongly typed `SeleniumManagerResponse` class, improving type safety and clarity.
- Introduced `JsonSerializerOptions` with a custom serializer context to support AOT (Ahead Of Time) compilation.
- Updated the `RunCommand` method to utilize the new structured response class, ensuring more reliable data handling.
- Added internal classes `SeleniumManagerResponse`, `LogEntryResponse`, and `ResultResponse` to represent the JSON structure.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>SeleniumManager.cs</strong><dd><code>Implement strong typing for JSON deserialization in SeleniumManager</code></dd></summary>
<hr>

dotnet/src/webdriver/SeleniumManager.cs

<li>Replaced <code>JsonNode</code> with a strongly typed <code>SeleniumManagerResponse</code> class.<br> <li> Introduced <code>JsonSerializerOptions</code> with a custom serializer context.<br> <li> Updated the <code>RunCommand</code> method to use the new response class.<br> <li> Added internal classes for structured JSON deserialization.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14481/files#diff-df9a0140c4ef310382b15de2b26d228971d00530d18f4c1bd3c74f735c3af665">+50/-17</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by nvborisenko** [comment]
Blocked by https://github.com/bazelbuild/rules_dotnet/issues/443

**Comment by purkhusid** [comment]
This has been fixed in rules_dotnet. I tested it out on this branch and you can fix it with the following patch:
```
diff --git a/MODULE.bazel b/MODULE.bazel
index 348c66a2bf..ea0a6a3aa2 100644
--- a/MODULE.bazel
+++ b/MODULE.bazel
@@ -26,6 +26,11 @@ bazel_dep(name = "rules_pkg", version = "0.10.1")
 bazel_dep(name = "rules_python", version = "0.33.0")
 bazel_dep(name = "rules_proto", version = "6.0.0")
 bazel_dep(name = "rules_ruby", version = "0.11.0")
+git_override(
+    module_name = "rules_dotnet",
+    commit = "cb4545964decdca5d4cc984e170635a2dc3bc893",
+    remote = "https://github.com/bazelbuild/rules_dotnet",
+)
 
 linter = use_extension("@apple_rules_lint//lint:extensions.bzl", "linter")
 linter.configure(
diff --git a/dotnet/paket.dependencies b/dotnet/paket.dependencies
index 35689c8116..e7e982d52f 100644
--- a/dotnet/paket.dependencies
+++ b/dotnet/paket.dependencies
@@ -24,5 +24,6 @@ nuget System.Diagnostics.Tools 4.3.0
 nuget System.Drawing.Common 7.0.0
 nuget System.Runtime 4.3.1
 nuget System.Runtime.InteropServices 4.3.0
-nuget System.Text.Json 8.0.4
+nuget System.Text.Json 8.0.0
+nuget System.Text.Encodings.Web 
 nuget Runfiles 0.12.0
diff --git a/dotnet/src/webdriver/BUILD.bazel b/dotnet/src/webdriver/BUILD.bazel
index 1f23755fa1..00db006f6e 100644
--- a/dotnet/src/webdriver/BUILD.bazel
+++ b/dotnet/src/webdriver/BUILD.bazel
@@ -56,6 +56,7 @@ csharp_library(
         framework("nuget", "System.Threading.Tasks.Extensions"),
         framework("nuget", "System.Memory"),
         framework("nuget", "System.Text.Json"),
+        framework("nuget", "System.Text.Encodings.Web"),
     ],
 )
 

```

I'll be cutting a new rules_dotnet release soon and then the override in `MODULE.bazel` can be removed

**Comment by nvborisenko** [comment]
That's great! I verified locally, and seems it works smoothly:

image

So, just waiting official release. Thank you @purkhusid!

**Comment by nvborisenko** [comment]
Finally it is happening, thanks all participants!

**Pull request merged**
