### PR TITLE
[java][sm] Configure Selenium Manager environment from System Properties

### LINKED ISSUE #13857: [🚀 Feature]: Allow to configure Selenium Manager from java
### Feature and motivation

Currently, the Java bindings do not allow to directly change the Selenium Manager configuration .
The only way to manage this configuration is to define environment variables at OS level (windows) or to use a configuration file.
Both approaches require initial manual configuration on every new machine/os. It requires to write/read additional guides, to execute additional steps by users, who need to execute tests locally (example: manual qa team)

The one of the solutions is to use Java's systems properties and pass them as environment variables into Selenium Manager process (only those, which have prefix 'SE_'
Anther solution is to find a way to pass a path to the custom configuration file (se-config.toml)

### Usage example

For our project we want to make things simple: All required configuration should be initialized automatically by the framework code, without additional actions on the part of an inexperienced user who needs to run tests locally. 
This avoids potential problems with incorrect configurations, as well as avoiding additional infrastructure maintenance steps (which basically is the main purpose of this library).

P.S>
The properties, which we require to configure:
--driver-mirror-url, --browser-mirror-url  (to our local mirrors)
--force-browser-download to use CfT instead of local version (when versions are the same)
--ttl  (1h is too little for our case - we want to avoid version switch when use qualifiers like 'stable'). Going to use this key with:
--cache-path : to have local project cache (for  stable browser version during --ttl)

### PR DESCRIPTION
**Pull request by kool79**
## **User description**
Fixes #13857 

Allow to configure Selenium Manager from java bindings with help of java System Properties

### Description
  Configure a Selenium Manager with a system properties from Java

  When create process for Selenium Manager, pass the System Properties from java, which start with `SE_` prefix, to the Selenium Manager process.  With this approach, non-empty system properties, which are defined in java, have a higher priority over the environment variables (for Selenium Manager process only)

### Motivation and Context
See #13857 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

## **Type**
Enhancement

___

## **Description**
- This PR introduces the ability to configure the Selenium Manager using Java system properties that start with the `SE_` prefix.
- System properties are now prioritized over environment variables for configuring the Selenium Manager, providing more flexibility and control from within Java applications.
- The process builder for the Selenium Manager has been updated to include these system properties in its environment, ensuring that configurations are respected during runtime.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>SeleniumManager.java</strong><dd><code>Enhance Selenium Manager Configuration via System Properties</code></dd></summary>
<hr>
      
java/src/org/openqa/selenium/manager/SeleniumManager.java

<li>Added support for configuring Selenium Manager using Java system <br>properties prefixed with <code>SE_</code>.<br> <li> Enhanced the process builder to include system properties in the <br>environment of the Selenium Manager process.<br> <li> Modified cache path determination logic to prioritize system <br>properties over environment variables.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13858/files#diff-bc018f8fe13b0ca29c19df281b697583c7ab6ff28e052677871ad22c300464d2">+23/-7</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — APPROVED** [review]
Thank you, @kool79!

**Comment by diemol** [comment]
@kool79 do you think you can help us and update the docs for Selenium Manager, please?

**Comment by titusfortner** [comment]
@diemol do we need to do this in the other bindings?

**Comment by diemol** [comment]
No.
This was necessary because there is no straightforward way to create environment variables in Java.

**Pull request merged**
