### PR TITLE
Fix to avoid security vulnerability

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Netty repo which is being used has a potential security vulnerability

Also safari driver is using the same netty repo which has a securtiy threat and severity shows "medium".It would be really great to move to latest to avoid these security threats.

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
screen shot 2016-05-08 at 3 35 36 pm

**Comment by SrinivasanTarget** [comment]
@shs96c Please look into this

**Comment by lukeis** [comment]
We also primarily build off the dependencies in third_party, please update there too:
https://github.com/SeleniumHQ/selenium/tree/master/third_party/java/netty

**Comment by jleyba** [comment]
Netty 4.x introduces wide ranging API changes, so even if you update the JARs correctly, you'll break the Selenium build. Please update your PR to include the appropriate code changes for a 3.x -> 4.x update.

**Comment by SrinivasanTarget** [comment]
Sure will do that...

**Pull request closed without merging**
