### PR TITLE
Make shouldCache overridable/accessible

### PR DESCRIPTION
**Pull request by ghost**
Added a getter method for shouldCache. So this is overridable and accessible in inheriting classes.

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by krmahadevan** [comment]
@phoenix384 - Just curious. 

```java
this.shouldCache = annotations.isLookupCached();
```
 
is being initialized like this and `annotations` is of type `AbstractAnnotations` which can be sub-classed and `shouldCache` can be controlled via it. So why not use that ? You can take a look at my blog [here](https://rationaleemotions.wordpress.com/2016/06/27/pagefactory-page-objects-and-locators-from-an-external-file/) for some code snippets to show you what I am talking about.

**Comment by phoenix384** [comment]
In case of inheriting from class DefaultElementLocator and using the constructor DefaultElementLocator(SearchContext, Field) I cannot control the Annotations.
And I don't think an additional getter would hurt.

**Comment by phoenix384** [comment]
This is just a simple getter and nobody cares about this PR for 3 months. That doesn't really motivate to contribute.

**Comment by krmahadevan** [comment]
ping @shs96c @barancev - Simon/Alex can you please help take a look at this PR ?

**Comment by krmahadevan** [comment]
@phoenix384 - I understand your frustration because I myself have experienced it. But please also be considerate of the fact that the selenium dev community is just a handful bunch of folks who are devoting their free time to this project. 

I would suggest that you try pinging folks on the IRC chat with this PR to get some traction on this one. But now that this is the holiday season, I doubt if anyone is going to be around. 

I am not part of the core dev community, so I can't do much to help you out here!

**Comment by shs96c** [comment]
Apologies for the slow review of this --- work and the holidays slowed me down.

**Pull request merged**
