### PR TITLE
FirefoxDriver.cs

### PR DESCRIPTION
**Pull request by Johnsavadkuhi**
using System.Collections.ObjectModel
using System.Globalization
using System.Text
using System.Text.RegularExpressions
using OpenQA.Selenium.Firefox.Internal
using OpenQA.Selenium.Internal 

they are not necessary

### CODE REVIEW

**Comment by mohammadsavadkuhi** [comment]
i think they are not important in source code

**Comment by jimevans** [comment]
Please don't submit pull requests removing unused `using` clauses. These do not cause any harm by being there, and there are a large number of files with them, so one file at a time is unnecessary.

**Comment by ddavison** [comment]
thanks for the contribution, however @mohammadsavadkuhi! :+1: there are a ton more areas you could try for

**Comment by mohammadsavadkuhi** [comment]
how can i help to this project @jimevans   @ddavison  ?

**Comment by lukeis** [comment]
@mohammadsavadkuhi a good place to start (if you don't have any particular issue yourself) is to look at the issues list and try to fix one :)

**Pull request closed without merging**
