### PR TITLE
Python 3.2+ instead of listing specific Python 3.x versions

### PR DESCRIPTION
**Pull request by nikolas**
Python 3.4 is listed as being supported by Selenium in setup.py:
https://github.com/SeleniumHQ/selenium/blob/master/setup.py

### CODE REVIEW

**Comment by ivargas-handy** [comment]
Can you test Python 3.5 as well, and add that?

**Comment by cgoldberg** [comment]
Perhaps it should just read: "Python 3.2+", rather than listing specific versions.  I don't believe the project's CI actually runs all those versions anyway.  

Also... I haven't tested it exhaustively, but CPython 3.5 should work fine.

**Comment by nikolas** [comment]
@cgoldberg good idea. I've added a new commit to this branch.

**Comment by lukeis** [comment]
merged in 4b14c304934f8559ef6c755ffa39caed1d685d5c

**Pull request closed without merging**
