### PR TITLE
Installing Requests in Python

### PR DESCRIPTION
**Pull request by kinjelom**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6628)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This appears to be for buck to work... @shs96c can we have the setup do this automatically

**Comment by wildloop** [comment]
At the moment this is the only step missing...

**Comment by wildloop** [comment]
Did you consider separating java projects as maven projects?

**Comment by shs96c** [comment]
@AutomatedTester, we probably can. I think @barancev looked into it. The central script to futz with is the "buckw" one.

**Comment by shs96c** [comment]
Until then, this is a helpful thing to add to the project. Thank you @wildloop.

**Pull request merged**
