### PR TITLE
[js] Add windowTypes option support for ChromiumDriver

### PR DESCRIPTION
**Pull request by txava**
### Description
Adds support for setting windowTypes option for ChromeDriver, which
allows getting an extra set of window type handles like webview handles.

### Motivation and Context
In order to be able to interact with a webview, one needs to get a handle for the webview (which is a window handle).
ChromeDriver won't return handles for webviews unless it is explicitly specified via **windowTypes** option see: https://chromedriver.chromium.org/capabilities.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by corevo** [comment]
Please add a test where you add a windowType and assert that the array contains that windowType.

**Comment by diemol** [comment]
@txava, would you like to continue with this PR? Seems there are pending comments to resolve.

**Comment by txava** [comment]
@diemol, @corevo 
> Please add a test where you add a windowType and assert that the array contains that windowType.

Added commit with a test for this request.

**Review by harsha509 — APPROVED** [review]
Thank you @txava !

**Pull request merged**
