### PR TITLE
Correct Net::HTTP::Persistent bug when using newer versions

### PR DESCRIPTION
**Pull request by DylanLacey**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Fix the integration with the Net HTTP Persistent Gem.

### Motivation and Context
The default Net::HTTP Library allows the end user to force SSL using the `use_ssl=` method.  Net::HTTP::Persistent doesn't in newer releases.  This causes errors to be thrown when using the Net::HTTP::Persistent shim.

This change moves SSL configuration into its own method, allowing the shim to handle this for different versions while keeping the default HTTP code clean.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
Hah, just noticed that we didn't have a conversation about removing it, I just suggested it and didn't follow up: https://github.com/SeleniumHQ/selenium/pull/7065#issuecomment-477432000

**Comment by DylanLacey** [comment]
Either of these are fine by me!  I didn't note the change to the standard HTTP client and since the Persistent shim was still present but not working...

Shall I leave this open for a week or so in case anyone else is watching the issue tracker with rabid interest for Persistent improvements and has an argument for keeping it?

**Comment by p0deje** [comment]
I believe we should proceed with deprecating this class in favor of default HTTP client for 4.0.

**Comment by titusfortner** [comment]
And deprecated: f6d831b848b9cbe63c41b55c61eb97ec23bbfb69

**Pull request closed without merging**
