### PR TITLE
[java] Add JSpecify annotations to WebElement and SearchContext

### PR DESCRIPTION
**Pull request by mk868**
### Description

I think the easiest way to cover code with nullable annotations is to iterate over classes, annotate them with [@NullMarked](https://jspecify.dev/docs/user-guide/#nullmarked) annotation and then annotate the types in methods that allow null values with [@Nullable](https://jspecify.dev/docs/user-guide/#nullable-and-nonnull).

The feature description:  #14291 

#### Changes in this PR:

**Added `org.jspecify:jspecify:1.0.0` dependency**
  - 1.0.0 is [official release](https://jspecify.dev/blog/release-1.0.0/)
  - dependency added to the `org.seleniumhq.selenium:selenium-api` lib
  - jspecify annotations on fields are part of API, it's recommended to add it as a runtime dependency - [Depending on the annotations](https://jspecify.dev/docs/using/#depending-on-the-annotations)

**`SearchContext` interface annotated with `@NullMarked`:**
- `List<WebElement> findElements(By by)` - doesn't accept or return null values
- `WebElement findElement(By by)` - doesn't accept or return null values

**`WebElement` interface annotated with `@NullMarked`:**
- `void sendKeys(CharSequence... keysToSend)` - doesn't accept null parameter
- `String getTagName()` - doesn't return null values
- `String getDomProperty(String name)`
  -  `String name` parameter cannot be null
  -  returned `String` can be null - annotated with `@Nullable`
- `String getDomAttribute(String name)`
  -  `String name` parameter cannot be null
  -  returned `String` can be null - annotated with `@Nullable`
- `String getAttribute(String name)`
  -  `String name` parameter cannot be null
  -  returned `String` can be null - annotated with `@Nullable`
- `String getAriaRole()`
  -  returned `String` can be null - annotated with `@Nullable`
- `String getAccessibleName()`
  -  returned `String` can be null - annotated with `@Nullable`
- `String getText()` - doesn't return null values
- `List<WebElement> findElements(By by)` - doesn't accept or return null values
- `WebElement findElement(By by)` - doesn't accept or return null values
- `SearchContext getShadowRoot()` - doesn't return null values
- `Point getLocation()` - doesn't return null values
- `Dimension getSize()` - doesn't return null values
- `Rectangle getRect()` - doesn't return null values
- `String getCssValue(String propertyName)` - doesn't accept or return null values

### Motivation and Context
In this PR JSpecify Nullness annotations were added to the Selenium framework project.
The nullness annotation will give developers better exposure of potential problems with their code in order to avoid NullPointerExceptions.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Dependencies

___

### **Description**
- Added `@NullMarked` annotation to the `SearchContext` interface.
- Added `@NullMarked` annotation to the `WebElement` interface.
- Added `@Nullable` annotation to methods in `WebElement` that can return null values.
- Added `org.jspecify:jspecify:1.0.0` dependency to Bazel and Maven configurations.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>SearchContext.java</strong><dd><code>Annotate `SearchContext` interface with `@NullMarked`</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/SearchContext.java

- Added `@NullMarked` annotation to the `SearchContext` interface.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14319/files#diff-94edb04ecc3068da966325d20df8a77ce00558c1e0fa8433fae0bf84531fae19">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>WebElement.java</strong><dd><code>Annotate `WebElement` interface with `@NullMarked` and `@Nullable`</code></dd></summary>
<hr>

java/src/org/openqa/selenium/WebElement.java

<li>Added <code>@NullMarked</code> annotation to the <code>WebElement</code> interface.<br> <li> Added <code>@Nullable</code> annotation to methods that can return null values.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14319/files#diff-16a9bff0a8aadb9791c842310b37ff70bf561a1a8ad821f7b9f0157978cc37ba">+8/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>MODULE.bazel</strong><dd><code>Add JSpecify dependency to Bazel configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

MODULE.bazel

- Added `org.jspecify:jspecify:1.0.0` dependency.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14319/files#diff-6136fc12446089c3db7360e923203dd114b6a1466252e71667c6791c20fe6bdc">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>maven_install.json</strong><dd><code>Update maven install configuration for JSpecify dependency</code></dd></summary>
<hr>

java/maven_install.json

<li>Updated maven install configuration to include <br><code>org.jspecify:jspecify:1.0.0</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14319/files#diff-111cfe2338069d6f77711f4a3b0c6ede1cbe2f2ae048bc1aeff41e363b6d95fb">+14/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>BUILD.bazel</strong><dd><code>Include JSpecify artifact in Bazel build configuration</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/BUILD.bazel

<li>Updated Bazel build file to include <code>org.jspecify:jspecify</code> artifact.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14319/files#diff-f92714d691b32bbcec53bc10402552a808677847af37928aeaeb65036ce47392">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mk868** [comment]
Branch rebased

**Comment by diemol** [comment]
Please rebase and run the [format script](https://github.com/SeleniumHQ/selenium/blob/trunk/scripts/format.sh).

**Comment by mk868** [comment]
@diemol Thanks, indeed, there was a problem with the order of imports.
rebased and fixed

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Thank you, @mk868!

**Pull request merged**
