### PR TITLE
Fixed several typos in promise.js

### PR DESCRIPTION
**Pull request by Marketionist**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by Marketionist** [comment]
Fixes https://github.com/SeleniumHQ/selenium/issues/3171

**Comment by Marketionist** [comment]
Fixed, @jleyba please review

**Comment by Marketionist** [comment]
Currently build in Travis failed because of "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself." - see https://travis-ci.org/SeleniumHQ/selenium/jobs/179590026#L1780. So, it's definitely not because of the typos fixing in this PR.

@jleyba please review again and merge if it's ok!

**Comment by Marketionist** [comment]
@mach6 @lukeis @titusfortner please review

**Comment by mach6** [comment]
Thanks!

**Pull request merged**
