### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
### **User description**
Fixes software supply chain safety warnings like at the bottom right of
https://github.com/SeleniumHQ/selenium/actions/runs/11738897387
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines. Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
 
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Introduced a new `.github/dependabot.yml` file to automate the updating of GitHub Actions using Dependabot.
- Configured the update schedule to be weekly, ensuring that all GitHub Actions are kept up to date.
- Grouped all updates into a single pull request for easier management and review.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>dependabot.yml</strong><dd><code>Add Dependabot configuration for GitHub Actions updates</code>&nbsp; &nbsp; </dd></summary>
<hr>

.github/dependabot.yml

<li>Added a new <code>dependabot.yml</code> configuration file.<br> <li> Configured Dependabot to update GitHub Actions weekly.<br> <li> Grouped all GitHub Actions updates into a single pull request.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14728/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28">+13/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by diemol** [comment]
We use renovate for dependencies which should be working for actions. If not, then it is probably misconfigured and we appreciate any help to get it working. Thanks!

**Comment by cclauss** [comment]
My experience with renovate is not good. I usually find it not working and difficult to configure.

**Comment by diemol** [comment]
We've got good results with the default configuration.

**Comment by diemol** [comment]
We've got good results with the default configuration.

**Comment by cclauss** [comment]
https://github.com/SeleniumHQ/selenium/actions/runs/11738897387 still contains a lot of warnings.

**Pull request closed without merging**
