### PR TITLE
[py] Add page load strategy enum

### LINKED ISSUE #13236: [🚀 Feature]: Add enum for `_PageLoadStrategyDescriptor`
### Feature and motivation

Hi!

In my project, I've encountered a situation where I need to change the default page load strategy, but the only way to find the names of the available strategies is by searching the documentation or looking at the descriptor implementation.

I think it would be convenient to have an enum for these names. This would help with hints of available strategy names and save us from having to remember their full names. It would also be great to add info about difference between these strategies in the docstring of this class, as [is done in the documentation](https://www.selenium.dev/documentation/webdriver/drivers/options/#pageloadstrategy).

Thanks!

### Usage example

If enum is named `PageLoadStrategy`, I can easily use strategy name as follows:

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options, PageLoadStrategy

options = Options()
options.page_load_strategy = PageLoadStrategy.EAGER
```

### PR DESCRIPTION
**Pull request by M1troll**
### Description
Add `PageLoadStrategy` to get rid of writing the webdriver's page load strategy manually.

### Motivation and Context
Fixes [issue#13236](https://github.com/SeleniumHQ/selenium/issues/13236):

> Hi!
> 
> In my project, I've encountered a situation where I need to change the default page load strategy, but the only way to find the names of the available strategies is by searching the documentation or looking at the descriptor implementation.
> 
> I think it would be convenient to have an enum for these names. This would help with hints of available strategy names and save us from having to remember their full names. It would also be great to add info about difference between these strategies in the docstring of this class, as [is done in the documentation](https://www.selenium.dev/documentation/webdriver/drivers/options/#pageloadstrategy).
> 
> Thanks!
> 
> ### Usage example
> If enum is named `PageLoadStrategy`, I can easily use strategy name as follows:
> 
> ```python
> from selenium import webdriver
> from selenium.webdriver.chrome.options import Options, PageLoadStrategy
> 
> options = Options()
> options.page_load_strategy = PageLoadStrategy.EAGER
> ```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation. -> [normal](https://www.selenium.dev/documentation/webdriver/drivers/options/#normal-default), [eager](https://www.selenium.dev/documentation/webdriver/drivers/options/#eager), [none](https://www.selenium.dev/documentation/webdriver/drivers/options/#none) for Python
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by isaulv** [comment]
One concern I have is that enum string objects remain Enums until a json library parses it as a string object. But if tests pass, this is fine.

**Review by diemol — APPROVED** [review]
Thank you, @M1troll!

Thank you for reviewing, @isaulv!

**Comment by titusfortner** [comment]
@isaulv do you have specific code recommendation for that?

**Comment by isaulv** [comment]
@titusfortner the enum object is fine so long it gets ran through a JSON converter. If it doesn't, and that caps object is used in some other context it may not work right.

**Pull request merged**
