### PR TITLE
[py] remote commands dict is moved outside `RemoteConnection` class in `remote/remote_connection.py` 

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
In `RemoteConnection` class under `remote/remote_connection.py`, instead of assigning a giant dictionary inside of an `__init__` method, I have created a separate dictionary outside `RemoteConnection` class and assigning that dictionary to `self._commands` in constructor.

### Motivation and Context
I felt it is little bit awkward to have a giant dictionary getting assigned inside of `__init__` method. So, I have moved that dictionary out of `RemoteConnection` class, maintaining it in a separate variable `remote_commands` outside the class and assigning it back to `self._commands` inside of constructor.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
I do not see the benefit from this. Is this because the current state is not aligned with a Python style guide or just a personal preference?

**Comment by titusfortner** [comment]
I think keeping methods shorter by splitting out large chunks of code is considered good practice in all languages?

**Comment by sandeepsuryaprasad** [comment]
After moving the dictionary outside `__init__`, the function is now more readable.

**Review by diemol — APPROVED** [review]
Thanks for explaining.

**Pull request merged**
