### PR TITLE
Update docstrings in options.py

### PR DESCRIPTION
**Pull request by jsfehler**
This PR modifies the docstrings in options.py in such a way that the documentation can better parse them.

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6710)

### CODE REVIEW

**Comment by lmtierney** [comment]
Would you mind doing this to all the `Options` classes for consistency?

**Comment by jsfehler** [comment]
@lmtierney Done. Sorry for the slow response.

**Comment by AutomatedTester** [comment]
Could you also update the commit message to explain more of what you’re doing and why?

**Comment by jsfehler** [comment]
@AutomatedTester Squashed the commits down and rewrote the commit message.

**Pull request merged**
