### PR TITLE
Add Edge bindings for C# and Java

### PR DESCRIPTION
**Pull request by petruc**
Add MicrosoftWebDriver.exe bindings for C# and Java. The exe is available at:
http://download.microsoft.com/download/6/D/7/6D7B7A44-B792-4CB4-AEC3-4C190EB99F85/MicrosoftWebDriver.msi

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This is awesome. Could you please squash the commits to relevant commits only?

Also have you(your employer probably) signed the [cla](http://goo.gl/qC50R)

**Comment by jimevans** [comment]
@AutomatedTester I'm happy to take on getting this merged, even squashing it to a single commit myself. 

@petruc, let me know how you'd like to proceed.

**Comment by petruc** [comment]
Thank you!

I have signed the CLA. I also have approval from my employer to contribute to Selenium. Do I need anything else?

I’m not a proficient github user, but I’ll try to squash the commits. Is it possible to do it from the web?

**Comment by petruc** [comment]
Hi Jim,

I’m not proficient with github (still learning). It would be great if you can take it from here. If you need me to address anything please do not hesitate to contact me directly petruc@microsoft.com<mailto:petruc@microsoft.com>

Thank you,
Petru

**Comment by jimevans** [comment]
Merged in 9ed9272.

Thank you very much for your contribution!

**Comment by petruc** [comment]
Thank you!

**Comment by sevaseva** [comment]
Thanks Petru, Jim!
Does the linked msi have both 32bit and 64bit exe? (the download doesn't seem to be easily find-able yet)

**Comment by jimevans** [comment]
@sevaseva I'm gonna ask that you wait for the official Microsoft announcement of availability. That might have the answers you're wanting.

**Comment by sevaseva** [comment]
Thanks, no worries, I will inspect the msi to find out a bit earlier than that... :)

**Comment by vania-pooh** [comment]
@petruc, @jimevans : what is the expected way to use this one within Selenium Grid? What we tried is:
1. Built the latest master into selenium-server-standalone.jar. 
2. Launched Selenium hub as usually:
```java
$ java -jar selenium-server-standalone-2.46.0.jar -role hub
```
3. Installed driver executable for Edge from Microsoft website and launched Selenium node like the following:
```java
$ java -Dwebdriver.edge.driver=/path/to/EdgeDriver.exe -jar selenium-server-standalone-2.46.0.jar -role node -nodeConfig /path/to/selenium-node.json -hubHost localhost -hubPort 4444
```
Our **selenium-node.json** contains the following:
```json
{
    "capabilities":
        [
            {
                "browserName": "MicrosoftEdge",
                "version": "1.0",
                "maxInstances": 1,
                "seleniumProtocol": "WebDriver",
                "platform": "WINDOWS"
            }
        ],
    "configuration":
        {
            "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
            "maxSession": 1,
            "register": true,
            "registerCycle": 5000
        }
}
```
After doing this we're seeing that grid console now contains one node with MicrosoftEdge browser. We're expecting it to work when specifying the following capabilities to RemoteWebDriver:
```java
final DesiredCapabilities browser = new DesiredCapabilities("MicrosoftEdge", "1.0", Platform.WINDOWS);
```
However node is still trying to use IE driver instead. What's wrong in what we're doing?

**Comment by jimevans** [comment]
The work for enabling use with grid hasn't been completed yet. You'll need to wait for a future commit.

**Comment by vania-pooh** [comment]
@jimevans ok, got it.

**Comment by mojwang** [comment]
@jimevans @petruc any idea when JavaScript bindings for Edge will be added?

**Comment by rameshnss** [comment]
@jimevans  Is there any update on Edge browser with Grid

**Pull request closed without merging**
