### PR TITLE
Updated IllegalArgumentException to NullPointerException for Null Values in Require Class

### PR DESCRIPTION
**Pull request by vinoth959**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Update IllegalArgumentException to NullPointerException for Null Values.
### Description
Updated IllegalArgumentException to NullPointerException for Null Values in Require.java file.
Changed MustBeSet to MustBePositive for one condition based on the action in the Require class.

### Motivation and Context
Misleading Exception and cause issues in debugging.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

Updated IllegalArgumentException to NullPointerException for Null Values.
Changed MustBeSet to MustBePositive for one condition based on the action in Require Class.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Can you please share the motivation for this pull request? The goal of `Require` is to check if the arguments passed are valid or not, and checking for nulls is a subset of those validations.

**Comment by vinoth959** [comment]
Hi,

I was getting error as Input should be Set for the nonNull method and could not identify the root cause of the issue and took a while for figuring out that the value is null. Method name says nonNull and it throws illegalargumentexception. Atleast the exception should be null or the message should say the value is null. That is the reason for this pull request

Thanks,
Vinoth

**Comment by diemol** [comment]
> Hi,
> 
> I was getting error as Input should be Set for the nonNull method and could not identify the root cause of the issue and took a while for figuring out that the value is null. Method name says nonNull and it throws illegalargumentexception. Atleast the exception should be null or the message should say the value is null. That is the reason for this pull request
> 
> Thanks, Vinoth

Can you share the code that caused you to get that exception?

**Comment by vinoth959** [comment]
i was doing creating new webdriverwait but did not realize the driver passed in the class was null. When i run the code i got illegalargumentexception with Input must be set error and did not have clue on what's happening. On further investigation i found the mistake but that error was confusing. This is just a cosmetic change i'm proposing..

I was passing the wait as below.
 waitforElementtoLoad(element, new WebDriverWait(driver, Duration.ofSeconds(3)));

**Comment by titusfortner** [comment]
looks like everything that doesn't include `MUST_BE_SET` can swallow the fact that the value was null:

```
  public static Duration nonNegative(String argName, Duration arg) {
    if (arg == null) {
      throw new IllegalArgumentException(String.format( , argName));
    }
...
```

It would make sense for some of these to be more clear what the problem is, but I don't think everything should be changed to `NullPointerException`

**Comment by vinoth959** [comment]
Got it.. just my thoughts.. if not needed also fine.. I know the problem now.

**Comment by vinoth959** [comment]
I strongly beleive this method should be fixed atleast.

        throw new IllegalArgumentException(String.format(MUST_BE_POSITIVE, argName)); should be        throw new IllegalArgumentException(String.format(MUST_BE_SET, message));


public static double positive(String argName, Double number, String message) {
    if (number <= 0) {
      if (message == null) {
        throw new IllegalArgumentException(String.format(MUST_BE_POSITIVE, argName));
      } else {
        throw new IllegalArgumentException(message);
      }
    }
    return number;
  }

**Comment by titusfortner** [comment]
I was agreeing with you, then I realized I was using a bad example....

The fix that needs to happen is that the logic for
```
public static double positive(String argName, Double number, String message)
```
needs to match the logic for
```
public static int positive(String argName, Integer number, String message)
```

i.e., the `if (number == null)` conditional got skipped for some reason.

**Comment by vinoth959** [comment]
> I was agreeing with you, then I realized I was using a bad example....
> 
> The fix that needs to happen is that the logic for
> 
> ```
> public static double positive(String argName, Double number, String message)
> ```
> 
> needs to match the logic for
> 
> ```
> public static int positive(String argName, Integer number, String message)
> ```
> 
> i.e., the `if (number == null)` conditional got skipped for some reason.

I actually understand the logic now.. i was confused.

**Comment by vinoth959** [comment]
Updated the above 

> > I was agreeing with you, then I realized I was using a bad example....
> > The fix that needs to happen is that the logic for
> > ```
> > public static double positive(String argName, Double number, String message)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > needs to match the logic for
> > ```
> > public static int positive(String argName, Integer number, String message)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i.e., the `if (number == null)` conditional got skipped for some reason.
> 
> I actually understand the logic now.. i was confused.

Updated the above logic in the pull request...

What can i do to make this more readable for null values?? We can leave it as it is?

**Comment by titusfortner** [comment]
I think we just have to know that `"myValue must be set"` indicates that it was `null`

**Review by diemol — APPROVED** [review]
Thank you, @vinoth959!

**Pull request merged**
