### PR TITLE
[js] convert camelCase and snake_case to `BIG_SNAKE_CASE`

### PR DESCRIPTION
**Pull request by navin772**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

A TODO
Convert the camelCase and snake_case to `BIG_SNAKE_CASE` in `get_atom_name()` function 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Enhanced the `get_atom_name` function to convert camelCase and snake_case to BIG_SNAKE_CASE using regex.
- Added the `re` module import to support regex operations in the code.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>gen_file.py</strong><dd><code>Enhance `get_atom_name` function for case conversion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

javascript/private/gen_file.py

<li>Added regex to convert camelCase and snake_case to BIG_SNAKE_CASE.<br> <li> Modified the <code>get_atom_name</code> function to handle different case <br>conversions.<br> <li> Imported the <code>re</code> module for regex operations.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14490/files#diff-ab8f361f20ffc068975f7c677d96fbf8285b0ea47cd641706454e2be6312715b">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by navin772** [comment]
@AutomatedTester can you please review this PR?

**Comment by AutomatedTester** [comment]
Why are we making this change? This is for generated code that people will never use directly. This code is going to be deleted as we move to bidi

**Comment by navin772** [comment]
@AutomatedTester, it was a TODO item which I thought of resolving

**Review by diemol — COMMENTED** [review]
Yeah, as @AutomatedTester says, we do not need to invest in this. I just modified the comment to add clarity about this.

**Comment by diemol** [comment]
Thank you for the PR, though, @navin772!

**Pull request closed without merging**
