### PR TITLE
adding unit tests for 3.3,3.4,3.5

### PR DESCRIPTION
**Pull request by llaskin**
- [X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by llaskin** [comment]
@davehunt

**Comment by davehunt** [comment]
Just a nit, but I'd position these between the Python 2.7 and 3.6 builds. Let's see the results in Travis before merging.

**Comment by llaskin** [comment]
Dave's comment made me identify a bug, I had duped 3.6 unit tests.  commit #919b214 fixed it as well as moving the unit tests around

**Comment by llaskin** [comment]
@davehunt I'm gonna rely on you to parse the fails here.  I think none of them matter, but want you to review if possible

**Comment by davehunt** [comment]
@llaskin you need to include the new version numbers on lines 7 and 22, otherwise the command and deps are missing for those environments.

**Pull request merged**
