### PR TITLE
[dotnet] Removed {{separator}} token from C# filename codegen

### PR DESCRIPTION
**Pull request by EdwinVanVliet**
### Description

On our own build environment we noticed that the intermediate files being generated when running the codegen contain the {{separator}} token. When looking into the Utility.cs ReplaceTokensInPath function there is no replacement being done on the {{separator}} token. This PR removes the {{separator}} token from the template within CodeGenerationDefinitionTemplateSettings.cs causing filenames to be outputted without {{separator}}. 

Also this issue caused some files to end up in the wrong directory. The AXPropertyName.cs should be located in the Accesibility domain, but it ended up in WebAuthn. 

Before fix.
SeparatorIssue

After fix.
SeparatorIssueFixed

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nvborisenko** [comment]
Somebody introduced `{{separator}}` token. I don't know why, but let's not break this logic.

I propose very simple fix:
Utility.cs
```csharp
path = path.Replace("{{separator}}", System.IO.Path.DirectorySeparatorChar.ToString());
```

If it works, then we also can remove the following line:
```csharp
path = path.Replace('\\', System.IO.Path.DirectorySeparatorChar);
```

Seems somebody also tried to fix the same thing around path separator token.

**Review by nvborisenko — CHANGES_REQUESTED** [review]
We still need to support `{{separator}}` token. Let's replace it in runtime.

**Comment by nvborisenko** [comment]
Seems it works, please doble-check carefully:

```diff
- path = path.Replace('\\', System.IO.Path.DirectorySeparatorChar);
+ path = path.Replace("{{separator}}", System.IO.Path.DirectorySeparatorChar.ToString());
+ //path = path.Replace('\\', System.IO.Path.DirectorySeparatorChar);
```

**Comment by EdwinVanVliet** [comment]
@nvborisenko 

That also works, confirmed with our build environment. Committed the changes.

We both need the `{{separator}}` and `\\` replacements because CodeGenerationDefinitionTemplateSettings.cs contains both forms.

**Review by nvborisenko — APPROVED** [review]

**Comment by nvborisenko** [comment]
Thanks @EdwinVanVliet for your contribution!

**Pull request merged**
