### PR TITLE
Update notices

### PR DESCRIPTION
**Pull request by ddavison**
I'm doing these piece by piece at a time so it's not changing too many files at once.

You can see i'm adding `.idea/copyright` and a couple of files.  IntelliJ makes this very easy to update all notices.  Once this is set, just right click any item in the project tree, and click "Update Copyright..."

https://www.jetbrains.com/idea/help/generating-and-updating-copyright-notice.html

### CODE REVIEW

**Comment by ddavison** [comment]
#401

**Comment by jleyba** [comment]
Closed this b/c the copyright plugin didn't work for every language. The rake task I added also doesn't depend on a specific IDE to run.

Thanks for getting this started though.

**Comment by ddavison** [comment]
no, but it did update the java section for a particular subset of them.. I was going to do it piece by piece and do one folder at a time, and let you guys merge it in.  

This PR is still of use, and isn't reliant on you getting a ./go task built for it.  can you merge this in?

**Comment by jleyba** [comment]
Merge in the IDE config changes? Is it necessary when there's a ./go task? I'm on the fence on that and will defer to others.

All java files should have up-to-date notices as of 8f56eaf19eb5079bfd1a16bd58c5270cabdad872

**Comment by ddavison** [comment]
I see... I wanted something to do to contribute to the project, and you just yanked it from under me! :-1:

**Comment by jleyba** [comment]
Well, the dotnet/ and cpp/ trees still haven't been cleaned up :)

**Pull request closed without merging**
