### PR TITLE
[py] fix packaging

### PR DESCRIPTION
**Pull request by benoit-pierre**
### Description

Ensure `selenium.webdriver.common.fedcm` gets packaged in.

```bash
# Before:
▹ python setup.py -q sdist && tar tf dist/selenium-4.28.0.202411261607.tar.gz | grep fedcm
selenium-4.28.0.202411261607/selenium/webdriver/remote/fedcm.py

# After:
▹ python setup.py -q sdist && tar tf dist/selenium-4.28.0.202411261607.tar.gz | grep fedcm
selenium-4.28.0.202411261607/selenium/webdriver/common/fedcm/
selenium-4.28.0.202411261607/selenium/webdriver/common/fedcm/__init__.py
selenium-4.28.0.202411261607/selenium/webdriver/common/fedcm/account.py
selenium-4.28.0.202411261607/selenium/webdriver/common/fedcm/dialog.py
selenium-4.28.0.202411261607/selenium/webdriver/remote/fedcm.py
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix

___

### **Description**
- Ensure `selenium.webdriver.common.fedcm` is included in the package distribution.
- Fix packaging issue to include missing `fedcm` module files.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by navin772 — COMMENTED** [review]
Thanks @benoit-pierre for adding `__init__.py` to fedcm.
LGTM!

**Comment by navin772** [comment]
@benoit-pierre can you also add the License headers to the file, it is required

**Comment by VietND96** [comment]
@navin772, do you have any idea on how to detect this issue via test, or CI when a new package would be added in future?

**Comment by mgorny** [comment]
You could run tests on installed package, i.e. in Gentoo we do the equivalent of:

```
pip install .
rm -rf selenium
pytest
```

**Comment by VietND96** [comment]
Thanks for your suggestion!

**Comment by navin772** [comment]
@VietND96 we can add a pre-check in python build CI that checks recursively inside `py/selenium/` directory if `__init__.py` file exists in every dir.

**Pull request merged**
