### PR TITLE
[C-py] Add `interval` option and shorten sleep interval for waiting until connectable

### LINKED ISSUE #6848: [Suggestion] Starting a service in Python bindings is slow
## Question

In my opinion, retrying interval to start the Service in Python bindings is a little too long.
We have to wait at least one second.
So that, it's good that shorten the retrying interval.
Does anyone have a good idea?

## Motivation
As you see in the below, we have to wait 1 second because of `time.sleep(1)` to start the Service.
I think it's so long.

https://github.com/SeleniumHQ/selenium/blob/11c25d75bd7ed22e6172d6a2a795a1d195fb0875/py/selenium/webdriver/common/service.py#L131-L135
https://github.com/SeleniumHQ/selenium/blob/11c25d75bd7ed22e6172d6a2a795a1d195fb0875/py/selenium/webdriver/common/service.py#L97-L104

### PR DESCRIPTION
**Pull request by iwasa-kosui**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Fix #6848

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6906)

### CODE REVIEW

**Comment by EbiEbiEvidence** [comment]
@cgoldberg Thank you for your comment in #6848.
If you like, can I get some advices?
It's serious problem for me.

**Comment by GQAssurance** [comment]
I like the change! 
However; would it make sense in `service.py` to a similar "seconds / interval" style you have used in `firefox_binary.py`?
That would make it more clear that the total time we are waiting is still 30 seconds
something like: `for x in range(30 / 0.2):`

**Comment by EbiEbiEvidence** [comment]
> I like the change!
> However; would it make sense in `service.py` to a similar "seconds / interval" style you have used in `firefox_binary.py`?
> That would make it more clear that the total time we are waiting is still 30 seconds
> something like: `for x in range(30 / 0.2):`

That's right.
I'll fix it.

**Comment by AutomatedTester** [comment]
Looking at this there is a problem where we can run out of Ephemeral port. Have you used this patch in anger?

**Comment by GQAssurance** [comment]
> Looking at this there is a problem where we can run out of Ephemeral port. Have you used this patch in anger?

Why do you believe this?
The is_connectable function closes its sockets.

**Comment by AutomatedTester** [comment]
> > Looking at this there is a problem where we can run out of Ephemeral port. Have you used this patch in anger?
> 
> Why do you believe this?
> The is_connectable function closes its sockets.

It tells the OS to close the port but there are numerous cases where OSX and Windows will not fully release the port and this can lead to ephemeral port exhaustion. This is a real problem that happens.

**Comment by AutomatedTester** [comment]
Also, can you sign the CLA

**Comment by GQAssurance** [comment]
If this change would exhaust the ports on a system then it sounds like it should be rejected, even without the CLA.

**Comment by cgoldberg** [comment]
> The is_connectable function closes its sockets.

still.. you can't rebind immediately, so could possibly exhaust available sockets if you set the polling interval too low for the system.  Could this happen in practice at that .02/sec level with most `ulimit`'s?

**Comment by AutomatedTester** [comment]
Closing this as I don't think that this is could lead to port exhaustion

**Pull request closed without merging**
