### PR TITLE
Add missing "break" statement

### PR DESCRIPTION
**Pull request by mtrea**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by mtrea** [comment]
Ping! Can somebody take a look at this, please?

**Comment by mtrea** [comment]
@dratler @shs96c Looping in participants of the commit that appears to have the bug.

**Comment by dratler** [comment]
Hi @mtrea ,
can you share some more info ?
Class name or package name ?
So I can isolate the problem ?

Cheers

**Comment by mtrea** [comment]
If your input JSON has content after "realm", the next item will be skipped because you fall through to the default case. Please see the commit attached to this pull request which resolves this issue.

**Comment by barancev** [comment]
Merged as dd80d5ed73b404a0de7c1d5ece00c77e003f1d87, thank you!

**Pull request closed without merging**
