### PR TITLE
[rust] xz uncompressor for Firefox Linux nightlies

### LINKED ISSUE #14831: [🐛 Bug]: selenium-manager misses xz decompressor for firefox linux nightlies
### What happened?

Calling `selenium-manager --browser firefox --browser-version nightly` fails with "Downloaded file cannot be uncompressed (xz extension)". Mozilla now provides the [download as tar.xz](https://blog.nightly.mozilla.org/2024/11/28/announcing-faster-lighter-firefox-downloads-for-linux-with-tar-xz-packaging/)

### How can we reproduce the issue?

```shell
selenium-manager --browser firefox --browser-version nightly --os linux
```

### Relevant log output

```shell
[2024-11-29T19:01:55.486Z ERROR] Downloaded file cannot be uncompressed (xz extension)
```

### Operating System

Linux

### Selenium version

0.4.27

### What are the browser(s) and version(s) where you see this issue?

Firefox nightly

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.35.0

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by bgermann**
### Description
Add a xz uncompressor.

### Motivation and Context
Mozilla provides Linux nightlies in tar.xz archived now. Closes: #14831

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Added support for decompressing XZ files using the `xz2` crate.
- Implemented a new function `uncompress_xz` to handle the extraction of XZ compressed files.
- Updated the `uncompress` function to include logic for handling XZ file extensions.
- Added the `xz2` crate to the project's dependencies in `Cargo.toml`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>files.rs</strong><dd><code>Add XZ file decompression support in Rust</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

rust/src/files.rs

<li>Added <code>xz2</code> dependency for XZ file decompression.<br> <li> Introduced <code>uncompress_xz</code> function to handle XZ file extraction.<br> <li> Updated <code>uncompress</code> function to support XZ file format.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14832/files#diff-64844fef0537ed5f6fd38575be93920c99efacb3fd4c317ed6ff1ce243c2e1f1">+26/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Cargo.toml</strong><dd><code>Add xz2 crate dependency for XZ support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

rust/Cargo.toml

- Added `xz2` crate to dependencies for XZ decompression.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14832/files#diff-74eb46d64310c0817ed15b2389cf81183c18cdebbaa256a4198057855ecf14d7">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by bgermann** [comment]
@VietND96 Are the two failing checks caused by the new crate dependency? Am I required to change anything?

**Comment by VietND96** [comment]
Looks like you missed to format code. Run `./scripts/format.sh` once

**Comment by bgermann** [comment]
I have run the test and included the Bazel lock file change.

**Comment by bgermann** [comment]
Ah, and the import sorting is now fixed as well.

**Review by bonigarcia — CHANGES_REQUESTED** [review]
@bgermann: Thanks a lot for reporting and contributing. I tested your code, and it works nicely. My only concern is that the new function `uncompress_xz` is almost identical to the existing `uncompress_bz2`, so it would be better to create a common function for both parameterizing the decoder (`XzDecoder` and `BzDecoder` respectively). Can you please make that change in your PR?

**Comment by bonigarcia** [comment]
Looks good to me, many thanks, @bgermann. I tested locally it and it works nicely. Some tests are failing in CI but the reason is other, so it can be merged. Thanks again!

**Pull request merged**
