### PR TITLE
Correct a part of timing issue #5024

### PR DESCRIPTION
**Pull request by Nawakator**
- [ X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Remove unecessary loop for mouse move.

### CODE REVIEW

**Comment by jimevans** [comment]
This pull request would make the driver no longer compliant with the [W3C WebDriver Specification](https://w3c.github.io/webdriver/webdriver-spec.html). Please pay particular attention to the ["Perform a pointer move"](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-perform-a-pointer-move) algorithm, which both specific Actions and element click ([sub-step 11 of the non-`<option>` element branch in step 7 of the Element Click remote end steps](https://w3c.github.io/webdriver/webdriver-spec.html#element-click)) are required to perform. It might be possible to tweak the duration of the move in the `WebElement.click()` case, but that's not what this PR does.

**Comment by Nawakator** [comment]
Indeed.

So could intend us to add a capabilities for switch the W3C compilant for Internet Explorer? (make IE W3C compilant it s a 'joke' no).

To explain the real pb: since the 3.5.1 we cannot compare the result beetween Internet Explorer and Chrome.
And this difference was only procude by the mouse move and other input events. So we cannot compare the real browser performance.

**Comment by jimevans** [comment]
No, having the IE driver be compliant with the WebDriver spec is certainly no “joke.” The spec refers to the driver, not the browser, and it’s a spec I’ve personally spent more than five years helping to bring into existence. So, no, we won’t be adding a capability to disable compliance with the spec. In any case, your PR does not attempt to add that capability, so if that is your proposal, the PR is incomplete. As submitted, this PR is not an acceptable solution to the issue.

**Comment by g0rk4** [comment]
Hi @jimevans, as i understand and in order to stick to the W3C specifications, the best way to proceed is to set an option to reduce the mouse movement speed ?

**Comment by jimevans** [comment]
@g0rk4 No,the right approach would be to fix the logic error in the calculation of the mouse move duration. I’m working on just such a fix later today.

**Comment by jimevans** [comment]
@Nawakator InputManager.cpp has been thoroughly refactored since this PR was created. If you still believe it to be necessary, please update and resubmit. I will be closing this PR in one week’s time.

**Comment by jimevans** [comment]
Closing PR because of lack of review after refactored input handling in IE.

**Pull request closed without merging**
