### PR TITLE
[py] Add support for the New Window command (#6873)

### LINKED ISSUE #6873: Add support for W3C "New Window" command
## 🚀 Feature Proposal

At the last TPAC it was decided to add a new command called "New Window" which allows tests to open a new tab or window. The related work can be seen at https://github.com/w3c/webdriver/issues/1138.

All drivers will have support for this probably soon, so it would be good to get support added in all the Selenium bindings.

As of now the command supports two types of browsing contexts to open, which are `tab` and `window`. If nothing gets passed in the browser will decide the best type on its own. This also happens when the requested type is not supported, eg. new browser window on mobile.

## Example

Please provide an example for how this feature would be used.

```python
handle, _type = driver.new_window(type_hint="tab")
driver.switch_to(handle)
```

More WebDriver tests which are part of the web-platform-tests suite can be found at https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/new_window.

### PR DESCRIPTION
**Pull request by whimboo**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Fixes #6873. @AutomatedTester can you please review? Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6930)

### CODE REVIEW

**Comment by whimboo** [comment]
Most of the tests fail due to a problem downloading geckodriver. Maybe someone could retrigger those jobs, especially https://travis-ci.org/SeleniumHQ/selenium/jobs/492382707? Thanks

**Comment by whimboo** [comment]
With the last update I removed the call to `Wait` given that `New Window` and `Switch To` are synchronous.

**Comment by whimboo** [comment]
@AutomatedTester as it looks like this never reached a 3.141 release:

https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/py/selenium/webdriver/remote/switch_to.py

All the other binding should have already shipped it. Can we get a py release out including the new window support?

**Comment by AutomatedTester** [comment]
> @AutomatedTester as it looks like this never reached a 3.141 release:
> 
> https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/py/selenium/webdriver/remote/switch_to.py
> 
> All the other binding should have already shipped it. Can we get a py release out including the new window support?

Its in the Se4 alpha releases, there won't be any Se3 releases anymore

**Pull request merged**
