### PR TITLE
[py] Added more internal logging for CDP

### PR DESCRIPTION
**Pull request by shbenzer**
### **User description**
Python implementation of #14558 

### Description
Added more logging for cdp in python

### Motivation and Context
Issue #14547 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Added debug logging to track the sending and receiving of CDP messages in the `execute` method.
- Logged exceptions raised during the handling of CDP messages to aid in debugging.

___

PRDescriptionHeader.CHANGES_WALKTHROUGH
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>cdp.py</strong><dd><code>Add debug logging for CDP message handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/bidi/cdp.py

<li>Added debug logging for sending and receiving CDP messages.<br> <li> Logged exceptions raised during CDP message handling.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14668/files#diff-e192596801445c69bdc9fcee1d7f7ff1c596f638ce38070a6e3e2bf38d5c04d6">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by shbenzer** [comment]
@VietND96 `//py:common-chrome-test/selenium/webdriver/common/upload_tests.py` passes locally for me, could you run it again? The pr doesn't affect that test, but I figure we might as well be sure.

**Comment by shbenzer** [comment]
weird - they pass locally for me, and that edge test passed in the last run so it has nothing to do with my code... Wonder if upload_tests.py is having trouble with the ci/cd pipeline.

**Comment by shbenzer** [comment]
@VietND96 can you see the log files? I can't figure out which test is failing/what the error message is

**Comment by VietND96** [comment]
Can you see this link? https://gypsum.cluster.engflow.com/invocations/default/6f30e2cd-e307-4fb8-9a44-a77abff4035a#highlights
See console logs of each test

**Comment by VietND96** [comment]
I'm checking a local run, test passed here. I tried to update the branch one more time to see.

**Comment by shbenzer** [comment]
> Can you see this link? https://gypsum.cluster.engflow.com/invocations/default/6f30e2cd-e307-4fb8-9a44-a77abff4035a#highlights See console logs of each test

I had, but couldn't see how to find the log file - I just figured it out.

So it looks like the upload_tests.py is having these errors:

```
_________________________ test_can_upload_file[chrome] _________________________
driver = <selenium.webdriver.chrome.webdriver.WebDriver (session="4282a38894728d08ede6aa5133d70dd2")>
pages = <conftest.pages.<locals>.Pages object at 0x7ff41da98a30>
get_local_path = <function get_local_path.<locals>.wrapped at 0x7ff41df11e50>
    def test_can_upload_file(driver, pages, get_local_path):
        pages.load("upload.html")
    
        driver.find_element(By.ID, "upload").send_keys(get_local_path("test_file.txt"))
        driver.find_element(By.ID, "go").click()
        driver.switch_to.frame(driver.find_element(By.ID, "upload_target"))
        body = driver.find_element(By.CSS_SELECTOR, "body").text
    
>       assert "test_file.txt" in body
E       AssertionError: assert 'test_file.txt' in ''
py/test/selenium/webdriver/common/upload_tests.py:44: AssertionError
py/test/selenium/webdriver/common/upload_tests.py::test_can_upload_two_files[chrome] FAILED [ 66%]
______________________ test_can_upload_two_files[chrome] _______________________
driver = <selenium.webdriver.chrome.webdriver.WebDriver (session="d42f152b4f592601b5dfe55acf095a04")>
pages = <conftest.pages.<locals>.Pages object at 0x7ff41df70850>
get_local_path = <function get_local_path.<locals>.wrapped at 0x7ff41df21820>
    def test_can_upload_two_files(driver, pages, get_local_path):
        pages.load("upload.html")
        two_file_paths = get_local_path("test_file.txt") + "\n" + get_local_path("test_file2.txt")
        driver.find_element(By.ID, "upload").send_keys(two_file_paths)
        driver.find_element(By.ID, "go").click()
        driver.switch_to.frame(driver.find_element(By.ID, "upload_target"))
        body = driver.find_element(By.CSS_SELECTOR, "body").text
    
>       assert "test_file.txt" in body
E       AssertionError: assert 'test_file.txt' in ''
py/test/selenium/webdriver/common/upload_tests.py:55: AssertionError
```

and the edge test got an invalid selector here:

```
py/test/selenium/webdriver/common/bidi_tests.py::test_collect_log_mutations[edge] FAILED [100%]
_______________________ test_collect_log_mutations[edge] _______________________
driver = <selenium.webdriver.edge.webdriver.WebDriver (session="61ed4e08a3b96e3ba3c893bb59c3a825")>
pages = <conftest.pages.<locals>.Pages object at 0x7f632b28c160>
    @pytest.mark.xfail_firefox
    @pytest.mark.xfail_safari
    @pytest.mark.xfail_remote
    async def test_collect_log_mutations(driver, pages):
        async with driver.bidi_connection() as session:
            log = Log(driver, session)
            async with log.mutation_events() as event:
                pages.load("dynamic.html")
                driver.find_element(By.ID, "reveal").click()
                WebDriverWait(driver, 10).until(
                    lambda d: d.find_element(By.ID, "revealed").value_of_css_property("display") != "none"
                )
>               WebDriverWait(driver, 5).until(EC.visibility_of(driver.find_element(By.ID, "revealed")))
py/test/selenium/webdriver/common/bidi_tests.py:79: 
```

@VietND96  both of these pass locally, and do not touch the code I added. Do you know what may be causing this? I'm honestly not sure what could be causing the upload error.

**Comment by VietND96** [comment]
I will merge this, since status is fine

> All tests passed but there were other errors during the build.
(14:09:53) INFO: Streaming build results to: https://gypsum.cluster.engflow.com/invocation/28c145cd-3b88-4bf6-a2e1-94917e669af0

**Comment by VietND96** [comment]
Thank you, @shbenzer !

**Pull request merged**
