### PR TITLE
Fix return types Actions and TouchActions classes.

### PR DESCRIPTION
**Pull request by mspiegel**
The challenge of the builder pattern when extending the class
is that the subclass must either redefine all the methods
of the parent class or the subclass will return instances
with a static type signature of the parent class.

For example the following would fail to compile without this
patch: new TouchActions(driver).click().singleTap(element).
Selfishly I would like to see this patch get accepted to
fix these same bugs in my own subclass of the Actions class
that might eventually become its own pull request.

I have filled in the CLA agreement.

### CODE REVIEW

**Comment by andreastt** [comment]
Thanks for the work you put in, but the TouchActions interface is correct as it is and this introduces backwards incompatibility which isn't acceptable.

**Comment by mspiegel** [comment]
I don't follow. This is not supposed to compile? "new TouchActions(driver).click().singleTap(element)"

**Comment by lukeis** [comment]
Yes, I agree, this needs some fixing as @mspiegel points out.

After reviewing I think the class name could use some work "ActionsSelfType"... something is unsettling with that name and should be changed.

Otherwise I think this is backwards compatible, but would be very good to add some tests for this.

**Comment by lukeis** [comment]
closing the PR as it's gone stale, if the changes pointed out are made and rebased against master, please issue a new pull request

**Pull request closed without merging**
