### PR TITLE
[py] Typing package import enhancement

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

In this pull request, I have standardized the imports from the typing package to only include the necessary types for type hints.

### Motivation and Context

I believe this approach makes the imports more decomposed, readable, and correct. From the changes, you can see that in some files, the entire package was imported as well as specific types.
Screenshot 2024-07-20 at 02 48 02

I consider this coding style inconsistent.

Initially, I started adding type hints and discovered such imports. I will add type hints in one of the following pull requests.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Standardized imports from the `typing` package across multiple files to improve readability and consistency.
- Replaced general `typing` imports with specific type imports such as `Optional`, `List`, `Dict`, `Union`, etc.
- Updated type hints throughout the codebase to use these specific imports.
- Improved code consistency by ensuring all files follow the same import structure for type hints.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>21 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>generate.py</strong><dd><code>Refactor typing imports for generate.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/generate.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use direct imports like <code>Optional</code>, <code>List</code>, etc.<br> <li> Used <code>cast</code> from <code>typing</code> directly.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-197acd5304c91406cc4a12818c1694fe525f0efb718a12996516b082c29345f1">+26/-26</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>types.py</strong><dd><code>Refactor typing imports for types.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/types.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use direct imports like <code>Union</code>, <code>Iterable</code>, etc.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-34124c6629b18d14863cbfbc7b5b7a0bc2d46ffbdea59ddcc275c27ebfa767bf">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for chrome service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/chrome/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-94e16ea2a7773a7ba8eeb142111c7956558fc0f90c08394bb1e99dd1fa7290b1">+7/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for chromium service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/chromium/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-062c917a35158860c8065910187232dbab480ac982cc48bb293c8e808d29818e">+7/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pointer_input.py</strong><dd><code>Refactor typing imports for pointer input</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/actions/pointer_input.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>Dict</code>, and <code>Any</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-38e29a691a003cf9a3b5636c287601ece711c70ba3880dda7205a0b9cee2a1e3">+6/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>cdp.py</strong><dd><code>Refactor typing imports for bidi cdp</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/bidi/cdp.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>AsyncGenerator</code>, <code>Generator</code>, and <code>TypeVar</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-e192596801445c69bdc9fcee1d7f7ff1c596f638ce38070a6e3e2bf38d5c04d6">+12/-7</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>script.py</strong><dd><code>Refactor typing imports for bidi script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/bidi/script.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>List</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-c4d141b056a48aff05840758a7591f2d2b86d6c2f6b8f79c7362ddc8b41c7fcc">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.py</strong><dd><code>Refactor typing imports for common options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/options.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-5ff2f2a84a79fce9e04511b572dcaab921c08e956345f4c41b7e701d4d018589">+5/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for common service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>Mapping</code>, and <code>Union</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-646e4c91d7ef7fbd2b4c088347c86f5b2d2cab8121b14987f3cb783ad120634c">+11/-7</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>virtual_authenticator.py</strong><dd><code>Refactor typing imports for virtual authenticator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/common/virtual_authenticator.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>Dict</code>, and <code>Union</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-5da367f7e3363010c619d8097422a270cd228eb9af198d8d4ee7482a0c647b66">+10/-7</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for edge service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/edge/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-fe6756f6489050e903be9db84475a54c6b90289dfc08db0aeb14d264a14c57d4">+6/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for firefox service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/firefox/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-1e444af73ad0e1c989ee6c2b0e03dd257071fe4a165e450a23bd86bea7d26323">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for IE service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/ie/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code> and <code>List</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-a13e626edcc84bf396cd60c854a31afd904cdeac659b8ab0b04ff98d9def7b02">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Refactor typing imports for remote webdriver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/remote/webdriver.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>Dict</code>, and <code>Type</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-c87c150ed2a08f5293db58a06da8bf7f14c3a5582586c6270c1be661dfdd0985">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.py</strong><dd><code>Refactor typing imports for safari options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/safari/options.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Dict</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-64fc5235b33b885afaf69284cbd3b20cfdc4422da90e0a20ae16ac42fea39821">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for safari service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/safari/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-1cdf7e9efaf8bfb650b4f4cffa398b690201451a702a3f93bf1c4ab840ddcc36">+7/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>event_firing_webdriver.py</strong><dd><code>Refactor typing imports for event firing webdriver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/support/event_firing_webdriver.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>List</code>, <code>Tuple</code>, and <code>Any</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-d085deada2ae12d284ce6ad0b6836345a52d4e102cbbcefb6c429ef76825febc">+7/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>wait.py</strong><dd><code>Refactor typing imports for support wait</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/support/wait.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>Tuple</code>, and <code>Type</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-05701a62e85680067a4d733d62203e430375996bb49dc1cea4d554286ddafb5c">+5/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for webkitgtk service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/webkitgtk/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-2f176dbccc5f64167acc6345e2351cab42ccebdefcc77374c69cb9e23b130806">+8/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>options.py</strong><dd><code>Refactor typing imports for wpewebkit options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/wpewebkit/options.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Dict</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-328aa76538eefc1145f9a680697666ac3e36ed0c11cad17b5a22ca91ed00fa95">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>service.py</strong><dd><code>Refactor typing imports for wpewebkit service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/wpewebkit/service.py

<li>Replaced <code>typing</code> imports with specific type imports.<br> <li> Updated type hints to use <code>Optional</code>, <code>List</code>, and <code>Mapping</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14283/files#diff-321ce05c1440d20719ef90b39396b3b32b495c7c9da1dcca04b2964596f2ccd0">+7/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
Hi, can you resolve the conflicts due to recently changes?

**Comment by iampopovich** [comment]
yepp . i'll do it until tomorrow morning

**Comment by iampopovich** [comment]
I decided to start again from the trunk's HEAD 🙏
There are quite a few conflicts here that I don’t want to resolve incorrectly.

**Comment by iampopovich** [comment]
@VietND96 cc

**Comment by VietND96** [comment]
The update is fine.
@AutomatedTester, do you foresee any issues?

**Review by VietND96 — APPROVED** [review]

**Pull request merged**
