### PR TITLE
Improved TimeoutException for EventFiringWebdriver.

### LINKED ISSUE #4408: Session ID and Capabilities omitted from TimeoutException when used with EventFiringWebDriver.
## Expected Behavior -
TimeoutExceptions thrown by WebDriverWait should include Session ID and Capabilities when instantiated with an EventFiringWebDriver.
## Actual Behavior -
Session ID and Capabilities are omitted from TimeoutExceptions thrown by WebDriverWait when it is instantiated with an EventFiringWebDriver.
## Steps to reproduce -
Running the following snippet will produce a TimeoutException that lacks the Session ID and Capabilities of the WebDriver instance used to instantiate the WebDriverWait. Commenting out the second line will enable the TimeoutException to include the Session ID and Capabilities.

`WebDriver driver = new InternetExplorerDriver();`
`driver = new EventFiringWebDriver(driver);`
`WebDriverWait driverWait = new WebDriverWait(driver, 1);`
`driver.get("www.google.com");`
`driverWait.until(ExpectedConditions.titleIs("Foobar"));`

### PR DESCRIPTION
**Pull request by Tom-Trumper**
Modified WebDriverWait.timeoutException(String, Throwable) method to
ensure that Session ID and Capabilities are included when used with an
instance of EventFiringWebdriver.

Fixes #4408.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by barancev** [comment]
We need a test or a scenario to reproduce the issue fixed by this patch.

**Comment by barancev** [comment]
Please add a test that shows that the issue is actually fixed by this patch.

**Comment by Tom-Trumper** [comment]
Is the _steps to reproduce_ section of #4408 suitable or would you like a concrete test case?

**Comment by barancev** [comment]
A patch should contain a regression test.

**Comment by Tom-Trumper** [comment]
Added a test case - please let me know if there's anything I can do to improve it.

**Comment by barancev** [comment]
Oops, something goes wrong, commit list is too long :(

**Comment by Tom-Trumper** [comment]
Ooo err sorry about that, I'm a bit of noob when it comes to using Git. How do I fix this?

**Pull request closed without merging**
