### PR TITLE
[dotnet] Avoid performing JSON serialization in debugger display

### PR DESCRIPTION
**Pull request by RenderMichael**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Inspired by conversion in #14726

### Motivation and Context

The debugger display should provide a very brief snapshot of the object's values (the user can expand the object if they want to see everything). Performing JSON serialization is antithetical to that, and can result in performance issues.

image

image

image

image

image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Added `DebuggerDisplay` attributes to `DriverOptions`, `ReturnedCapabilities`, and `RemoteSessionSettings` classes to improve debugging experience.
- Implemented `GetDebuggerDisplay` methods to provide concise object state information for debugging purposes.
- Changed `reservedSettingNames` from `List` to `HashSet` in `RemoteSessionSettings` for potential performance improvement.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DriverOptions.cs</strong><dd><code>Add DebuggerDisplay for DriverOptions class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/DriverOptions.cs

<li>Added <code>DebuggerDisplay</code> attribute to <code>DriverOptions</code> class.<br> <li> Implemented <code>GetDebuggerDisplay</code> method for concise object state <br>representation.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14734/files#diff-3a23deddc7c714feb41423be7a50f6e63df3541f4a50e21c28286d52fa3584fa">+38/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ReturnedCapabilities.cs</strong><dd><code>Add DebuggerDisplay for ReturnedCapabilities class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/Internal/ReturnedCapabilities.cs

<li>Added <code>DebuggerDisplay</code> attribute to <code>ReturnedCapabilities</code> class.<br> <li> Implemented <code>GetDebuggerDisplay</code> method to show browser and capability <br>count.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14734/files#diff-eebee15322f2484cc4e7a6a5f2145d0a162da97100de4ea49ae71cec70a09a84">+12/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>RemoteSessionSettings.cs</strong><dd><code>Add DebuggerDisplay and optimize reservedSettingNames in </code><br><code>RemoteSessionSettings</code></dd></summary>
<hr>

dotnet/src/webdriver/Remote/RemoteSessionSettings.cs

<li>Added <code>DebuggerDisplay</code> attribute to <code>RemoteSessionSettings</code> class.<br> <li> Implemented <code>GetDebuggerDisplay</code> method for displaying browser and <br>driver count.<br> <li> Changed <code>reservedSettingNames</code> from <code>List</code> to <code>HashSet</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14734/files#diff-288dfba3f612ed5c9b4def9fa29733bca2af53aca8e3d1a265b1303235201c26">+14/-1</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by nvborisenko** [comment]
Hi @RenderMichael , your statements are absolutely correct. But let me correct main goal: `ToString()` should not be involved in json serialization. If we can achieve it, then everything becomes clear. Because of using DebuggerDisplay attribute to avoid performance issues looks strange.

**Comment by RenderMichael** [comment]
I wanted to be more careful, since changing a `ToString()` method is a breaking change. Even if Selenium doesn’t rely on it, maybe some users use it? 

Maybe the break is acceptable (it should be), but the debugger changes do not lead to any behavior differences at all.

**Comment by nvborisenko** [comment]
I understand your motivation, but I don't like a way how it is achieved. We are mixing purposes for debugging, string representation and json serialization. It adds a complexity (which affects maintainability).

If we would resolve initial issue with `ToString()`, then everything would clear.

I am afraid I cannot accept this changes in context of "what and how we are trying to resolve it" - for me it is "workaround on top of workaround". Let's wait what others will say.

**Comment by RenderMichael** [comment]
For what it’s worth, this debugger display is in line with what other custom debugger displays look like. For example, dictionaries look like this (and these types are basically strongly-typed dictionaries).

I agree that without the heavy `ToString()`, these custom displays may not be necessary (I still like them) and the default `{GetType().Name}` would suffice.

**Pull request closed without merging**
