### PR TITLE
[java] Add ExpectedCondition checking invisibility of single WebElement

### PR DESCRIPTION
**Pull request by valfirst**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by shs96c** [comment]
How is this different from `not(elementIfVisible(element))`?

**Comment by valfirst** [comment]
@shs96c, it handles exceptions, for example, when element becomes stale and treats it as invisible. `not(elementIfVisible(element))` doesn't catch such cases, if we add handling to expected conditions for visibility, waiters will wait while, for example, stale element becomes visible, which is just a waste of time, so expected conditions for visibility should fail early.

**Comment by valfirst** [comment]
Is there any chance to review/merge these changes?

**Comment by valfirst** [comment]
@lukeis, could you please review the changes?

**Comment by valfirst** [comment]
Is there any chance to review/merge these changes?

**Comment by valfirst** [comment]
@lukeis, @shs96c, is there any chance to review/merge these changes?

**Comment by valfirst** [comment]
@barancev, maybe you can review these changes?

**Comment by shs96c** [comment]
I've manually merged this as 0d65c3d6863102a05cfea1f9daa4499f4057e5e7. Sorry it took so long --- the people able to review and merge have been a little bit pressed for time.

**Pull request closed without merging**
