### PR TITLE
[py] remove desired capabilities argument for Webkitgtk

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

according to #14087 
i removed capabilities and add default Options same as in safari.webdriver class

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Bug fix

___

### **Description**
- Removed the `desired_capabilities` argument from the `WebDriver` constructor in `webkitgtk` module.
- Updated the constructor to use `options` directly, simplifying the initialization process.
- Removed the logic for merging `desired_capabilities` with `options` capabilities.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Remove <code>desired_capabilities</code> argument and simplify WebDriver <br>initialization.</code></dd></summary>
<hr>
      
py/selenium/webdriver/webkitgtk/webdriver.py

<li>Removed <code>desired_capabilities</code> argument from the <code>WebDriver</code> constructor.<br> <li> Updated the constructor to use <code>options</code> directly.<br> <li> Simplified the initialization process by removing capability merging <br>logic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14128/files#diff-0d84f899f993a1342a3a2e75a3ef749fb36e08dd022b607a7ab81beda9cfcbfc">+8/-18</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
This does fix the problem described in the issue, but this class is problematic in several ways, still

It's hard to write this code when we can't have tests because we aren't managing the drivers. 

But I think it needs to look more like:
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/wpewebkit/webdriver.py

**Comment by iampopovich** [comment]
> But I think it needs to look more like

I'm trying to understand the differences between the classes if I make wpewebkit and webkitgtk identical. I removed parameters such as port, executable_path, and log path because there are default parameters in the Service class, and other driver binds similarly do not use them. However, in this case, the two classes become identical, and I'm not sure if I correctly understood what is required in the comment above.

classes in the latest commit
Screenshot 2024-06-13 at 22 32 35
classes after I applied changes described above
Screenshot 2024-06-13 at 22 51 28

**Comment by titusfortner** [comment]
It makes sense to me that they are identical if they aren't actually doing anything other than starting/stopping the driver.

**Comment by titusfortner** [comment]
@iampopovich the python linter is failing on some of these changes, can you take a look?

**Comment by iampopovich** [comment]
@titusfortner Running the script `format.sh` did not make any corrections, but during the linting stage, `isort` showed an error. It might be a good idea to add the `isort` run to the `format.sh` script.

**Comment by titusfortner** [comment]
From root run `./go py:lint`

The format script is supposed to work without any additional software installed, but we haven't gotten that figured out for python. If we add the python bit, everyone who doesn't have a python dev environment will get failures. There's an open PR for part of it, we need to dig into it again.

**Review by titusfortner — APPROVED** [review]

**Pull request merged**
