### PR TITLE
HtmlUnit 2_16 cleanup

### PR DESCRIPTION
**Pull request by rbri**
some code cleanup of the HtmlUnit adapter

### CODE REVIEW

**Comment by rbri** [comment]
> I don't see a need to apply this change

Technically i agree it's more a matter of taste.
Are there any coding rules for this project regarding this?

**Comment by barancev** [comment]
> Are there any coding rules for this project regarding this?

No one (afaik) regarding this exact case.

**Comment by barancev** [comment]
Applied most parts of this PR

**Comment by rbri** [comment]
Thanks for applying...

**Pull request closed without merging**
