### PR TITLE
[py] add execute_cdp_cmd to Remote

### PR DESCRIPTION
**Pull request by Delta456**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Implements `execute_cdp_cmd` for Remote WebDriver

### Motivation and Context

Implements https://github.com/SeleniumHQ/selenium/issues/14799 as it should be accessible via Remote driver as well since Grid provides the endpoints and the underlying command executor

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Introduced the `execute_cdp_cmd` method to the Remote WebDriver class, enabling the execution of Chrome DevTools Protocol commands.
- This enhancement allows users to execute specific browser commands directly through the Remote WebDriver, similar to the existing functionality in the Chrome WebDriver.
- The method takes a command name and a dictionary of command arguments, returning the result of the command execution.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Add `execute_cdp_cmd` method to Remote WebDriver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/remote/webdriver.py

<li>Added <code>execute_cdp_cmd</code> method to the Remote WebDriver class.<br> <li> The method allows execution of Chrome DevTools Protocol commands.<br> <li> Provides a way to pass command name and arguments.<br> <li> Returns the result of the command execution.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14809/files#diff-c87c150ed2a08f5293db58a06da8bf7f14c3a5582586c6270c1be661dfdd0985">+20/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
Do you think we should add a test for it?

**Comment by Delta456** [comment]
I don't see any tests of `execute_cdp_cmd` for `ChromiumRemoteConnection`. I don't know how will this be tested too.

**Comment by VietND96** [comment]
@p0deje, do you think this is fine to merge?

**Comment by p0deje** [comment]
@VietND96 Doesn't this create a duplication as we already have the same method in ChromiumDriver? I am not sure how to re-use it, but maybe we can at least remove it from ChromiumDriver.

**Comment by Delta456** [comment]
Let's add a deprecation warning before removing it?

**Comment by VietND96** [comment]
@Delta456, I saw `class ChromiumDriver(RemoteWebDriver):`, do you think can make Chromium can access and reuse the same method from Remote?

**Comment by Delta456** [comment]
I will try

**Comment by Delta456** [comment]
> @Delta456, I saw `class ChromiumDriver(RemoteWebDriver):`, do you think can make Chromium can access and reuse the same method from Remote?

Yes, we can use the same method from Remote. I think we can merge this for now.

We can think of a deprecation warning afterwards.

**Comment by VietND96** [comment]
Thank you, @Delta456 !

**Pull request merged**
