### PR TITLE
[grid] ensure --drain-after-session-count is respected with a lot of sessions in the queue

### PR DESCRIPTION
**Pull request by joerg1985**
### Description
This PR will ensure a node does not start more than drain-after-session-count session by moving the counter check before starting a new session. The `drainLock` does ensure we do not drain to early while another session is still starting.

### Motivation and Context
When a new node does register and there are alot of sessions in the queue, the node did start more than expected sessions.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed race condition issue where nodes could exceed configured drain-after-session-count when many sessions are queued
- Implemented proper synchronization using ReadWriteLock to ensure accurate session counting
- Moved session count validation before actual session creation to prevent over-allocation
- Added proper error handling when drain limit is reached
- Improved logging and error messages for drain-related scenarios

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LocalNode.java</strong><dd><code>Fix race condition in session count tracking and node draining</code></dd></summary>
<hr>

java/src/org/openqa/selenium/grid/node/local/LocalNode.java

<li>Added ReadWriteLock to synchronize session count checking and draining<br> <li> Moved session count decrement check before session creation<br> <li> Changed drainAfterSessions from AtomicBoolean to boolean<br> <li> Added proper locking around session creation and drain checking

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14987/files#diff-edc2e1943a5d89fa45151a9d214cc608551c61101f237ca9a5993d6dd157b57b">+49/-12</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by joerg1985** [comment]
@VietND96 i think this might be interresting for you too?

**Comment by VietND96** [comment]
As far as I understand, this PR will handle a case where the node is set e.g `--drain-after-session-count=3`, and the queue has e.g 4 requests. It ensure that 3 requests are picked up properly and 1 request still waiting without fail?

**Comment by joerg1985** [comment]
Yes, the node did start to drain to early due to this and the still running sessions did get stuck.

**Comment by VietND96** [comment]
Yes, it makes sense since this is a case that I was also thinking about.

**Review by VietND96 — APPROVED** [review]

**Pull request merged**
