### PR TITLE
Imports and performance fixes

### PR DESCRIPTION
**Pull request by machinexa2**
Imports and performance fixes

### CODE REVIEW

**Comment by AutomatedTester** [comment]
I can't see how this passed tests.

Please can you run the build task I mentioned in another PR

**Comment by AutomatedTester** [comment]
If we remove the pybase64 items from this PR and we can see about merging the rest.

**Comment by machinexa2** [comment]
Ok, so all pybase64 changed to base64

**Review by AutomatedTester — APPROVED** [review]
This could have been merged with other PRs. In future go for similar changes in a PR and then don't forget to add decent commit messages

**Pull request merged**
