### PR TITLE
Add proxy support for web requests to the remote server

### PR DESCRIPTION
**Pull request by cheesestringer**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by p0deje** [comment]
Jim will need to review this, but I can say that it would be great if you could explain the reason behind these changes and also add some regression test for it.

**Comment by cheesestringer** [comment]
In an enterprise environment we can't communicate with grids like BrowserStack unless we use a proxy for the requests.

**Comment by cheesestringer** [comment]
In our enterprise environment we can't communicate with grids like BrowserStack unless we use a proxy for the requests.

**Comment by Saetabis1** [comment]
Could it be this a posible solution for #4770 or #4387 ?

**Comment by stormoz** [comment]
@Saetabis1 I do not believe so

**Comment by cheesestringer** [comment]
@stormoz When fixing conflicts had to refactor to IWebProxy anyway :P

**Comment by Elufimov** [comment]
What stops this pull request from merging? It will bring ability to easy avoid #4770

**Comment by p0deje** [comment]
@Elufimov Jim (who is the only C# bindings maintainer) needs to have a look and obviously, it takes time to go through everything. Please be patient.

**Comment by Elufimov** [comment]
I understand that. But there is a paradox, library do not have enough maintainers because nobody can prove worthy enough and no one accept contribution because of insufficient number of maintainers.

**Comment by jimevans** [comment]
@Elufimov Is that criticism supposed to be implicit or explicit? Unfortunately, I have a family that relies on me to bring in an income for small things like food and shelter. My volunteer for he Selenium project does not provide that l, and has to be a lower priority. I’m sorry if I’ve not met your expectations, or if a particularly stringent work schedule on my company’s part for the last several months has interefered with what you’d like to see on this (or any other) issue.

**Comment by Elufimov** [comment]
@jimevans I did not criticize your contribution. I really apologize if it looks like this . I only want to say that project will never gets new contributors if no one will accept contribution. It easy to manage a fork than create a pull request that never be merge.

**Comment by jimevans** [comment]
And yet, you did manage to criticize, and did so again just now. Thanks for that. Allow me to direct you to [this Twitter thread](https://twitter.com/jimevansmusic/status/938744796319047680) wherein I give some context for the things I’ve been trying to manage. Most of it is not anyone’s concern, but now I’m having to air things I’d rather keep private because of the apparent lack of understanding some people seem to have.

**Comment by cheesestringer** [comment]
Sorry to hear Jim :(

**Comment by cgoldberg** [comment]
@cheesestringer

The current state of your PR is not even ready for review IMHO.  Personally, I don't want the maintainers spending their time on incomplete PR's from unknown contributors with no explanation and a lack of accompanying tests... It's a waste of time, no matter how important you perceive your code to be.

A maintainer quickly responded to the initial PR with: "it would be great if you could explain the reason behind these changes and also add some regression test for it".  Your response to that was: "I don't think a regression test is needed".  So... you submitted a PR with a blank description and don't want to write tests for it.  If you want your code merged, you should address those issues instead of just complaining about lack of maintainers.  Remember, the more effort you put into a contribution, the easier it is to review and merge.

**Comment by cheesestringer** [comment]
@cgoldberg I never complained...

**Comment by cgoldberg** [comment]
@cheesestringer my bad, I was referring to the comments by @Elufimov

**Comment by Elufimov** [comment]
@cheesestringer this is not my PR since that I am not the one who created it. And I totally agree with you about description and tests. However, since this pr does not have any breaking changes and it can fix (workaround actually) remoting on dotnet core it could be merged without tests. If it not possible I totally understand.

**Comment by Elufimov** [comment]
I think if I wrote my intentions this conversation would could be more constructive. Sorry for this.

**Comment by bradmarder** [comment]
Can this get merged? Package does not work at all currently with netcore 2.0,, and this fix solved the `PlatformNotSupportedException ` issue.

**Comment by elsyms** [comment]
I'm really surprised this hasn't been merged yet, it's a major blocker for us to actually get our tests running with a remote Selenium grid on .NET Core 2.0.

**Comment by jimevans** [comment]
Since the .NET Core reason for this PR (#4770) was resolved in 942b8a4, I'm going to close this PR without merging. I've decided to implement a different approach that will allow anyone to customize the HTTP request getting sent to the remote server without the need to proliferate additional constructors to `RemoteWebDriver`. To wit, I'm implementing a `BeforeRemoteHttpRequest` event that you can hook your code into, and modify the HTTP request as needed. To use it, you'd do something like this:

    public void Start()
    {
        HttpCommandExecutor executor = new HttpCommandExecutor(new Uri("http://localhost:4444/wd/hub"), TimeSpan.FromSeconds(60));
        executor.BeforeRemoteHttpRequest += BeforeRemoteHttpRequestHandler;
        IWebDriver driver = new RemoteWebDriver(executor, new ChromeOptions().ToCapabilities());
     }

    private void BeforeRemoteHttpRequestHandler(object sender, BeforeRemoteHttpRequestEventArgs e)
    {
        // Note: WebRequest.DefaultWebProxy is an IWebProxy implementation.
        // This could be anything, from adding additional headers, to modifying
        // the content of the request. Use with extreme caution.
        e.Request.Proxy = WebRequest.DefaultWebProxy;
        e.Request.AutomaticDecompression = DecompressionMethods.GZip
    }

This ought to give us the flexibility to be able to modify the requests as required, and be able to handle all of the use cases that would entail, without needing to pass additional information around into the driver.

**Comment by jimevans** [comment]
The event has been added in a3a2062, and will be available in the next release of the .NET bindings.

**Pull request closed without merging**
