### PR TITLE
#10812 don't allow selecting a disabled option

### PR DESCRIPTION
**Pull request by asolntsev**
fix for #10812

### CODE REVIEW

**Review by pujagani — APPROVED** [review]
Thank you for your contribution! @asolntsev  The changes look good to me. Other language bindings will also need to add the same checks.

**Review by titusfortner — DISMISSED** [review]
Need to agree this is a problem (I don't think it is) before we solve it with this code.

**Review by titusfortner — CHANGES_REQUESTED** [review]
I don't think we need to check if the select list is enabled. If it is disabled, the option will also be disabled. I'd prefer to optimize the number of commands made for a successful test rather than an unsuccessful test. What do you think?

**Comment by asolntsev** [comment]
> I don't think we need to check if the select list is enabled. If it is disabled, the option will also be disabled. I'd prefer to optimize the number of commands made for a successful test rather than an unsuccessful test. What do you think?

Yes, I also like to make as few commands as possible. 
But the correctness should be in first place, right?

If `<select id="cars">` is `disabled` then user cannot select any options. Cannot even see them. 
But method `new Select($("#cars")).selectByValue("saab");` doesn't throw any exceptions. _It leaves a false impression that the option has been selected._

**Comment by titusfortner** [comment]
A non-disabled `option` nested in a disabled `select`, will return `false` for `isEnabled()`.
`selectByValue()` calls `setSelected()` which calls `assertOptionIsEnabled()` which will error.

That said, it's only one extra command when using this wrapper, and it does give a better error message, so maybe I'm being too picky.

@diemol what do you think of this implementation?

**Review by diemol — APPROVED** [review]
Thank you, @asolntsev!

**Pull request merged**
