### PR TITLE
Chrome (so HtmlUnit) does not trigger alerts on unload

### PR DESCRIPTION
**Pull request by asashour**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by shs96c** [comment]
I'm not sure why this is needed: the `@Ignore` is effectively the same as the assumption you're putting in, and the test is marked as `@NotYetImplemented` for HtmlUnitDriver, and remains so with this change. I'm obviously missing something :)

**Comment by asashour** [comment]
From what I humbly understand, `assumeFalse` is a normal expected result, to say that this test is not meant to be used because of this condition.

However, `@NotYetImplemented`, means it is a bug in the implementation and should be fixed later.

But you are right, I will remove the `@NotYetImplemented` in PR, similar to what was done [here](https://github.com/SeleniumHQ/htmlunit-driver/blob/remote/src/test/java/org/openqa/selenium/AlertsTest.java#L385)

**Comment by shs96c** [comment]
Heh. There's history here!

The `@Ignore` was written before `Assume` was a A Thing in JUnit and allowed us to do much the same thing --- ignore a test completely. The `@NotYetImplemented` was there for tracking work in progress, but we never consistently applied it throughout the tree, relying on `@Ignore` instead. I think you've been the most assiduous about applying the latter annotation correctly :)

You're right, most of the time we can simply replace `@Ignore` with an assumption, particularly when it comes to the type of browser we're using.

**Comment by shs96c** [comment]
Merged and pushed manually.

**Comment by shs96c** [comment]
Thank you!

**Pull request closed without merging**
