### PR TITLE
Fix undefined method encoded for String

### PR DESCRIPTION
**Pull request by zlyaksa**
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/7119)

### CODE REVIEW

**Comment by twalpole** [comment]
@p0deje It used to support passing a profile name in, and it's still shown in the docs - https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver.rb#L74 - I think this is something we either need to fix, or fix & deprecate and do another 3.x release.

**Comment by twalpole** [comment]
The root issue is that the string passed in is only converted to an actual profile if it's set via the `profile=` writer - https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/firefox/options.rb#L125 .  If it's set any other way (initialize, add_option) it doesn't get converted.

**Comment by titusfortner** [comment]
I'm working on some code intended to make sure the same behaviors are used for options classes regardless of how it is added to the class (initialize, add_*, writer, etc)

**Comment by p0deje** [comment]
A proper fix landed in 34a2a39782ef1e3a4723ccb2e9ede1e2b469ed17 and will be released in 3.142.0 and 4.0.0.alpha1. Thank you!

**Pull request closed without merging**
