### PR TITLE
[py]: remove deprecated `find_element_by_` methods

### PR DESCRIPTION
**Pull request by symonk**
I think this is alright for `4.3` now.  Removal of `find_element_by_` methods throughout the python bindings.  I don't think any tests where running through those but instead the correct `find_element|find_elements`.  Will grab fallout from CI if any occurs.

Likely some `docs` related fallout here, will address as I find it.

### CODE REVIEW

**Review by AutomatedTester — APPROVED** [review]

**Comment by aluchuk4c** [comment]
image

**Comment by Ahsoka** [comment]
Hello,
I was wondering why these methods were removed.
Thank you!

**Comment by titusfortner** [comment]
@Ahsoka  https://github.com/SeleniumHQ/selenium/issues/8806#issuecomment-711947184

**Comment by Pikamander2** [comment]
For anyone who's in the process of updating their code, here are 16 find-and-replace strings that you can use:

```
.find_element_by_class_name(
.find_element(By.CLASS_NAME, 

.find_element_by_css_selector(
.find_element(By.CSS_SELECTOR, 

.find_element_by_id(
.find_element(By.ID, 

.find_element_by_link_text(
.find_element(By.LINK_TEXT, 

.find_element_by_name(
.find_element(By.NAME, 

.find_element_by_partial_link_text(
.find_element(By.PARTIAL_LINK_TEXT, 

.find_element_by_tag_name(
.find_element(By.TAG_NAME, 

.find_element_by_xpath(
.find_element(By.XPATH, 

.find_elements_by_class_name(
.find_elements(By.CLASS_NAME, 

.find_elements_by_css_selector(
.find_elements(By.CSS_SELECTOR, 

.find_elements_by_id(
.find_elements(By.ID, 

.find_elements_by_link_text(
.find_elements(By.LINK_TEXT, 

.find_elements_by_name(
.find_elements(By.NAME, 

.find_elements_by_partial_link_text(
.find_elements(By.PARTIAL_LINK_TEXT, 

.find_elements_by_tag_name(
.find_elements(By.TAG_NAME, 

.find_elements_by_xpath(
.find_elements(By.XPATH, 
```

You'll also need to import `By` if you haven't already done so:

    from selenium.webdriver.common.by import By

**Comment by grepwood** [comment]
I'm joining @Ahsoka. @symonk why was this removed? We would like to know the full story, because I as a selenium user honestly don't see any benefit, in fact, I had to commit spare time to rewrite my code. Time I could otherwise spend drinking beer and eating curry.

**Comment by titusfortner** [comment]
It's a more maintainable API and more consistent with what the other implementations are doing.

There's a lot of code in this repo to keep on top of, and we also like to have time to drink beer and eat curry.

**Comment by grepwood** [comment]
@titusfortner that's a perfectly understandable explanation. Thank you! Enjoy your beer and curry :)

**Pull request merged**
