### PR TITLE
use StringBuilder instead of StringBuffer

### PR DESCRIPTION
**Pull request by asolntsev**
minor refactoring

### CODE REVIEW

**Comment by titusfortner** [comment]
Isn't `StringBuffer` preferred for thread safety?

**Comment by pujagani** [comment]
> Isn't `StringBuffer` preferred for thread safety?

You are right, Titus. However, the code changes made in this pull request are in the methods that are not marked synchronized nor do they use locks so it is safe to assume that multiple threads do not access them simultaneously. `StringBuilder` is recommended performance-wise in such cases.

**Review by pujagani — APPROVED** [review]
Thank you, @asolntsev!

**Comment by asolntsev** [comment]
@titusfortner @pujagani No, in most cases `StringBuilder` is preferred over `StringBuffer` because it doesn't use unneeded synchronisation. Almost always it's used as a local variable inside of a method, thus not needing any synchronisation.

`StringBuffer` does synchronisation, thus it's slower, and it's needed only if it's used in a multithreaded context. Which means: almost never.

**Pull request merged**
