### PR TITLE
Ensure you can close stream before attempting to.

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
This is to resolve the [issue](https://github.com/SeleniumHQ/selenium/issues/1469) introduced by [recent refactoring](https://github.com/SeleniumHQ/selenium/commit/0ee1c15d7dd98344cd2e35e7a4bfa92561e4a686).  For some webdriver types the streams in `self.process` are `None`.

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
@ivargas-handy, updated for your concern.

**Comment by ivargas-handy** [comment]
@lukeis :+1:

**Comment by lukeis** [comment]
@rmfitzpatrick can you confirm you've signed the [CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)?

**Comment by rmfitzpatrick** [comment]
Signed.

**Comment by AutomatedTester** [comment]
landed in cc07382

**Pull request closed without merging**
