### PR TITLE
[dotnet] Public but non-user-related types can be invisible

### LINKED ISSUE #14813: [dotnet] [🚀 Feature]: Consider using the new `Base64Url`
### Feature and motivation

With the recent release of .NET 9, the `Base64Url` type was released. This type fills a common need that .NET developers have, and up until recently, has been implemented, re-implemented, and polyfilled in many projects.

Selenium .NET has its own implementation: found here:
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Internal/Base64UrlEncoder.cs

As the links in that file show, this was ripped from the Azure Active Directory implementation. They recently migrated to using the `Base64Url` type as well: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2817/

Luckily for us, the .NET team released the `Base64Url` type as a .NET Standard 2.0 NuGet package, found here: https://www.nuget.org/packages/Base64Url

We can take this dependency unconditionally for now, and if/when we support a .NET 9+ TFM, we can conditionally remove the dependency there.

### Usage example

The polyfill type `Base64UrlEncoder` is `public` (should it be `internal`?). Anyone currently relying on it should not be affected though.

As noted in the linked PR on Azure AD, there are minor differences in behavior between the `Base64Url` type and the `Base64UrlEncoder` type. For Azure AD, it seems like that requires them to keep the type around.

For us, we should investigate what exactly those differences are and if it would be acceptable to just use `Base64Url` directly.

### PR DESCRIPTION
**Pull request by RenderMichael**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Certain types are used only internally, but must be public because they are used across projects for testing.

Due to technical limitations, we cannot make these types internal.

This change will make those types invisible to users, which should prevent anyone taking a dependency on them.

### Motivation and Context

Resolves #14813 the best we can.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
enhancement

___

### **Description**
- Added `EditorBrowsable` attribute to internal classes to make them invisible to users.
- Set `EditorBrowsableState` to `Never` for `Base64UrlEncoder`, `PortUtilities`, and `ReturnedCookie` classes.
- Enabled nullable reference types in `PortUtilities`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Base64UrlEncoder.cs</strong><dd><code>Hide Base64UrlEncoder class from user visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/Internal/Base64UrlEncoder.cs

<li>Added <code>EditorBrowsable</code> attribute to <code>Base64UrlEncoder</code> class.<br> <li> Made the class invisible to users by setting <code>EditorBrowsableState</code> to <br><code>Never</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14833/files#diff-35d9ef4edcc03326e175080418cb703fc44a741765ab59a58ed2039813178fef">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>PortUtilities.cs</strong><dd><code>Hide PortUtilities class from user visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/Internal/PortUtilities.cs

<li>Added <code>EditorBrowsable</code> attribute to <code>PortUtilities</code> class.<br> <li> Made the class invisible to users by setting <code>EditorBrowsableState</code> to <br><code>Never</code>.<br> <li> Enabled nullable reference types.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14833/files#diff-c7ae823e95550e8b18f454f1f6199dc420a1d64263398ae151b13dae264a89c6">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ReturnedCookie.cs</strong><dd><code>Hide ReturnedCookie class from user visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/src/webdriver/Internal/ReturnedCookie.cs

<li>Added <code>EditorBrowsable</code> attribute to <code>ReturnedCookie</code> class.<br> <li> Made the class invisible to users by setting <code>EditorBrowsableState</code> to <br><code>Never</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14833/files#diff-59e197232c3804bd89a4b397c913285ba02a5c381995b936253ca6e17d5025ca">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by nvborisenko** [comment]
It should be `internal`.

**Comment by RenderMichael** [comment]
In that case, what do you think of the suggestion I made in #14813? We can't make it `internal` in a normal way, so we have to get creative. We can also copy-paste the code into the tests.

If we're not willing to make too much magic, then I think we should make this PR. The current state is the worst of all worlds: users may get intellisense suggestions for these types and start using them.

**Comment by nvborisenko** [comment]
> so we have to get creative

No creativity, it should be `internal`. Build system is not yet ready? Yes! But it should be `internal`.

**Comment by nvborisenko** [comment]
Maximum what I can do: https://seleniumhq.slack.com/archives/CBH302726/p1732918073634829.

I am closing it because of it is a strange workaround, not a proper solution.

**Pull request closed without merging**
