### PR TITLE
fixing #12469 - incompatible types error in mypy

### PR DESCRIPTION
**Pull request by bandophahita**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Fixed the annotation assigned to `driver` argument in `ActionChains` so mypy will allow all drivers to be accepted.
See #12469

### Motivation and Context

Allows mypy to pass properly when passing remote webdriver into `ActionChains`

### Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.

### CODE REVIEW

**Comment by MarcelWilson** [comment]
The Python/Lint github action failed on a file that wasn't changed in this PR.  It would appear that the head of trunk has commits that failed as well. 

What is the proper course of action?  Do I need to fix the linter errors from trunk in order to get the PR merged?

**Comment by symonk** [comment]
Sorry @MarcelWilson that was caused by me, I fixed another bug on mobile and didn't have the benefit of being able to run the pre-commit linter hooks! - fixed in `trunk` and pulled into this branch

**Review by symonk — APPROVED** [review]

**Comment by MarcelWilson** [comment]
@symonk No worries!  Contributing to a large project such as selenium is just a little intimidating.  Thanks.

**Comment by titusfortner** [comment]
Thanks for the fix!

**Pull request merged**
