### PR TITLE
add logging of a caught exception in TestSession

### PR DESCRIPTION
**Pull request by innokenty**
log exception that can occur while sending delete session request

### CODE REVIEW

**Comment by andreastt** [comment]
Have you signed the CLA?

**Comment by andreastt** [comment]
Thanks for the patch, by the way.  LGTM.

**Comment by innokenty** [comment]
So finally?..

**Comment by ddavison** [comment]
fixed in f55c012.. thanks!

**Comment by ddavison** [comment]
whoops.  did yo make sure you signed the [CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) @innokenty ?  go ahead and do that.

**Comment by innokenty** [comment]
@ddavison ..now i did!

**Pull request closed without merging**
