### PR TITLE
[java] Merge android specific parameters in chrome options

### LINKED ISSUE #14133: [🐛 Bug]: ChromiumOptions: android-specific options are removed after merge
### What happened?

1. Create ChromiumOptions (ChromeOptions) and set android-specific properties (activity/package/sn/process)
2. Create MutableCapabilities  (empty one)
3. Merge ChromiumOptions with Mutable capabilities
Expected: result contain the chromiumOptions
Actual: all android-related options (from 
the `ChromiumOptions.androidOptions field`) are removed
scr_20240614T01_18_10

### How can we reproduce the issue?

```shell
var original = new ChromeOptions();
		original.setAndroidActivity("co_activity");
		original.setAndroidPackage("co_package");
		original.setExperimentalOption("experimental", "co_experimental");
		original.addArguments("--co_argument");

		System.out.println("Original :: " + original.asMap());

		var caps = new MutableCapabilities();
		var merged = original.merge(caps);

		System.out.println("Merged   :: " + merged.asMap());
```

### Relevant log output

```shell
Original :: {browserName=chrome, goog:chromeOptions={androidActivity=co_activity, androidPackage=co_package, args=[--co_argument], experimental=co_experimental, extensions=[]}}
Merged   :: {browserName=chrome, goog:chromeOptions={args=[--co_argument], experimental=co_experimental, extensions=[]}}
```

### Operating System

windows 10

### Selenium version

java 4.21.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

according to bug #14133 I added androidOptions to merge method ChromiumOptions.mergeInPlace
I also added a test for the new functionality.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Added merging of `androidOptions` in `ChromiumOptions.mergeInPlace` method to handle Android-specific parameters.
- Introduced a new test in `ChromeOptionsTest` to verify the correct merging of Android-specific options.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ChromiumOptions.java</strong><dd><code>Add merging of Android-specific options in ChromiumOptions</code></dd></summary>
<hr>
      
java/src/org/openqa/selenium/chromium/ChromiumOptions.java

<li>Added merging of <code>androidOptions</code> in <code>mergeInPlace</code> method.<br> <li> Included a check for <code>androidOptions</code> before merging.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14217/files#diff-4133f16d6f27fa85995d3806efc8a9a862f9a073ecbf16fb03fc3657bb2a586c">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ChromeOptionsTest.java</strong><dd><code>Add test for merging Android-specific options in ChromeOptions</code></dd></summary>
<hr>
      
java/test/org/openqa/selenium/chrome/ChromeOptionsTest.java

<li>Added a test to verify merging of Android-specific options.<br> <li> Ensured the test checks for equality of options after merging.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14217/files#diff-a2da4c56efda1ff71535e17798b3e48b6599280a2e215d9837d082182061a584">+15/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by diemol** [comment]
@iampopovich seems the tests cannot be built https://github.com/SeleniumHQ/selenium/actions/runs/9745320822/job/26892961031?pr=14217#step:15:725

**Comment by iampopovich** [comment]
@diemol my bad , i forgot to import `assertEquals`
fix's on the way

**Review by diemol — COMMENTED** [review]
Did you run the build before? 

Still getting errors: https://github.com/SeleniumHQ/selenium/actions/runs/9913402348/job/27390332113?pr=14217#step:15:482

**Comment by iampopovich** [comment]
@diemol i guess something happened with my working environment, and I missed another import. I also did not check the build in Gitpod.

Now i ran build with command `bazel build //java/...`
the build result is attached in the log below.
I apologize for the time wasted on such elementary mistakes.
```
INFO: Found 1725 targets...
INFO: Elapsed time: 175.258s, Critical Path: 126.66s
INFO: 5138 processes: 3723 internal, 548 darwin-sandbox, 1 local, 866 worker.
INFO: Build completed successfully, 5138 total actions
```

**Review by diemol — APPROVED** [review]
Thank you, @iampopovich!

**Pull request merged**
