### PR TITLE
Pybase64 2

### PR DESCRIPTION
**Pull request by machinexa2**
Pybase64 part 2

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Have you run tests for these? I don't see how pybase64 is included into the build? 

build target for this is `bazel test //py/...`

**Comment by machinexa2** [comment]
Pybase64 is just replacement for base64, with improved speed

**Comment by machinexa2** [comment]
https://pypi.org/project/pybase64/ @AutomatedTester

**Comment by machinexa2** [comment]
Wait, I will try to run tests

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
