### PR TITLE
[js] Correct example code

### PR DESCRIPTION
**Pull request by jugglinmike**
Consistently await all Promise-returning API calls. Format code
according to `google_search_generator.js` (the equivalent example for
generator functions).

The current version technically works, although I'm not sure why. Note that [the "WebDriverJs" wiki page](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs) should also be corrected.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by jleyba** [comment]
The current version works because `driver.findElement(By.name('q'));` returns a [`WebElementPromise`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebElementPromise.html), so it can be used like any other promise.

`WebElementPromise` resolves to a plain `WebElement` - same basic API minus the promise methods (`then`, `catch`, etc).

**Comment by jugglinmike** [comment]
I think I understand. Is it accurate to say that these two statements are
equivalent?

```js
webElementPromise.sendKeys('abc');

webElementPromise.then(() => webElementPromise.sendKeys('abc'));
```

**Comment by jleyba** [comment]
Almost - you need the resolved webelement in your then callback:

```js
let webElementPromise = driver.findElement(By.name('q'));

webElementPromise.sendKeys('foo');
webElementPromise.then((e) => e.sendKeys('foo'));
```

**Comment by jugglinmike** [comment]
Got it. Thanks for the clarification!

**Pull request closed without merging**
