### PR TITLE
Fix: fixing imports in capability test (c-nodejs)

### PR DESCRIPTION
**Pull request by harsha509**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Harsha509** [comment]
Thanks for reviewing @christian-bromann

**Comment by christian-bromann** [comment]
@Harsha509 do you know why the test has not been failing before without these borked imports?

**Comment by Harsha509** [comment]
yes. bazel doest not run all js tests. there is an issue with bazel configuration for js bindings

**Comment by Harsha509** [comment]
Thanks @corevo ,

This is fixed with commit https://github.com/SeleniumHQ/selenium/commit/4c547754bcbb2702ffead845c757ee812021260e.

**Comment by corevo** [comment]
Already fixed in upstream

**Pull request closed without merging**
