### PR TITLE
chore/code style changes, add util

### PR DESCRIPTION
**Pull request by potapovDim**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Changes in code style, add util functions file

### Description
Changes in code style, add util functions file

### Motivation and Context
Align code style format 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by potapovDim** [comment]
@harsha509 Hi, can you take a look, please ?

**Comment by harsha509** [comment]
Thank you @potapovDim !

LGTM!

Waiting for CI checks!

**Comment by potapovDim** [comment]
@harsha509 some fails, but does not look like that it is related to my changes

**Comment by harsha509** [comment]
> @harsha509 some fails, but does not look like that it is related to my changes

Sure,

Looks like Firefox tests are failing, I will look into it!

**Comment by potapovDim** [comment]
@harsha509 hi, any updates ?

**Comment by harsha509** [comment]
> @harsha509 hi, any updates ?

I see window tests are failing in firefox. Am sure those failures are nothing to do with these changes.
Will merge the pr!

**Review by harsha509 — APPROVED** [review]

**Comment by harsha509** [comment]
Thank you @potapovDim !

**Comment by potapovDim** [comment]
@harsha509 i checked builds in trunk and there are many fails with firefox browser

**Pull request merged**
