### PR TITLE
[dotnet] Overwrite internal log file if it already exists

### LINKED ISSUE #13860: [🚀 Feature]: Ability to overwrite files when using FileLogHandler
### Feature and motivation

I want to make use of FileLogHandler to output driver logs to the filesystem for the testing suite (one file per test). Currently this only supports appending logs to the file. I do not need to keep logs from previous test runs and would prefer to create new files each time so that I only have the relevant logs.

### Usage example

The solution could be as simple as having an overload constructor for the FileLogHandler:

`public FileLogHandler(string filePath, bool overwriteExisting)`

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
Added overload constructor for `FileLogHandler(string filePath, bool overwrite)`.

### Motivation and Context
Fixes https://github.com/SeleniumHQ/selenium/issues/13860

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

## **Type**
Enhancement, Tests

___

## **Description**
- Added an overloaded constructor in `FileLogHandler` to support optional overwriting of log files.
- Modified file handling to append to an existing file or overwrite based on the new `overwrite` parameter.
- Enhanced unit tests to cover new functionality, including tests for appending to existing files, overwriting files, and handling non-existent files.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>FileLogHandler.cs</strong><dd><code>Support Optional Overwriting in FileLogHandler</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
dotnet/src/webdriver/Internal/Logging/FileLogHandler.cs

<li>Added an overloaded constructor to allow specifying whether to <br>overwrite the log file.<br> <li> Modified file opening logic to either append to or create/overwrite <br>the file based on the <code>overwrite</code> parameter.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13900/files#diff-88dbc4fbc36914be110881a9ad92d6484a5ea86aa043bdad7b797f666d28be26">+14/-2</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>FileLogHandlerTest.cs</strong><dd><code>Extend Tests for FileLogHandler Overwrite and Append Behaviors</code></dd></summary>
<hr>
      
dotnet/test/common/Internal/Logging/FileLogHandlerTest.cs

<li>Added tests to verify appending behavior when the file does not exist.<br> <li> Added tests to verify appending behavior when the file exists.<br> <li> Added tests to verify file overwriting behavior.<br> <li> Added tests to verify file creation and writing when the file does not <br>exist.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13900/files#diff-ae835de2be92fe1d05d7f0565bf909daecc58a4cd193ee591f5d5bc7240dab23">+91/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by nvborisenko** [comment]
Open questions:
- argument name `overwrite` or `rewrite`
- by default `true` or `false` (seems `true`, like a fresh log file per execution)

@diemol please suggest the best naming for point 1

@YevgeniyShunevych cc

**Comment by YevgeniyShunevych** [comment]
As for me, the current implementation is good. `overwrite` and `false` by default (the same behavior as it was before this PR). Just curious whether in other WebDriver language implementations similar log functionality by default overwrites log file or appends to it.

**Comment by diemol** [comment]
I agree with @YevgeniyShunevych

**Comment by diemol** [comment]
Can we merge this?

**Comment by nvborisenko** [comment]
We still need to agree whether existing file should be overwritten by default.

**Comment by diemol** [comment]
I thought the conversation above meant the default was `false`, did I miss something?

**Comment by nvborisenko** [comment]
OK, then let's proceed if it is aligned with others bindings.

**Comment by diemol** [comment]
Oh, wait. Good point. I was somehow not reading everything in detail. They all overwrite by default, except JS because it does not support sending logs to a file for now. 

So, yeah, good point @nvborisenko, it should be `true` the default then.

**Review by diemol — APPROVED** [review]
Thank you, @nvborisenko!

**Pull request merged**
