### PR TITLE
fixes typo

### PR DESCRIPTION
**Pull request by bmannix**
This was bugging me, here's a PR

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the CLA?

**Comment by ddavison** [comment]
i'll merge this in as soon as you've verified that you've signed the [CLA](http://goo.gl/qC50R) :+1:

**Comment by bmannix** [comment]
I've signed the CLA

**Comment by ddavison** [comment]
landed in 8bc01d6143a4e4c7636aea3b806c19af75ca5d0b .. thanks!

**Pull request closed without merging**
