### PR TITLE
typo in comment

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the [CLA](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)?

**Comment by gotcha** [comment]
Nope, I suggest you fix the typo yourself.

**Comment by ddavison** [comment]
not sure why you'd trouble yourself with a PR if you just wanted us to do it, but whatever. done.  thanks.

**Comment by gotcha** [comment]
To allow you to accept the fix with a single click. I did not know there was the CLA.

**Comment by ddavison** [comment]
when you create a pull request, there is a link at the top that says "please abide by the CONTRIBUTING guidelines" :)  it is step 6 to sign the contributor license agreement.

> We ask this so that we know that contributors have the right to donate the code.

also it will put you as an official contributor to the source code.

No worries though, it's in.  If you want to create a future pull request, feel free. just make sure to read the contribution guidelines :)    ([CONTRIBUTING.md](https://github.com/seleniumhq/selenium/tree/master/CONTRIBUTING.md)

**Comment by gotcha** [comment]
I have now signed the CLA. However, there should be a balance between formality and openness. It is in the interest of everyone to keep barrier to contribute fix to typos as low as possible.

**Comment by ddavison** [comment]
agreed.. I don't believe there's a contributor here that doesn't agree with that statement.  I think we also all agree that is super annoying and a pain to not just click the "Merge" button, but we need to sign-off of every commit per rules set by the software freedom conservancy.

**Pull request closed without merging**
