### PR TITLE
[js] Fix typo in execute_script_test.js

### PR DESCRIPTION
**Pull request by vitalets**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by vitalets** [comment]
We did not catch it before as tests always passed and `.then` was not executed

**Comment by jleyba** [comment]
In fairness, the test still would have failed with a ReferenceError if this code path triggered :)

Thanks for the patch!

**Comment by vitalets** [comment]
Yes, a kind of tricky test :)

btw, @jleyba I noticed that count of browser tests of javascript binding is significantly less than for java/python. Are they needed or it's intentional?

**Comment by jleyba** [comment]
Converting tests is tedious. I converted enough to be relatively happy with the coverage and called it a day. PRs for increased test coverage are always welcome.

**Comment by vitalets** [comment]
Ok, I will have a look on it. 
Could you advice how to measure coverage for javascript tests?
I use `mocha --harmony -t 600000 --recursive test` that seems not to set any coverage tool.

**Pull request merged**
