### PR TITLE
Increased JSON max depth in AbstractHttpCommandCodec to 100 so that A…

### PR DESCRIPTION
**Pull request by Yith1**
…xeBuilder.analyze() does not fail when processing results.

See comments on https://github.com/SeleniumHQ/selenium/pull/12205

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
@Yith1 thank you! can you please sign the license agreement?

**Comment by Yith1** [comment]
> @Yith1 thank you! can you please sign the license agreement?

I think I've done that.

**Comment by joerg1985** [comment]
@titusfortner I think this limit is more a general safety net, it might be best to increase the JsonOutput.MAX_DEPTH to 100?

**Comment by titusfortner** [comment]
@joerg1985 I don't know the answer, just encouraging participation and getting feedback from you since you do know the answer. 😄  
Thanks @Yith1 for the suggestion.

**Comment by joerg1985** [comment]
Before #12056 the limit was not really working, so i will just increase it now.
If there are further issues regarding this limit it might be best to make it configurable.

**Comment by joerg1985** [comment]
Here we go: https://github.com/SeleniumHQ/selenium/commit/26518336896b1f06381e2df3e1aa725daa21b03a

**Comment by diemol** [comment]
Thank you, @joerg1985!

**Pull request closed without merging**
