### PR TITLE
[py] moved project metadata from `setup.py` to `pyproject.toml`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
- Moved project metadata from `setup.py` to `pyproject.toml`

### Motivation and Context
- `pyproject.toml` is one stop solution which eliminates whole bunch of configuration files.
- https://peps.python.org/pep-0621/

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Moved project metadata from `setup.py` to `pyproject.toml`.
- Removed project metadata such as name, version, license, description, URLs, classifiers, packages, and dependencies from `setup.py`.
- Added project metadata including name, version, license, description, readme, Python requirements, classifiers, and dependencies to `pyproject.toml`.
- Defined package inclusion and exclusion rules in `pyproject.toml`.
- Added project URLs for repository, bug tracker, changelog, documentation, and source code in `pyproject.toml`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>setup.py</strong><dd><code>Removed project metadata from `setup.py`.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/setup.py

<li>Removed project metadata such as name, version, license, description, <br>URLs, classifiers, packages, and dependencies.<br> <li> Retained custom installation command and Rust extensions <br>configuration.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14311/files#diff-722aeeec2821793eb6adf0c529cc7439c4b27ce78937cbb8840e94d4fc1c4017">+0/-57</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pyproject.toml</strong><dd><code>Added project metadata to `pyproject.toml`.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/pyproject.toml

<li>Added project metadata including name, version, license, description, <br>readme, Python requirements, classifiers, and dependencies.<br> <li> Defined package inclusion and exclusion rules.<br> <li> Added project URLs for repository, bug tracker, changelog, <br>documentation, and source code.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14311/files#diff-3adb340b5a499e26b04507d972c31f5cf6fc27a6d81e3f7b547bf50e90c43be3">+44/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by sandeepsuryaprasad** [comment]
@AutomatedTester could you review this PR please. Thanks!

**Comment by sandeepsuryaprasad** [comment]
After the changes that I have made in this PR, I ran the build locally.  

`bazel build //py:selenium-wheel`

Screenshot 2024-11-15 at 9 09 08 AM

```
~$ pip3 install selenium-4.27.0.dev202410311942-py3-none-any.whl
Processing ./selenium-4.27.0.dev202410311942-py3-none-any.whl
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202410311942) (2.2.3)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202410311942) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202410311942) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202410311942) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202410311942) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202410311942) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202410311942) (24.2.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202410311942) (2.4.0)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202410311942) (3.10)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202410311942) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202410311942) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium==4.27.0.dev202410311942) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202410311942) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.27.0.dev202410311942) (0.14.0)
Installing collected packages: selenium
Successfully installed selenium-4.27.0.dev202410311942
```

Screenshot 2024-11-15 at 9 11 12 AM


@VietND96 @AutomatedTester can this be uploaded to test Pypi for further validation..

**Comment by VietND96** [comment]
Sure, I will trigger the CI to validate it once and get back to you

**Comment by sandeepsuryaprasad** [comment]
@VietND96 I have installed the test version from test Pypi. The installation is successful. I also verified the tar file by downloading it, but I don't see  the changes that I have made in `pyproject.toml`.. i.e all the metadata information is still in `setup.py`.. 

[tar file download](https://test.pypi.org/project/selenium/#files)

```
~$ pip3 install -i https://test.pypi.org/simple/ selenium
Looking in indexes: https://test.pypi.org/simple/
Collecting selenium
  Downloading https://test-files.pythonhosted.org/packages/a6/b3/ea3ef67230bc1c29cdfa38702f3e6c3d57a15f369562a8c65c7da6b276b4/selenium-4.27.0.202410311942-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium) (3.10)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Downloading https://test-files.pythonhosted.org/packages/a6/b3/ea3ef67230bc1c29cdfa38702f3e6c3d57a15f369562a8c65c7da6b276b4/selenium-4.27.0.202410311942-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 4.2 MB/s eta 0:00:00
Installing collected packages: selenium
Successfully installed selenium-4.27.0.202410311942
```

**Comment by sandeepsuryaprasad** [comment]
@VietND96 looks like the tar file is uploaded on Nov-11th. Not the latest one after I ran this build (this build was run on Nov-15th).  I think this is the reason why my latest `pyproject.toml` is not getting reflected.. Can you please check on this one please..

**Review by VietND96 — APPROVED** [review]
Daily, the Nightly is built from the trunk, so your changes can be found in a specific build.
Here is the CI validation I just triggered
Nightly build & upload: https://github.com/SeleniumHQ/selenium/actions/runs/11887595671
TestPyPi: https://test.pypi.org/project/selenium/4.27.0.dev202411180720/
Tests run: https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/11887729210
Overall is LGTM!

**Comment by VietND96** [comment]
@sandeepsuryaprasad, can you check, CI this PR is failing

**Comment by sandeepsuryaprasad** [comment]
> @sandeepsuryaprasad, can you check, CI this PR is failing

@VietND96 sure, I will look into this and confirm.

**Comment by sandeepsuryaprasad** [comment]
@VietND96 I have fixed the defect.. the table `[tool.setuptools.packages.find]` was duplicated in `pyproject.toml`. Now I have removed the duplicate occurrence. Request you to re-trigger CI.

**Comment by sandeepsuryaprasad** [comment]
Installed selenium from test PyPI

```
~$ pip3 install pip install -i https://test.pypi.org/simple/ selenium==4.27.0.dev202411180720
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (24.2)
Requirement already satisfied: install in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.0.1)
Collecting selenium==4.27.0.dev202411180720
  Using cached https://test-files.pythonhosted.org/packages/57/29/8d35116db32fd561d87a3897f8fde13680a47150109eb5cf217f2c877274/selenium-4.27.0.dev202411180720-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202411180720) (2.2.3)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411180720) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411180720) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411180720) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411180720) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411180720) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411180720) (24.2.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411180720) (2.4.0)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411180720) (3.10)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411180720) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411180720) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium==4.27.0.dev202411180720) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202411180720) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.27.0.dev202411180720) (0.14.0)
Using cached https://test-files.pythonhosted.org/packages/57/29/8d35116db32fd561d87a3897f8fde13680a47150109eb5cf217f2c877274/selenium-4.27.0.dev202411180720-py3-none-any.whl (9.7 MB)
Installing collected packages: selenium
Successfully installed selenium-4.27.0.dev202411180720
```
Screenshot 2024-11-18 at 8 02 27 PM

**Comment by sandeepsuryaprasad** [comment]
@VietND96 I have verified installing selenium from test PyPI. Looks good.. Also, I have fixed the defect. Now the CI is passing.

**Pull request merged**
