### PR TITLE
[rb] Update selenium manager types

### PR DESCRIPTION
**Pull request by aguspe**
### Description
This PR adds the correct type after the Selenium manager class has been updated for ruby

### Motivation and Context
It's important as described here #13989 that we utilize the new options available for us in the Selenium manager implementation and that we update the respective types

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Updated the Selenium manager commands in the Ruby client to use mixed output format instead of JSON.
- Changed the debug flag to use `--log-level debug` for better logging control.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>selenium_manager.rb</strong><dd><code>Update Selenium manager command options for Ruby client</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
rb/lib/selenium/webdriver/common/selenium_manager.rb

<li>Changed command output format from JSON to mixed.<br> <li> Updated debug flag to log-level debug.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14189/files#diff-09418c53c432e9827177f67e7fe211062c38ce1b044f88bb1f816f2ed79a41ca">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by aguspe** [comment]
@titusfortner I saw the update you did on the selenium manager class, so I changed my PR to add the right types and update the correspondent RBS file for the selenium manager class

**Comment by aguspe** [comment]
Hello @p0deje I hope you are having a great evening, whenever you have time could you review this PR? thank you for all your help

**Comment by p0deje** [comment]
> Hello @p0deje I hope you are having a great evening, whenever you have time could you review this PR? thank you for all your help

Hi, sorry for delay. Can you please take a look at the CI failures?

**Comment by aguspe** [comment]
> > Hello @p0deje I hope you are having a great evening, whenever you have time could you review this PR? thank you for all your help
> 
> Hi, sorry for delay. Can you please take a look at the CI failures?

Thank you so for taking the time, and no problem I know you are busy.

Now I remove the last updates on arguments so this PR just updates the types after the changes done to the selenium manager class

**Comment by p0deje** [comment]
@aguspe Can you please take a look at linter failures? https://github.com/SeleniumHQ/selenium/actions/runs/9828809475/job/27218278086?pr=14189

**Comment by aguspe** [comment]
@p0deje the linter issues are fixed now and only the RBS file is left

**Comment by p0deje** [comment]
Thank you!

**Pull request merged**
