### PR TITLE
[py]: #11093 - The PrintOptions.to_dict() method should return a shal…

### PR DESCRIPTION
**Pull request by tvataire**
…low copy of the internal data of the class.

### Description
The PrintOptions.to_dict() method should return a shallow copy of the dictionary where are stored internal data of the class, instead of returns the dictionary itself.
This prevents the session id from being stored inside the PrintOptions instance when the Webdriver.print_page() method is called.

### Motivation and Context
If the session id is stored inside the PrintOptions instance, a selenium.common.exceptions.InvalidSessionIdException is raised when the PrintOptions instance is reused in a subsequent session.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

I tried to run unit tests on a 4 core cpu / 8 Go RAM machine with the command `bazel test //py:unit` but nothing happens. 
I launched the tests several hours ago and a 'bazel-5.3.0' process is running, but nothing is displayed on the standard output.
Is this the expected behavior ?
Is it normal that unit tests take so much time ?

### CODE REVIEW

**Review by titusfortner — APPROVED** [review]

**Comment by symonk** [comment]
while this does fix the problem, I'm not 100% sure on the full fix, should `_print_options` be storing a `session_id` internally as a result of executing initially here?

Is the better fix to make a copy of params in webdriver `.execute(...)` if it exists; else `{}` ? might stop us mutating random session state internally to multiple objects? (would need to test), as is this fix will prevent print options from having a bogus session id stored, my concern it - what other objects are suffering a similar fate, handling it in the remote webdriver execute I think makes it a non issue for pretty much everything (for now)

**Comment by titusfortner** [comment]
@symonk I say we merge this to fix the specific problem now (it's a valid fix), then figure out a more comprehensive solution for the project. See discussion in #11093

**Comment by symonk** [comment]
Fine by me, just missing cla here

**Comment by titusfortner** [comment]
@tvataire looks like you committed with two separate emails that both need to be registered with CLA. I'm not sure if putting them on the same github account would also work.

**Comment by tvataire** [comment]
Abandoned in favor of #11121.

**Pull request closed without merging**
