### PR TITLE
Nodes List JSON API

### PR DESCRIPTION
**Pull request by j1n6**
This PR returns a list of nodes information under http endpoint '/grid/api/nodes'

An example of the JSON output:

```
GET: http://localhost:4444/grid/api/nodes
```

Results:

```
{
    "nodes": {
        "http://10.37.129.2:5555": {
            "id": "http://10.37.129.2:5555",
            "capabilities": [{
                "platform": "MAC",
                "seleniumProtocol": "WebDriver",
                "browserName": "chrome"
            }],
            "configuration": {
                "port": 5555,
                "servlets": [],
                "host": "10.37.129.2",
                "cleanUpCycle": 5000,
                "browserTimeout": 0,
                "hubHost": "localhost",
                "registerCycle": 5000,
                "hub": "http://localhost:4444/grid/register",
                "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
                "newSessionWaitTimeout": -1,
                "url": "http://10.37.129.2:5555",
                "remoteHost": "http://10.37.129.2:5555",
                "prioritizer": null,
                "register": true,
                "throwOnCapabilityNotPresent": true,
                "nodePolling": 5000,
                "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                "browser": "browserName=chrome,",
                "maxSession": 5,
                "role": "node",
                "hubPort": 4444,
                "timeout": 300000
            }
        }
    }
}
```

Anyone can give me a guide how to get `./go test` running properly on Mac OSX would be really helpful. I can then start writing some tests against it. 

Done CLA.

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/191)

### CODE REVIEW

**Comment by andreastt** [comment]
@nirvdrum, this PR was fixed up. Can you have a second pass at changed code if you like what you see?

**Comment by barancev** [comment]
Up!

**Comment by nirvdrum** [comment]
I'll take a look.

**Comment by lukeis** [comment]
@activars i know this PR is a bit old now, but mind rebasing it / fixing any of the conflicts?

**Comment by activars** [comment]
would you consider a merge after rebasing?

**Comment by lukeis** [comment]
I would actually like to see something like this go more in line with a REST api like what was proposed here:
https://github.com/SeleniumHQ/selenium/pull/265

If dima doesn't have time to update his PR, maybe incorporating what you want into it?

**Comment by activars** [comment]
This was the API needed when I work internal project. 

I'm happy to rebase and validate it again if you think this is useful.

**Comment by diemol** [comment]
@j1n6 apologies, this was not properly reviewed and merged on time. The codebase where this PR was based does not exist anymore,  and sadly this contribution won't be merged.

The good news are that the new Grid provides a `/status` resource where this information is already provided.

**Pull request closed without merging**
