### PR TITLE
Fix failing Grid related tests.

### PR DESCRIPTION
**Pull request by krmahadevan**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by krmahadevan** [comment]
@barancev - This is the other PR which you had asked for as part of #5078 , to fix the failing grid related tests. Please help take a look

**Comment by barancev** [comment]
Unfortunately this commit does not fix the issue too, it's a false positive again. The test itself is incorrect. It does not ckeck before cleanup if there is something in the registry. And apparently there is nothing! The created test session is not in the registry. It seems that grid behavior elolved since this test was created, and the test does not match current behaviour. It should be either modernized or deleted.

**Comment by krmahadevan** [comment]
@barancev - Please help take a look.

**Comment by barancev** [comment]
Merged as 2c8a1a5d59904d23085b1f04b8309ca033251740, thank you for the contribution!

**Pull request closed without merging**
