### PR TITLE
deprecating AuthenticateUsing because it is no longer supported by an…

### PR DESCRIPTION
**Pull request by llaskin**
…y browser vendors.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This was only in 1 browser and was a "beta" feature. It is _currently_ not in W3C but could be in Level 2

**Comment by llaskin** [comment]
Per Simon we are going to deprecate this feature.

**Comment by jleyba** [comment]
Can you add `@deprecated` javadoc tags explaining that the APIs will be removed and there is intentionally no replacement?

**Comment by shs96c** [comment]
`@Beta` gives us more freedom than `@Deprecated`. The guidelines we offer are that beta features can and will be deleted without notice. Deprecated features get at least one release before being deleted.

**Comment by llaskin** [comment]
@shs96c so should I swap it to @deprecated?  I can't believe I didn't see Jason's request, and happy to change this...(hey look a ghost commit)

**Pull request closed without merging**
