### PR TITLE
Fix typo in setup.py

### LINKED ISSUE #13486: [🐛 Bug]: Typo in setup.py
### What happened?

Dependency not installed because of typo introduced in https://github.com/SeleniumHQ/selenium/commit/f83765d173e057e85062129f0b0c805f2b4fce90, "typing_extension" vs "typing_extension**s**"

### How can we reproduce the issue?

```shell
Try to install the latest selenium with pip install on system that doesn't have typing_extensions installed and run `from selenium import webdriver`
```

### Relevant log output

```shell
E   ModuleNotFoundError: No module named 'typing_extensions'
```

### Operating System

Ubuntu 20.04

### Selenium version

4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.224

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by EwaMarek**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Fixes #13486

### Motivation and Context
To fix #13486, so that the latest selenium version installs all required dependencies.

### Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Is there a way you can force push and make the git user match the GitHub user so the CLA accepts the contribution?

**Review by diemol — APPROVED** [review]
Thank you, @EwaMarek!

**Comment by diemol** [comment]
I'll wait for the CI to finish and then I'll merge.

**Comment by EwaMarek** [comment]
> Thank you, @EwaMarek!

No problem!

**Comment by EwaMarek** [comment]
> I'll wait for the CI to finish and then I'll merge.

Thank you!

**Pull request merged**
