### PR TITLE
[java] [dotnet] Add move to location method to Actions

### PR DESCRIPTION
**Pull request by pujagani**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add move to location method to Actions class

### Motivation and Context

Explained in #10724. The change implement proposal 2.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
force pushing a rebased update; the new Java formatting updates made it easier to do it this way. Evaluating now.

**Comment by titusfortner** [comment]
@diemol which of these does it make more sense to support? It feels like we should be picking the "right" one and have people use it rather than supporting two options? `Point` isn't being used anywhere else, but everything else is offsets not something that represents coordinates on the viewport, so it might be more correct...

```java
    Action moveAndClick = getBuilder(driver).moveToLocation(70, 60).click().build();
```
and
```java
    Action moveAndClick = getBuilder(driver).moveToLocation(new Point(70, 60)).click().build();
```

Also, my default for multiple constructors or methods that do the same thing with different parameters is that one should call the other rather than be a re-implementation. So one way or the other I think this PR needs to be tweaked slightly.

.NET looks good; don't have .NET environment working on new laptop yet, though.

**Comment by titusfortner** [comment]
Hmm .NET test is failing in CI... Passing in my fresh .NET dev environment; probably a timing issue; trying the equivalent test from Ruby.

**Comment by diemol** [comment]
This one might be "easier"?

```java
Action moveAndClick = getBuilder(driver).moveToLocation(70, 60).click().build();
```

**Comment by titusfortner** [comment]
Java looks good, but .NET + Windows + Firefox isn't happy and I'll have to load up a VM to troubleshoot it.

**Pull request merged**
