### PR TITLE
[rust] Build selenium-manager for win32 (compatible when executed in win64)

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
This PR updated the workflow to build Selenium Manager in GH Actions, for building `selenium-manager` for Windows x32. An example execution can be see [here](https://github.com/SeleniumHQ/selenium/actions/runs/4446568310). I tested the resulting binary (e.g. [selenium-manager_windows-x32](https://github.com/SeleniumHQ/selenium/suites/11703832229/artifacts/608889643)) both in Windows x32 and x64. In both cases, it works as expected.

### Motivation and Context
This PR is part of #11599. Since the resulting binary is compatible with win32 and win64, it can be used to replace the selenium-manager binary for windows (in the folder `common/manager/windows`).

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
The Windows 32 binary appears to work on my 64bit Windows machine. Is there functionality that does not work? I feel like this was discussed but I don't remember what was said.

**Comment by bonigarcia** [comment]
The selenium-manager x32 binary executed in an x64 machine has different issues. See an example:

```
C:\Users\boni\Downloads>selenium-manager.exe --browser firefox --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\boni\.cache\selenium
DEBUG   Using shell command to find out firefox version
DEBUG   Running command: "wmic datafile where name='%PROGRAMFILES:\\=\\\\%\\\\Mozilla Firefox\\\\firefox.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\n\r"
DEBUG   Running command: "wmic datafile where name='%PROGRAMFILES(X86):\\=\\\\%\\\\Mozilla Firefox\\\\firefox.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\n\r"
DEBUG   The version of firefox cannot be detected. Trying with latest driver version
DEBUG   Required driver: geckodriver 0.32.2
DEBUG   Running command: "geckodriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-win32.zip
DEBUG   File extracted to C:\Users\boni\.cache\selenium\geckodriver\win32\0.32.2\geckodriver.exe (3419040 bytes)
INFO    C:\Users\boni\.cache\selenium\geckodriver\win32\0.32.2\geckodriver.exe
```

As you can see, the commands to discover the browser version (Firefox, in this case) are not working. In the case of Chrome it works because of the registry command. But the WMIC command is more reliable (since we ask directly to the browser binary instead of the info in the registry). In addition, WMIC command is required when the browser path is passed from options.

The second problem has to do with architecture discover. As you can see in the example before, the binary `geckodriver-v0.32.2-win32.zip` is downloaded, but the target should be x64 since that is the host running selenium-manager.

Of course, it would be ideal to have a selenium-manager x32 binary that also works for x64. I have been working on that since Saturday. I don't have a complete solution, but I think I am close. I'll let you know my results.

**Comment by titusfortner** [comment]
If we need another binary, we need it, I just wanted to make sure. Thanks for explaining it.

**Comment by bonigarcia** [comment]
I managed to make the resulting selenium-manager binary compatible with Windows 32 and 64. See for example: [selenium-manager_windows-x32](https://github.com/SeleniumHQ/selenium/suites/11703832229/artifacts/608889643)

Some output examples in **Windows 64**:

_Chrome_
```
C:\Users\boni\Downloads>selenium-manager --browser chrome --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\boni\.cache\selenium
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=111.0.5563.65\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 111.0.5563.65
DEBUG   Detected browser: chrome 111
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_111
DEBUG   Required driver: chromedriver 111.0.5563.64
DEBUG   Running command: "chromedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_win32.zip
DEBUG   File extracted to C:\Users\boni\.cache\selenium\chromedriver\win32\111.0.5563.64\chromedriver.exe (12765184 bytes)
INFO    C:\Users\boni\.cache\selenium\chromedriver\win32\111.0.5563.64\chromedriver.exe
```

_Firefox_
```
C:\Users\boni\Downloads>selenium-manager --browser firefox --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\boni\.cache\selenium
DEBUG   Using shell command to find out firefox version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Mozilla Firefox\\\\firefox.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=110.0.0.8437\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of firefox is 110.0.0.8437
DEBUG   Detected browser: firefox 110
DEBUG   Required driver: geckodriver 0.32.2
DEBUG   Running command: "geckodriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-win64.zip
DEBUG   File extracted to C:\Users\boni\.cache\selenium\geckodriver\win64\0.32.2\geckodriver.exe (3872672 bytes)
INFO    C:\Users\boni\.cache\selenium\geckodriver\win64\0.32.2\geckodriver.exe
```

_Edge_
```
C:\Users\boni\Downloads>selenium-manager --browser edge --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\boni\.cache\selenium
DEBUG   Using shell command to find out edge version
DEBUG   Running command: "set PFILES=%PROGRAMFILES(X86)%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Microsoft\\\\Edge\\\\Application\\\\msedge.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=111.0.1661.44\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of edge is 111.0.1661.44
DEBUG   Detected browser: edge 111
DEBUG   Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_111_WINDOWS
DEBUG   Required driver: msedgedriver 111.0.1661.44
DEBUG   Running command: "msedgedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://msedgedriver.azureedge.net/111.0.1661.44/edgedriver_win64.zip
DEBUG   File extracted to C:\Users\boni\.cache\selenium\msedgedriver\win64\111.0.1661.44\msedgedriver.exe (17107928 bytes)
INFO    C:\Users\boni\.cache\selenium\msedgedriver\win64\111.0.1661.44\msedgedriver.exe
```

... and in **Windows 32**:

_Chrome_
```
C:\Users\user\Downloads>selenium-manager --browser chrome --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\user\.cache\selenium
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=111.0.5563.65\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 111.0.5563.65
DEBUG   Detected browser: chrome 111
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_111
DEBUG   Required driver: chromedriver 111.0.5563.64
DEBUG   Running command: "chromedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_win32.zip
DEBUG   File extracted to C:\Users\user\.cache\selenium\chromedriver\win32\111.0.5563.64\chromedriver.exe (12765184 bytes)
INFO    C:\Users\user\.cache\selenium\chromedriver\win32\111.0.5563.64\chromedriver.exe
```

_Firefox_
```
C:\Users\user\Downloads>selenium-manager --browser firefox --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\user\.cache\selenium
DEBUG   Using shell command to find out firefox version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Mozilla Firefox\\\\firefox.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=111.0.0.8468\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of firefox is 111.0.0.8468
DEBUG   Detected browser: firefox 111
DEBUG   Required driver: geckodriver 0.32.2
DEBUG   Running command: "geckodriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-win32.zip
DEBUG   File extracted to C:\Users\user\.cache\selenium\geckodriver\win32\0.32.2\geckodriver.exe (3419040 bytes)
INFO    C:\Users\user\.cache\selenium\geckodriver\win32\0.32.2\geckodriver.exe
```

_Edge_
```
C:\Users\user\Downloads>selenium-manager --browser edge --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\user\.cache\selenium
DEBUG   Using shell command to find out edge version
DEBUG   Running command: "set PFILES=%PROGRAMFILES(X86)%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Microsoft\\\\Edge\\\\Application\\\\msedge.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\n\r"
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Microsoft\\\\Edge\\\\Application\\\\msedge.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=106.0.1370.52\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of edge is 106.0.1370.52
DEBUG   Detected browser: edge 106
DEBUG   Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_106_WINDOWS
DEBUG   Required driver: msedgedriver 106.0.1370.86
DEBUG   Running command: "msedgedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://msedgedriver.azureedge.net/106.0.1370.86/edgedriver_win32.zip
DEBUG   File extracted to C:\Users\user\.cache\selenium\msedgedriver\win32\106.0.1370.86\msedgedriver.exe (12613552 bytes)
INFO    C:\Users\user\.cache\selenium\msedgedriver\win32\106.0.1370.86\msedgedriver.exe
```

I updated the PR title and description accordingly.

**Comment by titusfortner** [comment]
This is great!

So, going off of this list: https://github.com/SeleniumHQ/selenium/issues/11357

`selenium-manager_windows-x32` works for `win32` & `win64`
`selenium-manager_macos-x64` works for `mac64` & `mac-arm64` 
`selenium-manager_linux-x64` works for `linux64`

That's ~95% of use cases based on [geckodriver numbers](https://github.com/SeleniumHQ/selenium/issues/11599#issuecomment-1416052356)

The only weird bit here... the new windows 32 bit, on 64 bit machines it uses the 64 bit msedgedriver & geckodriver, but the 32 bit chromedriver? Or is it using 32 bit versions for everything?

Finally that means for https://github.com/SeleniumHQ/selenium/issues/11599 all we need to do right now is to check for arm64 windows/linux and linux32 to throw an explicit error that the architecture isn't supported...

**Comment by bonigarcia** [comment]
> The only weird bit here... the new windows 32 bit, on 64 bit machines it uses the 64 bit msedgedriver & geckodriver, but the 32 bit chromedriver? Or is it using 32 bit versions for everything?

Yes, that is because chromedriver for Windows is only released as a `x32` binary (see [chromedriver page](https://chromedriver.storage.googleapis.com/index.html?path=110.0.5481.77/)) which works both in `x32` and `x64` (just like the new `selenium-manager` binary for Windows).

**Comment by diemol** [comment]
I actually meant to post [this comment](https://github.com/SeleniumHQ/selenium/issues/11599#issuecomment-1489020795) here.

**Comment by titusfortner** [comment]
Ah, then I meant to post [this comment](https://github.com/SeleniumHQ/selenium/issues/11599#issuecomment-1492386064) here as well.

**Review by titusfortner — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you, @bonigarcia!

**Pull request merged**
