### PR TITLE
Add withExecutor to FluentWait to support concurrent drivers in custom thread pools

### PR DESCRIPTION
**Pull request by bjuric**
### Description
`FluentWait` blocked and behaved unpredictably when called concurrently from multiple web driver threads executing in a custom thread pool. This commit adds the ability to pass the Executor service that manages the thread pool to fluent wait.

#### Sample usage
```java 
  // pass custom executor to fluent wait
  new FluentWait(driver)
      .withTimeout(Duration.ofSeconds(10))
      .withExecutor(myCustomExecutor)
      ..
```

### Motivation and Context
Many tools and frameworks built on Selenium offer options for running multiple web driver instances in parallel threads. Fluent wait can block and behave unpredictabily  under some conditions where concurrent calls are made by threads in custom `Executor`s. In such instances, it becomes necessary to use the custom Executor with `FluentWait`'s underlying `CompletableFuture`.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bjuric** [comment]
It's worth noting that launching Selenium with the following Java system property forces the CompletableFuture in FluentWait to run on the calling thread.
```
java.util.concurrent.ForkJoinPool.common.parallelism=0
```
There's no need to explicitly set the executor if you specify this property. This solves the concurrency issue with thread contention but also affects all instances where CompletableFutures are used throughout Selenium in that they would no longer run on separate threads. In some cases however, this might be a viable alternative to the withExecutor approach introduced in this PR. I guess it's good to have options.

**Comment by thegoldgoat** [comment]
Hello, not an expert here

This is related to #8727 isn't it?

**Comment by bjuric** [comment]
@thegoldgoat I think that one has the same underlying issue. I believe it to be a systemic issue in that CompleteableFutures are used throughout Selenium 4, and not just in FluentWait.

**Comment by thegoldgoat** [comment]
Thanks for the response!

Again, not an expert of this codebase

Is this PR ready to be tested by any chance?

Should I change something in my code?

Thanks again!

**Comment by bjuric** [comment]
@thegoldgoat try launching your app with the jvm option in my earlier comment above and use a custom thread pool. See also #8525

**Comment by thegoldgoat** [comment]
Great! Thanks a lot I'll let you know if that works

**Comment by thegoldgoat** [comment]
Hi, sorry for the late response.

Using that options everything works, thanks a lot!!

I hope the devs would investigate in this bug and consider your solution

**Comment by chrisgleissner** [comment]
What is blocking this PR from being merged?

**Comment by barancev** [comment]
We discuss the current implementation. And tend to revert back to legacy (blocking) implementation.

**Comment by barancev** [comment]
Sorry to say this, but we decided to return back to the legacy (blocking) implementation after clients' complains. It appears that many people use suboptimal approach to manage WebDriver instances using ThreadLocal variables. And running conditions in a separate thread makes them lose their driver. So we decided to revert this change in favour of backward compatibility.

**Pull request closed without merging**
