### PR TITLE
[py] WebElement parameter supported in some of expected_condition methods

### PR DESCRIPTION
**Pull request by Qnner**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
WebElement parameter supported in some of expected_conditions methods

### Motivation and Context
when you located an element already, you can just use it now;  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
This is why I don't like expected conditions classes, you always end up needing more of them than you want to maintain.

fwiw, if we are going to have EC classes, it does make sense to support both elements and locators.

At the same time, everyone should be using lambdas, so I'd be fine deprecating these entirely, too. :)

**Comment by titusfortner** [comment]
It was decided at TLC meeting to keep expected conditions class in Python, so I think we should also support Elements and not just locators.

**Review by titusfortner — CHANGES_REQUESTED** [review]
This needs tests in order to be approved

**Comment by diemol** [comment]
@Qnner can you please add tests to this pull requests in order to be merged?

**Comment by Qnner** [comment]
> @Qnner can you please add tests to this pull requests in order to be merged?

this is my first commit for a opensource，I need some time to complete this for test ^_^

**Pull request closed without merging**
