### PR TITLE
Add docker device mapping configuration

### PR DESCRIPTION
**Pull request by gifflet**
### Description
Configure docker containers device mapping

### Motivation and Context
Sometimes is needed to map a device file to a docker
container to make possible some tasks like virtualize
a VM or something else. Because of this, I believe it
is desirable to have a way to configure which device
files should be available in containers.

In this commit, we can define which device files should
be mapped in containers through the standard selenium grid
configuration file.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gifflet** [comment]
The documentation was updated in SeleniumHQ/seleniumhq.github.io#1011

**Review by diemol — COMMENTED** [review]
Code looks fine, thanks for the PR. I'd just like to understand better what the use case for this is, how would you be using this feature?

**Comment by gifflet** [comment]
Thank you @diemol for reviewing this PR. 

Answering your question, I implemented this change because the containers launched by selenium grid perform virtualization of virtual machines, that is, a virtual machine is started offering the native web browser of the platform at the same time that the selenium server runs in the virtual machine in standalone mode . So I need the containers to have access to the /dev/kvm device, available on the host, for the virtualization tool to work as expected.

**Comment by diemol** [comment]
Can volumes be used instead of devices?

**Comment by diemol** [comment]
Can volumes be used instead of devices?

**Comment by gifflet** [comment]
Unfortunately not. When we share a device through a volume, the container does not have the proper read and write permissions to the shared device. 

image

**Comment by diemol** [comment]
Got it, thanks.

Can you please have a look at the issues reported by Sonar?

**Comment by gifflet** [comment]
Sure, I will work on it.

**Comment by gifflet** [comment]
@diemol, I could not reproduce the issue reported by Sonar but I think that the last commit solves it.

**Comment by diemol** [comment]
Can you please rebase first? Or let us do it by enabling the PR?

**Comment by diemol** [comment]
Maybe I missed it, but I do not see the other Sonar issues being addressed.

**Comment by gifflet** [comment]
The other issues reported by Sonar was fixed in the last commit. The rebase was done as suggested.

**Comment by diemol** [comment]
I'd love to merge this but if I can't update this branch on my own is just going to take longer. Can you please update your fork?

**Comment by gifflet** [comment]
@diemol, I just enabled maintainer editing, so I believe you will be able to update this branch.

**Comment by diemol** [comment]
Thanks

**Review by diemol — COMMENTED** [review]
Thank you, @dilhelh!

**Pull request merged**
