### PR TITLE
CDP Storage domain

### PR DESCRIPTION
**Pull request by adiohana**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by jimevans** [comment]
I wonder if we really want to be supporting domains marked as `experimental` in the protocol definition. I'd be worried these may be likely to change on a whim, since the protocol is not subject to any published standard, and doing so might tie us to specific versions of Chrome/other Chromium-based browsers instead of being as version-agnostic as possible. I'm not a Java maintainer, so I don't really have a full say in this decision, but @shs96c really ought to weigh in.

**Comment by shs96c** [comment]
What I _really_ want to do is autogenerate the CDP bindings from the JSON description. The way to do that would be to generate a Command or Function per method, and then group them into protocol versions. That way, as methods move from "experimental" to production, we don't have to worry about users needing to modify their code.

**Comment by AutomatedTester** [comment]
I agree with @jimevans here. We dont want to do anything experimental

**Comment by AutomatedTester** [comment]
Thank you for your effort here. 

We are now auto generating these APIs moving forward so won't need this PR.

Thank you again!

**Pull request closed without merging**
