### PR TITLE
[py] Change formatted strings to f-strings

### LINKED ISSUE #11084: [🚀 Feature]: Python upgrade to f-strings [good first issue]
### Feature and motivation

The python code base shows it's age in a few places.  Opening this as a great first issue for new contributors!

The following are violations, take as many as you would like :+1:, data is `file:lineno:column`:

```console
selenium/webdriver/firefox/extension_connection.py:53:15
selenium/webdriver/firefox/extension_connection.py:69:21
selenium/webdriver/firefox/firefox_binary.py:113:20
selenium/webdriver/firefox/firefox_profile.py:198:28
selenium/webdriver/firefox/firefox_profile.py:236:25
selenium/webdriver/firefox/firefox_profile.py:303:26
selenium/webdriver/firefox/firefox_profile.py:327:30
selenium/webdriver/remote/webdriver.py:291:15
selenium/webdriver/remote/webdriver.py:852:20
selenium/webdriver/remote/webdriver.py:855:20
selenium/webdriver/remote/webdriver.py:858:20
selenium/webdriver/remote/webdriver.py:881:20
selenium/webdriver/remote/webdriver.py:884:20
selenium/webdriver/remote/webdriver.py:887:20
selenium/webdriver/remote/webelement.py:77:15
selenium/webdriver/remote/webelement.py:180:12
selenium/webdriver/remote/webelement.py:264:42
selenium/webdriver/remote/webelement.py:425:20
selenium/webdriver/remote/webelement.py:428:20
selenium/webdriver/remote/webelement.py:431:20
selenium/webdriver/remote/remote_connection.py:113:37
selenium/webdriver/remote/remote_connection.py:288:41
selenium/webdriver/remote/shadowroot.py:39:15
selenium/webdriver/remote/shadowroot.py:46:20
selenium/webdriver/remote/shadowroot.py:49:20
selenium/webdriver/remote/shadowroot.py:52:20
selenium/webdriver/remote/shadowroot.py:59:20
selenium/webdriver/remote/shadowroot.py:62:20
selenium/webdriver/remote/shadowroot.py:65:20
selenium/webdriver/remote/errorhandler.py:236:35
selenium/webdriver/common/utils.py:96:15
selenium/webdriver/common/utils.py:97:11
selenium/webdriver/common/utils.py:130:34
selenium/webdriver/common/action_chains.py:364:28
selenium/webdriver/common/bidi/cdp.py:153:15
selenium/webdriver/common/bidi/cdp.py:264:27
selenium/webdriver/common/bidi/cdp.py:443:39
selenium/webdriver/common/actions/pointer_input.py:33:43
selenium/webdriver/support/select.py:38:16
selenium/webdriver/support/select.py:76:14
selenium/webdriver/support/select.py:85:41
selenium/webdriver/support/select.py:101:37
selenium/webdriver/support/select.py:114:16
selenium/webdriver/support/select.py:128:24
selenium/webdriver/support/select.py:138:41
selenium/webdriver/support/select.py:163:14
selenium/webdriver/support/select.py:169:41
selenium/webdriver/support/select.py:186:37
selenium/webdriver/support/select.py:200:16
selenium/webdriver/support/select.py:206:41
selenium/webdriver/support/select.py:223:30
selenium/webdriver/support/select.py:231:19
selenium/webdriver/support/select.py:233:15
selenium/webdriver/support/wait.py:69:15
selenium/webdriver/support/color.py:153:15
selenium/webdriver/support/color.py:157:15
selenium/webdriver/support/color.py:178:15
```

### Usage example

in the example of `select.py:163`:

old:

```python
css = "option[value = %s]" % self._escape_string(value)
```

new:

```python
css = f"option[value = {self._escape_string(value)}]"
```

### PR DESCRIPTION
**Pull request by kianelbo**
### Description
Replace legacy formatted strings with f-strings

Closes #11084 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [n/a] My change requires a change to the documentation.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by symonk** [comment]
Thanks @kianelbo just going to eat then will review, much appreciated

**Comment by symonk** [comment]
minor conflict from some typing I recently added in `wait.py`, apart from that LGTM :+1:

**Comment by kianelbo** [comment]
@symonk any plans to merge this?

**Review by diemol — APPROVED** [review]
Thank you, @kianelbo!

**Pull request merged**
