### PR TITLE
Closes #489 avoid using getHostName() function because it can be very sl...

### LINKED ISSUE #489: Selenium tests are very-very slow in some networks
I am working in hotel on Bali, via public WiFi.
My Selenium tests are incredibly slow (see attached image).
image

The problem is in method `org.openqa.selenium.WebDriverException#getSystemInformation`:

``` java
    try{
      host = InetAddress.getLocalHost().getHostName();
    } catch (UnknownHostException throw_away) {}
```

Method `getHostName()` uses system call to get name of current computer, which can be **very-very long**. 
I believe host name is not really needed and can be skipped. Just log IP.

### PR DESCRIPTION
**Pull request by asolntsev**
...ow on some networks

### CODE REVIEW

**Comment by lukeis** [comment]
hmm, sometimes host name can be quite valuable (on some networks :) ). Can we hide disabling the host name resolution behind a flag? (default the old behavior).

**Comment by sevaseva** [comment]
I was curious in what circumstances is getHostName() slow (and wondering if such severe as well as rare  environment issue is something that selenium should work around at all [I bet a few other things are also slow in that network]), read the issue and it turns out -  it's in a hotel on Bali :) hm.

I wish I knew offhand what are the most common causes for that call to be slow. Without having a strong and educated opinion I'd give such change my humble -1

**Comment by vinogradoff** [comment]
From my experience, resolving the host names could be that bottleneck even on connections that are indeed fast. 

Slow DNS-Servers are very probably the cause, @sevaseva  you could probably simulate this setting a remote free DNS Server for you network :) Try one from Kenia in the list: http://public-dns.tk/nameserver/ke.html :)

**Comment by sevaseva** [comment]
Thanks @vinogradoff , that makes sense, slow dns responses might be the cause.

I'm traveling and won't have a chance to try stuff in the next 1.5 months or so, but I have another idea:

If the slow getHostName() situation can be detected at runtime (without profiling/stats but with a simple timer), I wonder if logging a warning "Slow DNS setup on the test machine greatly slows down your tests, fix to get performance improvements" would sufficiently mitigate the issue. If combined with a flag (java system property?) proposed by @lukeis, the warning could mention the flag.

**Comment by asolntsev** [comment]
@sevaseva @lukeis Yes, we can invent some tricks to retrieve host name in background thread. There are some code samples in the internet. But I am still sure it's not needed. Yagni! You always know on which computer you are running your tests.

Even if you have hassle with multiple nodes, knowing host name doesn't always resolve problem. For example, you could have multiple nodes on the same host/IP. So, if you really need to log useful information - we would need to log node ID/name/whatever else. 

But IP/host just does not solve any problems.

**Comment by sevaseva** [comment]
@asolntsev, I didn't mention or mean using background threads for anything. I'll clarify in case you thought I did. By '...with a simple timer' I meant simply recording system time before calling getHostName() and then again recording it after getHostName() returns. If getHostName() took longer than some (configurable, with a reasonable default) time, log the warning (possibly log it only once per a) JVM lifetime b) browser session c) some other session d) 10/100/1000/10000 slow getHostName() calls e) something else).

'You always know on which computer you are running your tests' - is true in many cases when *you* run your tests. When something other than you runs your (or other people's) tests - then you may not know which machine that happened on (think a system that runs browsers and possibly tests in a private or public cloud).

In some cases information other than hostname is useful/sufficient for things, in others hostname is essential. Plus, Selenium users used to having hostnames in the logs; I think removing it would cause a minor revolt.

I'll close this PR for now. It doesn't look like it would be merged as is; it can be easily reopened with new content.

We can keep using this for tracking the 'slow getHostName() slows down performance' issue or you can raise a new issue if you like (I would be in favor of the latter).

**Comment by barancev** [comment]
I want to reopen this issue, because I don't see strong arguments why host name (that is potentially slow to detect) provides more information than IP (that is much faster to get).

**Comment by SMUnlimited** [comment]
I also have this issue at work. We have java selenium testing code that normally take 15 minutes now takes over an hour with the latest version. We had to revert to the previous version as an over 300% performance loss is unusable for us. We will have no power to get DNS servers looked at if that is the cause. 

I agree with lukeis idea. There should be a switch to be able to provide more detailed logging/exceptions. That is the usual way things are done. Turn on some flag or increase logging levels to get more detail to help debug problems when needed.

**Comment by sevaseva** [comment]
@SMUnlimited This pull request is not fixing any new behavior/regression. As far as I know, nothing in the way the host name is retrieved has changed in the last couple of years. Longer test execution time must have been caused by something that is unrelated to this PR.

**Comment by tarlabs** [comment]
@sevaseva, how about the PR being changed to create a flag to pull ip or hostname. By default using hostname and then those facing this issue could go ahead could change the flag to capture ip instead of hostname. No regression impact, backward compatible as well

Your thoughts?

**Comment by sevaseva** [comment]
@tarlabs I would be fine with that. @lukeis also suggested this earlier.
For consistency with the rest of Selenium Java codebase, the "flag" should probably be a Java System Property

**Comment by SMUnlimited** [comment]
@sevaseva ah yes looks likes like the issue we have is likely related to closed issue 383. My apologies.

**Comment by asolntsev** [comment]
@sevaseva @tarlabs @barancev 
I believe introducing any new flags would add complexity for users. Avoid complexity!

I suggest the following solution that is very easy to implement.
Let's Selenium will run a separate thread that would try to resolve IP/HOST of current computer. 
This thread can work quickly or slowly, not affecting performance of running tests. If this threads fails to resolve host at the moment the IP is needed, nothing happens, just "unknown" IP will be logged (as currently).

**Comment by sevaseva** [comment]
@asolntsev I like this idea. To "save" some complexity ;) we could also keep that background thread around, periodically looking up the hostname and overriding the variable where the exceptions (and other code that wants to know the hostname) take it from - so changed hostname eventually makes it to Selenium logs

**Comment by barancev** [comment]
FYI: Hub startup profiling results:
http://screencast.com/t/jlBEEwTRPOR
85% of the total time spent inside NetworkInterface constructor. 122 invocations. It is terrible :(

**Comment by asolntsev** [comment]
@sevaseva @tarlabs @barancev I created another pull request for issue 489: https://github.com/SeleniumHQ/selenium/pull/591

This pull request resolves ip/host in a background thread every 10 seconds.

**Comment by barancev** [comment]
Fixed long ago.

**Pull request closed without merging**
