### PR TITLE
[py] Fix send_keys with variable argument by removing variable expansion.

### PR DESCRIPTION
**Pull request by sufyanAbbasi**
### Description
Fixes Issue [#8839](https://github.com/SeleniumHQ/selenium/issues/8839)

### Motivation and Context
Python `send_keys` method is broken for variable arguments. See Issue [#8839](https://github.com/SeleniumHQ/selenium/issues/8839).

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Could you add a test for this as it appears that there is a regression that isn't caught by the current test suite

**Comment by sufyanAbbasi** [comment]
> Could you add a test for this as it appears that there is a regression that isn't caught by the current test suite

From what I can tell, the variable argument `send_keys` is being tested here:
https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/py/test/selenium/webdriver/common/typing_tests.py#L100

I haven't run the test suite locally to verify myself, but please let me know what you find!

**Comment by AutomatedTester** [comment]
It's not tested at all. It needs to be a test that does multiple test files

**Comment by AutomatedTester** [comment]
We will need to add a test at a later date

**Pull request merged**
