### PR TITLE
Multiple file upload support for firefox via sendKeysToElement

### PR DESCRIPTION
**Pull request by twalpole**
This adds support for multiple file upload via sendKeysToElement that works with Capybara.  If someone can point me to where the file upload tests are located (I've looked for quite some time and must be missing something really obvious) I'll be more than happy to add tests for it.

CLA has been signed

### CODE REVIEW

**Comment by andreastt** [comment]
This PR is wrong.  We decided that support for `<input type=file multiple>` should be done through separate calls to `sendKeys`; one for every file.  Becaue `sendKeys` appends to a text field, this makes sense for multiple file input fields as well.  Then you could call `clear` to empty it.

@twalpole, could you please resubmit this with that information in mind?  It would be really great to have this, I think.

**Comment by twalpole** [comment]
@andreastt  I'm looking to implement this with separate calls to sendKeys as you requested, however that introduces an issue. When a user selects multiple files to add to a file input the browser doesn't append them to the currently selected set of files, it replaces the previous set selected with the new selected set of files and fires one change event.  If we do it with separate calls then there will be one change event fired for each file added - strange behavior.  I think the decision to do separate calls for each file added is a bad decision, and doesn't replicate user/browser behavior very well.

**Comment by andreastt** [comment]
That's true, and you'll need to change the individual driver implementations to make this possible.

Doing several `sendKeys` calls to add files to `<input type=file multiple>` makes a lot of sense because it's backwards compatible and it respects the behaviour of how `sendKeys` works against textual input elements.

If you do `el.sendKeys("foo"); el.sendKeys("bar")`, the text content of `el` will be "foobar".  Consequently if you do `el.sendKeys(file1); el.sendKeys(file2)`, the result should be `FileList [ File, File ]`.

**Comment by andreastt** [comment]
See the minutes from the WG's F2F in Cambridge for more info: http://www.w3.org/2013/06/13-testing-minutes.html#item08

**Comment by DanielHeath** [comment]
One issue with this solution is that it can't exercise javascript code which handles multiple files being added in the same change event. 

Any ideas how to trigger that? Or should I just change the application to let me fake it?

**Pull request closed without merging**
