### PR TITLE
[java] replace guava immutable map with built-in java8 immutable map, linter fixes

### PR DESCRIPTION
**Pull request by nir-tal-talkspace**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

general project refactor

### Motivation and Context

- replace guava immutable map with built-in java8 immutable map
- optimize imports
- linter fixes
- removed more public test methods

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
We are not making any changes to the `thoughtworks` package. Could you please revert those changes?

Also, can you please provide a better description for this PR?

**Comment by nir-tal-talkspace** [comment]
> We are not making any changes to the `thoughtworks` package. Could you please revert those changes?
> 
> Also, can you please provide a better description for this PR?

yes, this is still a draft 
and i will revert these changes

**Comment by diemol** [comment]
I don't really understand the purpose of the changes, is it just indentation?

**Comment by nir-tal-talkspace** [comment]
> I don't really understand the purpose of the changes, is it just indentation?

no, it's mentioned in the pr Motivation and Context.

**Comment by diemol** [comment]
> > I don't really understand the purpose of the changes, is it just indentation?
> 
> no, it's mentioned in the pr Motivation and Context.

Can you please do each thing in a separate PR? Reviewing over 1000 files takes a long time and it gets tricky.

**Comment by nir-tal-talkspace** [comment]
> > > I don't really understand the purpose of the changes, is it just indentation?
> > 
> > 
> > no, it's mentioned in the pr Motivation and Context.
> 
> Can you please do each thing in a separate PR? Reviewing over 1000 files takes a long time and it gets tricky.

Ok

**Pull request closed without merging**
