### PR TITLE
Add HTML5 functionality to .NET binding

### PR DESCRIPTION
**Pull request by petruq**
Add HTML5 functionality to .NET binding

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the [CLA](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)?

**Comment by petruq** [comment]
Yes. I have contributed the Edge bindings for C# and Java.

**Comment by petruq** [comment]
Sorry. This is the wrong account. I need to cancel this pull request and resubmit it from my other github account.

**Comment by ddavison** [comment]
@petruq Edge bindings are housed with microsoft.  if they have their own CLA, you'll still have to abide by ours

**Comment by petruc** [comment]
This needs to be closed. I submitted it from my personal gihutb account not from teh Microsoft sanctioned account.

**Pull request closed without merging**
