### PR TITLE
[py] Update Documentation api.rst File List 

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

trying to fix documentation for current and obsolete classes according to issue #13910 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Documentation, Bug fix

___

### **Description**
- Added module-level docstring for `DriverFinder` implementation.
- Updated the list of modules in `api.rst` to include new and reordered entries, ensuring alphabetical order.
- Added `NoSuchDriverException` to the exceptions list in `selenium.common.exceptions`.
- Added new documentation files for `selenium.webdriver.common.driver_finder` and `selenium.webdriver.common.selenium_manager`.
- Added `PageLoadStrategy` to the autosummary list in `selenium.webdriver.common.options`.
- Removed obsolete documentation for `selenium.webdriver.firefox.extension_connection`.
- Added `requirements.txt` to the dependencies list in `tox.ini`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>driver_finder.py</strong><dd><code>Add module-level docstring for DriverFinder</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/selenium/webdriver/common/driver_finder.py

- Added module-level docstring for `DriverFinder` implementation.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-06cebae290653d9a47afbbf9de789bbb1123db4c2ab5456984ff19bff0e40f50">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>api.rst</strong><dd><code>Update and reorder module list in api.rst</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/docs/source/api.rst

<li>Updated the list of modules in <code>api.rst</code> to include new and reordered <br>entries.<br> <li> Ensured alphabetical order for module listings.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-7e8f0a6376548281d6c1a5b57121f0a701a76c5f88129fe7def3d89f39b63c43">+36/-14</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium.common.exceptions.rst</strong><dd><code>Add NoSuchDriverException to exceptions list</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/docs/source/common/selenium.common.exceptions.rst

<li>Added <code>NoSuchDriverException</code> to the exceptions list.<br> <li> Minor formatting adjustments.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-93d8eaf46a522ebd6e7b4fa753703eda05618d8e42c464b030e68f5fef39b478">+15/-15</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium.webdriver.common.driver_finder.rst</strong><dd><code>Add documentation for selenium.webdriver.common.driver_finder</code></dd></summary>
<hr>
      
py/docs/source/webdriver/selenium.webdriver.common.driver_finder.rst

<li>Added new documentation file for <br><code>selenium.webdriver.common.driver_finder</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-f913f241b4c60c6cdeff1f2869f7ff14856e240a21f65cec860682291ee7da71">+29/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium.webdriver.common.options.rst</strong><dd><code>Add PageLoadStrategy to options documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/docs/source/webdriver/selenium.webdriver.common.options.rst

- Added `PageLoadStrategy` to the autosummary list.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-6ffc44d703fa7c97e412dc8c325f0da0d821bb9886c6387b3650264531f274e0">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium.webdriver.common.selenium_manager.rst</strong><dd><code>Add documentation for selenium.webdriver.common.selenium_manager</code></dd></summary>
<hr>
      
py/docs/source/webdriver/selenium.webdriver.common.selenium_manager.rst

<li>Added new documentation file for <br><code>selenium.webdriver.common.selenium_manager</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-f15f2c5d655fe4cf14e61f255796feb2574d4e18d3b449a028adc46eb798e3c6">+29/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium.webdriver.firefox.extension_connection.rst</strong><dd><code>Remove obsolete firefox extension connection documentation</code></dd></summary>
<hr>
      
py/docs/source/webdriver_firefox/selenium.webdriver.firefox.extension_connection.rst

<li>Removed obsolete documentation for <br><code>selenium.webdriver.firefox.extension_connection</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-7d173ee6e5949b2783eb08c3564b6f3a3a61974965b608488b0526b6e3e39999">+0/-35</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tox.ini</strong><dd><code>Add requirements.txt to tox dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/tox.ini

- Added `requirements.txt` to the dependencies list in `tox.ini`.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14172/files#diff-27d219400d7f64afbf3d9bceb197e20b299fdd58fb4e84c9b7c2ee7c4e828177">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
@iampopovich was this code automatically generated?

**Comment by iampopovich** [comment]
No, I think we should close this pull request and continue figuring out how to fix the document generation globally using Sphinx.

**Comment by titusfortner** [comment]
If this is going to generate the right things for 4.22, though, I'd like to get something updated and then we can figure out the automated way to do this going forward?

**Comment by iampopovich** [comment]
Hm

After I manually added new classes and removed non-existent ones, new .rst documents were generated automatically.

When I ran it locally, I got a dialog asking, "Do you want to update the documentation?"

I declined, but I think even if I had agreed, I wouldn't have had the write permissions to update the documentation in production.

Is there a way to check the validity of the created documents without updating the existing documentation? I saw that sphinx can generate HTML, but unfortunately, I'm not at my computer right now.

**Comment by iampopovich** [comment]
Some documents that were generated locally were not included in the commits.
I deliberately didn't add them because I thought they could be created automatically when the documentation update action runs.

These are the files with documentation for bidi.

This can be checked by running `./go py:docs` locally.

**Comment by titusfortner** [comment]
You can't break anything. The [current code](https://github.com/SeleniumHQ/selenium/blob/00f6b7c00b235389e9dcc87fe1cbfd0da4d33b0f/Rakefile#L552-L564)
1. Deletes relevant `/build/docs/api/py` directory
2. Generates new docs to that directory
3. Checks out gh-pages branch
4. Deletes current `/docs/api/py/` directory
5. copies from `/build/docs/api/py` to `/docs/api/py`
6. Commit/Push and Github does the build/publish

So we just need to get `tox -c py/tox.ini -e docs` (or the equivalent) to generate the right files into buid/docs/api/py directory and compare it to the directory in gh-pages.

**Comment by titusfortner** [comment]
Oh yeah, I just changed what `./go py:docs` does. It used to try to do everything for you, now it just generates and makes the commit. Trying to get all the docs stuff done in Github actions now: https://github.com/SeleniumHQ/selenium/blob/trunk/.github/workflows/update-documentation.yml

**Comment by iampopovich** [comment]
@titusfortner you can see in my latest commit that new documents were generated according to the list of files in api.rst
In the screenshot, I provided an example of the previously missing class wpewebkit.
4.21.0 
Screenshot 2024-06-22 at 21 48 51
my local build
Screenshot 2024-06-22 at 21 46 31

guess we can use manually updated api.rst for the 4.22.0 documentation

**Comment by titusfortner** [comment]
Closing this in favor of #14173

**Pull request closed without merging**
