### PR TITLE
[py] Fix TypeError when init Safari webdriver

### LINKED ISSUE #14698: [🐛 Bug]: [Python 4.26.1] webdriver.safari TypeError: __init__() missing 1 required positional argument: 'remote_server_addr'
### What happened?

Unfortunately, while patching 4.26.1, an unexpected error (missing in CI tests) caused a basic test below is fail to initialize the driver instance for Safari

### How can we reproduce the issue?

```shell
@pytest.mark.skipif(sys.platform != "darwin", reason="requires Mac")
def test_basic_options():
    options = webdriver.SafariOptions()
    driver = webdriver.Safari(options=options)

    driver.quit()
```

### Relevant log output

```shell
client_config = ClientConfig(remote_server_addr=self.service.service_url, keep_alive=keep_alive, timeout=120)
>       executor = SafariRemoteConnection(
            ignore_proxy=options._ignore_local_proxy,
            client_config=client_config,
        )
E       TypeError: __init__() missing 1 required positional argument: 'remote_server_addr'
```

### Operating System

MacOS

### Selenium version

Python 4.26.1

### What are the browser(s) and version(s) where you see this issue?

Safari (any version)

### What are the browser driver(s) and version(s) where you see this issue?

Safari driver (any version)

### Are you using Selenium Grid?

No

### PR DESCRIPTION
**Pull request by VietND96**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
- Fixes #14698
- Add to CI a test to verify Safari launcher 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Fixed a `TypeError` in the Safari WebDriver initialization by removing the `ClientConfig` and adjusting the `SafariRemoteConnection` setup.
- Added a new job in the CI workflow to run Safari tests on macOS, ensuring better test coverage for Safari.
- Marked the `test_launch_safari_with_legacy_flag` as skipped, indicating it needs updates.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Fix TypeError by adjusting SafariRemoteConnection initialization</code></dd></summary>
<hr>

py/selenium/webdriver/safari/webdriver.py

<li>Removed <code>ClientConfig</code> import and usage.<br> <li> Modified <code>SafariRemoteConnection</code> initialization to directly use <br>parameters.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14699/files#diff-17f0ef4ff7107dea65c60c41cb73096d541f95727842abe9b58a47eb87d6470f">+2/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>launcher_tests.py</strong><dd><code>Mark Safari legacy flag test to be skipped</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/safari/launcher_tests.py

- Added a skip marker to `test_launch_safari_with_legacy_flag`.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14699/files#diff-9557c62c05996ffd564f1f7bd65fb6e9d5616b347a15b91ef0c417625974f46c">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ci-python.yml</strong><dd><code>Add Safari tests to CI workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.github/workflows/ci-python.yml

<li>Added a new job for Safari tests in the CI workflow.<br> <li> Configured Safari tests to run on macOS.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14699/files#diff-a7ec86144013d78c9f1d734aa65a898e66b609638aa7b872491ee3858ebebbeb">+12/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by cclauss** [comment]
Has this fix landed in any release?  https://github.com/SeleniumHQ/selenium/releases

**Comment by VietND96** [comment]
FYI, Chrome early stable release will comes out, we also will do a minor release next week including this fix. https://chromiumdash.appspot.com/schedule
cc @diemol

**Comment by rsugumar** [comment]
waiting for this fix to come out soon. I see this error in py 3.12.7 / 3.13. Let me check quickly in 3.11

**Comment by VietND96** [comment]
I think Python version is not a problem, you can try to pin selenium==4.25.0 in the meantime.

**Comment by cclauss** [comment]
Pinning to `selenium==4.25.0` does work.  Thanks.  Would it be possible to get these fixes into a Nightly build?

**Comment by diemol** [comment]
https://www.selenium.dev/downloads/#nightly

**Pull request merged**
