### PR TITLE
#10345 make driver.close() tolerant to CDP failures

### PR DESCRIPTION
**Pull request by asolntsev**
Driver should still be closed even if failed to disconnect DevTools session (which apparently happens because Selenium doesn't support current version of browser's CDP)

### Description
Fixes URGENT bug with latest Firefox https://github.com/SeleniumHQ/selenium/issues/10345

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by titusfortner — APPROVED** [review]
I think this is a good solution for this particular issue.

**Comment by asolntsev** [comment]
@titusfortner I also think so. :) 
Why don't we release an update?

**Comment by diemol** [comment]
I'm fixing another couple of bugs. We'll do a release early next week.

**Review by diemol — APPROVED** [review]
Thank you, @asolntsev!

**Pull request merged**
