### PR TITLE
Added DepricationWarning to the warnings.warn methods inside the find_element_by_x methods

### PR DESCRIPTION
**Pull request by BusHero**
Added "DepricationWarning" argument to the warnings.warn inside the find_element_by_x methods from the WebElement class.

In such a way, the IDE will mark the methods as deprecated, similar to how it marks the find_element_by_x methods from the webDriver class.

### CODE REVIEW

**Review by symonk — CHANGES_REQUESTED** [review]
might be some value in not using the default `stacklevel` too,  can we pass `stacklevel=2`?

**Comment by BusHero** [comment]
> might be some value in not using the default `stacklevel` too, can we pass `stacklevel=2`?

Sounds like a good idea

**Review by AutomatedTester — DISMISSED** [review]

**Comment by AutomatedTester** [comment]
There are some tox errors, please can you fix and then we will merge it.

**Review by diemol — APPROVED** [review]
Review comments were addressed and tox failures are gone, will merge.

Thanks, @BusHero!

**Pull request merged**
