### PR TITLE
py: fix RelativeBy#near to take 2 parameters

### PR DESCRIPTION
**Pull request by pinterior**
### Description

`RelativeBy#near` should take 2 parameters to specify target *element (or locator)* and *distance*.

also:
- add more strict type hints on relative_locator.py
- ~remove default arguments raises Exception~
- add some tests

### Motivation and Context

want to find far element

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed. 
   - on my side, some tests already fails on trunk, but newly created tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
1. We can't change a public method without warning. We typically mark methods or parameters as obsolete for 2 releases before removing something.
2. We aren't accepting changes in the support classes right now. We're meeting next week to decide how to approach this section of the code going forward.

**Comment by pinterior** [comment]
> 1. We can't change a public method without warning.

resurrected default `None` argument.
old `locate_with(...).near(elem)` style call still works with default `distance` argument,  but need to use different name for `near(element_or_locator, distance)` method?

> 2. We aren't accepting changes in the support classes right now.

sure.
hope `near` locating will be able to use with custom distance in the future.

**Comment by diemol** [comment]
The "issue" is that Java and C# already accept distance as a parameter. JavaScript and Python don't, and I did not understand the Ruby code to know whether it accepts it.

**Comment by pinterior** [comment]
the main issue is following `near` method looks like to take single `int` parameter, but it doesn't work.

```python3
    def near(self, element_or_locator_distance: Union[WebElement, Dict, int] = None) -> "RelativeBy":
```

**Comment by diemol** [comment]
> the main issue is following `near` method looks like to take single `int` parameter, but it doesn't work.
> 
> ```python
>     def near(self, element_or_locator_distance: Union[WebElement, Dict, int] = None) -> "RelativeBy":
> ```

Good point. Where can I see the failed test that shows the bug on the current implementation?

**Comment by pinterior** [comment]
running test on faddc1b0ec0d453815e3cfffce95d1b345249bc3 clearly shows `near(123)` fails with `InvalidArgumentException`

**Comment by diemol** [comment]
@pinterior can you please fix the linting so I can merge this?

**Review by diemol — APPROVED** [review]
Thank you!

**Pull request merged**
