### PR TITLE
[rust] Now the logger accepts any kind of type that can be converted to string

### PR DESCRIPTION
**Pull request by oriongonza**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Now the logger accepts any kind of type that can be converted to string
### Motivation and Context

Enable fix of https://github.com/SeleniumHQ/selenium/pull/11810#discussion_r1158432437

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by bonigarcia — CHANGES_REQUESTED** [review]
There are compilation errors. Also, please verify that all tests pass with the new changes (`cargo test`).

**Comment by oriongonza** [comment]
@bonigarcia I'm sorry for the really long wait! I have merged and it should work now.

**Review by bonigarcia — APPROVED** [review]
LGTM. Thanks a lot, @dev-ardi!

**Review by diemol — APPROVED** [review]
Thank you for reviewing, @bonigarcia!

Thank you, @dev-ardi!

**Comment by titusfortner** [comment]
This commit broke the `--proxy` parameter. It currently ignores the proxy passed in.

**Pull request merged**
