### PR TITLE
Add support for FedCM commands

### PR DESCRIPTION
**Pull request by cbiesinger**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
This adds the FedCM webdriver commands that are specified in:
https://fedidcg.github.io/FedCM/#automation

Currently implemented in Chromium, but Firefox is interested as well:
https://github.com/fedidcg/FedCM/pull/395#issuecomment-1384466751
https://github.com/fedidcg/FedCM/pull/465#issuecomment-1549781575

Bug #12088 

### Motivation and Context
This lets identity providers and relying parties use Selenium's Java API to control
the FedCM browser dialog to test that their website works correctly when
using the FedCM API.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ x My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cbiesinger** [comment]
I believe this is ready for review now!

However, the test I've written requires Chrome 115, and I don't know how to handle that?

**Comment by diemol** [comment]
We would need to make some changes in the test setup to allow beta Chrome to be used for testing. Not sure if we will have time to do that before the actual Chrome 115 is released. Would you be OK if we review this PR when that happens?

**Comment by cbiesinger** [comment]
Hm, what kind of support would you need? I could perhaps look into doing that work if you outline what is needed.

I could also change this CL so that the test is skipped if the command throws a NotImplemented error?

Either way -- it seems like the review doesn't have to wait until then, only the merging? I would certainly appreciate getting comments earlier :)

**Comment by diemol** [comment]
You are right, I will find time in the next couple of days to review this.

**Review by diemol — COMMENTED** [review]
I think the code looks good, so there is no action needed for now. I will see if I can find time to enable testing with Chrome beta in our CI in the meantime. Thank you.

**Comment by cbiesinger** [comment]
@diemol -- fyi, Chrome 115 has now been released (https://chromereleases.googleblog.com/2023/07/stable-channel-update-for-desktop.html), so just updating to the latest stable should allow this PR to be merged

**Comment by cbiesinger** [comment]
ping?

**Review by diemol — APPROVED** [review]
Thank you, @cbiesinger!

**Comment by diemol** [comment]
@cbiesinger do you know why we are getting the following error in these tests now?
>unknown command: fedcm/setdelayenabled

CI Link: https://github.com/SeleniumHQ/selenium/actions/runs/8418971824/job/23050594831#step:16:503

**Comment by cbiesinger** [comment]
@diemol it looks like that was broken by 7ad44eef93a2797fdfa14f05f0ff0bb8c4a2525f which removed the session ID prefix

**Comment by cbiesinger** [comment]
@titusfortner FYI, see last comment

**Comment by cbiesinger** [comment]
I have created PR #14070 to fix that issue.

**Pull request merged**
