### PR TITLE
[rust] Enable Firefox nightly for linux on arm64

### PR DESCRIPTION
**Pull request by bgermann**
### Description
Mozilla provides nightly Firefox releases for ARM64 Linux now. Make selenium-manager aware of them.

### Motivation and Context
On ARM64 Linux, selenium-manager downloads binaries for x86_64 even though there are releases for ARM64.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Added support for downloading ARM64 binaries for nightly Firefox builds on Linux.
- Modified the platform label assignment to distinguish between ARM64 and other architectures for nightly builds.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>firefox.rs</strong><dd><code>Add ARM64 support for nightly Firefox on Linux</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
rust/src/firefox.rs

<li>Added support for ARM64 architecture in nightly Firefox builds.<br> <li> Modified platform label assignment logic for nightly builds.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14099/files#diff-a223ca8815bf06c61bd96d36c5ebae1789d76dbc4d91ae6aa82d47f6d087f611">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
Looks like this is related to #13793

1. How does Selenium manager run on arm64 when it is only compiled for x86?
2. We need to also be able to get the arm64 driver for it to matter that we are getting the arm64 browser

**Comment by bgermann** [comment]
> Looks like this is related to #13793
> 
> 1. How does Selenium manager run on arm64 when it is only compiled for x86?

I compile it myself on for arm64. Generally it runs.

> 2. We need to also be able to get the arm64 driver for it to matter that we are getting the arm64 browser

That is already the case.

**Review by bonigarcia — APPROVED** [review]
LGTM

**Comment by bgermann** [comment]
I do not think that the failing test (Windows-only: fatal error LNK1181: cannot open input file 'windows.0.52.0.lib') is related to this change as this codepath is not relevant on Windows.

**Comment by bonigarcia** [comment]
No, that error is not related. In theory, that should be fixed in the trunk branch.

**Pull request merged**
