### PR TITLE
fix and use ephemeral port from platform

### PR DESCRIPTION
**Pull request by tflori**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

This solves the port negotiation problem on linux (and maybe other platforms). #1630 

The removed code leads to the result that `FIRST_PORT` and `LAST_PORT` is both set to 1024 which always returns 1024. In fact we should trust the ephemeral ports reports by the detector. With the min and max we just assure a valid port range.

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6704)

### CODE REVIEW

**Comment by cgoldberg** [comment]
default ephemeral port range in the Linux kernel is: 32768-60999

see `ip_local_port_range`:
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by tflori** [comment]
> default ephemeral port range in the Linux kernel is: 32768-60999
> 
> see `ip_local_port_range`:
> https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

I'm aware of this fact. Before the ephemeral port range was not used. Instead the higher range (between 1024 and <start of ephemeral port range> or between <end of ephemeral port range> and 65535) outside the ephemeral port range was used.

This must have been implemented when the most users used windows xp - because there the port range was too small. I just understood today what this code should do but I can't agree that it makes sense.

In some linux environments (often on servers) the ephemeral port range is just set to 1024-65535 and the code before was just stuck on port 1024. This can not be a solution too.

In my opinion the ephemeral port range should be used unless it has enough ports.

```
ephemeralRange = ephemeralUpperBound - ephemeralLowerBound
if ephemeralRange < 5000 then
  belowRange = ephemeralLowerBound - 1024
  aboveRange = 65535 - ephemeralUpperBound
  if belowRange > aboveRange then use belowRange
  else use aboveRange
else use ephemeralRange
```

**Comment by shs96c** [comment]
@tflori, first of all a heartfelt apology. Leaving this PR in limbo for the better part of three years isn't a good way to show the appreciation and thanks for feel for the hard work it represents. I'm sorry it took so long for us to finally get round to reviewing and merging this, and I thank you for your patience. We do thank you for the PR, though! It's clearly solving a real problem.

Secondly, I've now merged this into the tree as 294d1c92fb9578513c82c1431d6c25b98364fcc2. I had to rebase this locally and handle some merge conflicts, but your name is on the commit. 

Once again, thank you!

**Comment by tflori** [comment]
Yay! Finally 😀 Thank you

**Pull request closed without merging**
