### PR TITLE
[py] Drop python 2.7 and 3.4 support

### PR DESCRIPTION
**Pull request by uriyyo**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## [py] Drop python 2.7 and 3.4 support

python 2.7 and 3.4 are no longer supported. I believe we can drop support for those versions.

This PR related to #7462

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Thanks for putting in the effort on this PR. Unfortunately there hasn't been a decision made on whether we are going to drop 2.7 straight away.

**Review by AutomatedTester — CHANGES_REQUESTED** [review]
Setting request changes so that it is not accidentally merged.

**Comment by uriyyo** [comment]
Hi @diemol,
Should I update PR?

**Comment by isaulv** [comment]
@uriyyo Please do update your PR to fix branch change. It won't be merged at this time but when there is a decision to drop Python 2.7 support. This will be the first change.

**Comment by uriyyo** [comment]
Hi @Dude-X I have updated PR

I have a question, which python version will be the next minimal version supported by `selenium`?

I saw usage of `asynccontextmanager`, so it looks like a minimal version is *python 3.7*.

We can also update old-style string formatting with f-strings, in case if minimal version will be above or equals to python 3.6.

**Comment by isaulv** [comment]
@uriyyo The next version will support Python 2.7 but I think David will add the option to install CDP support which will be limited to Python 3.7+. So I imagine a `pip install selenium[cdp]` will be a thing in the short term.
I feel that when 4.0.0 is made a stable release, it should be forked for Python 2.7 support and the next version bump that isn't a bug fix will drop Python 2.7, Python 3.5 support.

**Comment by uriyyo** [comment]
@Dude-X Thanks for the answer. Everything clear for me now 🙂

**Comment by isaulv** [comment]
@uriyyo One change that is missing and important is to change `setup.cfg` and remove the entry on `universal=1` since it will no longer be a universal wheel once we drop Python 2.7.

**Comment by uriyyo** [comment]
@Dude-X I have removed `bdist_wheel` section from `setup.cfg`

**Review by MarcSteven — COMMENTED** [review]
Grete job, I truly hope it can be merged into the branch as soon as possible.

**Comment by uriyyo** [comment]
Hi all should I update this PR? Are there any plans to merge it?

**Comment by AutomatedTester** [comment]
closing this as we have changed tact on this a little and have been updating files we go. It's not complete but we can fix as we go now.

**Pull request closed without merging**
