### PR TITLE
[java] Increased the max depth of new session payload

### LINKED ISSUE #12201: [🐛 Bug]: Can't set chrome options due to JSON MAX_DEPTH
### What happened?

I can't set complex chrome webdriver options because `org/openqa/selenium/json/JsonOutput.java` specifies a `MAX_DEPTH` of `10`.

This was working in 4.8.1.

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
options.addArguments("--no-sandbox"); // has to be the very first option
options.addArguments("--disable-gpu");
options.addArguments("--disable-translate");
options.addArguments("--disable-plugins");
options.addArguments("--window-size=1920,1080");

options.setAcceptInsecureCerts(true);

Map<String, Object> prefs = new HashMap<>();
Map<String, Object> profile = new HashMap<>();
Map<String, Object> contentSettings = new HashMap<>();
Map<String, Object> exceptions = new HashMap<>();
Map<String, Object> clipboard = new HashMap<>();
Map<String, Object> domain = new HashMap<>();

// Enable clipboard permissions
domain.put("expiration", 0);
domain.put("last_modified", System.currentTimeMillis());
domain.put("model", 0);
domain.put("setting", 1);
clipboard.put(siteRoot + ",*", domain);
exceptions.put("clipboard", clipboard);
contentSettings.put("exceptions", exceptions);
profile.put("content_settings", contentSettings);
prefs.put("profile", profile);
options.setExperimentalOption("prefs", prefs);


log.debug("Connecting to selenium at " + webDriverURI);
RemoteWebDriver newDriver = new RemoteWebDriver(webDriverURI, options);
log.debug("Connected to selenium");
```
```


### Relevant log output

```shell
org.openqa.selenium.json.JsonException: Reached the maximum depth of 10 while writing JSON
```
```


### Operating System

macOS 13.4

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

standalone-chromium:113.0

### What are the browser driver(s) and version(s) where you see this issue?

standalone-chromium:113.0

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by joerg1985**
### Description
Made the max depth more flexible and increased the max depth of new session payload to 100.

### Motivation and Context
fixes #12201

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — APPROVED** [review]
Thank you, @joerg1985!

**Comment by Yith1** [comment]
There's still a problem. The toJson method is called by the AbstractHttpCommandCodec (at line 273) and the version that sets the default max depth to 10 is still being called. 

This is causing the toJson method to fail with a tree depth error when we are using AxeReporter to report Accessibility problems. The depth of the structure returned is above the 10 maximum.

This is happening when AxeBuilder.analyze() is being called.

image

**Comment by titusfortner** [comment]
Can you make a PR with a fix?

**Comment by Yith1** [comment]
> Can you make a PR with a fix?

I could, but I've never written any Selenium stuff before.

**Comment by Yith1** [comment]
I'm not sure whether I've created the Pull Request properly, but here's the change.

I've tested it and it fixes my problem.
https://github.com/SeleniumHQ/selenium/pull/12581

**Comment by joerg1985** [comment]
@titusfortner I think this limit is more a general safety net, it might be best to increase the JsonOutput.MAX_DEPTH to 100?

**Pull request merged**
