### PR TITLE
Update remote_connection.py with new Cast commands

### PR DESCRIPTION
**Pull request by cliffordcheng**
The new Cast commands are added here:
https://chromium-review.googlesource.com/c/chromium/src/+/1401270

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6995)

### CODE REVIEW

**Comment by cliffordcheng** [comment]
Friendly ping.
I think this change is quite straightforward and we have some other tasks that're depending on this change.
If someone can help to look at it quickly, that will be great.

**Comment by AutomatedTester** [comment]
How are you intending on using these new commands? It looks like a half completed PR

**Comment by cliffordcheng** [comment]
We intend to consume these new commands in testing different functionalities between Chrome and Chromecast. We use ChromeDriver in most of our tests.
There is no way for us to trigger any action on Chromecast, or any Cast enabled devices, without using the new DevTools commands.

**Comment by cliffordcheng** [comment]
This is used by Google internally and will also be used by third party.
We have some test updates that rely on this change.
Please feel free to let me know if there is anything needed from me to land this CL.

**Comment by AutomatedTester** [comment]
What is missing is actual calls like https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py#L85-L147 so that they become usable.

**Comment by cliffordcheng** [comment]
Ah. I see.
We just directly use execute in our cases.
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L297

I am going to add those changes today and will reply again once it's done.
Thanks for pointing it out.

**Comment by cliffordcheng** [comment]
Just added all the calls.
Please take a look again.

**Comment by cgoldberg** [comment]
@AutomatedTester @cliffordcheng 
These commands just call their equivalent in DevTools Protocol... and we already have `execute_cdp_cmd()` for that.
IMHO this just expands the API for no real benefit.

**Comment by cliffordcheng** [comment]
It looks like execute_cdp_cmd only do POST, but not GET.

**Pull request merged**
