### PR TITLE
[java] pick random port outside of well-known ranges of ephemeral ports

### PR DESCRIPTION
**Pull request by h-arlt**
### Description
Let port prober choose from a safe range of ephemeral ports that explicitly exclude the well-known range of ephemeral ports used by the OS for port allocation (as was done in Selenium v3) while keeping fallback to IANA port range in case range of ephemeral ports is too low (less than 5k).

### Motivation and Context
Instead of choosing a random port within the well-known ranges of ephemeral ports, those ranges should be excluded in order to minimize probability of collisions with port allocations performed by OS.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by h-arlt** [comment]
I followed the steps described in README to build and test Selenium Java but had to abort the build process as it eats all of my free disk space. I would really appreciate if someone else could take over that part.

**Comment by pujagani** [comment]
Related to #10974

**Comment by pujagani** [comment]
I have gone through the changes and it looks fine on the surface. However, Simon and Diego will have a better idea about this area. I have requested them to help review it.

**Comment by nocive** [comment]
bump

**Comment by h-arlt** [comment]
Hi guys. Any news on this?
Just let me know if there is anything missing from my side. Thx!

**Review by diemol — APPROVED** [review]
Thank you, @h-arlt!

**Comment by h-arlt** [comment]
:partying_face: Thanks for merging, @diemol !

**Pull request merged**
