### PR TITLE
Old style exceptions are syntax errors in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by luke-hill** [comment]
@cclauss I know we still run some tests in python 2, will this syntax work in python 2?

@lmtierney should be a quick review and merge / decline here?

**Comment by cclauss** [comment]
This change is compatible with both Python 2 and Python 3.

**Comment by barancev** [comment]
The changed file is a part of the build infrastructure, it does not touch any code that can affect end users.

**Comment by barancev** [comment]
Merged as ca9e9a4a752baa588f88eca87f2b936c0ed50709, thank you for the contribution!

**Pull request closed without merging**
