### PR TITLE
 Proper handling HTTP Host header in Python client

### PR DESCRIPTION
**Pull request by grz0**

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the [CLA](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)?

**Comment by grz0** [comment]
@ddavison yes

**Comment by lukeis** [comment]
wouldn't you also want to add the header in the keep_alive section? ~ line 415.

Also according to HTTP spec, when there is not an "Internet host name", the HOST header must be given with an empty value. Often in the cases of use with selenium only IP addresses are given, you may need to check for that.

Also, I don't see too much value in doing this, unless it's a problem with a selenium service like saucelabs? But this would imply an multi-tenant system and I don't understand that use case with selenium.

**Comment by grz0** [comment]
@lukeis 
>Also according to HTTP spec, when there is not an "Internet host name", the HOST header must be given with an empty value. Often in the cases of use with selenium only IP addresses are given, you may need to check for that.

Firefox when using only IP adress sets Host header to IP:port.

> But this would imply an multi-tenant system and I don't understand that use case with selenium.

I'm using Nginx in front of multiple selenium grids as reverse proxy.

**Comment by lukeis** [comment]
one machine with multiple selenium grids? I really don't agree with that as an architecture...

That being said... merged with b095d43024230d0e13c2673673dcdcc87b8ed33d

**Pull request closed without merging**
