### PR TITLE
[grid][java]: relay service can set protocol version in fetching status

### LINKED ISSUE #13481: [🐛 Bug]: Node can't connect to Grid hub from version 4.14.0 (Error checking service status http://localhost:4723/status)
### What happened?

From version 4.14.0 node can't connect to hub ( checked on 4.10, 4.13 ,4.14.0, 4.14.1, 4.16.1, selenium-server-4.17.0-SNAPSHOT). it works on 4.13 and below.

from browser run link "http://localhost:4723/status"- {"value":{"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.4.1"}}}

node window result:
____._____@_________ Grid % java -jar selenium-server-4.16.1.jar node --config node4.toml
15:48:48.216 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:48:48.220 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:48:48.268 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
15:48:48.289 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:48:49.295 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:48:49.393 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.1.144:5557
15:48:49.403 INFO [NodeOptions.getSessionFactories] - Detected 10 available processors
15:48:49.411 INFO [RelayOptions.getSessionFactories] - Adding relay configs for http://localhost:4723
15:48:49.415 INFO [RelayOptions.lambda$getSessionFactories$1] - Mapping Capabilities {appium:automationName: UiAutomator2, appium:deviceName: Pixar 5а, appium:platformVersion: 13, platformName: ANDROID}, 1 times
15:48:49.415 INFO [RelayOptions.lambda$getSessionFactories$1] - Mapping Capabilities {appium:automationName: UiAutomator2, appium:deviceName: Pixar 4, appium:platformVersion: 13, platformName: ANDROID}, 1 times
15:48:49.437 INFO [Node.<init>] - Binding additional locator mechanisms: relative
15:48:49.509 INFO [NodeServer$1.start] - Starting registration process for Node http://192.168.1.144:5557
15:48:49.510 INFO [NodeServer.execute] - Started Selenium node 4.16.1 (revision 9b4c83354e): http://192.168.1.144:5557
15:48:49.620 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4723/status. java.io.IOException: HTTP/1.1 header parser received no bytes
15:48:49.621 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://192.168.1.144:5557 is DOWN

### How can we reproduce the issue?

```shell
java version "21.0.2" (same with "20.0.2")
grid - 4.16.1 (also checked selenium-server-4.17.0-SNAPSHOT, and 4.15) 
Appium v2.4.1

1. Run hub "sudo java -jar selenium-server-4.16.1.jar hub" 
2. Run node "java -jar selenium-server-4.16.1.jar node --config node4.toml"


# node4.toml
[server]
port = 5557
[node]
detect-drivers = false

[relay]
# Default Appium/Cloud server endpoint
url = "http://localhost:4723"
status-endpoint = "/status"
configs = ["1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"13\", \"appium:deviceName\": \"Pixar 5а\", \"appium:automationName\": \"UiAutomator2\"}",
"1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"13\", \"appium:deviceName\": \"Pixar 4\", \"appium:automationName\": \"UiAutomator2\"}"]
```

### Relevant log output

```shell
____._____@_________ Grid % java -jar selenium-server-4.16.1.jar node --config node4.toml
15:48:48.216 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:48:48.220 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:48:48.268 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
15:48:48.289 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:48:49.295 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:48:49.393 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.1.144:5557
15:48:49.403 INFO [NodeOptions.getSessionFactories] - Detected 10 available processors
15:48:49.411 INFO [RelayOptions.getSessionFactories] - Adding relay configs for http://localhost:4723
15:48:49.415 INFO [RelayOptions.lambda$getSessionFactories$1] - Mapping Capabilities {appium:automationName: UiAutomator2, appium:deviceName: Pixar 5а, appium:platformVersion: 13, platformName: ANDROID}, 1 times
15:48:49.415 INFO [RelayOptions.lambda$getSessionFactories$1] - Mapping Capabilities {appium:automationName: UiAutomator2, appium:deviceName: Pixar 4, appium:platformVersion: 13, platformName: ANDROID}, 1 times
15:48:49.437 INFO [Node.<init>] - Binding additional locator mechanisms: relative
15:48:49.509 INFO [NodeServer$1.start] - Starting registration process for Node http://192.168.1.144:5557
15:48:49.510 INFO [NodeServer.execute] - Started Selenium node 4.16.1 (revision 9b4c83354e): http://192.168.1.144:5557
15:48:49.620 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4723/status. java.io.IOException: HTTP/1.1 header parser received no bytes
15:48:49.621 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://192.168.1.144:5557 is DOWN
```

### Operating System

Mac os 14.2.1

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

appium

### What are the browser driver(s) and version(s) where you see this issue?

2.4.1

### Are you using Selenium Grid?

4.16.1

### PR DESCRIPTION
**Pull request by VietND96**
## **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context
Fix: https://github.com/SeleniumHQ/selenium/issues/13481

```bash
15:48:49.620 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4723/status. java.io.IOException: HTTP/1.1 header parser received no bytes
15:48:49.621 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://192.168.1.144:5557 is DOWN
```

Pass the protocol version to the HttpClient config before executing the request in method `isServiceUp()`
Required the CLI config `--service-protocol-version` or `protocol-version` in TOML config
The config accepts values following [enum]( https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpClient.Version.html). For example: `HTTP/1.1` (or `HTTP_1_1`), `HTTP/2` (or `HTTP_2`)

TOML config looks like

```toml
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
    "1", "{\"platformName\": \"android\", \"appium:platformVersion\": \"10\", \"appium:deviceName\": \"Samsung SM-G988\", \"appium:automationName\": \"uiautomator2\"}"
]
```

For testing it works is mentioned in https://github.com/SeleniumHQ/selenium/issues/13481#issuecomment-2067952128

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

## **Type**
Enhancement

___

## **Description**
- Added support for specifying the HTTP protocol version in Selenium Grid's relay service.
- Introduced new configuration parameters and command-line options to set the desired HTTP protocol version.
- Enhanced the RelaySessionFactory and RelayOptions classes to utilize the specified protocol version when creating HttpClient instances.
- Added comprehensive tests to ensure the new configuration is parsed correctly and handles errors as expected.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RelayFlags.java</strong><dd><code>Add service protocol version configuration in RelayFlags</code>&nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/grid/node/relay/RelayFlags.java

<li>Added a new command-line parameter and configuration value for <br>specifying the HTTP protocol version when communicating with the <br>service status endpoint.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13849/files#diff-0a0863678a201432598493648c4518498979d263ce2ca4546159e3588a1358d5">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RelayOptions.java</strong><dd><code>Implement service protocol version handling in RelayOptions</code></dd></summary>
<hr>
      
java/src/org/openqa/selenium/grid/node/relay/RelayOptions.java

<li>Added method to fetch and validate the service protocol version from <br>configuration.<br> <li> Enhanced <code>isServiceUp</code> method to use the specified protocol version when <br>creating the HttpClient.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13849/files#diff-4b6013b24288d87bdc8afa95f26e8ff2e1e218d7de62dacd40e7d787ec00d6f1">+17/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RelaySessionFactory.java</strong><dd><code>Support protocol version in RelaySessionFactory</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/grid/node/relay/RelaySessionFactory.java

<li>Added handling for the service protocol version in the session factory <br>constructor.<br> <li> Modified <code>isServiceUp</code> method to configure the HttpClient with the <br>specified protocol version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13849/files#diff-8fe345d7ed627b58287d8a4c5d6813fae678894be658c5c87ffc3f9c862f62ab">+10/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RelayOptionsTest.java</strong><dd><code>Add tests for service protocol version parsing in RelayOptions</code></dd></summary>
<hr>
      
java/test/org/openqa/selenium/grid/node/relay/RelayOptionsTest.java

<li>Added tests to verify the correct parsing and handling of the service <br>protocol version.<br> <li> Included tests to ensure proper exception handling for unsupported <br>protocol versions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13849/files#diff-2039d658a7bf893b3bfca1b8624c2e31cc027a28d2299c56edae98e4afb4ec7e">+48/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by VietND96** [comment]
@diemol, can you review this and include it in the 4.20.0 release?

**Review by diemol — COMMENTED** [review]
Thank you, @VietND96!

Can you check the [code suggestions](https://github.com/SeleniumHQ/selenium/pull/13849#issuecomment-2067881306)?

**Comment by VietND96** [comment]
I fixed some points

> Ensure that the serviceProtocolVersion is not null or empty before setting it in the
ClientConfig. This prevents potential issues with client configuration when an invalid or
empty version is used.

[java/src/org/openqa/selenium/grid/node/relay/RelaySessionFactory.java [219]](https://github.com/SeleniumHQ/selenium/pull/13849/files#diff-8fe345d7ed627b58287d8a4c5d6813fae678894be658c5c87ffc3f9c862f62abR219-R219)

This one already guarded in part of constructor, so can ignore `
    this.serviceProtocolVersion =
        Require.nonNull("Service protocol version", serviceProtocolVersion);`

**Review by diemol — APPROVED** [review]
Thank you, @VietND96!

**Pull request merged**
