### PR TITLE
refactor concrete WebDriverException#getSupportUrl's

### PR DESCRIPTION
**Pull request by alb-i986**
extract urls to constants

### CODE REVIEW

**Comment by ddavison** [comment]
I like this change, but i'm not sure I like the access modifier you put on there.  I think it could be handy to have the ability to call `InvalidSelectorException.SUPPORT_URL` from other places as well.  change this to public, unless you have a valid reason for your choice :)

**Comment by ddavison** [comment]
disregard... forgot that there was a getter :)

**Comment by alb-i986** [comment]
BASE_SUPPORT_URL could be split into "http://seleniumhq.org" + "/exceptions" and the first token could be made public, and moved to some other class: other code might need it. E.g. now I see that DefaultSelenium could benefit of that.

**Comment by ddavison** [comment]
I was also thinking initially of an enumeration, but i think that the url's are fine contained in their respective classes

i'll merge soon

**Comment by ddavison** [comment]
committed in 22a21b4f90f08be938d844a5e1496ef406c217fd.  thanks! :+1:

**Pull request closed without merging**
