### PR TITLE
[java] Added a check for intentionally existing loggers

### LINKED ISSUE #14160: [🐛 Bug]: [GRID] logging.properties is ignored when trying to remove stack trace errors from Logs
### What happened?

When using:
-Djava.util.logging.config.file=/opt/logging.properties
which contains:
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tF %1$tT.%1$tL %4$s: %3$s %5$s %n

this works in other Java app that uses java.util.logging for logging, but it has zero effect on Grid Logs.

### How can we reproduce the issue?

```shell
Create logging.properties file with below contents:
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tF %1$tT.%1$tL %4$s: %3$s %5$s %n

start Grid Hub or Node with -Djava.util.logging.config.file=/your_path/logging.properties
```

### Relevant log output

```shell
Expecting to NOT see stack trace in Logs such as these:
10:46:37.229 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: DevToolsActivePort file doesn't exist
Host info: host: 'selenium-grid-4-node-72-2prgt', ip: 'x.x.x.x'
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.71.1.el8_6.x86_64', java.version: '17.0.11'
Driver info: driver.version: unknown
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
                at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:161)
                at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:71)
                at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
                at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:469)
                at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:50)
                at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
                at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
                at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:62)
                at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:87)
                at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
                at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
                at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
                at org.openqa.selenium.grid.node.Node.execute(Node.java:270)
                at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
                at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
                at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
                at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
                at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
                at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
                at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
                at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:842)
```

### Operating System

RH8 and Win10

### Selenium version

4.21.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

4.21.0

### PR DESCRIPTION
**Pull request by JHeflinger**
### Description
A check for the existence of the handlers property in the LogManager is added in the configureLogging() function as to ensure that intentionally existing loggers such as ones defined in the logging.properties file are not overwritten

### Motivation and Context
This is to allow users to use their own loggers and formatting with the grid program.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Fixes #14160

___

### **PR Type**
Bug fix

___

### **Description**
- Added a check in the `configureLogging` method to ensure that existing loggers, such as those defined in the `logging.properties` file, are not overwritten.
- This change allows users to maintain their custom loggers and formatting when using the grid program.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>LoggingOptions.java</strong><dd><code>Add check to preserve existing loggers in LoggingOptions</code>&nbsp; </dd></summary>
<hr>

java/src/org/openqa/selenium/grid/log/LoggingOptions.java

<li>Added a check for existing loggers in <code>configureLogging</code>.<br> <li> Prevents overwriting of loggers defined in <code>logging.properties</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14754/files#diff-df04b67d453fdda127e86957b1cb29596a05a07e711f9081cfa4af5ed7094a1b">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by shbenzer** [comment]
@JHeflinger Thank you for the PR! Before it can be evaluated, please sign the Contributor License Agreement.

**Comment by shbenzer** [comment]
After looking at this PR, could you please add a test to ensure this functionality works as expected.

**Review by diemol — APPROVED** [review]
Thank you, @JHeflinger!

I don't think we need a test for this because the number of people using this is very low. If we get bug reports around this, then I would consider adding a test for this.

**Comment by lprimak** [comment]
Famous last words hehe. 
didn’t take long to find the bug
See #15150

**Pull request merged**
