### PR TITLE
Add chance_click method

### PR DESCRIPTION
**Pull request by tit**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by p0deje** [comment]
wat

**Comment by p0deje** [comment]
Why would you ever want this?

**Comment by Jarob22** [comment]
+1 for why would you ever want this

**Comment by mstankovic86** [comment]
+1 for "WAT"

**Comment by diemol** [comment]
Automated exploratory testing?

**Comment by tit** [comment]
> Automated exploratory testing?
Yes. :)

I apologize for the meager description of the commit.
When you automatically test forms, you often need to click on the optional element. Or do not click.
A small analog of monkey testing.

Previously, for a random click, you had to write your own method:

```ruby
def chance_click
  yield if [true, false].sample
end

chance_click do
  driver.find_element(:tag_name, 'button').click
end
```

I suggest adding this method to the WebUpdate Selenium.

```ruby
driver.find_element(:tag_name, 'button').chance_click
```

example_form

**Comment by Jarob22** [comment]
Hi @tit - generally you don't want randomised testing - you'd create one test scenario where you clicked the button, and one where you didn't, so you'd be able to test both outcomes with certainty.

**Comment by tit** [comment]
@Jarob22, hi!
Do you suppose that random click is too special a case?
And it's not worth adding this feature to the main WebDriver?

**Comment by Jarob22** [comment]
@tit As a general rule, webdriver aims to be a framework to build off, rather than a catch-all for all types of scenarios. I can't speak for whether the dev team will or will not accept a feature, but going back to what I said - you should really be following your own scenarios, eg:

1) When I enter my email, and select the optional checkbox and submit the form, I get output a
2) When I enter my email, and do NOT select optional checkbox and submit the form, I get output b

Rather than randomly clicking it.

**Comment by jimevans** [comment]
I’m -1 on this change for the general-purpose WebDriver language bindings. .NET will not be implementing this.

**Comment by p0deje** [comment]
@tit This should definitely belong to the client code, not Selenium.

Thank you for a pull request, but I agree with Jim on this.

**Pull request closed without merging**
