### PR TITLE
Py safari options

### LINKED ISSUE #10122: [🐛 Bug]: Selenium 4.0 and 4.1 Relative locators are not working properly starting from December 6 2021, but the same worked fine till November end 2021
### What happened?

We are using web based application and working in Chrome browser 96.0.4664.93 version. We implemented Selenium relative locators for the project and the same was working fine till November end 2021 and starting from December 6th 2021, it is not working.

below direction is not working so far, it is not inputting value in the immediate next below input box, instead it is inputting value in the 2nd input box.

Note: tried in both Selenium 4.0 and 4.1

### How can we reproduce the issue?

```shell
.
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.0.0 and Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.93

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 96.0.4664.93

### Are you using Selenium Grid?

no

### LINKED ISSUE #10267: [🚀 Feature]: Add Safari Options to Python
### Feature and motivation

Python is the only language not to have a Safari Options class.

There are only 2 options, and they aren't likely to be used, so low priority, but should be an easy update for someone looking to jump in. Well, except that safari doesn't do `apple:safariOptions` like the other drivers, both of these options are individually namespaced with `safari:` so that might make things complicated in Python potentially

here's what Ruby has:
https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/safari/options.rb

### Usage example

```py
    options = SafariOptions()
    driver = webdriver.Safari(options=options)
```

### PR DESCRIPTION
**Pull request by MWschutte**
### Description

Adds same functionality as the the safari options in the [java repository](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/safari/SafariOptions.java). Enables the user to set safari options:
- Set Safari browser name to technology preview
- Set Automatic Inspection
- Set Automatic Profiling

### Motivation and Context

Python is the only language not to have a Safari Options class.
Closes #10267

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
Thanks for the PR. I have started the github actions and there are some failures (tox mostly). Can you have a look at those please

**Comment by MWschutte** [comment]
> Thanks for the PR. I have started the github actions and there are some failures (tox mostly). Can you have a look at those please

@AutomatedTester thanks for your response. I have fixed the tox failures. I also tried to take a look at why the firefox_tests_remote failed. The `bidi_tests.py` seems to cause a Timeout. However this PR does not involve changes for the firefox code and all the test in the `bidi_test.py` are marked with `xfail_safari`. Furthermore I've noticed this test causing a timeout at other workflows as well.

**Comment by Alraku** [comment]
Hi, does this feature helps with warning that comes up on MacOS while using safari?
The warning says "DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg RemoteWebDriver.__init__("

well now when safari options have been added, how do I get rid of this warning? How do I pass properly the arguments while initialising web driver for safari?

**Comment by titusfortner** [comment]
Yes, should fix it. Use like this:
```
from selenium.webdriver import Safari
from selenium.webdriver.safari.options import Options as SafariOptions

safari_options = SafariOptions()
driver = Safari(options=safari_options)
driver.quit()
```

**Comment by Alraku** [comment]
Actually I've had done that exactly the same before your answer and it hadn't worked.


conftest.py
```
@pytest.fixture(scope='class')
def setup(request, browser, url):
    if browser == "edge":
        driver = webdriver.Edge(service = Service(EdgeChromiumDriverManager().install()))
    elif browser == "chrome":
        driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))
    elif browser == "safari":
        safari_options = SafariOptions()
        driver = webdriver.Safari(
              service = Service(executable_path='/usr/bin/safaridriver'), options=safari_options)

    driver.maximize_window()
    request.cls.driver = driver
    
    yield driver
    driver.quit()
```

```
@pytest.mark.usefixtures("setup", "logger")
class TestSearchbox:

    @pytest.fixture()
    def class_setup(self):
        self.page_home = PageHome(self.driver)
        self.page_login = PageLogin(self.driver)
        self.driver.get(globals.base_url)


    @pytest.mark.order(1)
    @pytest.mark.parametrize("data_search_term, data_location, data_result", testdata_searchbox)
    def test_searchbox_term_one(self, class_setup, data_search_term, data_location, data_result):
        self.page_login.accept_privacy_dialog()
        self.page_home.search_phrase(search_term=data_search_term, location=data_location)
        assert data_result in self.driver.title, "Assertion Failed - Title does not match"
```

Warning still appears.

**Comment by titusfortner** [comment]
Sure enough. The driver sets the value by default, then the superclass throws the warning not to set it.
I don't want to change the default behavior right now, though. We're pulling a bunch of this code out with the existing deprecations in 4.3 and that should fix all of this.

**Pull request merged**
