### PR TITLE
[dotnet] Fix continueResponse method in CDP

### PR DESCRIPTION
**Pull request by nvborisenko**
Looks like this code was wrote by a mistake.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
Is there a test we can add to show it failing/passing?

**Comment by nvborisenko** [comment]
Most likely only for cdp v115 (as the latest, I didn't find tests for others).

**Comment by titusfortner** [comment]
Yes yes, we only test the version that is on the CI...

**Comment by nvborisenko** [comment]
No, it is supposed to be used by https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/NetworkManager.cs which is not even covered by unit tests.

Given that BiDi is our primary goal, I have no motivation to create tests for features nobody is using (or usage of it is blocked by https://github.com/SeleniumHQ/selenium/pull/12431)

**Review by diemol — APPROVED** [review]
Thank you, @nvborisenko!

**Pull request merged**
