### PR TITLE
Remove "shadow_root" assertion in Python bindings for Firefox

### PR DESCRIPTION
**Pull request by whimboo**
The "Get Element ShadowRoot" command has been implemented in Firefox 96 (a year ago) and it should no longer cause an assertion.

### CODE REVIEW

**Comment by whimboo** [comment]
This PR is ready for review. Thanks!

**Comment by whimboo** [comment]
CC'ing @patrickangle and @gsnedders given that the same assertion still exists for Safari and as it looks like there might have been some ongoing work here on experimental.

**Review by diemol — APPROVED** [review]
Thank you, @whimboo!

**Comment by gsnedders** [comment]
> CC'ing @patrickangle and @gsnedders given that the same assertion still exists for Safari and as it looks like there might have been some ongoing work here on experimental.

actually shipped in Safari 16.4 on Tuesday: https://wpt.fyi/results/webdriver/tests/get_element_shadow_root/get.py?run_id=5118756219518976&run_id=6320265787604992&run_id=6292883592708096

**Pull request merged**
