### PR TITLE
Add encoding=utf-8 to add_on's open(install.rdf) line.

### PR DESCRIPTION
**Pull request by DArtagan**
When running Selenium on windows, and installing an add-on to firefox, it chokes on this particular line:

```
File "C:\Python34\lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 343, in _addon_details
    manifest = f.read()
File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 990: character maps to <undefined>
```

Specifying an encoding at the open line seems to resolve this.
CLA signed.

### CODE REVIEW

**Comment by DArtagan** [comment]
May resolve issue #527.

**Comment by ddavison** [comment]
LGTM :+1: .  Travis error looks irrelevant to this change

**Comment by lukeis** [comment]
This doesn't work on python 2.7 with firefox, I get:

>               with open(os.path.join(addon_path, 'install.rdf'), 'r', encoding='utf-8') as f:
E               TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by mfalesni** [comment]
@DArtagan In python2, you have to use `codecs.open` in order to specify the encodiing of the file. The `codecs.open` is basically equivalent to python3's built-in `open`. `codecs` is also present in python3 so that might be the common place to start ...

**Comment by DArtagan** [comment]
Yeah, I've begun to better educate myself on encodings. Hopefully I'll have the time soon to produce a proper fix.

**Comment by Dude-X** [comment]
@DArtagan A simpler fix is to import codecs and use codecs open. This would work in Python 2 and 3.

**Comment by lmtierney** [comment]
@DArtagan are you still planning on fixing this?

**Comment by DArtagan** [comment]
@lmtierney, honestly I had forgotten about this - thank you for the prompt.  

Today I fired up my development environment to start on this, however I learned something along the way.  Firefox has gone the way of "WebExtensions" and has deprecated and removed XUL-style extensions, making ```install.rdf``` obsolete.  The ```add_extension``` code will probably need to be thrown out and re-written.  I am going to close this PR, with deference to #4093.

**Pull request closed without merging**
