### PR TITLE
Update remote_connection.py

### PR DESCRIPTION
**Pull request by rohitanand1614**
Suggesting this change as when we try to run scripts on remote platform like browserstack and sauce labs, the urllib3 is throwing an error urllib3.exceptions.MaxRetryError: HTTPConnectionPool, this can be avoided if we set this value. the error was not coming until the urllib3==1.24.3. But post that urllib3 made certificate default.  There have been multiple communication chains regarding this issue. I could only fix this issue by explicity setting this value to none in the library stack.   In case you feel like not approving the change please do share the suggested fix to handle this issue as i could not find any.

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rohitanand1614** [comment]
Please review and take action accordingly

**Comment by AutomatedTester** [comment]
Thank you for this PR but I don't understand fully why this is needed, what scenarios create this situation or why we are setting a default to something very different.

Please can you explain it further and when you said there are 
> There have been multiple communication chains regarding this issue.

Where are these?

**Comment by symonk** [comment]
Could you share any of the communication threads here so I can catch up on it please?  as of urllib3 `1.25` https connections are verified by default using `CERT_REQUIRED`

**Comment by symonk** [comment]
will take a look at the ssl contexts / what is happening under the hood here when I get back from PTO

**Comment by titusfortner** [comment]
Thank you for submitting this PR, but we need a reproducible bug report to understand the underlying problem and if this is the preferred fix.

**Pull request closed without merging**
