### PR TITLE
Remove uncalled code (base generator amongst others)

### PR DESCRIPTION
**Pull request by luke-hill**
Remove / tag / move code in files.rb - Most of this can be deleted or moved once another PR is merged in

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by luke-hill** [comment]
I'll add 1/2 more commits to this @p0deje once the other PR's have been merged in

**Comment by luke-hill** [comment]
The 2nd portion of removals was concerned with a piece of code that called `Platform.file_for`

However this has been removed and is no longer in use. So each of these instances could not be being called. And after commenting them out, they didn't crash the system. So I managed to delete a couple of hundred LOC. :boom: 

If I can get some eyes from one of @barancev / @shs96c then this is RtM

**Comment by p0deje** [comment]
As far as I can see Python tasks are now failing on Travis. Can you take a look?

**Comment by luke-hill** [comment]
OOOOoooooh dear. Oki, It was to be expected removing more and more code eventually I'd ping something.

I'm back now from a short break. Will take a look in the next day or so.

**Comment by luke-hill** [comment]
So this was oddly caused by the Rakefile requiring the same file twice (Maybe I did this, maybe not), but either way removing the offending line now fixes the things up (So wasn't a big fix)

This is now ready for review / merge.

Primarily this removes code from 2 places.
- Places in which code was calling a broken method (This has been broken by me, through refactoring, but shows they should have been removed alongside them, they were originally deeply nested inside JS crazy_fun objects.
- Places which called `Export::` cf tasks. These had no caller. And as such a large chunk of code has been :boom: from here.

There is plenty more areas like this which have large segments, and I've seen patterns, so future PR's will remove much larger chunks :wine_glass:

**Comment by luke-hill** [comment]
ping @barancev / @p0deje

**Pull request merged**
