### PR TITLE
[rb] Waiting till Socket connection completed

### PR DESCRIPTION
**Pull request by N0xFF**
After `select` we should use `getsockopt` to read the SO_ERROR option at
level SOL_SOCKET to determine that connection completed successfully. Otherwise in `connect_nonblock` we can get EISCONN error.

http://man7.org/linux/man-pages/man2/connect.2.html

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/6909)

### CODE REVIEW

**Comment by N0xFF** [comment]
This is reason why I all time get error
```
Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
```
and can't run Ruby on Rails system tests on WSL.

**Comment by twalpole** [comment]
While I believe this PR is technically more correct, I fail to see how it fixes any Errno::ECONNREFUSED issue you're having?

**Comment by N0xFF** [comment]
https://github.com/SeleniumHQ/selenium/blob/361c73109627351291505e4453debb300a225748/rb/lib/selenium/webdriver/common/socket_poller.rb#L79-L82
`Errno::EINPROGRESS` error means that connection in progress and we need to check status to make a decision. We check that socked is writable via `IO.select` and retry connection. But connection is not ready and next we got `Errno::EALREADY` error.

She was caught by
https://github.com/SeleniumHQ/selenium/blob/361c73109627351291505e4453debb300a225748/rb/lib/selenium/webdriver/common/socket_poller.rb#L84-L89
So `listening?` returns `true`. That allow commands by webdriver. But connection still not ready and finally we got `Errno::ECONNREFUSED`.

**Comment by N0xFF** [comment]
Now we check `conn_completed?` otherwise raise `Errno::ECONNREFUSED`. 
So `listening?` returns `false` and `listening?` is retry with new connection in `with_timeout` block.
https://github.com/SeleniumHQ/selenium/blob/361c73109627351291505e4453debb300a225748/rb/lib/selenium/webdriver/common/socket_poller.rb#L38-L40

**Comment by twalpole** [comment]
Ok - makes sense -- do you have time to fix the conflicts here so it's mergeable?

**Comment by N0xFF** [comment]
Done. But after merge I found other problem https://github.com/SeleniumHQ/selenium/pull/7010

**Comment by twalpole** [comment]
Thanks.

**Pull request merged**
