### PR TITLE
Update HtmlUnit and HtmlUnitDriver to 2.26

### PR DESCRIPTION
**Pull request by asashour**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Also, please note that many tests seem to miss `@JavascriptEnabled`, I guess this annotation is relevant to only HtmlUnit.

I would later create a PR later to remove it.

### CODE REVIEW

**Comment by barancev** [comment]
Would you please rebase this PR to master HEAD? I've already upgraded apache httpclient in the trunk.

**Comment by barancev** [comment]
And I've changed @Ignore and @NotYetImplemeted annotations to be Repeatable.

**Comment by asashour** [comment]
Rebased, thanks.

**Comment by barancev** [comment]
Merged as d0631857157a567df5708fabad0e2cb01bd32923

**Pull request closed without merging**
