### PR TITLE
Fix FluentWait so it completes in more cases.

### LINKED ISSUE #7494: FluentWait might never complete
## 🐛 Bug Report

When `Function` passed to `until` never returns then FluentWait never completes.

## To Reproduce
1. Set a timeout value (e.g.: 1 second), 
2. Pass in a function to until that takes more time then timeout value set in previous step (e.g.: 2 sec).

## Expected behavior

`FluentWait` throws timeout exception after timeout value set for it has passed.

## Test script or set of commands reproducing this issue

```
        long start = System.currentTimeMillis();
        String actual = new FluentWait<>(driver)
                .withTimeout(ofSeconds(1))
                .pollingEvery(ofMillis(450))
                .withMessage("I got bored waiting for this function to complete")
                .until($ -> {
                    try {
                        SECONDS.sleep(5);
                        return "I'm done";
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                });

        long end = System.currentTimeMillis();
        assert end - start < 2000;
```

### PR DESCRIPTION
**Pull request by utamas**
FluentWait could potentially never complete when the condition
passed to it made no progress (either because it fall into an
infinite loop or waiting for a resource or response over
network).

Fixes #7494

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by utamas** [comment]
@barancev Could you please review this PR?

**Comment by utamas** [comment]
@barancev : could you please give an insight on how PRs get accepted? I can imagine that you guys are extremely busy and 20 days is not the end of the world to wait for a PR to be reviewed. It's just killing my excitement to try to do any further contribution not to know what to expect and when.

**Comment by shs96c** [comment]
I appreciate this is not the best experience with the project. We really are very grateful for the PR. Right now, there are two people active in the java tree: @barancev and @shs96c (me!), and both of us are a little overwhelmed. Thank you for your patience, and the nudge to get things going.

The review process is a little ad-hoc, but I'll speak for myself. I try and scan the backlog of PRs when I get a chance (which, I'll be honest, hasn't been often recently). If I can review it quickly, and merge it, I'll do that. If the PR requires a longer review, I tend to set it aside for a time when I have enough time to do a proper job. A gentle nudge on the Slack channel is a great way to get one of us to focus on your PR if we're being super-slow.

Yes, I know that this isn't the best way to run a project, but I'm generally working on Selenium in my free time, and there's not been a lot of that lately. :(

**Comment by utamas** [comment]
Thank you @shs96c for the insight and for your work on this project.

**Comment by utamas** [comment]
I'll try to resolve the test failures

**Comment by barancev** [comment]
Merged as 51de5363808d6ee3c5c93cc5f36f91e17aed4ceb, thank you!

**Comment by barancev** [comment]
Sorry to say this, but we decided to return back to the legacy (blocking) implementation after clients complains. It appears that many people use suboptimal approach to manage WebDriver instances using TreadLocal variables. And running conditions in a separate thread makes them lost their driver. So we decided to revert this change in favour of backward compatibility.

People who want to use FluentWait for potentially blocking conditions should create an alternative class that uses a sort of ExecutorService, and this PR can be used as a draft for this new class.

**Pull request closed without merging**
