### PR TITLE
Throw specific exception when port is already in use

### PR DESCRIPTION
**Pull request by asolntsev**
### Description
This PR provides a fix for issues #9972 and #10066

NB! This PR will also solves some of **Selenium own flaky tests**, for example [caused by "BindException: Address already in use"](https://github.com/asolntsev/selenium/runs/4412949195?check_suite_focus=true).

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asolntsev** [comment]
@diemol This PR will solves Selenium own flaky tests. Would be great to merge it.

**Comment by diemol** [comment]
I was trying this approach but it does not solve the problem, because the `NettyAppServer` is used in several places. Retrying here is not enough. We need to rethink how the server can be started for during tests.

**Comment by asolntsev** [comment]
@diemol Yes, it's not a universal approach, and it cannot be (as much as I understand). 
I only added re-try to the test that I saw failing multiple times. 

But the most important is that this PR allows me (and other users) to add try-catch **to their tests**. This is what I really need.

**Comment by diemol** [comment]
I ended up merging #10170, which retries for all cases when the exception is thrown. Thank you for the thought process.

**Pull request closed without merging**
