### PR TITLE
[build] Re-enabling browser-actions/setup-geckodriver@latest

### PR DESCRIPTION
**Pull request by whimboo**
### Description
[mozilla/geckodriver#2009](https://github.com/mozilla/geckodriver/issues/2009) got fixed a while ago and getting the latest geckodriver binary is working again.

### CODE REVIEW

**Comment by whimboo** [comment]
@titusfortner or @diemol could you please review? Thanks

**Comment by titusfortner** [comment]
Ruby & Python weren't even using this so I added it. Let me make sure it runs for everything.

**Comment by whimboo** [comment]
> Ruby & Python weren't even using this so I added it. Let me make sure it runs for everything.

I just noticed that myself for my investigation on #11025. Thanks for getting these added!

**Comment by titusfortner** [comment]
We've got a really cool filter to only run builds when changes are made... except it then becomes difficult to force the builds to be run. I've pushed this branch to selenium/latest_geckodriver and am forcing runs just to make sure we have everything.

**Comment by titusfortner** [comment]
Verified this works, thanks!

**Pull request merged**
