### PR TITLE
[py] fixed safari tests

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Fixed Select class and Launcher tests for Safari.

### Motivation and Context
- Chrome raises `NotImplementedError` while trying to select item from a list box which is disabled. But Safari doesn't. I have marked all those tests as `xfail_safari`.
- Fixed Safari launcher test by passing `service` object to `WebDriver`
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
What is raising `NotImplemented` errors? I'm wondering if that is the right behavior.

**Comment by sandeepsuryaprasad** [comment]
@titusfortner , when we try to operate on a list box which is disabled, in chrome below exception is raised.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/select.py", line 98, in select_by_index
    self._set_selected(opt)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/select.py", line 213, in _set_selected
    raise NotImplementedError("You may not select a disabled option")
NotImplementedError: You may not select a disabled option
```
In case of Safari, no exception is raised, program execution completes without any exceptions or any messages. But yes, since the list box is disabled nothing gets selected. I think it is better to raise `ElementNotInteractableException` instead of `NotImplementedError`

**Comment by titusfortner** [comment]
Oh, support classes are special, but we should know why it isn't getting that error before just skipping the tests

**Comment by sandeepsuryaprasad** [comment]
My understanding is that the error should be raised by safaridriver itself and nothing to do with python bindings.

**Comment by titusfortner** [comment]
These tests are all about describing intended vs actual behavior. The xfail message needs to reflect how actual behavior differs from intended.

This is the support module where we are working with opinionated behavior. The opinion we are enforcing is that if the user wants to select a disabled option with the Select class, it should throw an error instead of ignoring it. So we check the status and throw the error in the bindings.

Is Safari reporting that the element is not disabled when it is? Why isn't it getting the error that we want it to have?

**Comment by sandeepsuryaprasad** [comment]
I was debugging this issue, and found that in function `_set_selected` in `select.py`,
```
    def _set_selected(self, option) -> None:
        if not option.is_selected():
            if not option.is_enabled():
                raise NotImplementedError("You may not select a disabled option")
            option.click()
```
`option.is_enabled()` returns `True` (Incorrect)for Safari and `False` for Chrome (Correct). So that's the reason why `NotImplementedError` is raised in case of Chrome and not in Safari

**Comment by titusfortner** [comment]
So that needs to be the message in xfail, "options incorrectly reported as enabled"

**Comment by sandeepsuryaprasad** [comment]
Yes, I have changed it and pushed commit.

**Pull request merged**
