### PR TITLE
Fixes #734

### LINKED ISSUE #734: Python Selenium doesn't load firebug extension (firefox)
Hi,

  The Python-Selenium doesn't load firebug extension of Firefox, which happen in the Firebug versions superior the 2.0.7. This doesn't happen in the Firebug 1.XX.XX versions, I think that the problem is file format changed.

**Firebug 1.XX.XX version**
```
fike@kamino:~/d/annabe/annabe$ file firebug-1.13.0a10.xpi 
firebug-1.13.0a10.xpi: Zip archive data, at least v1.0 to extract
```

**Firebug 2.XX.XX version**
```
fike@kamino:~/d/annabe/annabe$ file firebug-2.0.11-fx.xpi 
firebug-2.0.11-fx.xpi: Zip archive data, at least v2.0 to extract
```

Below a example code, it's same  of [Python-Selenium FAQ](https://selenium-python.readthedocs.org/faq.html#how-to-use-firebug-with-firefox).

 Code example:
```python
Python 2.7.10 (default, Jul  1 2015, 10:54:53) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> 
>>> fp = webdriver.FirefoxProfile()
>>> 
>>> fp.add_extension(extension='firebug-2.0.11-fx.xpi')
Traceback (most recent call last):
  File "/usr/local/bin/firefox_navigate.py", line 19, in <module>
    fp.add_extension(extension='firebug-2.0.11-fx.xpi');
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 93, in add_extension
    self._install_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 264, in _install_extension
    with open(os.path.join(tmpdir, name), 'wb') as f:
IOError: [Errno 21] Is a directory: '/tmp/tmpjH9lmE.firebug-2.0.11-fx.xpi/content/firebug/'
```

Thanks,
Fernando Ike

### PR DESCRIPTION
**Pull request by marcotcr**
Problem was a small logic error that caused the code to try to open a directory as a file.
I've signed the CLA.
I accidentally  requested a pull request on my own fork, which is why I have two commits instead of one.

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the CLA?  see CONTRIBUTING.md

**Comment by lukeis** [comment]
@ddavison "I've signed the CLA."  ;)

**Comment by lukeis** [comment]
merged as 8bf1c714368b13ba47314d803cee94ef29124494

**Comment by lukeis** [comment]
thanks for the patch!

**Pull request closed without merging**
