### PR TITLE
[dotnet] Make cdp domains with lazy initialization

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
- Just make CDP domains as lazy objects
- Avoid creation an unnecessary Task when calling event handlers

### Motivation and Context
Each time, when browser makes a request, client side creates new cdp domain object. Let's initialize it once and reuse.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
@nvborisenko these have test failures, can you verify?

**Comment by nvborisenko** [comment]
Reproduced it locally - if we execute the following tests in shared driver:
1. TestCanInterceptNetworkCalls
2. InitializedWebDriverDoesNotThrowException
Then we get `TimeoutException`.

I should investigate what is a reason. This scenario is not reproducible in `trunk`. Thanks for pointing me.

**Comment by nvborisenko** [comment]
I fixed it, but this [fix](https://github.com/SeleniumHQ/selenium/pull/12708/commits/9296a3901b9ae91f2a2e8ee7706066fb3db308f8) looks strange. I don't believe this is true fix. @titusfortner I wonder if other bindings do the same when stopping network monitoring.

Please re-run CI.

**Comment by titusfortner** [comment]
@pujagani I'm still clueless about the bidi implementations. I think the .NET approach is very different from the Java approach, but do you know the answer to this one?

**Comment by nvborisenko** [comment]
Fully ignore this PR for now, I converted it to draft.

**Comment by nvborisenko** [comment]
Closing it, I don't want to break something what is working even if I could not understand how.

**Pull request closed without merging**
