### PR TITLE
Proxy support for NodeJS client

### PR DESCRIPTION
**Pull request by elifa**
Proxy support for the NodeJS webdriver.http.Client.

### CODE REVIEW

**Comment by andreastt** [comment]
@elifa, do you have time to follow up on this?

**Comment by elifa** [comment]
Thanks for the reminder @andreastt , been a bit busy but I've fixed the comments above.
@jleyba , yes i have signed the CLA.

**Comment by jleyba** [comment]
Please squash you commits

**Comment by elifa** [comment]
@jleyba, ok done.

**Comment by jleyba** [comment]
One of the included tests fails (tested node 0.10.36 and 0.12.0):

    $ mocha test/http/http_test.js 
    child_process: customFds option is deprecated, use stdio instead.
    Running tests against [firefox]

      ․․․․․

      4 passing (93ms)
      1 failing

      1) HttpClient proxies requests through the webdriver proxy on redirect:

          + expected - actual

          +127.0.0.1
          -another.server.com
          
          at /Users/jleyba/Development/selenium2/javascript/node/selenium-webdriver/test/http/http_test.js:122:18
          at promise.ControlFlow.runInFrame_ (/Users/jleyba/Development/selenium2/javascript/webdriver/promise.js:1877:20)
          at promise.Callback_.goog.defineClass.notify (/Users/jleyba/Development/selenium2/javascript/webdriver/promise.js:2464:25)
          at promise.Promise.notify_ (/Users/jleyba/Development/selenium2/javascript/webdriver/promise.js:563:12)
          at Array.forEach (native)
          at Object.goog.array.forEach (/Users/jleyba/Development/selenium2/third_party/closure/goog/array/array.js:203:43)
          at promise.Promise.notifyAll_ (/Users/jleyba/Development/selenium2/javascript/webdriver/promise.js:552:16)
          at goog.async.run.processWorkQueue (/Users/jleyba/Development/selenium2/third_party/closure/goog/async/run.js:125:21)
          at runMicrotasksCallback (node.js:337:7)
          at process._tickCallback (node.js:355:11)
      From: Task: HttpClient proxies requests through the webdriver proxy on redirect
          at Context.ret (/Users/jleyba/Development/selenium2/javascript/node/selenium-webdriver/testing/index.js:126:10)
          at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:194:15)
          at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:372:10)
          at /usr/local/lib/node_modules/mocha/lib/runner.js:448:12
          at next (/usr/local/lib/node_modules/mocha/lib/runner.js:297:14)
          at /usr/local/lib/node_modules/mocha/lib/runner.js:307:7
          at next (/usr/local/lib/node_modules/mocha/lib/runner.js:245:23)
          at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:274:5)
          at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by elifa** [comment]
@jleyba, sorry about that. I have fixed the failing test now.

**Comment by jleyba** [comment]
Merged in ef8112f

**Pull request closed without merging**
