### PR TITLE
[rust] Select release with artifact when filtering Edge response

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
This PR makes the filtering process used by Selenium Manager more robust in discovering the proper Edge release to download.

### Motivation and Context
It seems the responses provided by the [Edge products API](https://edgeupdates.microsoft.com/api/products/) has recently changed, since now, it can provide releases with empty artifacts. As a result, Selenium Manager fails discovering Edge, as it happens in some tests (e.g. [here](https://github.com/SeleniumHQ/selenium/actions/runs/8420832610/job/23056676931?pr=13725#step:16:1981)). This PR should prevent that.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

___

## **Type**
Bug fix

___

## **Description**
- Filters out Edge releases without artifacts to ensure proper discovery of Edge releases.
- Fixes an issue where Selenium Manager could fail to discover Edge due to releases with empty artifacts.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>edge.rs</strong><dd><code>Improve Edge Release Filtering in Selenium Manager</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
rust/src/edge.rs

<li>Filters Edge releases to only consider those with non-empty artifacts.<br> <li> Returns an unavailable discovery result if no releases with artifacts <br>are found.<br> <li> Ensures that the selected release has at least one artifact.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13735/files#diff-dcd62c3bd133281f5bd97d8a876bcf753d7a4f3edd6ccbacf44eff3e9fcc484e">+9/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by diemol** [comment]
I think we need to merge this anyway because I see failures in `trunk`.

**Comment by bonigarcia** [comment]
Yes, this needs to be merged. I'm doing it.

**Comment by diemol** [comment]
macOS tests are still failing... I wonder if the paths have changed?

**Comment by diemol** [comment]
However, they are all passing locally for me.

**Comment by bonigarcia** [comment]
> However, they are all passing locally for me.

Same here. I will investigate why it is failing in GHA.

**Pull request merged**
