### PR TITLE
[py] Fix type hints and docstring

### PR DESCRIPTION
**Pull request by M1troll**
Hello!

### Description

I found that `get_attribute` method in `webelement` in docstring says that method can return `None`, but type hint is only as a string. I ran into an unexpected error calling a string method on an NoneType-object.

I also saw that docstring in `location_once_scrolled_into_view` property of `webelement` contains an incorrect description of value returned when element is not visible.

### Motivation and Context

This will help you avoid unexpected errors that may be caught by typecheckers (e.g. `mypy`).

### Reproduce
You need install `selenium` and `mypy`:
```bash
pip install selenium mypy
``` 

Code example:
```python
from selenium import webdriver
from selenium.webdriver.common.by import By

URL = "https://www.w3schools.com/css/tryit.asp?filename=trycss_display_none"

driver = webdriver.Chrome('/usr/sbin/chromedriver')
driver.get(URL)
driver.find_element(By.ID, "accept-choices").click()

hidden_element = driver.find_element(By.CLASS_NAME, "hidden")
hidden_element.get_attribute("class").strip()
```
Now if we run `mypy .` we won't see any errors:
image

But after fixing type hint, mypy will give us an error:
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
>I also saw that docstring in location_once_scrolled_into_view property of webelement contains an incorrect description of value returned when element is not visible.

Was this with Chrome and Firefox?

**Comment by M1troll** [comment]
Yes, I checked it in Chrome and Firefox
If element is not visible method returns `{"x": 0, "y": 0}`, not `None`

**Review by diemol — APPROVED** [review]
Thank you, @M1troll!

**Comment by diemol** [comment]
Seems the linter is failing?

**Comment by M1troll** [comment]
You're right, but locally all linters run successfully, strange..
Can we rerun this check? 
image

**Comment by diemol** [comment]
Not sure what the difference is, but the command used is `TOXENV=linting-check tox -c py/tox.ini`

**Comment by M1troll** [comment]
With this command everything passing too 🥲

 image

**Comment by diemol** [comment]
I can see the same error, I started an environment in GitPod: 

- https://gitpod.io/#https://github.com/SeleniumHQ/selenium/pull/12067
- Opened a terminal and did `pip install tox==2.4.1`
- Executed `TOXENV=linting-check tox -c py/tox.ini`


I also checked out the PR locally and got the same:

image

**Comment by M1troll** [comment]
@diemol
It looks like I found reason for the fall of linters - `docformatter` moved part of docstring to line above.
Can you approval workflow to run actions?

**Comment by M1troll** [comment]
@diemol
Linters have been passed 🎉

**Review by diemol — APPROVED** [review]
Thank you, @M1troll!

**Pull request merged**
