### PR TITLE
Delete deprecated FindsBy* interfaces

### LINKED ISSUE #8175: [Java] Delete deprecated FindsBy* interfaces
## 🚀 Feature Proposal

As the issue title says

## Motivation

...

## Example

...

### PR DESCRIPTION
**Pull request by bongosway**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Delete deprecated FindsBy* interfaces

### Motivation and Context

Fixes #8175

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
 
### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bongosway** [comment]
`TestUtilities.java` has a test referencing HtmlUnit Driver, which cause the test to fail. 
I have raised issue here https://github.com/SeleniumHQ/htmlunit-driver/issues/89

**Comment by barancev** [comment]
Looks like an improved copy of my experimental branch killing_FindByXXX:
https://github.com/SeleniumHQ/selenium/commit/0dc3abcaa1004603c35794e3478c5b1235833b17

The decision is not made yet if we're going to merge this branch. Yes, we're going to remove FindByXXX classes, but the implementation is not choosen yet.

**Comment by bongosway** [comment]
> Looks like an improved copy of my experimental branch killing_FindByXXX:
> [0dc3abc](https://github.com/SeleniumHQ/selenium/commit/0dc3abcaa1004603c35794e3478c5b1235833b17)
> 
> The decision is not made yet if we're going to merge this branch. Yes, we're going to remove FindByXXX classes, but the implementation is not choosen yet.

Yes. you are correct. it is an improved copy and I referenced it in the original ticket. 
Sure no worries if decision is not reached yet or if you need to close this PR.

**Comment by shs96c** [comment]
I suggest we merge this. It moves us forward, deletes the original interfaces, and appears to leave the original semantics in place.

**Comment by shs96c** [comment]
Thank you @bongosway!

**Comment by bongosway** [comment]
> Thank you @bongosway!
👍 
Thank you too for cleaning up. Truly appreciate your support.

**Pull request merged**
