### PR TITLE
Add missing word in python readme

### PR DESCRIPTION
**Pull request by ghost**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by lukeis** [comment]
The file is also duplicated here:
https://github.com/SeleniumHQ/selenium/blob/master/py/docs/source/index.rst

Mind updating there too :)

**Comment by fbergin** [comment]
Here you go!

**Comment by lukeis** [comment]
thanks!

**Comment by fbergin** [comment]
Thank you!

**Pull request merged**
