### PR TITLE
Removed unnecessary modifier

### PR DESCRIPTION
**Pull request by ghost**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by ddavison** [comment]
you may want to fix your

`$ git config --global user.name <first last>`

and

`$ git config --global user.email <email>`

I think i'm going to ask that you put those in because right now, you signed the CLA as Tomasz C, but your username is "Programming UP"  😃

**Comment by tomaszczerminski** [comment]
@ddavison Done :)

**Comment by ddavison** [comment]
@tomaszczerminski bump

**Comment by lukeis** [comment]
closing.. PR needs rebasing and fixing up of commits, but is only cosmetic in code style.

If this gets fixed up, please open a new pull request

**Pull request closed without merging**
