### PR TITLE
Conform to the api of urllib2 for adding header for a request

### PR DESCRIPTION
**Pull request by clubfest**
urllib2 capitalize the header key and relies on this capitalization to decide if the 'Content-type' field is filled in and if not, fill it in with the default of 'application/x-www-form-urlencoded'. A recent change causes the header in the request named 'Content-type' to change to 'Content-Type' and urllib2 assumes the 'Content-type' field in the request header is not filled in, so tests are using the default instead and are giving the error:
<class 'selenium.common.exceptions.WebDriverException'>: Message: Given content type 'application/x-www-form-urlencoded' is not 'application/json;charset=UTF-8'.

- [X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by Dude-X** [comment]
@clubfest This is pretty good. Have you tested this under Python 2 and Python 3?

**Comment by clubfest** [comment]
It works for the webdriver tests that I have in Python 2 that were failing with the error.

**Comment by Dude-X** [comment]
@clubfest would it be any trouble to test this change with Python 3 (3.5+)? You can create a virtual environment and just write a short script to confirm.

**Comment by davehunt** [comment]
Could you also provide a test in https://github.com/SeleniumHQ/selenium/blob/master/py/test/unit/selenium/webdriver/remote/test_remote_connection.py so we don't regress again? You can then run this test against Python 2/3 using Tox as detailed here: https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings#tests

**Comment by clubfest** [comment]
It's a bit difficult to add a test for this currently, unless I create an independent function that returns the request from line 495
https://github.com/clubfest/selenium/blob/cbf367b5506ad02354eb004ef7cc86fa7e5a0352/py/selenium/webdriver/remote/remote_connection.py#L495

Or is it sufficient to add a comment to say that the request header must be modified with add_header instead of modifying the headers field?

**Comment by clubfest** [comment]
I am a bit confused. Many of the tests that failed are in ruby, but the change is only for python. Is there a way to re-run the continuous integration?

**Comment by lmtierney** [comment]
@clubfest ignore the ruby test failures

**Comment by clubfest** [comment]
I am unable to run tests locally with tox. Am I missing some additional setup?
$ tox -e py27-unit

logs:
...
    error: can't copy 'selenium/webdriver/firefox/x86/x_ignore_nofocus.so': doesn't exist or not a regular file
    Running setup.py install for selenium: finished with status 'error'
...

**Comment by lmtierney** [comment]
Yes, to get that file you need to follow [the instructions here](https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings#development)

Specifically `./go py_prep_for_install_release`

**Comment by clubfest** [comment]
I ran `./go py_prep_for_install_release`, and then encounter another error: 
   Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-QOi0I0-build/setup.py", line 35, in <module>
        'long_description': open(join(abspath(dirname(__file__)), "README.rst")).read(),
    IOError: [Errno 2] No such file or directory: '/tmp/pip-QOi0I0-build/README.rst'

$ ls /tmp/pip-QOi0I0-build/
CHANGES      pip-delete-this-directory.txt  PKG-INFO  selenium.egg-info  setup.py
MANIFEST.in  pip-egg-info                   selenium  setup.cfg

**Comment by clubfest** [comment]
Never mind. Just upgraded via `pip install -U setuptools pip`.

**Comment by clubfest** [comment]
For the remaining failures, I don't think they are related to my changes. Please take a look, thanks!

**Comment by davehunt** [comment]
Thanks!

**Pull request merged**
