### PR TITLE
Upgrade HtmlUnit to 2.17

### PR DESCRIPTION
**Pull request by asashour**
Upgrade HtmlUnit to 2.17 and fixing tests

The default simulated FIREFOX version is now 38.
TypingTest.testShouldBeAbleToTypeOnANumberInputField is @Ignored with HtmlUnit (for now)

### CODE REVIEW

**Comment by lukeis** [comment]
can you also update the maven pom files:

https://github.com/SeleniumHQ/selenium/blob/master/maven/htmlunit-driver/pom.xml#L23
https://github.com/SeleniumHQ/selenium/blob/master/maven/pom.xml#L153

(not sure if I missed any of the other dependencies you updated)

**Comment by lukeis** [comment]
you can always force push to your branch to update this PR.

Also if you could squash the commits, it would be appreciated.

**Comment by asashour** [comment]
Updated squashed, which I learnt just now, thanks ;)

BTW, it is noticed that:
  - .xml files are not handled uniformly, e.g. maven/pom.xml and maven/htmlunit-driver/pom.xml, one in UNIX and the other in Windows. I guess all the project should be in system format (e.g. "*.xml text" in .gitattributes).
  - maven dependencies are not up to date, e.g. junit 4.12

**Comment by lukeis** [comment]
merged as 6ca78c5c6124b857305a94d9e2bbc79afdbbb43d

**Pull request closed without merging**
