### PR TITLE
Use `nameof()` for refactoring safety (C# / .NET)

### PR DESCRIPTION
**Pull request by thomhurst**
### Description
Use the `nameof()` language/compiler feature, which provides a safety net, ensuring messages/exceptions always contain the correct parameter name in the case of a variable being renamed.

### Motivation and Context
A safety net, meaning parameters stay correctly named in messages in future refactors.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jimevans** [comment]
@thomhurst Looks like a fine(-ish) thing to do. Happy to give this a merge, once you've signed [the CLA](https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=9958).

**Comment by thomhurst** [comment]
@jimevans I think it's bugged.
image

**Comment by diemol** [comment]
> @jimevans I think it's bugged. image

Yeah, somehow the assitant is not reporting the correct status. I checked and the CLA is signed
image

**Review by jimevans — APPROVED** [review]
LGTM.

**Comment by jimevans** [comment]
Thanks for your contribution!

**Pull request merged**
