### PR TITLE
 Add .NET bindings for WiniumDriver

### PR DESCRIPTION
**Pull request by tkurnosova**
WiniumDriver [https://github.com/2gis/Winium] is Selenium-based tools for testing of Windows apps.
This patch includes .NET bindings for WiniumDriver.

Signed-off-by: Tatyana Kurnosova tgkurnosova@gmail.com

### CODE REVIEW

**Comment by jimevans** [comment]
Much like there are no Appium classes included in the Selenium project's .NET bindings, likewise, there should not be Winium classes included here as well. This sounds like code that should live in a companion project to Selenium (maybe the Winium project?), not in the Selenium project itself.

**Comment by TikhomirovSergey** [comment]
@tkurnosova 
Maybe it makes sense to collaborate with the Appium. We've thought about WindowsMobile automation :)

**Comment by tkurnosova** [comment]
When writing tests we use bindings selenium (OpenQA.Selenium for .net). This request allows to create instance of the driver not only as RemoteWebDriver.

**Comment by jimevans** [comment]
And that's what I'm saying doesn't belong in the core Selenium bindings, anymore than an AppiumDriver belongs in the core Selenium .NET bindings.

**Comment by tkurnosova** [comment]
Unfortunately, that's true. Thanks!

**Comment by NickAb** [comment]
@TikhomirovSergey we are already working on establishing contact on this issue.

**Pull request closed without merging**
