### PR TITLE
Update remote_connection.py

### PR DESCRIPTION
**Pull request by jkohls**
If the connection is going to use https then don't modify the URL to use an IP address. Keep that sucker a hostname.

### CODE REVIEW

**Comment by lukeis** [comment]
i take it this is a fix for #420 ?

**Comment by lukeis** [comment]
also can you confirm you've signed the [cla](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)

**Comment by jkohls** [comment]
Fix for #420. Just signed the cla.

**Comment by llaskin** [comment]
@lukeis can this still be merged?

**Comment by titusfortner** [comment]
Replaced by #3179. If anything different needs to be done, please discuss it there, or rebase this code better than I did and we can re-open.

**Pull request closed without merging**
