### PR TITLE
[py]: #11093 - The SessionId shouldn't be added to params themself bu…

### PR DESCRIPTION
**Pull request by tvataire**
…t to a copy of them.

### Description
The Webdriver.execute() method shouldn't add the SessionId to its params themself but to a copy of them.
This avoid the SessionId to be preserved in the PrintOptions instance.

### Motivation and Context
If the session id is stored inside the PrintOptions instance, a selenium.common.exceptions.InvalidSessionIdException is raised when the PrintOptions instance is reused in a subsequent session.

### Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
ah, nice solution. Can you add a unit test?

**Comment by tvataire** [comment]
Hi
An unit test is ready but I couldn't find the way to run the tests.
When I run a bazel command, nothing happens. 
I tried these commands :
`bazel build //py:selenium`
`bazel test //py:test-firefox`
A bazel process is started, but it never ends and nothing is displayed on stdout.
Can somebody help me to fix this.

**Comment by tvataire** [comment]
Ok, my install of bazel was broken.
Seems to work properly now...

**Comment by titusfortner** [comment]
thanks!

**Pull request merged**
