### PR TITLE
[dotnet] Remove JSON serialization from `.ToString()` methods

### LINKED ISSUE #14741: [dotnet] Avoid serializing to JSON in `ToString()` methods.
### Feature and motivation

There are a few types whose `ToString()` methods will serialize the contents into a JSON representation. This has some drawbacks

- Performance: This operation is heaver than a `ToString()` method should be. This is especially noticeable when using the debugger display.
- AOT: These methods are on types which contain open-typed `object` values, which is inherently not AOT-safe. This can throw exceptions in AOT scenarios, which `ToString()` methods should never do. Of less concern is the fact that, since the `ToString()` method is basically always rooted, these operations will never be trimmed away, and AOT programs may be larger than they need to be.

Each of the relevant types are strongly-typed dictionaries. For reference, the standard convention for dictionary types is to avoid overriding the `ToString()` method.

The following types are affected:
- `DriverOptions` (the base class for all browser options types)
- `ReturnedCapabilities` (internal class)
- `RemoteSessionSettings`

### Usage example

N/A

### PR DESCRIPTION
**Pull request by RenderMichael**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

This removes the `ToString()` method on `DriverOptions`, `ReturnedCapabilities`, and `RemoteSessionSettings`, to avoid heavy and AOT-unsafe JSON serialization.

Offshoot of #14734 

### Motivation and Context

There is an ongoing effort to make operations AOT-safe. Additionally, this `ToString()` method is heavy, which can be especially taxing when looking at the debugger display for the instance.

Fixes #14741

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Simplified the `DriverOptions.ToString()` method by removing JSON serialization and implementing a custom string representation using `StringBuilder`.
- Added tests for the `ToString()` method across different browser options (Chrome, Edge, Firefox, Internet Explorer, Safari) to verify the output format.
- Ensured the output includes browser name, version, and platform for better clarity and AOT safety.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DriverOptions.cs</strong><dd><code>Simplify `DriverOptions.ToString()` method for AOT safety</code></dd></summary>
<hr>

dotnet/src/webdriver/DriverOptions.cs

<li>Removed JSON serialization from <code>ToString()</code> method.<br> <li> Implemented custom string representation using <code>StringBuilder</code>.<br> <li> Included browser name, version, and platform in the output.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-3a23deddc7c714feb41423be7a50f6e63df3541f4a50e21c28286d52fa3584fa">+31/-2</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ChromeSpecificTests.cs</strong><dd><code>Add test for ChromeOptions ToString method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/chrome/ChromeSpecificTests.cs

<li>Added test for <code>ChromeOptions.ToString()</code> method.<br> <li> Verified output format for browser and platform.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-9c32a39a991584681ed755c12b2376458d3d041d771606d66672fe29f373c657">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>EdgeSpecificTests.cs</strong><dd><code>Add test for EdgeOptions ToString method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/edge/EdgeSpecificTests.cs

<li>Added test for <code>EdgeOptions.ToString()</code> method.<br> <li> Verified output format for browser and platform.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-42053ccdb86f30fc9473a2accb2b87b82a5a5718d3e1715ef130b6b455828322">+16/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>FirefoxDriverTest.cs</strong><dd><code>Add test for FirefoxOptions ToString method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/firefox/FirefoxDriverTest.cs

<li>Added test for <code>FirefoxOptions.ToString()</code> method.<br> <li> Verified output format for browser and platform.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-0ab06d3248144f57868f7615a95675e208584dbc4209ae447dd64dbde783b094">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>IeSpecificTests.cs</strong><dd><code>Add test for InternetExplorerOptions ToString method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/ie/IeSpecificTests.cs

<li>Added test for <code>InternetExplorerOptions.ToString()</code> method.<br> <li> Verified output format for browser and platform.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-fda46091a601dcbff6726072c48017f5861e4ec3aa10167a205bf52366dff2a8">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>SafariSpecificTests.cs</strong><dd><code>Add test for SafariOptions ToString method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dotnet/test/safari/SafariSpecificTests.cs

<li>Added test for <code>SafariOptions.ToString()</code> method.<br> <li> Verified output format for browser and platform.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14736/files#diff-c6e0b33bf234e4749360edb4d80e8e0d409dd11295cd51f1e37c3ddec125ba43">+17/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by nvborisenko** [comment]
I like that this PR excludes json serialization from `.ToString()` method. We are cleaning up codebase.

The next question: what we want to see as a string representation of any object? While I was walking through codebase, I don't see strong rule for objects. Yeah, json representation is still showing everything, but in general it is not ideal way to represent any object as a string.

@RenderMichael what if I propose just to remove `ToString()` in this PR? I propose to search for all `.ToString()` methods where json is involved, and "deprecate/remove" it (as separate unit of work). Let's initiate a discussion about expected string representation of most used objects in selenium (not sure which way is comfortable, issue in GitHub?).

**Comment by RenderMichael** [comment]
@nvborisenko I completely agree, the three types with JSON serialization in the `ToString()` method probably do not need those implementations at all. Since there are only 3, I don’t think we need a separate issue (I can change this PR) unless you think some people might disagree. Nobody should depend on the `ToString()` results, but maybe we want to he careful.

Should I open a separate issue for discussion?

**Comment by RenderMichael** [comment]
If we want to be careful and alert users, we can change the ToString to

```csharp
public string ToString() => $"{base.ToString()}, Use ToCapabilities() for a serializable representation.";
```

**Comment by nvborisenko** [comment]
Only 3 types? Then I propose to remove ToString() in this PR, and think of about it in separate PR. Discussion will be happened there, not here. Thank you!

**Comment by RenderMichael** [comment]
Opened #14741

**Comment by nvborisenko** [comment]
Let's do it: `Remove JSON serialization from all ToString() methods` here, why not, I am happy to merge. And then think about how to improve it.

**Comment by RenderMichael** [comment]
Done! PR is ready for review

**Comment by nvborisenko** [comment]
From all ToString(), then we can consider https://github.com/SeleniumHQ/selenium/issues/14741 as fixed.

**Comment by RenderMichael** [comment]
All 3 types are ready. Such a satisfying change

**Comment by nvborisenko** [comment]
Thank you, while you are adjusting PR's topic/description, I will validate that Appium project doesn't use `.ToString()` for json representation (I hope so).

**Comment by RenderMichael** [comment]
Hopefully they are not calling `ToString()` on any `ICapabilities` instance, since that could be affected here.

**Comment by nvborisenko** [comment]
You can help me, they are more friendly for .net: https://github.com/appium/dotnet-client (at least at compilation level)

**Comment by RenderMichael** [comment]
Luckily they do not. This is the only instance of handling `ICapabilities` on their side.

image

**Review by nvborisenko — APPROVED** [review]
Thanks Michael!

**Pull request merged**
