### PR TITLE
[dotnet] Fix missing documentation comments in NuGet package

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
### Description
All .nuspec files failed to include the XML files containing documentation comments. This regression was introduced with d77555a8e13d22a0c02ea7b22260d6844c0e1cbd and affects v4.0.0, v4.0.1 and v4.1.0.

Fixes:
- #10371
- #10375

Both have been closed as duplicates of an unrelated bug (missing online documentation). Please consider reopening #10371 to track the underlying issue until this has been fixed. Both bugs do not mention online documentation, so I don't understand why they were closed.

### Motivation and Context
Starting with version 4.0.0, all documentation comments were missing. This is because the XML file that contains those comments has been inadvertently excluded from the NuGet package.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**I was unable to test my changes because I was unable to complete a full build. Please consider improving your build instructions if you require such a complex build with this amount of dependencies.**

### CODE REVIEW

**Comment by nvborisenko** [comment]
Nobody? Easy fix.

**Review by diemol — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you, @BaerMitUmlaut!

**Comment by nvborisenko** [comment]
`4.2.0` was released without `xml` files in the nuget package. Thus inline documentation still doesn't work.

I think I am able to propose a fix for this, but building solution locally is a big pain.

**Comment by BaerMitUmlaut** [comment]
That's a shame. I wasn't able to make a proper build, maybe you'll have better luck.

**Comment by titusfortner** [comment]
reopened the issue. I'm guessing it needs to be added to bazel somewhere in order to be included

**Comment by Tony-Liou** [comment]
Maybe adding `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to csproj file would fix it.
Since #10371 has been locked, I am leaving comments here.

**Comment by nvborisenko** [comment]
Everything, you know how to do it, does not work because of `bazel`.

**Pull request merged**
