### PR TITLE
[rust] Use apple-flat-package crate to extract PKG files

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
This PR uses an existing crate called [apple-flat-package](https://crates.io/crates/apple-flat-package) to uncompress PKG artifacts, required to manage Firefox and Edge in macOS.

### Motivation and Context
Previously, SM used the shell command `pkgutil` to this aim. Nevertheless, this extraction is not working properly in GHA (although in local machines seems to continue working).

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

___

## **Type**
bug_fix, enhancement

___

## **Description**
- Replaced the use of shell commands with the `apple_flat_package` crate for uncompressing PKG files, enhancing reliability and portability.
- Removed obsolete code and simplified function calls following the new PKG uncompression approach.
- Added `apple-flat-package` to dependencies for handling PKG file extraction.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>files.rs</strong><dd><code>Replace Shell Command with Crate for PKG Uncompression</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
rust/src/files.rs

<li>Replaced shell command-based PKG uncompression with <code>apple_flat_package</code> <br>crate usage.<br> <li> Removed unused <code>major_browser_version</code> parameter from <code>uncompress_pkg</code> <br>function.<br> <li> Added logic to extract PKG files using <code>PkgReader</code> from <br><code>apple_flat_package</code>.<br> <li> Implemented file extraction and permissions setting for Unix systems.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13740/files#diff-64844fef0537ed5f6fd38575be93920c99efacb3fd4c317ed6ff1ce243c2e1f1">+33/-48</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>lib.rs</strong><dd><code>Cleanup and Simplification after PKG Uncompression Update</code></dd></summary>
<hr>
      
rust/src/lib.rs

<li>Removed unused constants related to the old PKG uncompression method.<br> <li> Simplified <code>uncompress</code> function calls by removing the <br><code>major_browser_version</code> parameter.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13740/files#diff-f64796ccc388f201986ea7eaaf07bbefbd8ac1a56bb995fb505da80879872a39">+0/-9</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Cargo.toml</strong><dd><code>Add Dependency for PKG File Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
rust/Cargo.toml

- Added `apple-flat-package` crate to dependencies.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13740/files#diff-74eb46d64310c0817ed15b2389cf81183c18cdebbaa256a4198057855ecf14d7">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by diemol** [comment]
Does the SM binary grow?

**Comment by bonigarcia** [comment]
This PR fixes the Rust build. In addition to uses the previously described crate to extract PKG files, this PR bumps the version of the rules_rust. We were using a very old version, and that was causing several issues. Now everything seems to work nicely.

> Does the SM binary grow?

Not really. You can see the size of the resulting binaries at the bottom of the workflow run:

https://github.com/SeleniumHQ/selenium/actions/runs/8442841426

I don't see differences with respect to the current stable binaries:

https://github.com/SeleniumHQ/selenium/blob/trunk/common/selenium_manager.bzl

**Comment by diemol** [comment]
Nice, I will merge after CI passes again.

**Review by diemol — APPROVED** [review]
Thank you, @bonigarcia!

**Pull request merged**
