### PR TITLE
Add types to set_window_position parameters

### PR DESCRIPTION
**Pull request by adamtheturtle**
## **Type**
enhancement

___

## **Description**
- This PR enhances the `set_window_position` method by adding type annotations to its parameters, improving code readability and type checking.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>webdriver.py</strong><dd><code>Add Type Annotations to set_window_position Parameters</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
py/selenium/webdriver/remote/webdriver.py

<li>Added type annotations to the <code>x</code> and <code>y</code> parameters of the <br><code>set_window_position</code> method.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/13786/files#diff-c87c150ed2a08f5293db58a06da8bf7f14c3a5582586c6270c1be661dfdd0985">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by adamtheturtle** [comment]
The bot suggests:

```
Consider changing the type hints for x and y from float to int since window positions are
typically represented in integer values. Using float might imply unnecessary precision and
could lead to confusion or the need for additional type conversions.
```

I chose not to do this as the function casts `x` and `y` to `int` - this is only useful if a non-int can be passed in.

**Review by A1exKH — APPROVED** [review]
LGTM.

**Review by diemol — COMMENTED** [review]
Are integers considered as floats in Python? What happens if the user enters `1` instead of `1.0`?

**Comment by adamtheturtle** [comment]
@diemol

> Are integers considered as floats in Python?

Only in the type system, because this is such a common use case.
See [Special cases for float and complex](https://typing.readthedocs.io/en/latest/spec/special-types.html#special-cases-for-float-and-complex).

```
when an argument is annotated as having type `float`, an argument of type `int` is acceptable
```

> What happens if the user enters 1 instead of 1.0?

That's accepted. It is as if we have written `Union[int, float]`.

**Review by diemol — APPROVED** [review]
Thank you, @adamtheturtle!

**Pull request merged**
