### PR TITLE
[nodejs] code cleanup first iteration

### PR DESCRIPTION
**Pull request by potapovDim**
### Description

Clean up code of the javascript/node/selenium-webdriver folder iteration first.
assert.deepEqual - deprecated, updated to assert.deepStrictEqual
assert.equal - deprecated, updated to assert.strictEqual

### Motivation and Context

Cleanup javascript/node/selenium-webdriver folder and variables declaration aligning

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harsha509** [comment]
Hi @potapovDim ,

Thanks for the PR.

There are few test failures and conflicts. can you please resolve them to get this merged.

Thanks,
Harsha

**Review by harsha509 — CHANGES_REQUESTED** [review]
Hi @potapovDim ,

Can you please resolve the conflicts and look into the failed tests?

**Comment by potapovDim** [comment]
@JS31096 Hey, will do, as soon as will have some free time

**Comment by harsha509** [comment]
Hi @potapovDim ,

Hope you're doing great.

Did you get a change to look into above request ?

Thanks!

**Review by harsha509 — APPROVED** [review]

**Comment by harsha509** [comment]
HI @potapovDim ,

Thanks for the PR.

I've resolved the conflicts and fixed the failed tests to get this PR merged.

Thanks,
Harsha

**Comment by potapovDim** [comment]
Hi, @harsha509, thanks !

**Pull request merged**
