### PR TITLE
Resolve inconsistency in Webdriver.__init__ desired_capabilities parameter

### PR DESCRIPTION
**Pull request by drobota**

### CODE REVIEW

**Comment by lukeis** [comment]
This is a breaking API change. We should still accept the old 'capabilities' keyword arg. I would only be ok removing it in a major release (like 3.0)

**Comment by drobota** [comment]
@lukeis  I am totally agree with that however this needs to be dome somewhen.

**Comment by AutomatedTester** [comment]
And that can be done when we move to Selenium 3 (date to be determined)

David Burns
Email: david.burns@theautomatedtester.co.uk
URL: http://www.theautomatedtester.co.uk/

**Comment by drobota** [comment]
I've added that in https://github.com/robotframework/Selenium2Library/pull/552

**Comment by Dude-X** [comment]
@drobota would be nice to revisit this with the latest revision and see if your patch is needed.

**Comment by drobota** [comment]
Inconsistency is still exist different drivers have different constructor variables 
f.e. firefox has - [capabilities](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L52)
when safari  - [desired_capabilities](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/safari/webdriver.py#L36)
In my view it has to be consistent with remote web driver class which has [desired_capabilities](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L59)

**Comment by lmtierney** [comment]
I know it's been a while... but would be good to make them consistent for the `4.0` release ;)

**Comment by lmtierney** [comment]
This PR is outdated and obsolete as #5513 has been merged

**Pull request closed without merging**
