### PR TITLE
further improvements to the json processing

### PR DESCRIPTION
**Pull request by joerg1985**
Faster reading and writing of json data, focused on base64 encoded data.
This will e.g. help reading 4k screenshots or sending binary data.

### Description
`Input.java` maintained a buffer with the chars read, to allow a helpfull `toString()`. It is more efficient to use an input buffer and keep the chars read in the buffer to allow a helpfull `toString()`. Changes to `JsonOutput.java` / `JsonInput.java` are small performance improvements, not related to the changes inside the `Input.java`.

### Motivation and Context
same as https://github.com/SeleniumHQ/selenium/pull/8546

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joerg1985** [comment]
I am not able to run all tests, the tests of the json package are successful.

**Comment by barancev** [comment]
Thank you for the patch, but it requires a little improvement. I've added more tests to cover the code touched by this PR to ensure backward compatibility, see commit f59e5ce16d2cd67b4adcf225e5910e8148dc4573. This patch does not pass the test `shouldBeAbleToReadNonWellFormedDataLongerThanReadBuffer` because it adds EOF char to the buffer unlike the previous implementation. Including EOF in the text generated by `toString` method looks suboptimal.

**Review by barancev — CHANGES_REQUESTED** [review]
Needs rework to pass `shouldBeAbleToReadNonWellFormedDataLongerThanReadBuffer` test

**Comment by joerg1985** [comment]
@barancev Thanks for the review, i changed the code to drop the EOF from the toString method.

The test is still failing, the string is one char shorter (due to the slot for the EOF char in the buffer).
I could either add some lines to be 100% backward compatible or change the tests to the new behaviour.

In my mind it would be better to change the test, because the extra lines for backward compatibility would only be some hard to understand remains in the code. Could you please decide which of the solutions is the best way to go?

**Comment by barancev** [comment]
Is it worth to put EOF to the buffer at all? We can simply return it from the `read()` method without storing to the buffer.

**Comment by joerg1985** [comment]
@barancev it is possible to use a return value, see the latest push. kind regards!

**Comment by barancev** [comment]
Merged as 80bd2628658d226a6b02e0ff5d155146726ad71d, thank you for the contribution

**Pull request closed without merging**
