### PR TITLE
Minor refactoring to use streams and lambdas

### PR DESCRIPTION
**Pull request by krmahadevan**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @shs96c - Please help take a look

**Comment by barancev** [comment]
I'm not ready to accept this PR as is. BaseRemoteProxy changes behavior, it's not "minor refactoring" and it should be excluded from this change set.

**Comment by krmahadevan** [comment]
@barancev - The changes to `BaseRemoteProxy` are mere null checks. Its not changing any functionality per say. I had to introduce them, because I was seeing a test failure owing to those missing null checks.

**Comment by barancev** [comment]
"I was seeing a test failure, now I don't see them" -- is not it a change in fuctionality? ;)

And, yes, this change _hides a problem_ detected by recently enabled DefaultRemoteProxyTest.

**Comment by krmahadevan** [comment]
@barancev - ok :) 

So I have two options to go about with this 

1. Raise 2 PRs. PR-1 will just have the lambda+stream changes, PR-2 will have the changes done to `BaseRemoteProxy`.
2. In the same PR have two explicit commits. Commit-1 has the lambdas+stream changes, Commit-2 has the changes done to `BaseRemoteProxy`

Which one would you prefer. Please let me know. I will proceed accordingly.

**Comment by barancev** [comment]
Make a commit with lambda+stream changes, it can be landed immediately.

As for the other change, it should go with improved version of DefaultRemoteProxyTest. This test fails because cleanup thread is null, whereas it should not be null and it should do cleanup. Adding a null-check makes the test green, but does not resolve the issue, it's a false positive.

**Comment by krmahadevan** [comment]
@barancev - Thanks. I have amended the commit to exclude the `BaseRemoteProxy` changes and include just the lamdas+streams changes. Please check. I will raise a new PR as per your suggestion for the failing test.

**Comment by barancev** [comment]
Merged as ef5de3815983c6cbcfb23d8dbcb2e55d00853a7c (with minor simplifications)

**Pull request closed without merging**
