### PR TITLE
[java] Overload `Rectangle` class constructors

### PR DESCRIPTION
**Pull request by valfirst**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Overload `Rectangle` class constructors.

### Motivation and Context
Improve usability of API.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
I prefer requiring the POJO over primitives for things like this, but... wouldn't it make more sense to do either all primitives or all POJO rather than having a mix?

**Comment by valfirst** [comment]
@titusfortner I don't have any strong opinion here, so it's up to you to choose the API design

**Review by diemol — COMMENTED** [review]
I do not see the value of adding these extra constructors, but I am probably missing the overall idea.

**Comment by valfirst** [comment]
@diemol the overall idea is to simplify client's code: to use the corresponding constructor instead of creation of additional objects, but as I stated above, I don't have strong opinion, feel free to close the PR

**Comment by titusfortner** [comment]
The nice thing about the current API is that it is obvious what each parameter value represents. We're trying to avoid creating and maintaining new constructors in general, so I'm going to close this.

But thanks for submitting code. If you are interested in working on something else, or want to discuss other ideas, please find us on Selenium slack/irc

**Pull request closed without merging**
