### PR TITLE
Correctly closing zip archive in C# file upload

### PR DESCRIPTION
**Pull request by vania-pooh**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

With current implementation C# client seems to produce broken zip archives as zip data is being base64-encoded before zip archive is closed.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@shs96c @diemol I'm not a C# expert, but according to tests I made this fix starts producing correct base64-encoded zip archive instead of broken stuff.

**Comment by bpyronn** [comment]
Looking forward to having this issue solved ! Thx !

**Comment by vania-pooh** [comment]
Any updates on this?

**Comment by diemol** [comment]
I am not familiar with the C# bindings, so I was checking the commit history and that block of code has barely changed in several years. 
Does it mean the functionality was always broken? Or is there a specific set of versions where it does not work?
Is there a related GitHub issue showing the error? Just trying to understand and help to merge this if it makes sense.

@jimevans do you have any comments?

**Comment by vania-pooh** [comment]
@diemol I think this was not working at all because last bytes of zip archive were not flushed to memory stream. However I'm also not an expert, probably in some cases it's working. Let's wait for Jim comment.

**Comment by jimevans** [comment]
Merged as fd17c1e. Thank you for your contribution!

**Pull request closed without merging**
