### PR TITLE
Additional expected conditions added

### PR DESCRIPTION
**Pull request by YevheniiaSilbernagl**
new conditions to check webelement attributes, number and so on. Documentation included

### CODE REVIEW

**Comment by ddavison** [comment]
hey @jtymoschuk , 

this change seems very big.. you may want to rebase then update your pull request.  looks like some of these changes may be old.  go ahead and do that and I'll take another look :)

**Comment by ddavison** [comment]
additionally, have you signed the CLA?

**Comment by jtymoschuk** [comment]
@ddavison, this change consists of one class only, I didn't think it to be a big one ;)
Regarding CLA: No, I didn't sign it, where I can do that, where I could read about that?

**Comment by jtymoschuk** [comment]
@ddavison Git tells me "Current branch master is up to date.", so I'm not sure what exactly you needs me to do. I rebased it, and I forked it from SeleniumHQ::master again, anyway it tells me the same.

**Comment by ddavison** [comment]
The CLA [can be found here](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla).

Also, to rebase, you can do the following:

```sh
.../selenium $ git remote add upstream https://github.com/seleniumhq/selenium.git
.../selenium $ git pull --rebase upstream master
```

**Comment by jtymoschuk** [comment]
@ddavison  everything seems to be done

**Comment by lukeis** [comment]
@jtymoschuk if you've done the rebase locally, you will then need to force push to your fork

**Comment by jtymoschuk** [comment]
I pushed it already

**Comment by lukeis** [comment]
Doesn't appear you did the commands that ddavison listed then. 

Feel free to hop onto IRC freenode.net #selenium and have someone help you through this

**Pull request closed without merging**
