### PR TITLE
Reuse SocketLock to fix Chrome port race condition

### PR DESCRIPTION
**Pull request by diurnalist**
When the Chrome browser boots up via the Ruby library, it attempts
to find a free port and launch the bridge on that port. However, it's
possible that, if you're running tests in parallel, two bridges will
try to bind to the same port at the same time. This will cause a very
ambiguous "end of file" error as documented [here](https://github.com/grosser/parallel_tests/issues/322).

This patch is based on one initially proposed in the original
[bug report](https://code.google.com/p/selenium/issues/detail?id=8241). However, it goes a step further, taking the technical
comments into account, and generalizing the `SocketLock` class used
in the Firefox launcher to assist.

### CODE REVIEW

**Comment by diurnalist** [comment]
I had some tests in-progress for this, but had a lot of difficulties getting them to run locally for verification. The issues I had:

- How does one install `bundler` reliably so the ruby unit tests can be executed via rspec? I found the `test_rb` target buried somewhere in the Rakefile, but I'm not sure how to run it b/c of that dependency. I have bundler installed locally via RVM, but that's no good, because of the way jruby tries to find gems.
- Even `./go clean test` failed due to what I presume is [an unrelated Closure test][1].

[1]: https://gist.github.com/diurnalist/6f6374e36fcf9e5df232

**Comment by bootstraponline** [comment]
:+1:

**Comment by cbwebdevelopment** [comment]
+1 for reviewing and pulling this in.  We can't reliably use the chromedriver (well, in parallel, at least) until this is resolved.

**Comment by titusfortner** [comment]
Interesting. Might this be the root cause for what I'm rescuing with #394?

**Comment by diurnalist** [comment]
Is there anything I need to do to get this reviewed? It would be nice to not have to keep using a forked codebase.

**Comment by titusfortner** [comment]
p0deje, jarib, and I have all looked at it. The consideration right now is expanding it as a generalized solution to other browsers/bindings. We're discussing it on irc.

**Comment by barancev** [comment]
Squashed and merged as 437725cbfb74f6752548d323c235922ff939ff47

**Comment by p0deje** [comment]
@titusfortner What was the result of this conversation?

**Comment by borski** [comment]
@titusfortner Would love the generalization as we're seeing this same issue in PhantomJS. Any chance you guys have a plan?

**Comment by p0deje** [comment]
@borski There is SeleniumHQ/selenium#736 which implements this for PhantomJS, but it was not really discussed with other Selenium developers now.

**Pull request closed without merging**
