### PR TITLE
Add '--no-results-cache' when running tests via BUCK

### PR DESCRIPTION
**Pull request by mojwang**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/3754)

### CODE REVIEW

**Comment by mojwang** [comment]
thanks @shs96c

**Comment by barancev** [comment]
Merged as b8da61f55585a05c02c9f23e2e78cd2b1e746369, thank you for contributing to the project!

**Comment by barancev** [comment]
This change causes an error
`BAD ARGUMENTS: "--no-results-cache" is not a valid option`

**Comment by barancev** [comment]
Reverted by e36b8c05200634f5613676b4d8329b94097e8e6b

**Comment by barancev** [comment]
We have migrated to bazel so this change is not applicable anymore.

**Pull request closed without merging**
