### PR TITLE
Pass options to RemoteWebDriver

### PR DESCRIPTION
**Pull request by nijel**
### Description
I believe that was the original intention of code in c23e4406a2a94f6546fe3bc69dcd9662126dc7d0 - it updates or creates the options object, but it doesn't use it later.

This reverts #9208 and passes options to the super class.

In case passing desired_capabilities instead of options to super class is really intended, a lot of code dealing with the `options` object can be removed because it is never used here.

CC @Dmitri-Sintsov, @earendil, @AutomatedTester 

### Motivation and Context

Please see #9188, #9208 and #7348

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Dmitri-Sintsov** [comment]
Would it work with headless option? In case `desired_capabilities` are deprecated, these should be removed everywhere, including `RemoteWebDriver` where these are currently used for headless option.

**Comment by nijel** [comment]
Yes it works headless. I did not orignally discover your fix and did fix it this way independently...

There is code which puts `desired_capabilities` into `options` and `options` are not used after that point:

https://github.com/SeleniumHQ/selenium/blob/9c41b0b5312cdaa70ed085665b5b0a04d91745e5/py/selenium/webdriver/chromium/webdriver.py#L75-L77

So either this is useless and should be removed or it is desired and then the `options` should be used later. This code was changed in c23e4406a2a94f6546fe3bc69dcd9662126dc7d0.

Maybe even `desired_capabilities` should be removed from the ` RemoteWebDriver.__init__` params as it is deprecated and it is put into the `options`. 

I'm happy to improve or close the pull request based on the feedback, but my knowledge of Selenium internals is very limited.

**Comment by Dmitri-Sintsov** [comment]
Just checked with my CI, indeed your version works in headless mode as well! I do not understand then why `desired_capabilities` are deprecated only in `ChromiumDriver` but not in `RemoteWebDriver` then? Maybe `desired_capabilities` should be removed everywhere, then?

**Comment by AutomatedTester** [comment]
> Just checked with my CI, indeed your version works in headless mode as well! I do not understand then why `desired_capabilities` are deprecated only in `ChromiumDriver` but not in `RemoteWebDriver` then? Maybe `desired_capabilities` should be removed everywhere, then?

The reason is I want to get Selenium 4 out the door first before as it's going to be a larger breaking change for people who use Selenium grid. Perhaps I am being overly cautious...

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
