### PR TITLE
Fix the problem that it closes all tabs when using webdriver.close() to close the current tab in Edge IE Mode.

### PR DESCRIPTION
**Pull request by yk9772**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Let it go the same way in Edge IE Mode as in IE when closing the current tab(window).

### Motivation and Context

To solve the problem that it closes all active tabs(windows) when using webdriver.close() to close the current tab(window) in Edge IE Mode.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jimevans** [comment]
@guangyuexu What would be the implications of this change after merging your [pending PR](https://github.com/SeleniumHQ/selenium/pull/10006)?

**Comment by bwalderman** [comment]
I see the CloseWindowCommandHandler and the QuitCommandHandler both use Browser::Close, and the key difference is that QuitCommandHandler iterates through all managed Browsers instead of just one.

In IE Mode, this will correctly terminate all of the underlying IE processes, but for the Quit command we should still make sure the parent Edge process is cleaned up to. I'd recommend keeping the `PostMessage(GetTopLevelWindowHandle(), WM_CLOSE, 0, 0);` call. This should be the last step after all of the managed Browser objects have been closed.

**Comment by jimevans** [comment]
@bwalderman Noted. I'll merge this one, and move the `PostMessage` call to a more appropriate place.

**Review by jimevans — APPROVED** [review]

**Comment by jimevans** [comment]
@yk9772 Thank you for your contribution!

**Pull request merged**
