### PR TITLE
Add: Added Missing 'fileUploadDialogTimeout' capability in JS bindings

### PR DESCRIPTION
**Pull request by harsha509**
### Description
While writing the selenium doc, i have observed this capability was missing in JS bindings

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Harsha509** [comment]
HI @corevo,

I have added the missing functionality in JS bindings, but to include tests I don't see any reference to existing IE tests. can you please suggest

Regards,
Harsha.

**Comment by corevo** [comment]
@jimevans what is the best way to test this?

**Comment by Harsha509** [comment]
> Could you add a test, like https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/test/chrome/options_test.js for this?

Got it

Sure @AutomatedTester ,

I need to create a seperate test file for Internet Explorer as there is no test written for IE in JS bindings so far.  I will update the PR once tested in WINDOWS machine.

Regards,
Harsha

**Comment by Harsha509** [comment]
IE Test local run

IE test console

**Pull request merged**
