### PR TITLE
Update license date for Ruby README

### PR DESCRIPTION
**Pull request by guillaumebriday**
Really simple PR to update the date from `2023` to `2024` in the README

### CODE REVIEW

**Comment by titusfortner** [comment]
@guillaumebriday thanks, but we need the CLA signed by the email address of the commit in order to merge, even single digit changes. 😁

**Comment by diemol** [comment]
@guillaumebriday would you like to sign the CLA and get this merged?

**Review by A1exKH — APPROVED** [review]
LGTM.

**Comment by titusfortner** [comment]
closing as we did not hear back

**Pull request closed without merging**
