### PR TITLE
[rust] Search better driver possible in the cache

### PR DESCRIPTION
**Pull request by bonigarcia**
### Description
This PR  add some Rust logic to get the _best_ possible driver from the cache when the regular algorithm does not work (e.g., in offline mode or other error). It throws a `WARN` when this logic is reached. This _best_ driver is found in two different ways:

1. It tries to find a driver that matches the major browser version. This should for Chrome and Edge, but not for Firefox (since geckodriver follows a different versioning schema than Firefox).
2. It tries to find the latest driver in the cache.

Example (offline mode but the driver was already there):

```
boni@slimbook:~/dev/selenium/rust$ cargo run -- --browser chrome --debug --offline
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/selenium-manager --browser chrome --debug --offline --clear-metadata`
WARN	Offline flag set, but also asked not to avoid browser downloads. Honouring offline flag
DEBUG	Using Selenium Manager in offline mode
DEBUG	Deleting metadata file /home/boni/.cache/selenium/se-metadata.json
DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at /opt/google/chrome/google-chrome
DEBUG	Running command: /opt/google/chrome/google-chrome --version
DEBUG	Output: "Google Chrome 116.0.5845.140 "
DEBUG	Detected browser: chrome 116.0.5845.140
WARN	There was an error managing chrome (Unable to discover proper chromedriver version in offline mode); using driver found in the cache
INFO	Driver path: /home/boni/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
INFO	Browser path: /opt/google/chrome/google-chrome
```

### Motivation and Context
This will allow to prevent problems explained in #12691.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
Just curious, if 116 isn't in cache, will it look for 115?

I'm not as worried about DEBUG messages, but I think we need to be more clear with WARN messages.

> WARN	Offline flag set, but also asked not to avoid browser downloads. Honouring offline flag

This message is confusing. We shouldn't refer to "offline" unless the user actually is offline, but right now we're using "offline mode" as the "non opted-in" mechanism for the Grid. (We can't disable SM because we need it to check on path, but we aren't accessing the network because we want users to opt-in to that). 

How about:
> WARN 	 downloads disabled, to enable set --selenium-manager true

or 
> WARN 	 network calls disabled, to enable set --selenium-manager true

**Comment by bonigarcia** [comment]
> Just curious, if 116 isn't in cache, will it look for 115?

If 116 is not in the cache, it will look for latest (which might be 117, 115, or whatever latest).

> I'm not as worried about DEBUG messages, but I think we need to be more clear with WARN messages.

I agree. That `WARN` message was introduced by Simon in their last change to fix the RBE build. But for me, it is more a `DEBUG`  than a `WARN`. But I decided not to change it in this PR since I want to review it carefully in a future change.

**Comment by titusfortner** [comment]
No, I think `WARN` is right. If the user doesn't get what we think is "right" we should warn them, but the message needs to be informative and it should explain how to fix it or link them to a place they can get that info. More people will opt-in to using Selenium Manager if SM warns them they aren't getting what they should be using.

**Comment by titusfortner** [comment]
Oh, you're right, these should be debug.

**Pull request merged**
