### PR TITLE
[dotnet] Change a list of downloadable files to IReadOnlyList

### LINKED ISSUE #13264: [dotnet] Change signature of GetDownloadableFiles to IEnumerable<string>?
https://github.com/SeleniumHQ/selenium/blob/1bcb948894767cf4525b565f0c5dac73cd3e15e0/dotnet/src/webdriver/IHasDownloads.cs#L32C9-L32C9

`List<string> GetDownloadableFiles();` allows add new items to the list.

I think it would be better to use `IReadonlyList<string>` or `IEnumerable<string>` (or any other immutable interface friendly with `Linq`). It is breaking change, but would not be widely spread.

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
Retrieved list should be immutable.

### Motivation and Context
Fixes #13264 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
Is this change worth breaking backwards compatibility without warning?

**Comment by nvborisenko** [comment]
There are 2 types of breaking changes: compilation compatibility and binary compatibility. This change is related to binary compatibility (even not sure), and is not related to compilation compatibility. I suppose only 0.01% of users might be impacted.

**Review by titusfortner — APPROVED** [review]

**Comment by nvborisenko** [comment]
I lied, it is compilation level breaking change. It breaks users who wrote:
```
List<string> myVar = driver.GetDownloadableFiles();
```

**Comment by titusfortner** [comment]
I see how it is. Still want to do it, or put it back?

**Comment by nvborisenko** [comment]
Now or later... Given that selenium doesn't follow semver...

**Pull request merged**
