### PR TITLE
Bugfix: Values must be appended before freezing IGNORED_ERRORS.

### PR DESCRIPTION
**Pull request by kou1okada**
- [ ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)
- [x] By submitting my Contribution to the Selenium Project, I hereby agree to license my Contribution under the Apache License, Version 2.0, and to include the appropriate copyright notice required by the license.  

In the ruby on the cygwin environment, `selenium-webdriver` makes error as below:

    $ ruby -r selenium-webdriver -e 'p "hello selenium!"'
    /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/port_prober.rb:42:in `<class:PortProber>': can't modify frozen Array (RuntimeError)
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/port_prober.rb:22:in `<module:WebDriver>'
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/port_prober.rb:21:in `<module:Selenium>'
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/port_prober.rb:20:in `<top (required)>'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common.rb:29:in `<top (required)>'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver.rb:26:in `<top (required)>'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
            from /home/kou/.gem/ruby/gems/selenium-webdriver-3.0.1/lib/selenium-webdriver.rb:20:in `<top (required)>'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:133:in `require'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
            from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:40:in `require'

My patch fixes it.

### CODE REVIEW

**Comment by kou1okada** [comment]
Hmm, master seems broken in test of Travis CI.
It failes at [#1289.27, Python: 2.7, CHROME=1 TOXENV=py27-chrome](https://travis-ci.org/SeleniumHQ/selenium/jobs/178499024).
Of course, its cause is not a fix (for ruby) of mine.
Please fix it who broke it.

**Comment by davehunt** [comment]
> Hmm, master seems broken in test of Travis CI

Unfortunately the python suite is still a bit unstable on Travis. I've retriggered the failed job for you.

**Comment by kou1okada** [comment]
Hmm, indeed,,,
Your last commit (6dbc73b7c1c7c27829a3888ae33a80e14ceee039) has no errors at https://travis-ci.org/SeleniumHQ/selenium/builds/178269241.
But my patch(37e64baca7dbd8adaa8d29028399ab5e8b8ad39d) made an error at https://travis-ci.org/SeleniumHQ/selenium/builds/178498997 even though it branched from there.
It is certainly unstable, isn't it?

O.K. I wait for triggering a failed test again.
Thanks so much.

**Comment by AutomatedTester** [comment]
Unfortunately, Chrome is super unstable when handling alerts. I have disabled the test (I thought I already did) in bfd415f

**Comment by kou1okada** [comment]
Thanks.
I merged it to my patch.

**Comment by titusfortner** [comment]
@kou1okada - don't worry about this; we've had a ton of Ruby PRs this past week and I'm rolling them all together and testing them independently of Travis. Hope to have a new point release for Ruby later today or tomorrow. Thanks for your help!

**Comment by titusfortner** [comment]
Merged - ef2003cd6a61364a1a353481d906b3bfdbe00f97
Thanks!

**Pull request closed without merging**
