### PR TITLE
[py] update ShadowRoot find element signatures to match those in WebElement

### PR DESCRIPTION
**Pull request by titusfortner**
@AutomatedTester just making sure there wasn't a reason the signatures were different.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This is a zero value change. A more useful addition would be adding type hinting.

**Review by AutomatedTester — APPROVED** [review]

**Comment by diemol** [comment]
Why do we merge it if it is a zero value change?

**Comment by AutomatedTester** [comment]
I will finish off the patch with the type hinting

**Comment by titusfortner** [comment]
This is not a zero value change. It was literally a feature request from a user who wanted to have the same method wrapper for both methods and couldn't. I only PR'd it instead of merging it because I thought there might have been a reason you didn't just copy/paste what you already had.

If the WebElement methods had type hinting, I would have copied that over as well.

**Pull request merged**
