### PR TITLE
Run tests only when changes in folder

### LINKED ISSUE #6208: Smarter Travis Builds
A PR on Travis was auto-canceled when someone committed to Master, which makes it hard to know that the PR didn't break anything. I thought we used to have it so that tests were only run when changes from a particular folder.

It shouldn't be too difficult (though perhaps time consuming to make sure it works correctly) to add a conditional using something like `git diff --name-only HEAD~1` to check for what has changed to [these tasks](https://github.com/SeleniumHQ/selenium/blob/master/scripts/travis/script.sh) based on folder (python tests when changes in /py/*, ruby tests when changes in /rb/*, etc)

If we minimize what gets run, that should keep us from having to auto-cancel PR builds.

### PR DESCRIPTION
**Pull request by knmkr**
Fixes #6208 

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/7111)

### CODE REVIEW

**Comment by titusfortner** [comment]
@barancev do you think we should only do this for PR's? 

I'm wondering if we should add an `||` here and still run things if  ENV `TRAVIS_PULL_REQUEST` is false.

**Comment by shs96c** [comment]
LGTM, but will wait for @barancev. Note that if we modify anything in the top-level of the project, this will not cause any tests at all to run, but I guess we don't do that very often.

**Comment by barancev** [comment]
I think it's worth to use always, not only for Prs. If someone make changes on the top level they can run selected tests manually on travis. But I agree with @shs96c that this happens not often and usually causes compilation issues, not test failures.

**Comment by titusfortner** [comment]
@knmkr thanks for your contribution!

**Comment by knmkr** [comment]
@titusfortner @shs96c @barancev Thanks 🙌

**Comment by barancev** [comment]
Excellent work!

**Pull request merged**
