### PR TITLE
[py] add edge driver tests

### PR DESCRIPTION
**Pull request by Delta456**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Add Python driver tests for Edge Browser.

### Motivation and Context

These were missing and it is required to test if everything is working on Edge or not

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Tests

___

### **Description**
- Added new Python tests for the Edge browser driver to ensure functionality and reliability.
- Created a pytest fixture for setting up and tearing down Edge driver instances.
- Implemented tests for launching and closing Edge browser instances, including multiple instances.
- Added tests to verify Edge WebDriver service logging and environment variable path usage.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add initialization file for Edge driver tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/edge/__init__.py

<li>Added license and copyright information.<br> <li> Created an empty <code>__init__.py</code> file for the Edge driver tests package.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14723/files#diff-bdadc4ae98c0d46f45271e715018d2d5234fed010de028cbc91ffc184c6ab0fc">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>conftest.py</strong><dd><code>Add pytest fixture for Edge driver setup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/edge/conftest.py

<li>Added license and copyright information.<br> <li> Defined a pytest fixture for setting up and tearing down an Edge <br>driver instance.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14723/files#diff-8dbcc2f287cbf9d209fae76269f39037d22ab61e2d1e68bd2c447c5d8d41035c">+27/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>edge_launcher_tests.py</strong><dd><code>Implement Edge browser launch and multiple instance tests</code></dd></summary>
<hr>

py/test/selenium/webdriver/edge/edge_launcher_tests.py

<li>Added license and copyright information.<br> <li> Implemented tests for launching and closing Edge browser instances.<br> <li> Included tests for launching multiple Edge instances.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14723/files#diff-ede1b0fbd94d25ccb38bc169cf011e65db421411c057fe0563b775ac7b71ecb2">+34/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>edge_service_tests.py</strong><dd><code>Add tests for Edge WebDriver service and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/test/selenium/webdriver/edge/edge_service_tests.py

<li>Added license and copyright information.<br> <li> Implemented tests for Edge WebDriver service logging.<br> <li> Included tests for environment variable path usage.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14723/files#diff-9ba4cbc1f50e44a2b01e9ffda260a45177281d243a43e3466cc12808d2aca955">+123/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
Looks like this test is failing in RBE
`py/test/selenium/webdriver/edge/edge_launcher_tests.py::test_launch_and_close_browser FAILED [ 50%]`

**Comment by AutomatedTester** [comment]
tests are failing

**Comment by Delta456** [comment]
It is passing locally for me 

image

**Comment by shbenzer** [comment]
This is a good catch, should we make an issue for adding all test cases to edge?

**Comment by shbenzer** [comment]
We'll likely also want to add "test/selenium/webdriver/common/**/*.py" to the edge test suite in bazel.build

**Comment by AutomatedTester** [comment]
This isn't working. Please check the action

**Pull request merged**
