### PR TITLE
Selenium for .Net. Enhancements. IContextAware interface. PageFactory enhancement.

### PR DESCRIPTION
**Pull request by TikhomirovSergey**

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
1. IContextAware interface. 

Appium project needs this. If the similar interface exists at
selenium-java so why it can't be at C#/.Net client. :)


2. PageFactory enhancement. 
These tools were implemented the perfectly similar way as it was done in Selenium Java. Now it is possible to design your own attributes/algorithms in order to decorate fields/properties by:

```csharp
IFieldDecorator
ILocatorFactory
IElementLocator
```

Default implementations are already here. They can be extended, their virtual methods can be overridden

**Comment by TikhomirovSergey** [comment]
Some more about 
>2 PageFactory enhancement. 

Appuim project needs this in order to provide the following use case (field of page/screen object):

 ```csharp
[FindsBy(How = How.CssSelector, Using = "relevant css")] //if there the similar browser UI as UI of a //native app
[AndroidFindBy(UIAutomator = "ui Automator locator for Android")] //if page object is going to be used against Android
[iOSFindBy(Accessibility = "accessibility for iOS")] //if page object is going to be used against 
//iOS
IWebElement targetElement;  //element is used for the mobile and browser testing
```

It is already present on the java-client side. If it is interesting details are refered to this.

**Comment by Jonahss** [comment]
I dropped into the #selenium IRC channel on freenode and mentioned this PR. Here's a quick response:
```
[11:23] <jimevans> nope. i'm not merging that.
[11:23] <jimevans> it should be two pull requests, not one.
[11:24] <jimevans> and i'm not taking a dependency on another third-party library that can't be ilmerged into a single assembly.
[11:24] <jimevans> which castle.core can't.
[11:30] <jimevans> if the author wants to break it up into two pull requests, i'll look at them.
```

So breaking this into separate pull requests will make things easier to review.

**Comment by TikhomirovSergey** [comment]
Ok! I'll setarate it soon.

**Comment by TikhomirovSergey** [comment]
Actually there is no Castle.Core reference anymore.

**Comment by TikhomirovSergey** [comment]
I am closing this PR as it should be divided...

**Comment by TikhomirovSergey** [comment]
Was splitted to:
#305 
#306

**Pull request closed without merging**
