### PR TITLE
[JS] Support for 'print' endpoint 

### PR DESCRIPTION
**Pull request by harsha509**
### Description

1. Adding support for 'print' endpoint with 'printToPdf' WebDriver client
2. feature works in geckodriver 0.27.0

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harsha509** [comment]
Hi @corevo ,

Can you please review this PR. Am not sure if it is the best implementation or not, if not can you please suggest me the best approach.

Also, I've added no tests as am not sure on how to test base64 encoded string. 

Regards,
Harsha

**Comment by corevo** [comment]
You can test it by saving as test fixtures the pdfs of the pages test pages, and read them as base64 and then do a string compare.

We'll have to see over time how flaky it is, we should probably check how takeScreenshot was tested and take a similar approach.

**Comment by AutomatedTester** [comment]
We don't need to test the correctness of the PDF over base64 since that is what browser vendors should be doing in their tests. We just need to test that we are given a base64 string

**Comment by corevo** [comment]
👍

**Comment by corevo** [comment]
Also make sure to test all the options that we can pass, we don't have to check for correctness, that it the vendor's job, but we have to check that we pass them correctly to the driver.

**Pull request closed without merging**
