### PR TITLE
[atoms] Fix getText atom for unicode charater middle of word

### PR DESCRIPTION
**Pull request by k7z45**
The change to getText atom by commit c065ddaeb6c5cf91ebf797c242128604e38b79e1
does not handle case when unicode character is in the middle
of a word, and unicode character will be incorrectly capitalized
(see https://bugs.chromium.org/p/chromedriver/issues/detail?id=3611).
The problem is \b mark the boundary between word character and
unicode character as a boundary. This is fixed by explicitly using
unicode flag and specifying unicode character and unicode symbol
in the regex.

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by k7z45** [comment]
Encountered some issues running test locally,
"After I did ./go node:atoms,
then I do bazel run //java/client/test/org/openqa/selenium/environment:appserver
and visit http://localhost:2310/javascript/atoms/test/text_test.html but I still see
test_bootstrap.js:74 GET http://localhost:2310/javascript/deps.js net::ERR_ABORTED 404 (Not Found)"

**Comment by shs96c** [comment]
Hi! Thank you for the contribution! Thank you, also, for pointing out that the `run` command didn't work for you. The process has changed slightly since the docs were written, and I've recently fixed an issue in the way we set things up. Could you please:

* Rebase on `trunk`
* Run `bazel run //java/client/test/org/openqa/selenium/environment:appserver`
* Visit [http://localhost:2310/filez/selenium/javascript/atoms/test/text_test.html](http://localhost:2310/filez/selenium/javascript/atoms/test/text_test.html)

It looks your new test cases are failing, but once they pass, I'd be very happy to merge this change in!

**Comment by k7z45** [comment]
Hi, thanks for fixing the test framework!
Do you know why there is a difference in how the text is displayed when I visit the page via
http://localhost:2310/filez/selenium/javascript/atoms/test/text_test.html vs.
file:///path/to/text_test.html?
The texts are totally unexpected in terms of processing the capitalize style.
For example,
Ã¤Ã¥Ã¬Ã® in the hosted page vs.
Äåìî in local file
and
Manipulowanie PrzepÅ‚Ywem in the hosted page and
Manipulowanie Przepływem in the local file.

**Comment by shs96c** [comment]
I'd suspect that file encodings are to blame. I think the server expects everything to be in UTF-8

**Comment by AutomatedTester** [comment]
Add `<meta charset="utf-8"/>` to render it properly

**Comment by AutomatedTester** [comment]
Also, this patch breaks other tests.

**Comment by k7z45** [comment]
Thanks, after adding `<meta charset="UTF-8">`, the text_test.html test passes.
What other tests does it break?

**Review by AutomatedTester — APPROVED** [review]

**Comment by AutomatedTester** [comment]
Looks like a merge must have fixed the tests that were failing. 

I have merged this PR, thanks for making it work

**Pull request merged**
