### PR TITLE
Add Travis CI badge to README.md

### PR DESCRIPTION
**Pull request by Dominator008**
Also remove trailing whitespaces.

### CODE REVIEW

**Comment by lukeis** [comment]
Thanks for the offer, but Travis is not our main CI, we have another Jenkins instance and only pull requests are run through Travis for Python and ruby changes.

So for now we'd prefer to not have this.

**Comment by johnjbarton** [comment]
FWIW, I think the Travis would be helpful to know that the build known to be failing. As it is, I opened an issue that was probably not useful.  The fact that another CI also runs is fine, but that does not reduce the benefit of the Travis signal as far as I can tell.

**Comment by cgoldberg** [comment]
@lukeis ,
are the jenkins results publicly viewable somewhere?

**Comment by lukeis** [comment]
@cgoldberg http://ci.seleniumhq.org:8080/

**Comment by Dominator008** [comment]
@lukeis https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin seems to provide a Jenkins CI badge.

**Comment by cgoldberg** [comment]
@lukeis 
are the python tests also run by Jenkins?  I don't see them

**Comment by lukeis** [comment]
@cgoldberg sadly no... they are not.

@Dominator008 will need to bring it up with @juangj to install.

**Pull request closed without merging**
