### PR TITLE
[dotnet] Declare selenium manager binaries as content

### LINKED ISSUE #12577: [🐛 Bug]: Unable to obtain MicrosoftEdge using Selenium Manager
### What happened?

Yet another "Unable to obtain ... using Selenium Manager" **after upgrading to version 4.11.0**.

In my case the error occurs when I call `CreateDefaultService()` without passing the webdriver location path parameter (in .NET project).

It **works only  on the development machine** but not when deployed by ClickOnce. It also works when I pass the location of the webdriver executable to `CreateDefaultService()`, e.g. `CreateDefaultService("C:\\webdriver\\msedgedriver.exe"); `.

Context:
- Visual Studio 2022
- .NET / C# / VSTO (MS Office 2010)
- x86 build (MS Office Add-In)
- x64 machine
- ClickOnce deployment

I have tried to build the latest nightly pre-release but this was not successful at all. So I couldn't say, whether the bug has been fixed meanwhile.  

### How can we reproduce the issue?

```shell
EdgeOptions edgeOptions = new EdgeOptions() { };
edgeOptions.AddArgument("no-sandbox");
edgeOptions.AddArgument("--disable-dev-shm-usage");
EdgeDriverService edgeService = EdgeDriverService.CreateDefaultService();
EdgeDriver edge = new EdgeDriver(EdgeService, edgeOptions);
```

### Relevant log output

```shell
Unable to obtain MicrosoftEdge using Selenium Manager (...)

at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
at OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService(EdgeOptions options)
at OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService()
```

### Operating System

Windows 10

### Selenium version

4.11.0, 4.12.3

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge v115.0.1901.203

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver v115.0.1901.203

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
It allows selenium manager to be included into installers, like `msi`/`exe` or `vsto`.

### Motivation and Context
Fixes #12577

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Sigrec** [comment]
Not sure if this is the best place to ask but, is there a nightly build for this?

**Comment by titusfortner** [comment]
No, but we'd like to. I think nuget supports them. @diemol did we look into this? Are we limited by bazel?

**Comment by diemol** [comment]
@nvborisenko said they need to be pushed with a beta suffix or something like that. I don't think bazel is blocking us. We are just very short on time.

**Comment by Sigrec** [comment]
Follow up to this fix, how can I change where the web driver looks for selenium-manager to the self-contained executable itself (ClickOnce), as it still checks the current working directory path where the .exe resides? Or maybe I'm just doing something wrong or missing something.

**Comment by nvborisenko** [comment]
Selenium manager should be inside of your ClickOnce app, and it should be unpacked when you deploy/install your app. Thus you don't care about selenium manager location, it should just work.

If it doesn't, please create new issue.

**Comment by Sigrec** [comment]
Issue created [#12842](https://github.com/SeleniumHQ/selenium/issues/12842) found out the issue is when publishing to a single file.

**Pull request merged**
