### PR TITLE
Add Github Action - Prepare Python Release

### PR DESCRIPTION
**Pull request by dev-velo**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Added a script and workflow to help with python releases. This is an initial version of this workflow. Given a release version, this workflow will update the bazel/python/rst files. This will only touch the files[ included here ](https://github.com/SeleniumHQ/selenium/wiki/Releasing-Selenium#python).

**Some important notes:** 
1. I added a versions.py file which will be the single source of truth for all python files which reference a version number. This file is not really meant to be edited by anybody but it can be. I say this because the workflow will update the other places as well. IMO less error prone. 
2. I did think of adding a version.bzl which would have the same info as version.py and have the build file pull the version from there but I opted not to since it would be weird to have two version files containing the same info. From what I [read](https://bazel.build/build/share-variables) Bazel can only pull from bzl files so the other option was to have python read from the bzl file and do some extra work but this seemed simpler and cleaner.
3. It builds a changelog, the changelog can be [modified](https://github.com/mikepenz/release-changelog-builder-action#configuration) 

### Motivation and Context

Read slack and seen a place where I can contribute. This does not do the full python release yet but does alleviate some pain as there are many files to edit.
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Can we test this first with Nightly releases? Please check #12207

**Comment by dev-velo** [comment]
@diemol yea this can be tested with nightlies. I removed the change log stuff since this would ultimately get absorbed in the nightly workflow. I'd like to see this ran manually once and then have the python-ci ran to make sure stuff is fine ( locally was good ) and then I can get this integrated with the nightly workflow and remove this workflow.

**Comment by dev-velo** [comment]
Made a new pull request #12605 which integrates the some of this work with the current nightly workflow, feel free to close this unless it wants to be used for testing before merging #12605

**Review by diemol — COMMENTED** [review]
I prefer that a tag is created locally and when it is pushed triggers the release.

**Comment by diemol** [comment]
Thank you for your efforts, @RevealOscar! Thanks to the scripts @titusfortner did to automate releases, I completed this work and got some inspiration from this PR.

We are now [publishing](https://github.com/SeleniumHQ/selenium/actions/runs/7949128770/job/21699936354#step:16:110) nightly builds to [TestPyPi](https://test.pypi.org/project/selenium/).

The Selenium [Downloads](https://www.selenium.dev/downloads/#nightly) page has also been updated.

**Pull request closed without merging**
