### PR TITLE
Remove Browser Connection driver extension and add Network Connection driver extension

### PR DESCRIPTION
**Pull request by jimvm**
This is related to this issue: https://code.google.com/p/selenium/issues/detail?id=7315

It's basically the Ruby version of this commit: https://github.com/SeleniumHQ/selenium/commit/8629dc6ec6ddd96bbe0975ee86d0c4c2f4b9ebb2

HasBrowserConnection is a driver extension that is only an option for the Android driver. The
Selendroid JSON Wire implementation doesn't support the `browser_connection` method anymore,
so all code related to this driver extension can be removed from the Ruby bindings.

The new Selendroid JSON Wire method `network_connection` returns the connection type on a GET request and changes the connection type on a POST request. Currently you can only switch between Airplane mode and All mode. (The implementation is here: https://github.com/selendroid/selendroid/blob/master/selendroid-standalone/src/main/java/io/selendroid/server/handler/NetworkConnectionHandler.java.)

The new HasNetworkConnection driver extension can handle all types even though that doesn't work yet. In case an unknown type is returned `network_connection_type` returns this unknown type value. I just wanted to have something for this possibility. Can someone think of something better to return if this happens? 

I did have some problems with getting the integration specs running for Selendroid. Could someone help verify that these specs pass?

I haven't signed the CLA yet. I will do that once these changes are approved.

### CODE REVIEW

**Comment by jimvm** [comment]
I think it is a failure. I just tested this again in irb.

First, I tested the getter:
```
irb(main):004:0> driver.network_connection_type
=> :all
```

After that I tested the setter:
```
driver.network_connection_type = :airplane_mode
=> :airplane_mode
```

Then, I tested the getter again to see if the response has changed from `:all` to `:airplane_mode`:
```
driver.network_connection_type
Selenium::WebDriver::Error::UnknownError: The test session has been marked as invalid. This happens if a hardware device was disconnected but a test session was still active on the device.
io.selendroid.exceptions.SelendroidException: The test session has been marked as invalid. This happens if a hardware device was disconnected but a test session was still active on the device.
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:53)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
 (io.selendroid.exceptions.SelendroidException)
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/remote/bridge.rb:325:in `getNetworkConnection'
	from /usr/local/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.44.1.dev/lib/selenium/webdriver/common/driver_extensions/has_network_connection.rb:6:in `network_connection_type'
	from (irb):7
	from /usr/local/bin/irb:11:in `<main>'
```

Selendroid releases my hardware device for some reason.

I also tried to get these tests to run with Appium but I couldn't get that to run either.

**Comment by jarib** [comment]
OK. At least this is more correct than the old BrowserConnection stuff. Let's get this merged. Can you sign the [CLA](http://goo.gl/qC50R)?

**Comment by jimvm** [comment]
I got the tests to run on Appium too but they failed as well.

Here's what I got:
```
Selenium::WebDriver::DriverExtensions::HasNetworkConnection can return the network connection type
     Failure/Error: expect(driver.network_connection_type).to eq :all
     Selenium::WebDriver::Error::WebDriverError:
       unexpected response, code=404, content-type="text/plain"
       unknown command: session/be6d1ff32f0b3cfd69f4c485fa9f99fc/network_connection
     # ./build/rb/lib/selenium/webdriver/remote/http/common.rb:66:in `create_response'
     # ./build/rb/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
     # ./build/rb/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:325:in `getNetworkConnection'
     # ./build/rb/lib/selenium/webdriver/common/driver_extensions/has_network_connection.rb:6:in `network_connection_type'
     # ./rb/spec/integration/selenium/webdriver/network_connection_spec.rb:7:in `block (3 levels) in <module:DriverExtensions>'

  41) Selenium::WebDriver::DriverExtensions::HasNetworkConnection can set the network connection type
     Failure/Error: expect { driver.network_connection_type = :airplane_mode }.to change { driver.network_connection_type }.from(:all).to(:airplane_mode)
     Selenium::WebDriver::Error::WebDriverError:
       unexpected response, code=404, content-type="text/plain"
       unknown command: session/be6d1ff32f0b3cfd69f4c485fa9f99fc/network_connection
     # ./build/rb/lib/selenium/webdriver/remote/http/common.rb:66:in `create_response'
     # ./build/rb/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
     # ./build/rb/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
     # ./build/rb/lib/selenium/webdriver/remote/bridge.rb:325:in `getNetworkConnection'
     # ./build/rb/lib/selenium/webdriver/common/driver_extensions/has_network_connection.rb:6:in `network_connection_type'
     # ./rb/spec/integration/selenium/webdriver/network_connection_spec.rb:11:in `block (4 levels) in <module:DriverExtensions>'
     # ./rb/spec/integration/selenium/webdriver/network_connection_spec.rb:11:in `block (3 levels) in <module:DriverExtensions>'
```

It seems that the Appium JSON wire protocol doesn't have the network_connection command implemented yet.

I added some local changes to my branch to the pull request. These changes were required to get the HasNetworkConnection extension and the tests to work.

Then I rebased my branch and ran the tests again. No changes. I've also signed the CLA.

**Comment by andreastt** [comment]
@lukeis, are you involved with Appium and can you see about adding the `network_connection` command there so we can merge this?

**Comment by andreastt** [comment]
`network_connection` seems to have landed, and so I'm landing this change: https://github.com/SeleniumHQ/selenium/compare/085aecb2d21e...51d4486911e9

**Pull request closed without merging**
