### PR TITLE
[dotnet] implement WebDriver BiDi

### PR DESCRIPTION
**Pull request by titusfortner**
### Status
This is in Draft so we can discuss what the API could look like
The PR is overly complicated because it relies on #13952 & #14010 so those must be merged first; can tidy it up after merging those (and if you want to hold off on reviewing it until then, that's fine, too).

### Description
* Adds the WebDriver BiDi dependency from Jim
* BiDi is disabled in tests by default
* Starts a BiDi session if `webSocketUrl` is set
* Implements all the Navigation commands with conditionals for whether BiDi is present

### Motivation and Context
This should be the easiest way to have working BiDi implementation in .NET since Jim has already written all the lower level commands (and would love not to duplicate that effort if we don't have to)
The conditionals in each method are not the most elegant, but they are straightforward, and I think that's preferred.
It'll be easy enough to just remove the conditionals when we remove support for WebDriver classic (Selenium 6?)

### Considerations
We still need to implement updating `browsingContextId` when windows are switched, and figure out how navigation works if the browser context is a frame (recursively get parent?)

Figure out a better way to toggle BiDi with Bazel; I foresee us running tests with it toggled on and off, and I'm not sure an environment variable is the right way to do it. (@p0deje probably knows how to allow adding a flag for this)

@YevgeniyShunevych your input is appreciated as well

### CODE REVIEW

**Comment by titusfortner** [comment]
Ok, I also need to figure out how to add the nuget dependency to:
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/paket.bzl
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/paket.nuget.bzl
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/workspace.bzl

and maybe also some  `BUILD.bazel` files

**Comment by p0deje** [comment]
> Figure out a better way to toggle BiDi with Bazel; I foresee us running tests with it toggled on and off, and I'm not sure an environment variable is the right way to do it. (@p0deje probably knows how to allow adding a flag for this)

We probably want to have both environment variable and a Bazel flag?

```
bazel test --bidi rb/...
bazel test --cdp rb/...
```

**Comment by titusfortner** [comment]
@p0deje I'm more thinking about toggling between WebDriver classic and webDriver BiDi commands. I'm not very interested in toggling between CDP & BiDi, because we should be getting away from CDP. 😁

**Comment by p0deje** [comment]
> Figure out a better way to toggle BiDi with Bazel; I foresee us running tests with it toggled on and off, and I'm not sure an environment variable is the right way to do it. (@p0deje probably knows how to allow adding a flag for this)

Maybe then it would be better to have individual test targets for classic and bidi? It would ensure that we properly cache test results and don't re-run unless necessary?

```
bazel test //rb/spec/integration/selenium/webdriver:driver-firefox-bidi
bazel test //rb/spec/integration/selenium/webdriver:driver-firefox-classic
```

To run all the tests, we'd use:

```
bazel test --test_tag_filters bidi rb/spec/...
bazel test --test_tag_filters classic rb/spec/...
```

**Comment by titusfortner** [comment]
@p0deje I think I like that idea more. I created a separate issue to discuss this here - #14020

**Comment by titusfortner** [comment]
I made a mess of this one and can't seem to fix it, closing and opening a new PR. 😁

**Pull request closed without merging**
