### PR TITLE
Updated cs-wd.js and webdriver.js of Se IDE

### PR DESCRIPTION
**Pull request by phasze**
added waitForPopup function to C#

added mainWindow variable to C# because I've noticed the main window doesn't always stay an index 0.

fixed WDAPI.Element.prototype.select

added a function to fix javascript stuff.

added:
contextMenu
switchWindow
selectPopup
switchFrame
SelectedOption
location
getElementPositionTop
MoveToElement
mouseDown
mouseUp
dragAndDrop
isEditable
doubleClick
keyPress
dragAndDropOffset

### CODE REVIEW

**Comment by andreastt** [comment]
@samitbadle?

**Comment by samitbadle** [comment]
Hi Phasze,

Thank you for your hard work. I appreciate the effort. Would it possible to provide me with some sample test suites along with the exported output for the newly added commands?
Once I have those, I will update the rest of the official formatters to support these as well.

Cheers,
Samit

**Comment by phasze** [comment]
Sorry, I haven't developed anything for the IDE for almost a year now.  I've been getting all my testers to migrate to programming it themselves.  I'm afraid I won't be going back to develop test suites for these.

**Comment by samitbadle** [comment]
No worries, I will take care of it.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Pull request closed without merging**
