### PR TITLE
Closing out logging on quit

### PR DESCRIPTION
**Pull request by Sean-Gomez**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

The line I added closes out the log file connections before the service performs a full shutdown

### Motivation and Context

A project I'm working on uses the Selenium webdriver and I noticed unclosed sockets remained in some of our unit tests, which could potentially affect performance. This addition should now properly close the open sockets of the log output file process.

### Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by titusfortner — CHANGES_REQUESTED** [review]
The biggest problem is that not all `log_output` instances respond to `close()`. It can be used to set STDOUT or STDERR which are actually `int`

What if we move it to the Service class's `close()` method and put in a conditional so that it works for log file, stdout or null?

**Comment by Sean-Gomez** [comment]
Screenshot from 2023-08-30 13-49-30

Hi Titus, I have attached a screenshot of the modified quit function with a conditional to close log_output whether it's an int or a file-like object. I'm not sure what you meant by move it to the service class's close() function

**Comment by Sean-Gomez** [comment]
Hi Titus, my latest commit should close log_output if it's set to an int like you said. Sorry, but I'm not sure what you meant when you said move it to the server class' close method, could you clarify that if there's still an issue with the commit? Thanks!

**Comment by titusfortner** [comment]
oops, sorry, I meant the `stop()` method: https://github.com/Sean-Gomez/selenium/blob/ed632c22efccab6abb88de25622d9f40a1de389c/py/selenium/webdriver/common/service.py#L142

This logic would apply to all the service classes, not just Firefox.

**Comment by titusfortner** [comment]
Ok, I moved your solution to the stop method. There was already logic there, but I don't think it was doing the right thing.

@isaulv can you double check us on this change?

I think the issue is that devnull needs to be closed and we were ignoring it before. Also not sure what previous code was rescuing; should I keep that just in case?

**Comment by isaulv** [comment]
@titusfortner I think the proposed code is correct. It will close open files (TextIO) and if it's a file descriptor like stdout or stdin, os.close should handle that file descriptor, and even dev/null. 
It shouldn't throw if the resource is already closed.

**Review by isaulv — APPROVED** [review]
LGTM

**Comment by titusfortner** [comment]
Thanks @Sean-Gomez

**Pull request merged**
