### PR TITLE
Update EdgeOptions constructor to use new ms:edgeOptions capability name

### PR DESCRIPTION
**Pull request by stanleyhon**
msedgedriver has been updated to accept ms:edgeOptions instead of goog:chromeOptions in the capabilities. This change updates the .NET bindings to reflect this too.

followup changes to other languages to come.

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by stanleyhon** [comment]
@jimevans also this one too. thanks!

**Comment by bwalderman** [comment]
Can you update EdgeOptions.java as well?

**Comment by stanleyhon** [comment]
Updating java bindings too.

@jimevans just a gentle ping. Would be great to have you take a look at this change.

**Comment by jimevans** [comment]
@stanleyhon Would be great if I had time to look at it. I’m swamped at the moment. Will try to get to it within the next couple of weeks.

**Comment by stanleyhon** [comment]
@jimevans just a reminder we're still looking to get this in when you have time. Thanks!

**Comment by shs96c** [comment]
This seems fine to me. Landing, and hoping that it doesn't break anything for @jimevans!

**Comment by jimevans** [comment]
@shs96c Thanks, Simon. I'm swamped under a bunch of things at the moment.

**Pull request merged**
