### PR TITLE
[py] remove xfail attr for firefox and safari for cookie tests

### PR DESCRIPTION
**Pull request by Delta456**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Removes `@pytest.mark.xfail_safari` and `@pytest.mark.xfail_firefox` attribute for python cookie tests

### Motivation and Context

As per the docs and tested locally the attribute is no longer needed and can be tested with Safari and FireFox

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Removed `@pytest.mark.xfail_firefox` and `@pytest.mark.xfail_safari` decorators from cookie tests, allowing them to run on Firefox and Safari without expected failures.
- This change reflects that the `sameSite` cookie attribute is now supported in these browsers, aligning with local testing results.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>cookie_tests.py</strong><dd><code>Remove xfail markers for Firefox and Safari in cookie tests</code></dd></summary>
<hr>

py/test/selenium/webdriver/common/cookie_tests.py

<li>Removed <code>@pytest.mark.xfail_firefox</code> decorator from tests.<br> <li> Removed <code>@pytest.mark.xfail_safari</code> decorator from tests.<br> <li> Tests can now run on Firefox and Safari without expected failures.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14794/files#diff-478d123ad61d455ee5c2b8195bc8e6f110b6690b75ed4ef5530be6e63b2862fa">+0/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
The common test has been removed from the test matrix for safari since it took 3 hours to complete.
Do you have any idea to optimize it and add it back via https://github.com/SeleniumHQ/selenium/blob/4b7d17441352f990a3a3c322aabde51e392abad7/.github/workflows/ci-python.yml#L126 ?

**Comment by Delta456** [comment]
I will try to see what can be done.

**Comment by Delta456** [comment]
I wasn't able to find a way to optimise this.

A workaround for this can be simply skipping this in the CI like it's done for other tests I believe.

**Review by diemol — APPROVED** [review]
Thank you, @Delta456!

**Pull request merged**
