### PR TITLE
[JS] kill chromium service on quit

### LINKED ISSUE #10795: [🐛 Bug]: chromedriver service is not killed
### What happened?

Even after calling `driver.quit`. Not able to start chrome driver on the same port. Server is not getting killed and the port is not released.

### How can we reproduce the issue?

```shell
const webdriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const BROWSER_NAME = webdriver.Browser.CHROME;

async function getDriver() {
  let service = new chrome.ServiceBuilder(require('chromedriver').path).setPort(9515);

  service.setStdio(['pipe', process.stdout, process.stderr]);

  return new webdriver.Builder()
    .setChromeService(service)
    .forBrowser(BROWSER_NAME)
    .build();
}

async function runTestWithCaps() {
  for (i = 0; i <= 5; i++) {
    try {
      driver = await getDriver();
      await driver.get("http://www.google.com");
      await driver.quit();
    } catch(err) {
      console.log(err);
    }
  }
}

runTestWithCaps();
```

### Relevant log output

```shell
tarting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.


Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1655906636.622][SEVERE]: bind() failed: Address already in use (48)
IPv4 port not available. Exiting...


Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1655906639.852][SEVERE]: bind() failed: Address already in use (48)
IPv4 port not available. Exiting...


Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1655906642.727][SEVERE]: bind() failed: Address already in use (48)
IPv4 port not available. Exiting...

Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1655906647.038][SEVERE]: bind() failed: Address already in use (48)
IPv4 port not available. Exiting...

Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1655906651.742][SEVERE]: bind() failed: Address already in use (48)
```

### Operating System

macOS Monterey

### Selenium version

4.2.2

### What are the browser(s) and version(s) where you see this issue?

chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 102

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by gravityvi**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context

- fixes #10795 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
This is not the right solution because of https://github.com/SeleniumHQ/selenium/issues/10499

The ideal solution is to start a driver per session, and not a single driver for all sessions.

**Comment by gravityvi** [comment]
removed `setDefaultService` as we want one service per instance it doesn't make sense to use same service across all instances of drivers and modified `getDefaultService` to return a new Driver Service instance

**Review by AutomatedTester — APPROVED** [review]
I think this looks fine, I am not sure where the `setDefaultService` command was used in a public setting or why one would use. 

I won't merge as @diemol might have a different view of things to me

**Review by diemol — APPROVED** [review]
Looks good to me, we just need to be responsive in case issues are raised.

**Pull request merged**
