### PR TITLE
[py] moved `MANIFEST.in` contents to `pyproject.toml`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
In this PR I have moved all the information about the non-default/data files that gets shipped as part of selenium package from `MANIFEST.in` to `pyproject.toml file`.

### Motivation and Context
This eliminates the need of having a separate config file `MANIFEST.in` to include all data/non-default files in package.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Moved the contents of `MANIFEST.in` to `pyproject.toml`, streamlining the configuration by using a single file.
- Removed `MANIFEST.in` from the project, as its contents are now managed within `pyproject.toml`.
- Updated `pyproject.toml` to include package data configuration, specifying which files should be included in the package.
- Adjusted the Bazel build configuration to reflect the removal of `MANIFEST.in`.

___

PRDescriptionHeader.CHANGES_WALKTHROUGH
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>BUILD.bazel</strong><dd><code>Remove MANIFEST.in from Bazel build configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/BUILD.bazel

<li>Removed <code>MANIFEST.in</code> from the list of source files for the <br><code>selenium-sdist-pkg</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14680/files#diff-3e8ff3a52e8e6c0b195ea328e17c50ba6d90abca1ce1624110607da20691d7a9">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>MANIFEST.in</strong><dd><code>Remove MANIFEST.in file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/MANIFEST.in

- Deleted the entire `MANIFEST.in` file.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14680/files#diff-a89f6d91ce436fcb6f6a5e2bf1ec8ab24670842fb46be64c67c6555f0ccfdc47">+0/-24</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pyproject.toml</strong><dd><code>Configure package data in pyproject.toml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/pyproject.toml

<li>Added package data configuration to include necessary files in the <br>package.<br> <li> Defined package inclusion and exclusion rules.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14680/files#diff-3adb340b5a499e26b04507d972c31f5cf6fc27a6d81e3f7b547bf50e90c43be3">+22/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by sandeepsuryaprasad** [comment]
@VietND96 I have re-raised this PR once again by fixing a bug. Can you please re-trigger the workflow for this PR.

**Comment by sandeepsuryaprasad** [comment]
@VietND96 would you please consider merging this PR. All the tests are getting are passed.

**Comment by diemol** [comment]
Maybe @AutomatedTester can have a look first?

**Comment by AutomatedTester** [comment]
can you run ` bazel build //py:selenium-wheel` and install the wheel to make sure that everything is still working after this change?

**Comment by sandeepsuryaprasad** [comment]
@AutomatedTester Here is the result.
Screenshot 2024-11-05 at 6 32 34 PM
 
Screenshot 2024-11-05 at 6 50 05 PM

**Comment by AutomatedTester** [comment]
> and install the wheel to make sure that everything is still working 

Did you do this part? Just want to make sure that Bazel is building the correct wheel for us to upload to pypi

**Comment by sandeepsuryaprasad** [comment]
> > and install the wheel to make sure that everything is still working
> 
> Did you do this part? Just want to make sure that Bazel is building the correct wheel for us to upload to pypi

@AutomatedTester 
```
~$ pip3 install selenium-4.26.0.dev202409202351-py3-none-any.whl
Processing ./selenium-4.26.0.dev202409202351-py3-none-any.whl
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.26.0.dev202409202351) (1.26.18)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.26.0.dev202409202351) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.26.0.dev202409202351) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.26.0.dev202409202351) (2023.7.22)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.26.0.dev202409202351) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.26.0.dev202409202351) (1.8.0)
Requirement already satisfied: attrs>=19.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (21.4.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (1.10)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (3.3)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (1.1.0)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio~=0.17->selenium==4.26.0.dev202409202351) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium==4.26.0.dev202409202351) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.26.0.dev202409202351) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.26.0.dev202409202351) (0.13.0)
Installing collected packages: selenium
  Attempting uninstall: selenium
    Found existing installation: selenium 4.24.0
    Uninstalling selenium-4.24.0:
      Successfully uninstalled selenium-4.24.0
Successfully installed selenium-4.26.0.dev202409202351

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

~$ pip3 show selenium
Name: selenium
Version: 4.26.0.dev202409202351
Summary: Official Python bindings for Selenium WebDriver
Home-page: https://www.selenium.dev
Author:
Author-email:
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: certifi, trio, trio-websocket, typing_extensions, urllib3, websocket-client
Required-by:
```

**Comment by VietND96** [comment]
Via CI, I triggered some validation for your reference.
- The change is built Nightly and uploaded to TestPypi: https://test.pypi.org/project/selenium/4.27.0.dev202411051921/#files
- A set of example tests in docs repo run on top of that Nightly build - https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/11691201375

You can inspect further in the uploaded `whl` and source to see all are fine

**Comment by sandeepsuryaprasad** [comment]
> Via CI, I triggered some validation for your reference.
> 
> * The change is built Nightly and uploaded to TestPypi: https://test.pypi.org/project/selenium/4.27.0.dev202411051921/#files
> * A set of example tests in docs repo run on top of that Nightly build - https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/11691201375
> 
> You can inspect further in the uploaded `whl` and source to see all are fine

Sure. I will go through the uploaded files , verify it and will confirm the same.

**Comment by sandeepsuryaprasad** [comment]
@VietND96 , @AutomatedTester 
I have verified the source that is uploaded in PyPI, It looks fine, but in `selenium/webdriver/common` I can see `devtools` folder included as well. Just want to confirm whether or not this folder should be included in final source distribution (with current settings in `pyproject.toml`, this directory would be included as it is a package).

I installed selenium from the uploaded test PyPI. Below are the results.
```
~$ pip3 install -i https://test.pypi.org/simple/ selenium==4.27.0.dev202411051921
Looking in indexes: https://test.pypi.org/simple/
Collecting selenium==4.27.0.dev202411051921
  Downloading https://test-files.pythonhosted.org/packages/3c/c4/59081abb32dd133f1f5720f9fd78c6d27ea2a120de04e1c4db8ed82e4c94/selenium-4.27.0.dev202411051921-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202411051921) (1.26.18)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411051921) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411051921) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from selenium==4.27.0.dev202411051921) (2023.7.22)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/pyt3.11/site-packages (from selenium==4.27.0.dev202411051921) (0.9.2)                               08:38:01 [44/1831]
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3
.11/site-packages (from selenium==4.27.0.dev202411051921) (2023.7.22)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/pyt
hon3.11/site-packages (from selenium==4.27.0.dev202411051921) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/pyth
on3.11/site-packages (from selenium==4.27.0.dev202411051921) (1.8.0)
Requirement already satisfied: attrs>=19.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/s
ite-packages (from trio~=0.17->selenium==4.27.0.dev202411051921) (21.4.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.1
1/site-packages (from trio~=0.17->selenium==4.27.0.dev202411051921) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/pytho
n3.11/site-packages (from trio~=0.17->selenium==4.27.0.dev202411051921) (1.10)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packa
ges (from trio~=0.17->selenium==4.27.0.dev202411051921) (3.3)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-pa
ckages (from trio~=0.17->selenium==4.27.0.dev202411051921) (1.1.0)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-pa
ckages (from trio~=0.17->selenium==4.27.0.dev202411051921) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/s
ite-packages (from trio-websocket~=0.9->selenium==4.27.0.dev202411051921) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.11/li
b/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.27.0.dev202411051921) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/s
ite-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.27.0.dev202411051921) (0.13.0)
Downloading https://test-files.pythonhosted.org/packages/3c/c4/59081abb32dd133f1f5720f9fd78c6d27ea2a120de04e1c4db8e
d82e4c94/selenium-4.27.0.dev202411051921-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 3.8 MB/s eta 0:00:00
Installing collected packages: selenium
  Attempting uninstall: selenium
    Found existing installation: selenium 4.26.0.dev202409202351
    Uninstalling selenium-4.26.0.dev202409202351:
      Successfully uninstalled selenium-4.26.0.dev202409202351
Successfully installed selenium-4.27.0.dev202411051921
```

**Comment by sandeepsuryaprasad** [comment]
@VietND96, @AutomatedTester, can we have this one merged?

**Comment by AutomatedTester** [comment]
> Via CI, I triggered some validation for your reference.
> 
>     * The change is built Nightly and uploaded to TestPypi: https://test.pypi.org/project/selenium/4.27.0.dev202411051921/#files
> 
>     * A set of example tests in docs repo run on top of that Nightly build - https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/11691201375
> 
> 
> You can inspect further in the uploaded `whl` and source to see all are fine

This is what I was asking for repeatedly. This looks great!

**Pull request merged**
