### PR TITLE
remove useless rimraf package, change io public api import

### PR DESCRIPTION
**Pull request by potapovDim**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Remove useless **rimraf** package

### Motivation and Context
[rimraf](https://www.npmjs.com/package/rimraf) package was updated 2 years ago. 
currently nodejs has own API which allows work with io/dirs/files without additional packages
selenium-webdriver js used rimraf only in one place thats why i replaced it to fs and remove **rimraf** from dependencies 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks for the PR. Can you please add the motivation for it and also improve the commit message? This serves for future documentation.

**Comment by potapovDim** [comment]
@diemol yes, sure

**Comment by potapovDim** [comment]
@diemol can you check, when you will have time, please?

**Review by diemol — APPROVED** [review]
Thank you, @potapovDim!

**Pull request merged**
