### PR TITLE
Introduce select support for js

### PR DESCRIPTION
**Pull request by luukvhoudt**
### Description
This PR is the start of the implementation for the select element support class for the JavaScript client. The global documentation already exists and can be found [here](https://www.selenium.dev/documentation/en/support_packages/working_with_select_elements/). The lag of this feature is already noted in the code example boxes on this page. However issue #8721 also mentions this, however it was never solved because the issue lags a template.

### Motivation and Context
Crucial feature for testing and automating.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Josegto1 — APPROVED** [review]

**Comment by AutomatedTester** [comment]
this seems a great start. Let us know when the tests are completed and we can see about merging this PR

**Comment by AutomatedTester** [comment]
@luukvhoudt Are you going to be able to finish this PR?

**Comment by luukvhoudt** [comment]
> @luukvhoudt Are you going to be able to finish this PR?

@AutomatedTester unfortunately not anytime soon, currently I also cannot really make an estimate when I will be able to finish this PR.

**Review by AutomatedTester — APPROVED** [review]

**Comment by potapovDim** [comment]
@AutomatedTester @diemol @harsha509  should _selenium-webdriver_ have all those elements wrappers? maybe it would be better to create separate package?

**Comment by diemol** [comment]
Closing in favor of https://github.com/SeleniumHQ/selenium/commit/35adf8bef56cd5efc166feda96224b74800b8503

**Pull request closed without merging**
