### PR TITLE
[java] case insensitive header names in http requests

### LINKED ISSUE #12697: [🚀 Feature]: use lowercase header names
### Feature and motivation

I would suggest to convert all header names to lowercase in the [`HttpMessage`](https://github.com/SeleniumHQ/selenium/blob/938058d969de2d2512eb8e3a47acea022927c4f2/java/src/org/openqa/selenium/remote/http/HttpMessage.java).
It might be [helpful in the future](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2) to have only lower case header names. 

The header names should be in general treated case-insensitive, but there might be code somewhere not aware of this, so i would see this in Selenium 5.

### Usage example

There is currently a hidden issue due to the case-sensitive map used in the HttpMessage.
The order of headers set depends currently on the map implementation and not on the [order of adding them](https://www.rfc-editor.org/rfc/rfc2616#section-4.2), this can be observed here:
https://github.com/SeleniumHQ/selenium/blob/938058d969de2d2512eb8e3a47acea022927c4f2/java/test/org/openqa/selenium/remote/http/HttpMessageTest.java#L53-L57
`message.getHeader("Content-Length")` should actually return `"1024"`

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

I opened PR with initial changes. i have already asked some questions about feature in feature request ticket
I will implement new tests as soon as I get more information about task details

### Motivation and Context

according to #12697 I started to discover how to implement this feature 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Normalize header names to lowercase in `setHeader` method to ensure case-insensitive handling.
- Normalize header names to lowercase in `addHeader` method to ensure case-insensitive handling.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>HttpMessage.java</strong><dd><code>Normalize header names to lowercase in HTTP message handling.</code></dd></summary>
<hr>
      
java/src/org/openqa/selenium/remote/http/HttpMessage.java

<li>Convert header names to lowercase in <code>setHeader</code> method.<br> <li> Convert header names to lowercase in <code>addHeader</code> method.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14095/files#diff-964afdcb3dadea085ff510cc2d4b3f7bf635dbb38f7581c5889adfdb40d841ca">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
Let's at least wait to merge this after the upcoming release so that Appium can run their tests against nightly and see if it causes them problems before a production release.

**Review by diemol — COMMENTED** [review]
Thank you, @iampopovich!

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Several tests failed. Can you please check?

**Comment by iampopovich** [comment]
@diemol sure 
The `FederatedCredentialManagementTest` could not be executed due to a process creation error on Windows, related to the long path to the executable file. As a result, the test failed three times, despite the successful execution of other tests. 
Screenshot 2024-08-09 at 22 51 06

This failure occurs frequently in test runs on Windows and is not directly related to the changes in the pull request.

**Comment by iampopovich** [comment]
i found issue that can help fix it https://github.com/bazelbuild/bazel/issues/19710

**Comment by diemol** [comment]
I meant this ones https://github.com/SeleniumHQ/selenium/actions/runs/10321185029/job/28573474046?pr=14095

**Comment by iampopovich** [comment]
oh...i see
I mentioned this in the feature request [here](https://github.com/SeleniumHQ/selenium/issues/12697#issuecomment-2153043627). The failing tests need to be fixed under the assumption that headers are now case-insensitive. I will correct the existing tests and resubmit them for review.

Screenshot 2024-08-09 at 23 29 04

**Comment by iampopovich** [comment]
@diemol please verify my changes in tests
I tried to preserve the logic of the checks, considering that header names are now case-insensitive. I also fixed the `HttpMessage.setHeader` method. Previously, it couldn't remove a header because the headers were set in lowercase, while the name was passed in an arbitrary case.

```java
public M setHeader(String name, String value) {
    return removeHeader(name.toLowerCase()).addHeader(name.toLowerCase(), value);
}
```

**Comment by iampopovich** [comment]
i noticed the problem with the formatting 👀

**Comment by iampopovich** [comment]
@diemol i fixed the tests with headers

**Pull request merged**
