### PR TITLE
Prevent grid from creating sessions that are about to timeout in queue (corrects issue #11881)

### PR DESCRIPTION
**Pull request by bhecquet**
### Description
As stated in issue #11881, when Selenium grid receives more session requests than it can handle, some sessions may be created whereas the client that requests it receives a timeout response.
This bug only shows up when `--session-request-timeout` option is set

### Motivation and Context
On our grid setup, for some reasons, many grid nodes may become unavailable (upgrade, electrical failure, network failure, ...)
In this case the remaining nodes are not able to handle all the incoming session requests. These requests goes to queue, but we observed that at some point, a browser may be created on node and never used (it remains in this state 5 minutes) before session is killed by grid.

This is due to the fact (details and logs can be found in mentionned issue: https://github.com/SeleniumHQ/selenium/issues/11881#issuecomment-1532552648)
- LocalNewSessionQueue waits at most 30 seconds (the configured session request timeout) before sending timeout to client
- nothing prevents the distributor to create the requested session just before that (e.g: at 29 secs)
- session creation takes about 2 seconds so when session si created, client has already received the timeout exception and will never use the created session

Correction takes place in LocalNewSessionQueue. When session request timeout expires, we first check if the session is still in queue or not (session not in queue means distributor is about to create it). In the latter case we wait a bit more so that distributor has time to create the session.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Remark: added tests are a bit long to run to test timeout behaviour

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you for this PR!

I think you have a good point, where the current logic allows for a window where the timeout is triggered but still the Distributor can create a session that will end up being orphaned. 

However, I do not think the approach in the PR is completely correct, or clean at least. This PR is basically waiting 5 seconds more for the session request to resolve.

A nicer approach, I think, is to put the logic you are putting in `isRequestInQueue`as a filter in `timeoutSessions`. With that, we timeout only session requests that are present in the `queue`.

Something around the lines of:

```java
  private void timeoutSessions() {
    Instant now = Instant.now();

    Lock readLock = lock.readLock();
    readLock.lock();
    Set<RequestId> ids;
    try {
      ids =
          requests.entrySet().stream()
              .filter(
                  entry ->
                      queue.stream()
                          .anyMatch(
                              sessionRequest ->
                                  sessionRequest.getRequestId().equals(entry.getKey())))
              .filter(entry -> isTimedOut(now, entry.getValue()))
              .map(Map.Entry::getKey)
              .collect(ImmutableSet.toImmutableSet());
    } finally {
      readLock.unlock();
    }
    ids.forEach(this::failDueToTimeout);
  }
```

(Might need testing, I just quickly tried this).

What do you think?

**Comment by bhecquet** [comment]
Hello

I think that my PR needed to be improved but, correct me if I'm wrong, the timeoutSessions method is only called once every 10 seconds by default and would not prevent the current problematic behaviour
Maybe we should (Or I misunderstand your exemple) combine both approaches:
- keep my change in 'addToQueue' method because there is no way to tell the latch not to timeout if session is being created
- take your suggestion for 'timeoutSessions' method which is way better than increasing the whole timeout

**Comment by bhecquet** [comment]
I changed the code as suggested

**Comment by diemol** [comment]
> Hello
> 
> I think that my PR needed to be improved but, correct me if I'm wrong, the timeoutSessions method is only called once every 10 seconds by default and would not prevent the current problematic behaviour Maybe we should (Or I misunderstand your exemple) combine both approaches:
> 
>     * keep my change in 'addToQueue' method because there is no way to tell the latch not to timeout if session is being created
> 
>     * take your suggestion for 'timeoutSessions' method which is way better than increasing the whole timeout

I think you are right to point out that we were timing out session requests that were being processed by the Distributor. Now that this PR is taking that into account, it should not happen anymore. Thank you.

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Oh wait, somehow when I reviewed the change set I only saw the filter added, not the initial code. I will revert the piece that adds the 5 seconds and go with the filter only. If the bug is still present, we can consider the other part of the PR.

**Comment by diemol** [comment]
Well, the tests you added are now failing. So maybe all the code you added is needed 😄 

I will leave it as it is, but hopefully you can be around in case bugs are raised.

**Comment by bhecquet** [comment]
Yes, I'll be happy to contribute improve it if necessary

**Pull request merged**
