### PR TITLE
Update chromeOptions key for capabilities

### PR DESCRIPTION
**Pull request by kereliuk**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by lmtierney** [comment]
@JKereliuk do you know how far back this works with older chromedriver versions, for backward compatibility? Will we break anything if we send both, or will it use `goog` and ignore the latter if both are sent?

**Comment by JKereliuk** [comment]
Good point, this works only as of Chromedriver 2.31.
Not sure if that is far enough back to justify.
@scs96c I noticed you updated this for the Java bindings, what do you think about the python bindings?

**Comment by shs96c** [comment]
giphy

The W3C payload should only have the `goog:` prefixed version, but the JSON Wire Protocol payload can have both, and that's legit.

**Comment by p0deje** [comment]
Or you can just use `goog:chromeOptions` like [.NET does](https://github.com/SeleniumHQ/selenium/blob/0303d312797ede068ef0165ab49ef85c3d10a88d/dotnet/CHANGELOG#L3-L6).

**Comment by shs96c** [comment]
You need both if you're going to support older versions of chrome.

**Comment by p0deje** [comment]
Yep, while .NET doesn't do this since 3.5.2.

¯\_(ツ)_/¯

**Comment by jimevans** [comment]
That's because I was a little overzealous in making sure the latest was supported going forward. Well, that, and being on "not the latest version of Chrome" takes a fair bit of work on the user's part.

**Comment by lmtierney** [comment]
Thanks @JKereliuk!

**Pull request merged**
