### PR TITLE
[Grid] Add delete files method

### LINKED ISSUE #11986: [🚀 Feature]: Implement DELETE request that deletes all present files in a session in /session/{sessionId}/se/files in grid
### Feature and motivation

I understand that files get automatically deleted after a session but let's say I have a test case (which I really do) that does 10 file downloads and those files don't have unique names. Now with the existing implementation when a POST request is made to "/session/{sessionId}/se/files" it will fetch all the files again and there will be a discrepancy between what file I need and what file is being given to me by the endpoint. To avoid this, if a DELETE request is supported, after fetching each file we could delete it and not worry about what file is being provided to us because other files just got deleted. 

Code example below - 

### Usage example

```java
protected String getDownloadedFileByGrid( String expectedFile ) throws Exception {

		 String home = System.getProperty("user.home");
		 SessionId sessionId = ( ( RemoteWebDriver ) driver ).getSessionId();
		 File dirToCopy = new File(home + File.separator + "Downloads" + File.separator +  "gridnodes" + File.separator + sessionId);
		 String uri = String.format("/session/%s/se/files", sessionId );

		 String fileToDownload = null;

		 try ( HttpClient client = HttpClient.Factory.createDefault().createClient(new URL( "http://localhost:4444/" ) )) {
			
			 HttpRequest request = new HttpRequest( org.openqa.selenium.remote.http.HttpMethod.GET, uri);
			 HttpResponse response = client.execute(request);
			 String text = string(response);
			 Type responseType = new TypeToken<Map<String, Map<String, List<String>>>>() {
			 }.getType();
			 Map<String, Map<String, List<String>>> map = new Json().toType(text, responseType);
			 Map<String, List<String>> parsedResponse = map.get("value");
			 for (String eachFile : parsedResponse.get("names")) {
				 if( eachFile.contains( expectedFile ) ) {
					 fileToDownload = eachFile;
					 break;
				 }
			 }
		 }

		 try (HttpClient client = HttpClient.Factory.createDefault().createClient(new URL( "http://localhost:4444/" ) )) {

			 HttpRequest request = new HttpRequest( org.openqa.selenium.remote.http.HttpMethod.POST, uri);
			 request.setContent( Contents.asJson(singletonMap("name", fileToDownload)));
			 HttpResponse response = client.execute(request);
			 String text = string(response);
			 Type responseType = new TypeToken<Map<String, Map<String, String>>>() {
			 }.getType();

			 Map<String, Map<String, String>> map = new Json().toType(text, responseType);
			 Map<String, String> parsedResponse = map.get("value");
			 String encodedContents = parsedResponse.get("contents");
			 Zip.unzip(encodedContents, dirToCopy );
			 System.out.println("The file which was "
					 + "downloaded in the node is now available in the directory: "
					 + dirToCopy.getAbsolutePath());
		 }

		 return dirToCopy + File.separator + fileToDownload;
```

This is where the problem is -
```
for (String eachFile : parsedResponse.get("names")) {
				 if( eachFile.contains( expectedFile ) ) {
					 fileToDownload = eachFile;
					 break;
				 }
			 }
```

Let's say I download 10 files and they don't have unique names and I say give me file that contains ".xls" or ".pdf". First file we get is good but when It downloads the second file, the list of files from node is fetched again. It will check ok this first file contains ".xls" or ".pdf and it will return back the same file.

### PR DESCRIPTION
**Pull request by aldobrynin**
Implement delete files method: `DELETE /session/{sessionId}/se/files`

Fixes #11986

### Description
Implemented method to delete all files in current session's downloads directory

### Motivation and Context
Sometimes it is required to cleanup downloads directory. For example, in order to use pooled session developers need to be able to reset session state before next test run. Downloads directory is of the session features that one might want to cleanup during session lifecycle

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by karanjeetbirdeye** [comment]
If a file is downloaded and gets deleted from session, when the next downloaded file is present in session, it would give us only 1 file (last downloaded file) or all of them?

**Comment by aldobrynin** [comment]
> If a file is downloaded and gets deleted from session, when the next downloaded file is present in session, it would give us only 1 file (last downloaded file) or all of them?

it would give us only 1 file

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@diemol - I have gone through the changes and they look good to me.

**Review by diemol — APPROVED** [review]
Thank you, @aldobrynin!

Thank you for reviewing, @krmahadevan!

**Pull request merged**
