### PR TITLE
selenium manager: check invalid browser version

### PR DESCRIPTION
**Pull request by Delta456**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Returns an error instead of downloading the possible browser version

### Motivation and Context

Fix the issue https://github.com/SeleniumHQ/selenium/issues/13418

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Implemented error handling in `SeleniumManager` to return an error when an invalid browser version is provided, preventing unnecessary downloads.
- Added a test case to verify the behavior when an invalid browser version is specified, ensuring the system fails gracefully.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>lib.rs</strong><dd><code>Add error handling for invalid browser version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

rust/src/lib.rs

<li>Added error handling for invalid browser version input.<br> <li> Prevented downloading of browser when version mismatch occurs.<br> <li> Set fallback driver from cache to false.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14511/files#diff-f64796ccc388f201986ea7eaaf07bbefbd8ac1a56bb995fb505da80879872a39">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>browser_tests.rs</strong><dd><code>Add test for invalid browser version handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

rust/tests/browser_tests.rs

<li>Added a new test for invalid browser version.<br> <li> Ensured the test checks for failure with incorrect version input.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14511/files#diff-c4663bdd0f9bda0b1870b94fe25dc61d2fec5ba6431521a52a330f8002a654c3">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by bonigarcia** [comment]
This implementation is not correct since it will make Selenium Manager to fail even for valid browser versions (e.g., Chrome 127). See for example:

```
cargo run -- --debug --browser chrome --browser-version 127

[2024-09-19T13:58:36.355Z DEBUG] chromedriver not found in PATH
[2024-09-19T13:58:36.357Z DEBUG] chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
[2024-09-19T13:58:36.358Z DEBUG] Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
[2024-09-19T13:58:36.521Z DEBUG] Output: "\r\r\n\r\r\nVersion=128.0.6613.138\r\r\n\r\r\n\r\r\n\r"
[2024-09-19T13:58:36.528Z DEBUG] Detected browser: chrome 128.0.6613.138
[2024-09-19T13:58:36.528Z DEBUG] Discovered chrome version (128) different to specified browser version (127)
[2024-09-19T13:58:36.529Z ERROR] Invalid version 127 provided
```

Also, the error message can be enhanced a bit:

```
                        return Err(anyhow!(format!(
                            "Invalid {} version provided: {}",
                            self.get_browser_name(),
                            major_browser_version
                        )));
```

**Comment by Delta456** [comment]
Oops look like I didn't consider all test cases. I will take a look 😅

**Comment by bonigarcia** [comment]
I reviewed this PR. I'm sorry, but it is not correct.

First, adding a call to `request_fixed_browser_version_from_online` like that is not a good idea. You can discover by yourself by running all the existing tests with:

```
cargo test
```

Also, the two new test cases are not adequate. First, `invalid_browser_version_test()` is redundant. See [here](https://github.com/SeleniumHQ/selenium/blob/trunk/rust/tests/browser_tests.rs#L68). Second, the logic assessed by `valid_browser_version_pass_test()` is already covered by this [test](https://github.com/SeleniumHQ/selenium/blob/trunk/rust/tests/browser_download_tests.rs#L56).


#13418 should be done with the following changes in `lib.rs`:

```
         // Download browser if necessary
         match self.download_browser_if_necessary(&original_browser_version) {
             Ok(_) => {}
-            Err(err) => self.check_error_with_driver_in_path(&use_driver_in_path, err)?,
+            Err(err) => {
+                self.set_fallback_driver_from_cache(false);
+                self.check_error_with_driver_in_path(&use_driver_in_path, err)?
+            }
         }
```

**Comment by Delta456** [comment]
@bonigarcia You are right. I have committed the code changes as suggested by you. Please let me know if something is missing.

**Review by bonigarcia — APPROVED** [review]
LGTM

**Pull request merged**
