### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jochenberger**
- [ ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by p0deje** [comment]
Have you signed [CLA](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)?

**Comment by jochenberger** [comment]
No. Is that really necessary for a simple typo fix?

**Comment by p0deje** [comment]
Yes, that's what license requires everyone to do. It's just a simple form - https://docs.google.com/forms/d/e/1FAIpQLSd2FsN12NzjCs450ZmJzkJNulmRC8r8l8NYwVW5KWNX7XDiUw/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0

**Comment by jochenberger** [comment]
Never mind then.

**Comment by ddavison** [comment]
We go by the [Obvious Fix Rule](https://docs.chef.io/community_contributions.html#the-obvious-fix-rule)

> HOWEVER, very small contributions such as fixing spelling errors, where the content is small enough to not be considered intellectual property, can be submitted by a contributor as a patch, without a [CLA] sign-off.

**Comment by shs96c** [comment]
Indeed. The Obvious Fix Rule clearly applies here.

**Comment by p0deje** [comment]
Thank you, I wasn't even aware of "Obvious Fix Rule".

**Pull request merged**
