### PR TITLE
Add awaitable method for Support.UI.DefaultWait

### PR DESCRIPTION
**Pull request by njahs**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

This makes it possible to wait asynchronously until something occurs based on the Task-based Asynchronous Pattern recommended by Microsoft.

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/5977)

### CODE REVIEW

**Comment by createS0ftware** [comment]
Any update on this ?

**Comment by diemol** [comment]
I believe this won't be merges as it is because there are technical/architectural decisions to be made in the .NET bindings before this eventually gets merged. Please add yourself as a watcher to #8009, and when a decision is made there, we could reopen and have a look at this PR (given that it aligns wiht the decision).

**Comment by giuliodz** [comment]
Still no plans on doing this?

**Comment by titusfortner** [comment]
We're still looking into doing a rewrite of .NET to be all Async focused rather than adding async functionality piecemeal.

**Pull request closed without merging**
