### PR TITLE
Dict comprehension

### PR DESCRIPTION
**Pull request by machinexa2**
https://www.programiz.com/python-programming/dictionary-comprehension
Since it's basically copying dictionary there might be more better or faster way to do it

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by machinexa2** [comment]
I think it's better to use samesies.copy()

**Comment by machinexa2** [comment]
https://github.com/SeleniumHQ/selenium/pull/10677

**Comment by machinexa2** [comment]
Both does the same job. Merge the PR which is best. I think copy() one is best because it's fastest but does it break any functionality???? Let me know which you merged and I will close the other

**Comment by symonk** [comment]
closing since https://github.com/SeleniumHQ/selenium/pull/10677 is a thing, we can implement whatever there.

**Pull request closed without merging**
