### PR TITLE
[py] Refactored `remote/client_config.py` by moving `properties` into `descriptor` object

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Refactored `remote/client_config.py` by moving whole bunch of `getters` and `setters` to descriptor object

### Motivation and Context
Refactored `remote/client_config.py` by moving whole bunch of `getters` and `setters` to descriptor object
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Introduced a new `_ClientConfigDescriptor` class to handle property access in a more maintainable way
- Replaced 13 pairs of getter/setter methods with descriptor-based properties, significantly reducing code duplication
- Maintained all existing functionality while making the code more concise and easier to maintain
- Properties affected include: remote_server_addr, keep_alive, proxy, ignore_certificates, timeout, ca_certs, username, password, auth_type, token, user_agent, and extra_headers

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>client_config.py</strong><dd><code>Refactor properties using descriptor pattern</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/selenium/webdriver/remote/client_config.py

<li>Added new <code>_ClientConfigDescriptor</code> class to handle property descriptors<br> <li> Replaced multiple getter/setter methods with descriptor-based <br>properties<br> <li> Simplified code by removing redundant property decorators and their <br>implementations<br> <li> Maintained same functionality while reducing code duplication<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14899/files#diff-421b55d14e80d4473c60003a3f53c9fa819375d52cb45b6c40403f481a9b8925">+38/-170</a></td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by diemol** [comment]
@shbenzer @VietND96 does this PR make sense?

**Review by VietND96 — APPROVED** [review]
These properties are covered in unit tests. Just need to resolve the format and `tox` rules

**Comment by sandeepsuryaprasad** [comment]
> These properties are covered in unit tests. Just need to resolve the format and `tox` rules

fixed linting issue with docformatter.

**Comment by VietND96** [comment]
@sandeepsuryaprasad, looks like rebase issue, lots of changes included?

**Comment by sandeepsuryaprasad** [comment]
> @sandeepsuryaprasad, looks like rebase issue, lots of changes included?

Cleaned it up.. Can you please check now..

**Comment by shbenzer** [comment]
> @shbenzer @VietND96 does this PR make sense?

LGTM

**Review by diemol — APPROVED** [review]
Thank you, @sandeepsuryaprasad!

**Pull request merged**
