### PR TITLE
Fix "Get Text" to retrieve the correct value for ShadowRoot using slot.

### LINKED ISSUE #13206: [🐛 Bug]: "Get Text" atom ignores slot value for web component without custom text
### What happened?

The Selenium atom `Get Text` should not only return the value from a slot when it is used but also it's default value when it has not been used. In the example below the value `foobar` is visible as text but the atom `Get Text` returns just `bar`.

### How can we reproduce the issue?

```shell
With the following testcase it can be reproduced:


    <head>
      <script>
        class TestContainer extends HTMLElement {
          connectedCallback() {
            this.attachShadow({ mode: 'open' });
            this.shadowRoot.innerHTML = `<slot><span>foo</span></slot>bar`;
          }
        }

        customElements.define('test-container', TestContainer);
      </script>
    </head>

    <body>
      <test-container></test-container>
    </body>
```

CC @43081j in case you are interested.
```


### Relevant log output

```shell
No log output available.
```

### Operating System

MacOS 13.6

### Selenium version

Latest

### What are the browser(s) and version(s) where you see this issue?

Firefox (not tested with others)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver (not tested with others)

### Are you using Selenium Grid?

No

### PR DESCRIPTION
**Pull request by whimboo**
Fixes https://github.com/SeleniumHQ/selenium/issues/13206

### Description
As discussed on issue https://github.com/SeleniumHQ/selenium/issues/13206 the "Get Text" atom currently fails to retrieve the correct text for ShadowRoot elements using `<slot>`. 

### Motivation and Context
This currently blocks WebDriver implementations using the Get Text atom to correctly retrieve the visible text of such an element.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
@diemol shouldn't this PR have kicked off the RBE job? Should we have changes in atoms directory run all the other tests as well? (Also, should we implement a way to run specific CI jobs on a PR based on specific words in a comment?)

**Comment by diemol** [comment]
@titusfortner I do not know. I have not even tried the RBE build. @shs96c should know.

**Comment by titusfortner** [comment]
I'm asking about the github CI starting the build in the first place, and thinking about whether we need to update the logic.
I was in this code yesterday for other reasons, I'll take a look today.

**Comment by whimboo** [comment]
@titusfortner any chance that you can trigger the workflows? Or should it wait for your investigation and the bot will do it afterward?

**Comment by titusfortner** [comment]
running; I never see that it needs to be done when I check from my phone ☹️

**Comment by whimboo** [comment]
@titusfortner or @diemol, it seems the tests were running fine and test failures existed in other areas. I've now rebased my PR to current trunk, but it requires again someone to manually approve the workflows. :/ Maybe you could help?

**Comment by whimboo** [comment]
@AutomatedTester or @shs96c could one of you please review? Or if not whom can I ask? Thanks!

**Comment by whimboo** [comment]
Thank you @titusfortner!

**Comment by whimboo** [comment]
FYI I'm going to update the Selenium atom reference in WebDriver classic on https://github.com/w3c/webdriver/issues/1783

**Pull request merged**
