### PR TITLE
Issue #10045  uploadFile not working with docker images exposing chromedriver directly

### PR DESCRIPTION
**Pull request by tyge68**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Updating to allow switching the uploadFile command using system property selenium.uploadFileMode
the default will still use the current solution to use the /se/file endpoint, while other value  would allow to use different implementation "chromedriver" mode for example.

### Motivation and Context
While updating to latest selenium 4.0 we encountered issues with the uploadFile command using docker image (selenoid/vnc:chrome_95.0) which used to work very well in the past. Based on the history of the uploadFile which was first set to use /file and finally again to use /se/file , it appears that it would make sense to allow to choose which endpoint to use for that command rather than to force one implementation.

### Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by jimevans** [comment]
I don’t use the docker images in my day-to-day work, but I am -1 on this change. The `/file` end point is not compliant with the W3C WebDriver Specification; the `/se/file` end point is. We should be aiming to be spec-compliant everywhere we can.

**Comment by tyge68** [comment]
@jimevans so you mean Google / Chrome should provide a Chromedriver that should expose the upload file endpoint on /se/file ? similar to other endpoint that are already under /se/  , ie /se/logs etc.. ? who can make this happen ?

**Comment by titusfortner** [comment]
I agree with Jim, Selenium should only be using w3c compliant endpoints. 

We are expecting that client code will only act directly with drivers when on the same machine, and that the user will only send commands to a driver on a remote machine via a server. 

An alternative to adding a Selenium server to your container would be to get the W3C spec to add an official `upload` endpoint that accepts a BASE64 zipped file as the value. Looks like an upload endpoint was agreed to (https://github.com/w3c/webdriver/issues/1355), and it might make sense for it to support the file itself rather than just a String representing the path (which would avoid the whole Local File Detector requirements).

**Comment by tyge68** [comment]
Thanks, actually I found a simpler solution, there is no need actually for the ../se/file etc.. implementations since nowaday you can easily copy files to your docker too, before send keys to the input. Thus I guess it's the reason it won't be part of the w3c too.

**Comment by titusfortner** [comment]
Oh, right, yes. I was going to include that as an option and got distracted and forgot. Make sure when you do that, though, that the path is different from client machine and / or that a Local File Detector is not set.

**Pull request closed without merging**
