### PR TITLE
[py] optimised `Proxy` object in `common/proxy.py`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Optimised `Proxy` object by replacing multiple `getters` and `setters` by a custom `ProxyDescriptor` .

### Motivation and Context
- If you carefully observe `Proxy` object in `common/proxy.py`, we are `getting` and `setting` multiple proxy attributes (around 10 attributes) through `getters` and `setters`.

- For each attribute we have one pair of `getter` and `setter` methods. So, for all 10 different attributes together we have 10 pairs of `getter` and `setter` methods (totally 20 methods).
- If you look at each `setter` method, we are doing 3 things in common, `_verify_proxy_type_compatibility`, set `proxyType` and assign `value` to each specific proxy.
- So, there is lot of scope here for optimisation and I have done it by replacing multiple `getters` and `setters` by a custom descriptor.
- Now the code in `Proxy` object is reduced to a great extent and looks lot cleaner since multiple `getters` and `setters` are being eliminated.
- Also, the method `to_capabilities` is being optimised by eliminating multiple `if` conditions.
### Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
There are more changes in this PR than the ones mentioned in the description. Could you please fix this?

**Comment by sandeepsuryaprasad** [comment]
> There are more changes in this PR than the ones mentioned in the description. Could you please fix this?

The only file that is changed in this PR is `common/proxy.py`. But it shows two files are being changed `proxy.py` and `errorhandler.py`, because when I submitted this PR, my previous PR (12190) related to `errorhandler.py` was not merged. So it is showing the changes made in this PR as well as previous PR (12190)

**Comment by diemol** [comment]
I see. Can you please leave this PR with the changes that should be included in it?

**Comment by titusfortner** [comment]
Yes, please rebase with trunk.

**Comment by sandeepsuryaprasad** [comment]
> Yes, please rebase with trunk.

Done.

**Comment by sandeepsuryaprasad** [comment]
Now the docstrings are displayed in IDE.

Screenshot 2023-06-17 at 8 04 17 PM
Screenshot 2023-06-17 at 8 03 12 PM

**Comment by AutomatedTester** [comment]
This PR appears to be littered with all the other PRs. Could we update it to be just about Proxy please as it makes it harder to review. I think this is ok but would need a smaller PR to review properly

**Comment by AutomatedTester** [comment]
Also, could we improve the commit messages to explain the change in 1 line and the rationale in subsequent lines. This comment will appear on all PRs

e.g.

```
Moved Proxy to use Descriptors

Moving to descriptors has the following benefits
...
...
...
```

**Pull request closed without merging**
