### PR TITLE
Set chromedriver to be a new process group leader

### PR DESCRIPTION
**Pull request by bsedat**
Allows for easier killing of the entire chromedriver process tree.

I have signed the CLA as "Benjamin Sedat".

### CODE REVIEW

**Comment by p0deje** [comment]
I'm not sure I follow your reasoning. What do you mean by "easier killing of the entire chromedrvier process tree"?

I may understand Unix process model wrong, but as far as I get it, chromedriver inherits runner process group ID (e.g. test runner, irb), so that when signal is sent to test runner, all processes in this process group receive signal. If chromedriver starts new process group, the signals will not be sent to it and its children process (Chrome).

Can you please elaborate on this a bit more?

**Comment by bsedat** [comment]
I was running into an issue where chromedriver was getting orphaned and reparented to pid 1. I was hoping to use this as a way to facilitate killing the whole chromedriver process tree when this occurs. Any suggestions for workarounds? Or should this an option that could be set?

**Comment by p0deje** [comment]
I would rather figure out the reason why chromedriver gets orphaned, it should not happen. Can you find a way to reproduce the issue?

**Comment by p0deje** [comment]
Closing since there is no response for more than 3 months. Please re-open if necessary.

**Pull request closed without merging**
