### PR TITLE
Fix sub path for UI

### LINKED ISSUE #11647: [🚀 Feature]: Allow user to provide a different base URL for the grid UI
### Feature and motivation

For the moment the base URL of a grid is locked to be /ui/ at root level.
For my usage i had to manually change the path in the file : selenium/grid-ui/package.json at line 38 `"homepage": "/ui"` to `"homepage": "/selenium/ui"`

Because for my usage the base URL host multiple services (so i have my URL like this www.myUrl.com/selenium/ui) 

Currently i found no other way to provide the grid a custom base without having to recompile everything after a manual change.

### Usage example

The grid could simply read an environment variable such as GRID_BASE_URL and if this variable exist use it instead of the /ui written in the code

### PR DESCRIPTION
**Pull request by yashcho**
[grid-ui] Re-route all internal endpoints with subpath

Fixes #11647

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Grid UI can now re-route all internal router request for hub that contains /ui and /graphql paths through provided subpath

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@diemol - The changes look good to me. Please help check if you are fine as well so that we can take this forward and have it merged.

**Comment by yashcho** [comment]
Thanks @krmahadevan

**Review by diemol — COMMENTED** [review]
I apologize for my late review of this PR, the SeleniumConf plus the Eastern holidays dragged me away for a while. 

So, the code seems correct and the sub path feature works. However, I believe the changes are made on the wrong place. @yashcho, I believe your [comment](https://github.com/SeleniumHQ/selenium/issues/11647#issuecomment-1452218579) was right on track, and after reading the PR and the associated issue, I googled a bit and the fix had to be done where you pointed it out. 

I believe the original implementation of sub-path by @krmahadevan is correct, but we needed to make a couple of changes on the React application to have it working completely. 

After googling, I found the [CRA docs](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths) where they point how to make the base path relative without the need of rebuilding the app. Plus then I tweaked the GraphQL URL. I tested it locally and I can see how all requests get routed through the prefix. Maybe something is still missing but we know now where to tweak things. This [commit](https://github.com/SeleniumHQ/selenium/commit/a1430636faa348298ea9db15aec21b4e25989605) shows the changes done.

Thank you @yashcho for putting the time and effort to work on this, and I am sorry to reject the PR given the reasons above.

**Comment by krmahadevan** [comment]
@diemol - This was a good learning. Thanks for sharing an important lesson, that I kind of conveniently forgot.. _Treat the problem, not the symptom_ I guess my lack of UI skills is what caused this wild goose chase. Will be more careful

@yashcho My humble apologies if the review feedback I shared basically led you to explore the wrong solution and also cost you a lot of time, which could have been better spent.

**Comment by yashcho** [comment]
Thank you @diemol for the feedback even I had same track in my mind but due to lack of knowledge against React I didn't tried this [commit](https://github.com/SeleniumHQ/selenium/commit/a1430636faa348298ea9db15aec21b4e25989605), so I accept the closing of MR if this can be done in simple and not hacky way.. :)

@krmahadevan no issue the comments and your guidance gave me some new learnings and the time I invested tough me that I am able to explore and fix the issue even if it not direct way.. :)

Thanks once again to both you and hope I would contribute in future features or bugs.. :), 

Will wait for next release to get it tested.. :)

**Pull request closed without merging**
