### PR TITLE
Style changes (PEP8)

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by cgoldberg** [comment]
+1

**Comment by lukeis** [comment]
@cool-RR can you please sign the [cla](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)

**Comment by cool-RR** [comment]
Already signed a day or two ago. You don't see it?

**Comment by lukeis** [comment]
Only one person has read access to it :) so we mainly take people's word for it (until we program a cla checker...)

Thanks! I'll look at getting this merged soon (on my phone)

**Comment by lukeis** [comment]
merged with b5a1d0783cc8b288be9ed2f37ff23bb40b676260

**Pull request closed without merging**
