### PR TITLE
[py] added `Select` and `WebDriverWait` classes to `webdriver/__init__.py`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Added `Select` and `WebDriverWait` classes to `webdriver/__init__.py`

### Motivation and Context
The above classes were missing from `webdriver/__init__.py` file.  Now `Select` and `WebDriverWait` classes can be directly imported by importing `webdriver` package.

### Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
I don't want to add items from support module to `__init__`. We still need to have a larger conversation in TLC about how we are managing support classes for Selenium 5.

**Comment by isaulv** [comment]
Some framework writers use their own waiting mechanisms. WebdriverWait has a few issues with certain kinds of waits so people use alternative or custom implementations.

**Comment by AutomatedTester** [comment]
I would rather not have support classes available like this. Keeping them in the support name space means we could remove them into a separate library later

**Comment by AutomatedTester** [comment]
Thanks for creating this PR but we're not going to go forward with it.

**Pull request closed without merging**
