### PR TITLE
[build] Switch to ready-to-use Docker Super-Linter image

### PR DESCRIPTION
**Pull request by valfirst**
### Description
Use pre-built Docker Super-Linter image instead of building it every time

### Motivation and Context
According to the official [documentation](https://github.com/github/super-linter/blob/366771ba4ec760c65d661807be7ce507bef2ce59/README.md):
> **NOTE:**
Using the line:`uses: docker://github/super-linter:v3` will pull the image down from **DockerHub** and run the **GitHub Super-Linter**.   Using the line: `uses: github/super-linter@v3` will build and compile the **GitHub Super-Linter** at build time. *This can be far more costly in time...*

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
I am about to turn off the linter as it doesn't appear to work properly if you no longer have a `master` branch.

**Comment by valfirst** [comment]
@AutomatedTester I've added the explicit branches configuration: https://github.com/SeleniumHQ/selenium/pull/8519/commits/a4a6df2840ca7fc354ec2523ff8e9f8ee821ba46. Will it help?

**Comment by AutomatedTester** [comment]
> @AutomatedTester I've added the explicit branches configuration: [a4a6df2](https://github.com/SeleniumHQ/selenium/commit/a4a6df2840ca7fc354ec2523ff8e9f8ee821ba46). Will it help?

Let's see if it starts working. I specified the default branch already according to their docs as an environment variable.

**Comment by AutomatedTester** [comment]
looks good!

Thank you for your contribution!

**Pull request merged**
