### PR TITLE
[grid] do not offload from multiple threads to a single worker

### PR DESCRIPTION
**Pull request by joerg1985**
The RequestConverter did read the payload of http request in a single worker thread. The netty framework creates multiple 
threads to read concurrent http requests, these where all send to this single worker thread and had to wait for this thread
to finish reading. Even GET http requests without payload had to wait until the `PipedOutputStream` was closed. On the other side
the reading thread had to wait after writing 1024 bytes to the `PipedOutputStream` for the netty framework thread to read the data. 

It was not possible to just increase the single thread to multiple threads to optimize this situation. The jobs submitted to the work-queue could have been executed in the incorrect order (e.g. the close is called before all data is red).

If something went wrong while processing a read/write lock could happen
https://github.com/SeleniumHQ/docker-selenium/issues/1646
https://github.com/SeleniumHQ/docker-selenium/issues/1605

This PR will:
- read the payload inside the thread handling the netty callback
- not kind of synchronize requests on a single thread 
- have less overhead while handling GET requests
- ensure there will be no other read/write lock issues
- remove the workaround added in [#f569d7f](https://github.com/SeleniumHQ/selenium/commit/f569d7f6b1f2a35ea41d9604cdc69dbbd5f58485)

I had some benchmarks on my local system and could not see any regression due to this change.
Some benchmark runs got slightly faster and might even get faster with more concurrent sessions.

This is one of the benchmarks, i know this is a synthetic benchmark and the results might be different with real workloads:
```
		System.setProperty("webdriver.http.factory", "jdk-http-client");

		AtomicInteger done = new AtomicInteger(0);
		final int rounds = 10000;

		Thread a = new Thread(() -> {
			try {
				WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"),  new ChromeOptions());
				driver.manage().window().maximize();
				driver.get("https://justepourtester.net/selenium/selenium_wait.html");

				WebElement input = driver.findElement(By.tagName("input"));

				Instant start = Instant.now();
				Instant end = null;

				for (int i = 0; done.get() != 4; i++){
					if (i == rounds) {
						end = Instant.now();
						done.incrementAndGet();
					} else if (i % 2000 == 0) {
						System.out.println("A@" + i);
					}
					input.getAttribute("class");
				}


				System.out.println("A took " + Duration.between(start, end).getSeconds());
				driver.quit();
			} catch (Exception e) {
				e.printStackTrace();
				System.exit(111);
			}
		});

		Thread b = new Thread(() -> {
			try {
				WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"),  new ChromeOptions());
				driver.manage().window().maximize();
				driver.get("https://justepourtester.net/selenium/selenium_wait.html");

				WebElement body = driver.findElement(By.tagName("body"));

				Instant start = Instant.now();
				Instant end = null;

				for (int i = 0; done.get() != 4; i++){
					if (i == rounds) {
						end = Instant.now();
						done.incrementAndGet();
					} else if (i % 2000 == 0) {
						System.out.println("B@" + i);
					}
					body.isDisplayed();
				}

				System.out.println("B took " + Duration.between(start, end).getSeconds());
				driver.quit();
			} catch (Exception e) {
				e.printStackTrace();
				System.exit(222);
			}
		});

		Thread c = new Thread(() -> {
			try {
				WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"),  new ChromeOptions());
				driver.manage().window().maximize();
				driver.get("https://justepourtester.net/selenium/selenium_wait.html");

				Instant start = Instant.now();
				Instant end = null;

				for (int i = 0; done.get() != 4; i++){
					if (i == rounds) {
						end = Instant.now();
						done.incrementAndGet();
					} else if (i % 2000 == 0) {
						System.out.println("C@" + i);
					}
					driver.findElement(By.tagName("body"));
				}

				System.out.println("C took " + Duration.between(start, end).getSeconds());
				driver.quit();
			} catch (Exception e) {
				e.printStackTrace();
				System.exit(333);
			}

		});


		Thread d = new Thread(() -> {
			try {
				WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"),  new ChromeOptions());
				driver.manage().window().maximize();
				driver.get("https://justepourtester.net/selenium/selenium_wait.html");

				Instant start = Instant.now();
				Instant end = null;

				for (int i = 0; done.get() != 4; i++){
					if (i == rounds) {
						end = Instant.now();
						done.incrementAndGet();
					} else if (i % 2000 == 0) {
						System.out.println("D@" + i);
					}
					driver.getCurrentUrl();
				}

				System.out.println("D took " + Duration.between(start, end).getSeconds());
				driver.quit();
			} catch (Exception e) {
				e.printStackTrace();
				System.exit(333);
			}

		});

		a.start();
		b.start();
		c.start();
		d.start();

		a.join();
		b.join();
		c.join();
		d.join();
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joerg1985** [comment]
Here is an example how to make the selenium-server-4.6.0 run into the read/write deadlock.
Just a simple POST call with unexpected Content-Type set and a payload with more bytes than the internal buffers are sized. 
This might happen when a security scanner will try to scan the server, as described in https://github.com/SeleniumHQ/docker-selenium/issues/1646

```
public static void main(String[] args) throws Exception {
        Process process = new ProcessBuilder(
                System.getProperty("java.home") + "/bin/java", "-jar",
                "selenium-server-4.6.0.jar", "standalone",
                "--port", "4444"
        ).redirectErrorStream(true)
                .redirectOutput(ProcessBuilder.Redirect.INHERIT)
                .start();

        HttpClient client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(1)).build();

        // wait for the server to start
        int status = -1;

        while (status != 200) {
            try {
                status = client.send(
                        HttpRequest.newBuilder(URI.create("http://127.0.0.1:4444/readyz"))
                                .timeout(Duration.ofSeconds(1))
                                .GET().build(),
                        HttpResponse.BodyHandlers.discarding()
                ).statusCode();
            } catch (Exception e) {
                status = -1;
            }
        }

        try {
            ChromeOptions options = new ChromeOptions();

            LOG.warning("\n*\n*\n* start and stop chrome #1 \n*\n*\n*");

            new RemoteWebDriver(new URL("http://127.0.0.1:4444"), options).quit();

            byte[] buf = new byte[64 * 1024];

            // use a seed to ensure we get the same payload for each call
            new Random(buf.length).nextBytes(buf);

            var request = HttpRequest
                    .newBuilder(URI.create("http://127.0.0.1:4444/wd/hub/session"))
                    // the incorrect Content-Type is to provoke a exception in the grid
                    .header("Content-Type", "text/html; charset=UTF-8")
                    // a playload bigger than the internal buffers to ensure we hit the read/write lock
                    .POST(HttpRequest.BodyPublishers.ofByteArray(buf))
                    .build();

            var response = client.send(request, HttpResponse.BodyHandlers.ofString());

            LOG.info("grid answer: " + response.statusCode() + " => " + response.body());

            LOG.warning("\n*\n*\n* start and stop chrome #2 \n*\n*\n*");

            new RemoteWebDriver(new URL("http://127.0.0.1:4444"), options).quit();
        } finally {
            process.destroyForcibly();
        }
    }
```

**Comment by joerg1985** [comment]
Here is another example how to freeze the grid, the one above will provoke a status code 500, this one will let the server answer with an 200 OK status code before locking.

```
public static void main(String[] args) throws Exception {
        Process process = new ProcessBuilder(
                System.getProperty("java.home") + "/bin/java", "-jar",
                "selenium-server-4.6.0.jar", "standalone",
                "--port", "4444"
        ).redirectErrorStream(true)
                .redirectOutput(ProcessBuilder.Redirect.INHERIT)
                .start();

        HttpClient client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(1)).build();

        // wait for the server to start
        int status = -1;

        while (status != 200) {
            try {
                status = client.send(
                        HttpRequest.newBuilder(URI.create("http://127.0.0.1:4444/readyz"))
                                .timeout(Duration.ofSeconds(1))
                                .GET().build(),
                        HttpResponse.BodyHandlers.discarding()
                ).statusCode();
            } catch (Exception e) {
                status = -1;
            }
        }

        try {
            ChromeOptions options = new ChromeOptions();

            LOG.warning("\n*\n*\n* start chrome #1 \n*\n*\n*");

            RemoteWebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"), options);

            byte[] buf = new byte[2 * 1024];

            // use a seed to ensure we get the same payload for each call
            new Random(buf.length).nextBytes(buf);

            var request = HttpRequest
                    .newBuilder(URI.create("http://127.0.0.1:4444/wd/hub/session/"
                            + driver.getSessionId().toString() + "/element/active"))
                    .header("Content-Type", "application/json; charset=UTF-8")
                    // a playload bigger than the internal buffers to ensure we hit the read/write lock
                    .method("GET", HttpRequest.BodyPublishers.ofByteArray(buf))
                    .build();

            var response = client.send(request, HttpResponse.BodyHandlers.ofString());

            LOG.info("grid answer: " + response.statusCode() + " => " + response.body());

            LOG.warning("\n*\n*\n* start and stop chrome #2 \n*\n*\n*");

            new RemoteWebDriver(new URL("http://127.0.0.1:4444"), options).quit();
        } finally {
            process.destroyForcibly();
        }
    }
```

**Comment by diemol** [comment]
Thanks for this, @joerg1985. We are just waiting on an extra pair of eyes before merging.

**Review by diemol — APPROVED** [review]
Thank you, @joerg1985!

**Pull request merged**
