### PR TITLE
[java] Bumping Java deps

### LINKED ISSUE #1883: [🐛 Bug]: opentelemetry-exporter-otlp not found on classpath
### What happened?

Hi, i'm trying to write traces in OpenTelemetry

### Command used to start Selenium Grid with Docker

```shell
I'm using helm chart v. 0.19.0 to start Grid in distributed mode in Kubernetes. In values file i add:
  extraEnvironmentVariables:
    - name: SE_JAVA_OPTS
      value: "-Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint=https://some.host -Dotel.resource.attributes=service.name=SomeTeam.selenium-grid"
```

### Relevant log output

```shell
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: otel.traces.exporter set to "otlp" but opentelemetry-exporter-otlp not found on classpath. Make sure to add it as a dependency.
```

### Operating System

k8s

### Docker Selenium version (tag)

selenium-grid-4.10.0-20230607

### PR DESCRIPTION
**Pull request by diemol**
- Adding `@SuppressWarnings({"rawtypes", "RedundantSuppression"})` to remove warning from AutoService using raw types and generics.
- Setting `System.setProperty("otel.logs.exporter", "none");` to keep the open telemetry behaviour as before.

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Also, fixes https://github.com/SeleniumHQ/docker-selenium/issues/1883

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joerg1985** [comment]
@diemol will merging this not automatically set the minimum java version to 11?

[graphql-java now requires Java 11 as a minimum version](https://github.com/graphql-java/graphql-java/releases/tag/v21.0)

**Comment by titusfortner** [comment]
I thought we just changed all of the CI execution to Java 17 for bazel reasons?

**Comment by diemol** [comment]
> I thought we just changed all of the CI execution to Java 17 for bazel reasons?

@titusfortner when? I was not aware of that.

**Comment by diemol** [comment]
> @diemol will merging this not automatically set the minimum java version to 11?
> 
> [graphql-java now requires Java 11 as a minimum version](https://github.com/graphql-java/graphql-java/releases/tag/v21.0)

Thanks for pointing it out, @joerg1985. I did not read the release notes. The strange part is that it seems things build with Java 8 as a target.

**Comment by titusfortner** [comment]
415786b3 which broke .NET tests because it was still using 11 and I'm working on fixing that in a branch on that now (b4771bbfce86becd930fdb77937ea7e22cf2d404)

**Comment by diemol** [comment]
I don't understand why tests using mockito fail, they pass for me locally.

**Comment by joerg1985** [comment]
> I don't understand why tests using mockito fail, they pass for me locally.

Bazel is again swallowing the cause of the exception thrown, i think this is something that should be fixed.

The logged 'IllegalStateException' is raised here and this should have a cause set:
https://github.com/mockito/mockito/blob/ece6107a22f0e4ea89dca7a9cfd7791f6a362a26/src/main/java/org/mockito/internal/configuration/plugins/PluginLoader.java#L90

**Comment by joerg1985** [comment]
@diemol [Looks like the mockito-inline is not needed any more](https://github.com/mockito/mockito/issues/3039#issuecomment-1594199470), removing it from maven_deps.bzl and .../remote/BUILD.bazel does not fix the issue, but will make different tests fail with another root cause.

I added this to the try/catch block in CommandLineTest.spyProcess
```
    } catch (IllegalStateException e) {
      throw new RuntimeException(e.getCause().getCause().getCause().toString());
    }
```

No i get this output:
```
java.lang.RuntimeException: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 17
JVM vendor name    : Azul Systems, Inc.
JVM vendor version : 17+35-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17+35-LTS
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 6.4.7-200.fc38.x86_64

	at org.openqa.selenium.os.CommandLineTest.spyProcess(CommandLineTest.java:161)
	at org.openqa.selenium.os.CommandLineTest.<init>(CommandLineTest.java:49)
```

And this seems to be this issue https://github.com/mockito/mockito/issues/2436

**Comment by diemol** [comment]
Thanks for debugging, @joerg1985. I will revert the version bump and watch the issue.

It is just strange that it passes for me locally.

**Comment by joerg1985** [comment]
> It is just strange that it passes for me locally.

Are you at jdk 17 or jdk 11 locally?

**Comment by diemol** [comment]
> > It is just strange that it passes for me locally.
> 
> Are you at jdk 17 or jdk 11 locally?

JDK 11 locally, but Bazel is using JDK 17 to run everything. However, if I run it on macOS it does not fail. On a Linux machine, it fails.

**Pull request merged**
