### PR TITLE
[java] custom duration for Actions constructor

### PR DESCRIPTION
**Pull request by iampopovich**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
according to #12118 feature request, I started to discover the best way to implement duration overriding

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement

___

### **Description**
- Added a new constructor to the `Actions` class in Selenium that allows specifying a custom `Duration` for actions.
- Introduced a new private member variable `actionDuration` to store the specified duration.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Actions.java</strong><dd><code>Add constructor with custom duration to Actions class</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
java/src/org/openqa/selenium/interactions/Actions.java

<li>Added a new constructor to the <code>Actions</code> class that accepts a <code>Duration</code> <br>parameter.<br> <li> Introduced a new private member variable <code>actionDuration</code> to store the <br>duration.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14085/files#diff-be22ba4639c55728723af6e60493d4bb5dfa2d9bab9d35e2fc2ba3b9076cc596">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by titusfortner** [comment]
Oh, thanks for taking on this one! I'm glad someone is finally looking into it. 

Your code doesn't actually show `actionDuration` getting used anywhere, though? Need to make it so that the default is overridden and used in necessary places.

**Comment by pujagani** [comment]
Please add tests for the new constructor added.

**Comment by iampopovich** [comment]
@pujagani I reused two existing tests for the scrollToElement and scrollByAmount methods with a custom Duration. Additionally, I wrote two tests to check the setting of the default Duration and the custom Duration. Will this be enough?

**Comment by titusfortner** [comment]
Haven't looked at the failures, pushing this one back to the next release

**Pull request merged**
