### PR TITLE
Add registration secret as header in node responses

### LINKED ISSUE #8559: Send registration-secret via header for web calls

### PR DESCRIPTION
**Pull request by raju249**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Fixes https://github.com/SeleniumHQ/selenium/issues/8559
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by raju249** [comment]
@adamgoucher Do you mind taking a look at my start for fixing #8559 ?

I am trying to find the places where the header will be validated. If possible, please point some files here, where the header should be validated :)

**Comment by AutomatedTester** [comment]
There are linting errors, please fix those

**Comment by raju249** [comment]
@adamgoucher Do you mind reviewing/approving this PR? 🙇

**Review by diemol — COMMENTED** [review]
How can I test this? 🤔

**Comment by adamgoucher** [comment]
My theory for how to test this is
- start a hub with https and registration secret
- start a node with the registration secret
- run a test through the node
- restart the node with the registration secret (while maybe blackhole-omg the traffic so it doesn’t try to re-register with the hub)
- try to send another another job to the node

The theory is that the hub would send a message and the node would reply without the header present and the hub would no longer trust the node and pull it out of the pool, not send commands, etc.

**Comment by raju249** [comment]
I have fixed the conflicts.

**Review by AutomatedTester — APPROVED** [review]

**Pull request merged**
