### PR TITLE
Support Default Capabilities for Nodes on Selenium 4

### PR DESCRIPTION
**Pull request by link89**
Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

https://github.com/SeleniumHQ/selenium/issues/8745

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shs96c** [comment]
Thank you for the contribution!

It's not clear from the description of this PR what the purpose is. It appears to be overriding the options added by the user when creating a new session, which may be problematic, but maybe I'm not understanding this properly.

It would be really helpful if you could describe the motivation behind this change. I'll shall hold off review this until then.

**Comment by link89** [comment]
Hi @shs96c Thank you for your reply. This PR is linked to issue https://github.com/SeleniumHQ/selenium/issues/8745. I have explained the motivation there.

> It appears to be overriding the options added by the user when creating a new session, which may be problematic, but maybe I'm not understanding this properly.

It won't. The client-side's capabilities will have higher priority over the server-side's.

**Comment by link89** [comment]
Hi @shs96c Can you help to review this patch?

**Review by diemol — CHANGES_REQUESTED** [review]
Thanks for this PR @link89, however, the approach is not aligned with how the new Grid works. The new Grid receives parametwers via command line and via a configuration (`toml`) file. Specifying system capabilities is not what we'd like to see.

An approach would be to read the capabilities configuration from the `toml` file and avoid detecting the drivers if that configuration is provided. The code that handles that is around [here](https://github.com/SeleniumHQ/selenium/blob/c38657eb29d4aead24fe27f9891bd4be868ada8a/java/server/src/org/openqa/selenium/grid/node/config/NodeOptions.java#L77).

**Comment by link89** [comment]
Thanks @diemol I will try to figure it out.

**Comment by link89** [comment]
While waiting for a fix on selenium, I just provide a lightweight solution to address the issue: https://github.com/link89/selenium-federation

**Comment by diemol** [comment]
Closed in favor of https://github.com/SeleniumHQ/selenium/commit/d48a9596d868180b8b2da96e3c3118127365d434

**Pull request closed without merging**
