### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the CLA?

**Comment by cool-RR** [comment]
Should I sign this one here?

https://docs.google.com/forms/d/11Z8LoYpTGUIwCegifVH1YtL9smxVDNk-fOykUZTAWhE/viewform?formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ&hl=en_US#gid=0

**Comment by AutomatedTester** [comment]
Could you also update the commit message to explain the change? Update select is meaningless when looking through commits



—

**Comment by cool-RR** [comment]
Title fixed, can you please confirm my question about the CLA?

**Comment by AutomatedTester** [comment]
That is the CLA and can you update the commit not the PR title. You do this with the git --amend command



—

**Comment by cool-RR** [comment]
Was quicker to make a separate PR:
https://github.com/SeleniumHQ/selenium/pull/590

**Pull request closed without merging**
