### PR TITLE
[dotnet] add asynchronous methods to Navigation class

### PR DESCRIPTION
**Pull request by titusfortner**
### Description
* This is a stripped down version of #13952 to focus on the bare minimum needed to get to the next step and compare BiDi implementations; 
* `Execute()` on `CommandExecutor` classes is already async, but has been made blocking; this PR now creates `ExecuteAsync()` to bubble up the await to `WebDriver`
* `Execute()` methods remain blocking but now call `ExecuteAsync()` 
* Async methods implemented for all Navigation methods with existing sync methods calling the Async methods in a blocking fashion to maintain backwards compatibility
* Note that this adds `ConfigureAwait(false)` inside all async lambdas executed in `Task.Run()` that include `GetAwaiter().GetResult()` at the end

### Motivation and Context
This is an example of a partial implementation of #14067 
We explicitly want to maintain both Sync and Async implementations for the time being. (possibly until Selenium 6)

### Questions
1. Is this the public facing API we want to expose to users? (I'm pretty sure the answer is yes, but I want to get an affirmative before starting next steps).

### Follow on
1. Add Async methods on all other classes
3. Create helper classes to improve the maintainability of the implementation class as desired (I'll let the .NET experts figure this one out)
4. AI thinks we shouldn't wrap things in Task.Run(), but I'll leave this for .NET experts to update as desired
> Consider removing the unnecessary use of Task.Run() for wrapping synchronous calls in Back(), Forward(), GoToUrl(), and Refresh() methods. Instead, directly await the asynchronous methods. This change will reduce overhead and improve performance
5. Same thing with Exception Handling
6. Same thing with the `CancellationToken` recommendation

attn: @YevgeniyShunevych

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Added asynchronous methods for navigation actions (Back, Forward, GoToUrl, Refresh) in `EventFiringWebDriver`, `INavigation`, and `Navigator`.
- Introduced `ExecuteAsync` method to `ICommandExecutor`, `DriverServiceCommandExecutor`, and `HttpCommandExecutor`.
- Synchronous methods now call their asynchronous counterparts to maintain backward compatibility.
- Added `ConfigureAwait(false)` to all async calls to prevent deadlocks.
- Added and updated tests to cover the new asynchronous methods.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>EventFiringWebDriver.cs</strong><dd><code>Add asynchronous navigation methods to EventFiringWebDriver</code></dd></summary>
<hr>
      
dotnet/src/support/Events/EventFiringWebDriver.cs

<li>Added asynchronous methods for navigation actions (Back, Forward, <br>GoToUrl, Refresh).<br> <li> Synchronous methods now call their asynchronous counterparts.<br> <li> Introduced <code>ConfigureAwait(false)</code> for all async calls.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-ecfb7c6b8ab17df6046130d592902620e9baddc4595b3140d1ebd7446da2d4d3">+62/-20</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ICommandExecutor.cs</strong><dd><code>Add asynchronous command execution to ICommandExecutor interface</code></dd></summary>
<hr>
      
dotnet/src/webdriver/ICommandExecutor.cs

- Added `ExecuteAsync` method to `ICommandExecutor` interface.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-4b9443bafd5a20a4713027f0f29bd91e6f83649cf92d3cf54f401a1a06639ef7">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>INavigation.cs</strong><dd><code>Add asynchronous navigation methods to INavigation interface</code></dd></summary>
<hr>
      
dotnet/src/webdriver/INavigation.cs

<li>Added asynchronous methods for navigation actions (Back, Forward, <br>GoToUrl, Refresh).<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-d25b415e4726a2c6a1b04b41009a2f75b00ae189d3a341eb59c52fa2a619ee2b">+33/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Navigator.cs</strong><dd><code>Implement asynchronous navigation methods in Navigator class</code></dd></summary>
<hr>
      
dotnet/src/webdriver/Navigator.cs

<li>Implemented asynchronous methods for navigation actions (Back, <br>Forward, GoToUrl, Refresh).<br> <li> Synchronous methods now call their asynchronous counterparts.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-13e558c131ed2ff6ab4315550e45f9bcaa3e0ae76c70a34fcd77cc4fa71a2152">+59/-12</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>DriverServiceCommandExecutor.cs</strong><dd><code>Add asynchronous command execution to DriverServiceCommandExecutor</code></dd></summary>
<hr>
      
dotnet/src/webdriver/Remote/DriverServiceCommandExecutor.cs

<li>Added <code>ExecuteAsync</code> method to <code>DriverServiceCommandExecutor</code>.<br> <li> Synchronous <code>Execute</code> method now calls the asynchronous version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-13da2c24ba7dad4e589e149d17d6007269b70944e5edb4609d087d68c7f48f17">+12/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>HttpCommandExecutor.cs</strong><dd><code>Add asynchronous command execution to HttpCommandExecutor</code></dd></summary>
<hr>
      
dotnet/src/webdriver/Remote/HttpCommandExecutor.cs

<li>Added <code>ExecuteAsync</code> method to <code>HttpCommandExecutor</code>.<br> <li> Synchronous <code>Execute</code> method now calls the asynchronous version.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-7e90084c9f3e8c994cbbfabdbc93ecd024159b65ca59d9f6efc53cace50e7b10">+11/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>WebDriver.cs</strong><dd><code>Add asynchronous internal command execution to WebDriver</code>&nbsp; </dd></summary>
<hr>
      
dotnet/src/webdriver/WebDriver.cs

<li>Added <code>InternalExecuteAsync</code> method for internal command execution.<br> <li> Synchronous methods now call their asynchronous counterparts.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-ef1874c09b1dca0d62ea1f0ead685355944b9cb7ae63df60ad9b32abdf90c8dc">+22/-3</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests
</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>NavigationTest.cs</strong><dd><code>Add tests for asynchronous navigation methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
dotnet/test/common/NavigationTest.cs

- Added tests for asynchronous navigation methods.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-949f3e2193640efef49f4dc096d01e37851df0edac65eeb9c0db24b4262edd63">+70/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>EventFiringWebDriverTest.cs</strong><dd><code>Update tests for EventFiringWebDriver to use async methods</code></dd></summary>
<hr>
      
dotnet/test/support/Events/EventFiringWebDriverTest.cs

- Updated tests to verify asynchronous navigation methods.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14051/files#diff-8a1f6089996b8c42dea999e7e0043f7820d548fe71b6a71a359a70c126da9443">+7/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by nvborisenko** [comment]
> Note that this adds ConfigureAwait(false) inside all async lambdas executed in Task.Run() that include GetAwaiter().GetResult() at the end.

I think it is unnecessary in this context. I also would suggest to introduce kind of `AsyncHelper` who will be responsible to "resolve" sync-over-async problem. Later on we will be able to find all places across the repo too understand what is still "bad" in the code.

**Comment by YevgeniyShunevych** [comment]
Agree with @nvborisenko. I would also keep sync-over-async implementation encapsulated in a class like this:

```cs
internal static class AsyncHelper
{
    internal static TResult RunSync<TResult>(Func<Task<TResult>> function) =>
        Task.Run(function).GetAwaiter().GetResult();

    internal static void RunSync(Func<Task> function) =>
        Task.Run(function).GetAwaiter().GetResult();
}
```

**Comment by titusfortner** [comment]
Abstracting out a helper class is out of scope for this PR. You can argue the best way to do that later; this is what the internet suggested I do (well, mostly) based on this particular execution.

This is the user-facing API we want?

I want to get something basic merged in before we start evaluating/comparing BiDi implementations

**Comment by nvborisenko** [comment]
If you land it now, than nobody will return to it back later. My internet is different https://devblogs.microsoft.com/dotnet/configureawait-faq/#can-i-use-task-run-to-avoid-using-configureawaitfalse:

image

**Comment by titusfortner** [comment]
Nice, hadn't seen that, just the general advice that in a library every await should include a ConfigureAwait(false)

**Comment by titusfortner** [comment]
> than nobody will return to it back later

That's fine too. That's a good indication that it doesn't actually matter.

Really I just want to make sure that a different implementation won't require a different user-facing API, and that any changes you might want to make will work with this API.

**Comment by titusfortner** [comment]
updated to use `async delegate`. Windows tests are failing due to whatever is going on with protoc.exe; Navigation tests are passing locally and on RBE.

**Comment by titusfortner** [comment]
Anyone should feel free to create helpers/abstractions for this and/or other code already in the library if it makes sense to do so.

**Pull request merged**
