### PR TITLE
[py] add deprecation library requirement

### PR DESCRIPTION
**Pull request by titusfortner**
### Description
Add a dependency on deprecation library

### Motivation and Context
Current means of doing deprecations in Python is challenging.
Using an annotation would be much easier

### Notes
* This may not be the right fix
* There were two libraries, this one seems to have fewer features, but its also the one being maintained
* I think I saw somewhere someone  rolling our own annotation, but I'm not sure where, but I seem to remember it feeling clunky?

What do y'all think?

### CODE REVIEW

**Review by diemol — APPROVED** [review]
This should be added. Deprecating something in Python should not be as complicated as it is currently.

**Comment by titusfortner** [comment]
@isaulv @AutomatedTester @symonk 
Do either of you remember seeing a custom implementation? I thought @symonk was doing something, but I can't find it; maybe @sandeepsuryaprasad did something at one point?
Anyway, would like to know if there's an easy win here, and what it is.

**Comment by sandeepsuryaprasad** [comment]
@titusfortner  @symonk @isaulv @AutomatedTester This decorator is implemented in Python 3.13. PEP 702  (https://peps.python.org/pep-0702/). So going forward once python 3.13 is released, we can avoid the dependency on deprecation library since the decorator is already implemented in `warnings` module https://peps.python.org/pep-0702/#example

**Comment by titusfortner** [comment]
@sandeepsuryaprasad We have to continue supporting users on 3.12 and below until ~2028.
Is there a way to back port that functionality to earlier versions of Python?

**Comment by sandeepsuryaprasad** [comment]
@titusfortner yes it is. the new decorator will be added to `typing_extensions` https://peps.python.org/pep-0702/#backwards-compatibility

**Comment by titusfortner** [comment]
@sandeepsuryaprasad — but this still won't be available until October?

**Comment by sandeepsuryaprasad** [comment]
@titusfortner  Yes.. you are right.. this feature won't be available until October-24.

**Comment by titusfortner** [comment]
There were two packages I saw:
* https://pypi.org/project/Deprecated/ — this PR; very basic and maintained
* https://pypi.org/project/deprecation/ — lots of cool bells and whistles but not actively maintained

It looks like the official deprecation implementation in 4.13 is going to be very basic as well, no bells, no whistles. In fact, the syntax looks exactly the same as the Deprecated package syntax.

@AutomatedTester what do you think about using this package, adding the annotations as necessary and then just removing this library and replacing it with the standard one in October?

**Comment by AutomatedTester** [comment]
I think this should be fine to add. I am always trying to limit third party but if we feel it will add value (I don't think there is much in terms of deprecation at the moment)

**Comment by titusfortner** [comment]
Well, there are a few Firefox things that @diemol didn't deprecate because it was complicated. 😂 

And I was going to use it to deprecate some Selenium Manager things, but we've decided we can just remove instead of deprecate Selenium Manager things while it is still in beta.

**Comment by titusfortner** [comment]
Hmm, it looks like we might be able to use this already? `from typing_extensions import deprecated`??

**Comment by titusfortner** [comment]
And I verified this works. Nice.

**Pull request merged**
