### PR TITLE
Add devcontainer.json to ease local dev environment setup

### PR DESCRIPTION
**Pull request by Trigtrig**
### Description
Adding a Dev Container configuration to ease local dev environment setup.

### Motivation and Context
I recently contributed to the Selenium project for the first time (see #13583). I opted for the Dev Container variant to set up my  local dev environment. This worked very well, but I had to create my own devcontainer.json to be able to work with my IDE and Dev Container. To make it easier to get started, especially for first time contributors, I would like to add a devcontainer.json to the Selenium project. This minimal devcontainer.json has two advantages:

1. IDEs will recognize that Dev Containers are supported when opening the project and may offer to create the container. Here is an example from Visual Studio Code:
grafik

2. contributors who do not have much knowledge of Dev Containers can use the devcontainer.json and the documentation link it contains as a starting point for their local dev environment.

According to the [Dev Container documentation](https://containers.dev/implementors/spec/#devcontainerjson), I have placed the file in the preferred folder `.devcontainer`. Both IntelliJ IDEA and Visual Studio Code recognize this Dev Container configuration correctly.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you, @Trigtrig!

Could you please add a simple note about this in the README file?

**Review by diemol — CHANGES_REQUESTED** [review]
Wait, but now you are replacing the content. Someone might want to use the Dockerfile. Can you please leave your added content and merge it with what already exists?

**Comment by Trigtrig** [comment]
My bad. I thought that the main purpose of the Docker image was to create a Dev Container. I restored the original section.

**Review by diemol — APPROVED** [review]
Thank you, @Trigtrig!

**Pull request merged**
