### PR TITLE
Closure update

### PR DESCRIPTION
**Pull request by 43081j**
This updates the closure compiler and closure library dependencies.

This is mostly in preparation for the shadow DOM updates coming from #4230.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by juangj** [comment]
Hm... I'm concerned about some of the test failures in the Travis run, particularly
* #2395.10 - https://travis-ci.org/SeleniumHQ/selenium/jobs/254595321
* #2395.11 - https://travis-ci.org/SeleniumHQ/selenium/jobs/254595322

In #2395.10, it looks like some of the tests are hanging and timing out. I can reproduce that locally, too, by putting `chromedriver` on my path and then running
`./go calcdeps //javascript/webdriver:webdriver-chrome:run`
but I haven't a clue at the moment what the problem might be.

**Comment by juangj** [comment]
Seems like a lot of the failures in [#2395.11](https://travis-ci.org/SeleniumHQ/selenium/jobs/254595322) are caused by the TagName change. For example, the enabled_test failures are probably all because the TagNames in https://github.com/SeleniumHQ/selenium/blob/d98e7951b81ea9e729dff8a01cbfc5e5ef60daa4/javascript/atoms/dom.js#L173 are no longer strings. Hopefully it's straightforward to fix a bunch of these.

**Comment by juangj** [comment]
fd4954f518ed0d84c31466d8c7a85b580f884ffd should fix all the failures in //javascript/atoms:atoms-firefox:run (#2395.11).

Out of time for today to look into the failures in //javascript/webdriver:webdriver-chrome:run, sorry. Perhaps @jleyba might be able to help out if he has time -- I think he's more familiar with that code.

**Comment by 43081j** [comment]
thanks a lot for the effort you've put into this. i'll take a look at your changes today and have a look at the remaining failures, though they're a little difficult to track down without having been in here before.

**Comment by shs96c** [comment]
I found that we're passing wonky flags to the test runner for the Firefox flags. That gets the test run failure rate at parity with current master. Time to look at the chrome failures, which I can also reproduce locally.

**Comment by shs96c** [comment]
Tracked down the reason why the tests are hanging: https://github.com/google/closure-library/commit/6453bc5c9d526120f759266b3f4d558511a54a92#diff-c359099ba4bc09bc2864536c49356d52 removes `good.dependencies_.pathIsModule`. This method is used in the `GeneratedJsTestServlet` and so the tests fail as they're unable to load a dependency.

With this fix applied, the `//javascript/webdriver:webdriver-chome` tests now pass:

```
diff --git a/java/client/test/org/openqa/selenium/environment/webserver/GeneratedJsTestServlet.java b/java/client/test/org/openqa/selenium/environment/webserver/GeneratedJsTestServlet.java
index 9415fd3411..3fee1445b2 100644
--- a/java/client/test/org/openqa/selenium/environment/webserver/GeneratedJsTestServlet.java
+++ b/java/client/test/org/openqa/selenium/environment/webserver/GeneratedJsTestServlet.java
@@ -49,7 +49,7 @@ protected void doGet(HttpServletRequest req, HttpServletResponse resp)
          + "    var path = '../../.." + req.getPathInfo() + "';\n"
          + "    goog.addDependency(path, ['" + symbol + "'],\n"
          + "        goog.dependencies_.requires['../../.." + req.getPathInfo() + "'] || [],\n"
-         + "        !!goog.dependencies_.pathIsModule[path]);\n"
+         + "        !!goog.dependencies_.loadFlags[path]);\n"
          + "    goog.require('" + symbol + "');\n"
          + "  })()\n"
          + "</script></head><body></body></html>").getBytes(Charsets.UTF_8);
```

**Comment by juangj** [comment]
Fantastic -- thanks for your help, Simon.

**Pull request merged**
