### PR TITLE
[py] [run python] Upgrade GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

[py]
[run python]

Upgrades to match:
* https://github.com/actions/cache/releases
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-java/releases
* https://github.com/actions/setup-python/releases

See Node.js 12 actions deprecation warnings at https://github.com/SeleniumHQ/selenium/actions/runs/3449658980

### Motivation and Context

Improved performance and compatibility.  See release notes above.
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Infrastructure upgrade

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cclauss** [comment]
Python-related GitHub Actions do not run when Python files are modified.

**Comment by diemol** [comment]
@cclauss we have a script to determine which build targets to run, as we use bazel. Our script has room for improvement, it determines the build targets based on the changed code files. Since the GitHub Actions files are not Python code, the workflow does not run.

To force the execution, make a temporal change to one of the `.py` files, and after it runs, you can revert it.

**Comment by cclauss** [comment]
Yes.  Both the Python files that were modified in  #11258 were modified in this PR and neither one of them woke up bazel.

**Comment by cclauss** [comment]
GitHub Actions [paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) already has [filter patterns like `**.py`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths) so perhaps that would be a safer, simpler approach.

**Comment by diemol** [comment]
> GitHub Actions [paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) already has [filter patterns like `**.py`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths) so perhaps that would be a safer, simpler approach.

@cclauss yes, but this would execute all build and test targets for the code, which is less than ideal. With the script we have, we build and test only what gets affected by the code change. It is not perfect as it ignores changes like the one you are submitting.

**Pull request merged**
