### PR TITLE
adding ExpectedConditions for URLs (contains, toBe, and matches regex)

### PR DESCRIPTION
**Pull request by ddavison**
Tested with these tests:

``` java
    Wait<WebDriver> wait = new WebDriverWait(driver, 5);
    driver.get("http://ddavison.io/tests/getting-started-with-selenium.htm");
    driver.findElement(By.id("redirect")).click();
    wait.until(ExpectedConditions.urlMatches(".*google.*"));
```

``` java
    Wait<WebDriver> wait = new WebDriverWait(driver, 5);
    driver.get("http://ddavison.io/tests/getting-started-with-selenium.htm");
    driver.findElement(By.id("redirect")).click();
    wait.until(ExpectedConditions.urlContains("google"));
```

``` java
    Wait<WebDriver> wait = new WebDriverWait(driver, 5);
    driver.get("http://ddavison.io/tests/getting-started-with-selenium.htm");
    driver.findElement(By.id("redirect")).click();
    wait.until(ExpectedConditions.urlToBe("https://www.google.com/?gws_rd=ssl"));
```

**Note**:  This, of course, only applies within the given context.  Opening a tab for example, this will have no effect without first changing the context.

### CODE REVIEW

**Comment by lukeis** [comment]
please add tests?  https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/support/ui/ExpectedConditionsTest.java

**Comment by TikhomirovSergey** [comment]
:+1:

**Comment by ddavison** [comment]
added tests to `PageLoadingTests` as the `ExpectedConditionsTest` class seemed to  be independent of WebDriver, and it was the most appropriate place i found.

**Comment by lukeis** [comment]
I would have rather your tests been in the ExpectedConditionsTest (or also in there?) as you say, it's "independent"… well, yes, that's because it's actually unit tests and not full stack integration tests (like what you actually made). These tests are 'slow' and in my opinion not necessary to test your new conditions.

You could mock the driver to return different urls to verify your new conditions, to quickly verify the functionality you have in place. I would like to see a few tests around each of the methods, testing positive and negative scenarios :)

**Comment by ddavison** [comment]
there we go!

**Comment by lukeis** [comment]
:+1:  (now just to wait for the travis build... which will coincidentally test your change now ;) )

**Comment by lukeis** [comment]
merged as 3bbdedb4d5761496b3b2377f8bc900a77c81f0da

**Pull request closed without merging**
