### PR TITLE
Updated the test method name

### PR DESCRIPTION
**Pull request by sri85**
Updated the test method name from `test_we_can_launch_multiple_firefox_instances` to `test_we_can_launch_multiple_chrome_instances` since it is a `chrome` test

### CODE REVIEW

**Comment by ddavison** [comment]
have you signed the CLA?

**Comment by ddavison** [comment]
this is a very small change so i went ahead and merged it.  (68dbd3e5a217773ecfb8b961ec9508dda0da63a7)  Go ahead and still sign that CLA for me so any future merges you make, we won't have to worry about it :)

**Comment by sri85** [comment]
Signed the CLA

**Comment by ddavison** [comment]
excellent, thanks. this change has been merged in so we can close.  (see above comment)

**Pull request closed without merging**
