### PR TITLE
Handled AttributeError with ImportError for IronPython Support

### PR DESCRIPTION
**Pull request by tarunlalwani**
IronPython raises AttributeError instead of ImportError exception when checking for Python 3 Import Errors. This change handles both ImportError and AttributeError when check doing imports with exception checks

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/761)

### CODE REVIEW

**Comment by tarlabs** [comment]
@ddavison, Is this being reviewed by someone?

**Comment by AutomatedTester** [comment]
While I am happy to look at this there will be no on going support for IronPython. IronPython Support will be purely on you/community.











On Thursday, 16 Jul 2015 at 07:44, Tarun Lalwani <notifications@github.com>, wrote:

@ddavison, Is this being reviewed by someone?

**Comment by tarlabs** [comment]
@AutomatedTester, that is perfectly acceptable

**Comment by diemol** [comment]
Seems this went stale, closing as we are doing a general issue/PRs cleanup.

**Pull request closed without merging**
