### PR TITLE
[py] fixed a bug in function `keys_to_typing` in `common/utils`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
The argument `value` in `keys_to_typing` function in `common/utils`, can never be an instance of `Keys` class. The `value` will be either a `str` or `int` or `float`.

### Motivation and Context
- One of the conditional statement never gets executed in function `keys_to_typing` due to the fact that the value of `value` argument can never be an instance of `Keys` class. 
- The values for `value` argument could be either a string `str` or `int` or `float`
- If the value is `int` or `float`, we are explicitly casting it to a `str` and appending each item to a list `_typing`
- Also, there are 2 `for` loops which was kind of redundant. I have fixed this redundancy by eliminating one of the loop.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by titusfortner** [comment]
The code you removed was to fix this bug - https://github.com/SeleniumHQ/selenium/issues/1839
We need to verify we didn't cause the problem again.

**Comment by sandeepsuryaprasad** [comment]
No, the change that I have made is not breaking the fix https://github.com/SeleniumHQ/selenium/issues/1839 
I just reverified by running all typing related tests once again in my local. 
when you say `element.send_keys(Keys.TAB)`, `Keys.TAB` gets evaluated to unicode `\ue004` string. Now a unicode string is being passed to `keys_typing_to`, which is not an `int` or `float`. So I am directly appending the unicode string to `_typing` list.

The problem with the current code is that with the line `if isinstance(val, Keys)` the argument `val` can never be an instance of class `Keys`. This code never gets executed and it always jumps to the  `else` block. In `else` block the unicode string is getting appended to the list `_typing`

**Review by AutomatedTester — APPROVED** [review]

**Comment by AutomatedTester** [comment]
There are some conflict. Could you look and correct and I will get it merged

**Comment by sandeepsuryaprasad** [comment]
> There are some conflict. Could you look and correct and I will get it merged

@AutomatedTester Please do not merge this PR since it is conflicting with one more commit https://github.com/SeleniumHQ/selenium/commit/a0e569b0825e19bbd1e931cdaffa48ae98efe090

**Comment by isaulv** [comment]
I think the intention of checking for `Keys` is that it's suppose to check for control/modifier keys. 
Can you update your pull request? Can you check if there are tests for action chains that test things like ctrl-c ctrl-v?

**Comment by diemol** [comment]
@sandeepsuryaprasad did you want to continue with this PR?

**Comment by sandeepsuryaprasad** [comment]
> @sandeepsuryaprasad did you want to continue with this PR?

@diemol you can close this for now.

**Pull request closed without merging**
