### PR TITLE
[dotnet] Implementation of event wrapped shadow root element

### LINKED ISSUE #12049: [🐛 Bug]: EventFiringWebDriver doesn't wrap ShadowRoot instance
### What happened?

Im using EventFiringWebDriver instance for invoke some events like a listeners and all was very good until the moment when I got ShadowRoot instance. When I used GetShadowRoot().FindElement() returned instance is without any events so if some elements nested in shadow root cause some problems I will not see that.

Is there any way to achive these events inside shadow root element? Im not seeing similar class like EventFiringWebElement for wrap ShadowRoot.

### How can we reproduce the issue?

```shell
IWebDriver searchContext = new EventFiringWebDriver(driver);
IWebElement parentElement = searchContext.FindElement(locator for parent element); <--- This will return EventFiringWebElement

ShadowRoot shadowRoot = parentElement.GetShadowRoot();
shadowRoot.FindElement(locator for child element); <--- This will return WebElement instance, but I expected something like EventFiringShadowRoot instance including events
```

### Relevant log output

```shell
Empty
```

### Operating System

Windows10

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.93

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.6300

### Are you using Selenium Grid?

Tested without RemoteWebDriver

### PR DESCRIPTION
**Pull request by nvborisenko**
### Description
Raises events for web elements under shadow root.

### Motivation and Context
Fixes https://github.com/SeleniumHQ/selenium/issues/12049

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Note:
This is draft. I am out of disk space even to build solution. Bazel took 10GBs, Git repo 3GB (excluding preinstalled dependencies), and this is just to build 30MB nuget package. I will migrate from 256GB ssd to 1TB ssd, and in any case I will **never** install selenium dev dependencies on my system drive, shortly saying selenium dev environment will be isolated in VM.

### CODE REVIEW

**Comment by diemol** [comment]
I understand the complexity of setting the environment when space is limited. I can help to test the PR on my local Windows machine. In addition, I am checking GitHub Codespaces to see if it is possible to have a cloud environment for Windows.

**Comment by nvborisenko** [comment]
I postponed OS re-installation. In scope of this PR I need to create new unit tests to cover functionality. This is why PR is draft. I quickly looked through code, and it promising operational. In any case unit tests are required here.

**Comment by nvborisenko** [comment]
Created new unit tests, this PR is ready for review.

**Review by diemol — APPROVED** [review]
Thank you, @nvborisenko!

Failures are not related to this PR, we need to check them apart.

**Pull request merged**
