### PR TITLE
Only allow CORS when using a —allow-cors flag

### PR DESCRIPTION
**Pull request by zcmgyu**
**Use case:** When make a request to Selenium server though API in
JS code in browser, the request will be ignored by CORS policy.

So, I added —allow-cors flag to turn CORS compatibility mode on,
which will allow connections to the Selenium server from within
websites hosted on any domain

I'm inspired by @jlipps. He made the same thing in Appium server.
https://github.com/appium/appium/pull/11719
Screen Shot 2019-09-05 at 9 48 42

**Usage:**
`java -jar selenium.jar standalone --allow-cors`

This will give user a warning related to CORS:

> [BaseServer.<init>] - You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Selenium sessions on your machine

**Test Result:**
Without --allow-cors
CORS

With --allow-cors
with-allow-cors

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by zcmgyu** [comment]
Does somebody know why all checks've failed? I don't think problem from my code. :D

**Comment by shs96c** [comment]
Thank you for the patch, and thank you for explaining why you needed it :) Welcome to the project!

Merged as b2888794eb63e1a9805136331b738e307e83b3a6

**Comment by jlipps** [comment]
\o/ well done @zcmgyu! excited this will work in Selenium now too.

**Comment by vishalbiradar** [comment]
How to disable CORS for firefox in Java?

**Pull request closed without merging**
