### PR TITLE
Have option to automatically refresh grid console

### PR DESCRIPTION
**Pull request by stopsopa**
just change url from:
http://xxx.xxx.xxx:4444/grid/console?config=true&configDebug=true
to:
http://xxx.xxx.xxx:4444/grid/console?config=true&configDebug=true&refresh=3000

### CODE REVIEW

**Comment by diemol** [comment]
This already exists, check https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/web/servlet/beta/ConsoleServlet.java#L76

Just add the parameter "refresh=XX" to your current grid console, where XX is expressed in seconds.

**Comment by stopsopa** [comment]
Oh cool, didn't know, thx. :)

**Comment by p0deje** [comment]
Guess we can close it then?

**Comment by diemol** [comment]
Agree, it should be closed.

**Comment by Dude-X** [comment]
Maybe we should update documentation. I didn't know this existed...

**Comment by p0deje** [comment]
Done.

**Pull request closed without merging**
