### PR TITLE
[py] Add py.typed file

### PR DESCRIPTION
**Pull request by Akuli**
### Description
Makes type checkers use type annotations from selenium itself.

### Motivation and Context

#9480

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
Let me know if I have to go through the boilerplate, but I verified it manually: after `pip install ./py` in the repo, I can successfully run mypy over a file containing `import selenium`.

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Akuli** [comment]
Sorry, where can I find the CLA? I have grepped in the repo, I have searched in CONTRIBUTING.md, and I have clicked the link in the above comment. All I find is references to "the CLA", e.g. a checkbox saying "I have read and agree to the CLA". So where is that CLA?

**Comment by diemol** [comment]
> Sorry, where can I find the CLA? I have grepped in the repo, I have searched in CONTRIBUTING.md, and I have clicked the link in the above comment. All I find is references to "the CLA", e.g. a checkbox saying "I have read and agree to the CLA". So where is that CLA?

Probably we have an outdated link or comment somewhere, in the [comment above](https://github.com/SeleniumHQ/selenium/pull/10310#issuecomment-1026095951) you can see that this is a process supported by a tool.

**Comment by Akuli** [comment]
From the link:

> By submitting your Contribution to the Selenium Project, You hereby agree to license your Contribution under the Apache License, Version 2.0, and to include the appropriate copyright notice required by the license.

Is this "the CLA"?

**Comment by diemol** [comment]
image
https://cla-assistant.io/SeleniumHQ/selenium?pullRequest=10310

Yes

**Comment by Akuli** [comment]
Thanks! Somehow I expected the CLA to be a wall of text of length 1 kilometre or so.

**Pull request merged**
