### PR TITLE
[py] Added the functionality for changing the user-agent of Firefox and Chromium-based browsers like Edge, Chrome and Opera

### PR DESCRIPTION
**Pull request by shreyanavigyan**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Now we can simply call `add_userAgent()` method on `FirefoxProfile` object, `FirefoxOptions` object `ChromeOptions` object, `EdgeOptions` object and `OperaOptions` object and while using the webdriver object we can pass the profile or options object as an argument. 

Like this in Firefox using `FirefoxProfile` object:-

```
from selenium import webdriver
profile = webdriver.FirefoxProfile()
profile.add_userAgent(_userAgent_)
driver = webdriver.Firefox(profile=profile)

```

If we wanted to use `FirefoxOptions`, it would look something like this:-

```
from selenium import webdriver
options = webdriver.FirefoxOptions()
options.add_userAgent(_userAgent_)
driver = webdriver.Firefox(options=options)

```

While using a Chromium-based browser it would look something like this (This is an example of how we can do it in Chrome but since the change has been made directly in the Chromium source code others like Edge and Opera also works) :-

```
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_userAgent(_userAgent_)
driver = webdriver.Chrome(options=options)

```
To verify the userAgent we can simple call `driver.execute_script('return navigator.userAgent')`.

### Motivation and Context

I added this functionality since as a beginner I had a lot of problems to change the user-agent. I searched the entire Internet only to find out selenium didn't provide a easy way to change the user-agent. Then I found out about how to change the user-agent from someone but it was still complex and pretty hard to remember. So to provide a much more easier way to change the user-agent, I added this functionality which is pretty simple and easy to remember. This is all I have to say about my new feature.

Thanking you,

With Regards,
Shreyan Avigyan

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shreyanavigyan** [comment]
Hi, please don't pay attention to the failed tests in programming languages other than Python since those scripts have not been tampered with...and the Python tox_flake8 test failed since I inserted a blank line at the end of a line which is hopefully not a bug...and the SonarCloud test also passed. I'd kindly to request a review of my work.

Thanking you

**Comment by AutomatedTester** [comment]
Could you explain why you would need to change the user agent? Since you can change browsers with Selenium I am not sure why this is needed

**Comment by shreyanavigyan** [comment]
Yeah I know that but I thought it would be nice to be able to change the user-agent of a browser. I actually got this idea from the requests module. And not every website allows the same user-agent.

**Comment by diemol** [comment]
In addition, this looks like the type of stuff that should be placed on a framework built on top of Selenium.

**Comment by AutomatedTester** [comment]
Since we have the ability to start multiple browsers as well as connecting to Firefox for android and Chrome for Android as well as iOS Safari I am not going to accept this PR. Especially since there are no compelling use cases in this PR.

**Pull request closed without merging**
