### PR TITLE
[nodejs] code cleanup second iteration

### PR DESCRIPTION
**Pull request by potapovDim**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — DISMISSED** [review]

**Comment by diemol** [comment]
@potapovDim I am sorry we did not merge this right away. Can you please fix the merge conflict and then I can merge this?

**Comment by potapovDim** [comment]
@diemol ok, will do in a while

**Comment by potapovDim** [comment]
@diemol done, can u check again, please

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Thank you, @potapovDim!

**Pull request merged**
