### PR TITLE
[rust] Save to directory

### PR DESCRIPTION
**Pull request by oriongonza**
Allows the user to download the webdriver to a specific directory.

### Description

Adds the `--save-path` flag, which allows the user to download the selected driver to a folder.

Also a few refactors that I didn't see in the other PR

### Motivation and Context

I had the need for this so I implemented it here.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by oriongonza** [comment]
@bonigarcia you might want to take a look at this two PRs #11832

**Review by bonigarcia — COMMENTED** [review]
This PR should not be merged. The flag `--save-path` is not necessary, since the feature to change the binary path will be implemented through the flag `--cache-path` (planned in #11688, which has a current PR under review: #11840).

**Comment by oriongonza** [comment]
This might still be useful (it is at least for me) since the webdriver will be saved under a specific version folder eg `~/mycache/111.xxx.xxx/chromedriver`.

**Comment by oriongonza** [comment]
Still, even if this gets pushed back there are a few refactors worth considering, especially using `#[Derive(Clone)]` attribute macro.
By the way, why does the get_config clone the configuration struct instead of returning a mutable reference to it? That way you can simplify (and speed up but that doesn't really matter) the addding of a new configuration.

Also it might be worth considering using optionals instead of empty strings for the configurations that don't exist since rust provides really powerful tools for working with options,

**Comment by bonigarcia** [comment]
> This might still be useful (it is at least for me) since the webdriver will be saved under a specific version folder eg `~/mycache/111.xxx.xxx/chromedriver`.

I see your point now. Still, I think having both flags `--cache-path` and `--save-path` can be confusing. Instead, I propose having only `--cache-path` (which it has already another PR), and created another extra flag e.g. called `--avoid-driver-tree` to store the driver without using a tree folder for the drivers. @dev-ardi What do you think?

**Comment by bonigarcia** [comment]
> Still, even if this gets pushed back there are a few refactors worth considering, especially using `#[Derive(Clone)]` attribute macro. By the way, why does the get_config clone the configuration struct instead of returning a mutable reference to it? That way you can simplify (and speed up but that doesn't really matter) the addding of a new configuration.

Yes, I have just seen your PR about it and it seems a handy way to avoid the cloning method, thanks a lot. I think we should merge it, thanks.

> Also it might be worth considering using optionals instead of empty strings for the configurations that don't exist since rust provides really powerful tools for working with options,

Yes, that is a good idea too.

**Comment by diemol** [comment]
I got lost a bit. What should we do with this PR? I believe it needs to be split to handle the refactor apart?

**Comment by oriongonza** [comment]
> I see your point now. Still, I think having both flags `--cache-path` and `--save-path` can be confusing. Instead, I propose having only `--cache-path` (which it has already another PR), and created another extra flag e.g. called `--avoid-driver-tree` to store the driver without using a tree folder for the drivers. @dev-ardi What do you think?

That looks like the correct approach

**Comment by oriongonza** [comment]
> I got lost a bit. What should we do with this PR? I believe it needs to be split to handle the refactor apart?

I guess so. I don't know how to select only some of the changes from each commit, I'm very good with git. I could use some help with this :)

**Comment by diemol** [comment]
You can create a complete new branch from `trunk` and only apply the refactoring changes to send a PR.

**Pull request closed without merging**
