### PR TITLE
Update firefox_profile.py

### PR DESCRIPTION
**Pull request by erikbeerepoot**
Issue #1294

### CODE REVIEW

**Comment by lukeis** [comment]
have you signed the [CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)?

**Comment by erikbeerepoot** [comment]
yes, it's all signed.

**Comment by lukeis** [comment]
merged as 7c97c37525d561e2963e86265c1b664456c0c86e

Thanks!

**Comment by erikbeerepoot** [comment]
Thank you!

**Pull request closed without merging**
