### PR TITLE
[rust] don't clone the config struct

### PR DESCRIPTION
**Pull request by oriongonza**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

Don't clone the config struct. This is not a big deal but it results in a bit of extra unnecessary complexity (and an extra allocation)

### Motivation and Context

It's a small refactor that doesn't affect anything but it's nice to have.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bonigarcia** [comment]
@dev-ardi Thanks a lot, LGMT. Can you please resolve the conflicts? If the tests pass with these changes, let's merge it.

**Comment by diemol** [comment]
@dev-ardi please check the user that made the commit, they have not signed the CLA.

**Comment by oriongonza** [comment]
I have signed it but it's not detecting it! You're free to merge it, I give consent :)

**Comment by diemol** [comment]
@dev-ardi we actually need it signed. 

The user that needs to sign it is the one who did the commit, so this one https://github.com/OrionGonzalez

**Comment by oriongonza** [comment]
Of course, thanks. I was wondering why it wasn't working.

**Comment by diemol** [comment]
This PR still has some conflicts that need resolution.

**Comment by oriongonza** [comment]
@diemol If I didn't make a mistake it should be okay.

**Review by bonigarcia — APPROVED** [review]

**Review by diemol — APPROVED** [review]
Thank you, @dev-ardi!

**Pull request merged**
