### PR TITLE
delete 'lock' file in FF profile

### LINKED ISSUE #11576: [🐛 Bug]: Ruby exception with firefox profiles on Linux due to File.stat on broken link
### What happened?

Just the default example code using options.profile

```ruby
require 'selenium-webdriver'

options = Selenium::WebDriver::Firefox::Options.new
options.profile = "default"

driver = Selenium::WebDriver.for :firefox, options: options
```

triggers

```
No such file or directory @ rb_file_s_stat - /tmp/webdriver-rb-profilecopy20230121-192209-yy5fi1/lock (Errno::ENOENT)
```

Due to following code in [lib/selenium/webdriver/common/zipper.rb](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/common/zipper.rb)

```ruby
      def add_zip_entry(zip, file, entry_name)
        entry = Zip::Entry.new(zip.name, entry_name)
        entry.follow_symlinks = true

        zip.add entry, file
      end
```

Which enables follow_symlinks, as per commit https://github.com/SeleniumHQ/selenium/commit/a44367ad80

This causes Rubyzip to use File.stat instead of File.lstat, which explodes with the above exception when called on firefox profile lock file, which is a weird broken link leading [nowhere](https://superuser.com/questions/1363677/in-a-symlink-pointing-to-127-0-1-1xxxxx-what-is-the-plus-character-for):
```
$ ls -la .mozilla/firefox/1c43irlt.default/lock
lrwxrwxrwx 1 this this 20 Jan 17 17:39 .mozilla/firefox/1c43irlt.default/lock -> 192.168.0.103:+27270
```

Tested with ruby 3.0.5 and 2.7.7 on Linux 6.1.6 and firefox 109.0

Solution could be to remove the above `entry.follow_symlinks = true` line, which works but conflicts with the apparent issue the 2011 commit https://github.com/SeleniumHQ/selenium/commit/a44367ad80 was addressing (which I was unable to track down by it's number).

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'

options = Selenium::WebDriver::Firefox::Options.new
options.profile = "default"

driver = Selenium::WebDriver.for :firefox, options: options
```

### Relevant log output

```shell
irb(main):007:0> driver = Selenium::WebDriver.for :firefox, options: options
/home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:409:in `stat': No such file or directory @ rb_file_s_stat - /tmp/webdriver-rb-profil
ecopy20230121-192209-1x6dcl/lock (Errno::ENOENT)
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:409:in `file_stat'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:551:in `gather_fileinfo_from_srcpath'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:303:in `add'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:89:in `add_zip_entry'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:55:in `block (2 levels) in zip'
        from /usr/lib/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/lib/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/lib/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/lib/ruby/3.0.0/find.rb:43:in `each'
        from /usr/lib/ruby/3.0.0/find.rb:43:in `find'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:54:in `block in zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:78:in `block in with_tmp_zip'
        from /usr/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:76:in `with_tmp_zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:53:in `zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/profile_helper.rb:39:in `encoded'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:144:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:160:in `block in process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each_with_object'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:142:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:160:in `block in process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each_with_object'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:142:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:116:in `as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:322:in `block in create_bridge'
        from <internal:kernel>:90:in `tap'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver.rb:88:in `for'
        from (irb):7:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/irb-1.4.2/exe/irb:11:in `<top (required)>'
        from /usr/bin/irb:25:in `load'
        from /usr/bin/irb:25:in `<main>'
```

### Operating System

Linux

### Selenium version

Ruby 3.0.5, Ruby 2.7.7

### What are the browser(s) and version(s) where you see this issue?

firefox 109

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.30.0

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by MatzFan**
Exising profile model can now be used to instantiate FF profile

Fixes #11576

**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
It seems several files have been added, while the change applies only to a few. Can you please check and submit only the change set that was intended?

**Comment by MatzFan** [comment]
@diemol sorry I should have explained. The last 2 files are the test and functionality change. All the new files are a Firefox (v119) profile I've added to `common/profiles` (a new dir) in a dir named `0fbxm2ve.default-release`. This was copied from a fresh install on my system with one change for my test, in `prefs.js`; `user_pref("browser.aboutConfig.showWarning", false);` (the default is true). The profile is a fixture to test that the `Selenium::WebDriver::Firefox::Profile` class can be instantiated with an existing model. I've put it in `common` as I figured other language bindings may want to use the fixture.

I could try and figure out what is unnecessary for the test and trim the profile files, assuming FF doesn't need them all.

**Comment by diemol** [comment]
We are moving away from profiles and recommending to use preferences. We'll definitely not add those files that belong to a profile.

**Comment by titusfortner** [comment]
There are things that cannot be done with preferences, and I think there has been some miscommunication on what Firefox is doing and what they request users to do — https://github.com/mozilla/geckodriver/issues/1656#issuecomment-1135084240

That said, there is no way for us to know if the next version of Firefox changed the profile structure slightly and what we have would break things or need to be updated. The potential maintenance costs are too high.

**Comment by MatzFan** [comment]
Understood, I guess there are 2 choices then:

1) Ditch the profile fixture and the test and just keep the tiny change to `Selenium::WebDriver::Firefox::Profile` to fix the bug
2) Create a profile on disk (from a download of FF?) and remove it afterwards all within the test => no overhead of a fixture that needs maintaining. At least this way functionality is tested and any breaking changes Mozilla make to FF profile will at least be picked up with a breaking test.

My own view is that using an existing profile is very useful, can work with this tiny change (one word) and therefore ought to be supported and tested. If there are no objections I'll edit the PR to do 2).

**Comment by MatzFan** [comment]
Gone for option 1) for now to fix #11576. Will do new PR with a test once I figure out how to create a FF profile directory in a test.

**Review by titusfortner — APPROVED** [review]

**Comment by MatzFan** [comment]
So this now fails on Windows with 
```
 KeyError:
       key not found: "APPDATA"
     # ./rb/lib/selenium/webdriver/firefox/util.rb:30:in `fetch'
     # ./rb/lib/selenium/webdriver/firefox/util.rb:30:in `app_data_path'
     # ./rb/lib/selenium/webdriver/firefox/profiles_ini.rb:28:in `initialize'
     # ./rb/spec/integration/selenium/webdriver/firefox/profile_spec.rb:31:in `new'
     # ./rb/spec/integration/selenium/webdriver/firefox/profile_spec.rb:31:in `profile_model'
     # ./rb/spec/integration/selenium/webdriver/firefox/profile_spec.rb:28:in `block (2 levels) in <module:Firefox>'
     # ./rb/spec/integration/selenium/webdriver/firefox/profile_spec.rb:65:in `block (2 levels) in <module:Firefox>'
```
I can edit the test code to rescue this, but I'd guess this problem is CI not having the correct env vars. If that is right can someone add APPDATA to the win environment? Thx.

**Comment by titusfortner** [comment]
Weird, even this indicates it should be available: https://stackoverflow.com/questions/75669170/getting-the-appdata-roaming-folder-inside-windows-github-action

**Comment by titusfortner** [comment]
Maybe we try `LOCALAPPDATA` insteaqd?

**Comment by MatzFan** [comment]
Can't get test to pass in CI and can't spend any more time on this so have reverted to simple change to delete the 'lock' file to fix https://github.com/SeleniumHQ/selenium/issues/11576

**Comment by titusfortner** [comment]
Sorry I haven't had time to look at the failures. Nothing looks obvious for why it isn't happy 😦

**Comment by MatzFan** [comment]
No worries @titusfortner it has passed once with my final commit so the failures are intermittent ones :smile:

**Pull request merged**
