### PR TITLE
Allow methods wrapped by EventFiringWebDriver and EventFiringWebElement to  accept keyword arguments.

### PR DESCRIPTION
**Pull request by tbeadle**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by lukeis** [comment]
@tbeadle can you descibe what was broken? and ideally add a scenario so it isn't broken in the future to the tests:

https://github.com/SeleniumHQ/selenium/blob/master/py/test/selenium/webdriver/common/correct_event_firing_tests.py

**Comment by tbeadle** [comment]
@lukeis This change is to make it so that, when an event listener is used, a caller can pass arguments by name and not just by position.  I've added a unit test to demonstrate it.  I confirmed that without my change, the test fails and with it, it passes.  The Travis build failed for some reason, even though it shows that all the tests passed.  I would appreciate any insight in to why that happened.

**Comment by Dude-X** [comment]
@tbeadle This seems like a nice useful fix. Can you please rebase your changes and also sign the CLA? If the CLA option doesn't appear, I think you should just create a new PR.

**Comment by lmtierney** [comment]
@tbeadle I've updated your first comment to put the CLA checkbox back in, can you confirm you've signed the CLA and check the box?

**Comment by tbeadle** [comment]
@lmtierney I've signed the CLA and updated the comment to select the checkbox.

**Comment by lmtierney** [comment]
thanks @tbeadle

**Pull request merged**
