### PR TITLE
Feature/11686 change default ttl cli

### PR DESCRIPTION
**Pull request by iampopovich**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
According to feature request #11686  i've passed custom ttl parameter for browser and driver in CLI 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by bonigarcia — APPROVED** [review]
Looks good to me

**Comment by diemol** [comment]
@bonigarcia feel free to merge it if everthing looks fine.

**Comment by bonigarcia** [comment]
Many thanks @iampopovich!

**Comment by iampopovich** [comment]
@bonigarcia glad to be a part of project !

**Pull request merged**
