### PR TITLE
[node] Update ESLint setup

### PR DESCRIPTION
**Pull request by nschonni**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Bump to the latest versions of the linting plugins and autofix issues

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by harsha509 — APPROVED** [review]
Thank you @nschonni !

**Comment by diemol** [comment]
@nschonni, seems there is a small conflict, could you please resolve it and I can merge this right away.

**Comment by nschonni** [comment]
@diemol gave it a rebase and re-ran `npm run lint --fix` to format.
Not sure is the linting is actually being called by the CI, but that's a separate issue 😄

**Review by diemol — APPROVED** [review]
Thank you, @nschonni!

**Pull request merged**
