### PR TITLE
[grid] fix bug in downloading files by ensuring browser vendor option…

### PR DESCRIPTION
**Pull request by titusfortner**
### Description
If browser vendor options missing, merge in mutable capabilities with the capabilities set. 
I think this is better than casting the capabilities to `MutableCapabilities` to add it?

### Motivation and Context

Not all bindings create an empty browser vendor options map by default

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Where is the bug? In the absence of browser options key or the casting? In theory `ofNullable` should be handling it.

**Comment by titusfortner** [comment]
If there isn't a moz:firefoxOptions key, then we're just mutating a new hash that isn't attached to anything. Python downloading doesn't work unless another geckodriver option happens to be set.

**Review by diemol — APPROVED** [review]
Thank you for the explanation

**Comment by titusfortner** [comment]
What, the description made complete sense in my mind... 😂 

I'll fix the formatting.

**Pull request merged**
