### PR TITLE
Fix HtmlUnitWebElement.getCssValue

### PR DESCRIPTION
**Pull request by asashour**
Return correct value for colors.

### CODE REVIEW

**Comment by lukeis** [comment]
the ColorMap class seems to be a duplicate of the Colors enum. Can you not use that instead?

**Comment by asashour** [comment]
Thanks for hinting, PR updated

**Comment by asashour** [comment]
Any thing is still missing?

**Comment by lukeis** [comment]
nope, just forgot about it :)  thanks, merged as c181d392fb04c93f88be2549e2961a883221b6fb

**Comment by asashour** [comment]
Thanks a lot for your quick response.

Appreciate also looking into #799 and #809

**Pull request closed without merging**
