### PR TITLE
[py] Move all Python related files into py directory

### PR DESCRIPTION
**Pull request by davehunt**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by cgoldberg** [comment]
nice +1

**Comment by davehunt** [comment]
Landed in https://github.com/SeleniumHQ/selenium/commit/bd8ac6dbab98f0d876a879b8d015e9b5f7bbac4e

**Comment by AutomatedTester** [comment]
go commands no longer work

**Comment by davehunt** [comment]
> go commands no longer work

I believe this was a very limited targets that were broken. Anyway, they're now fixed in https://github.com/SeleniumHQ/selenium/commit/4b6a297fd1073c07275294c0785efe5fd0428e2b

**Pull request closed without merging**
