### PR TITLE
Update Closure Compiler and Closure Library to v20160208

### PR DESCRIPTION
**Pull request by Dominator008**
Update Closure Compiler and Closure Library to v20160208

Removed unnecessary test_module.js and test_module_dep.js.

Fixed compile errors.

### CODE REVIEW

**Comment by lukeis** [comment]
@jleyba can you review this?

@Dominator008 looks like you need to rebase your change

**Comment by Dominator008** [comment]
@lukeis Rebased.

**Comment by Dominator008** [comment]
@jleyba Ping?

**Comment by jleyba** [comment]
Merged in f91121d109ac34517763a465463842f5d414e9e8

**Pull request closed without merging**
