### PR TITLE
[java] remove lift related packages and dependencies

### PR DESCRIPTION
**Pull request by joerg1985**
### Description
Remove lift related packages and dependencies.

### Motivation and Context
This is the follow up PR to #12263, removing the deprecated code.

The [Wiki-Page](https://github.com/SeleniumHQ/selenium/wiki/Lift-Style-API) should be deleted.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joerg1985** [comment]
@titusfortner is it okay, when i delete the wiki page? Or is there something to consider before deleting it?

**Comment by titusfortner** [comment]
go for it

**Comment by titusfortner** [comment]
Well, actually I copied a lot of the old stuff to the legacy section of our website

**Comment by titusfortner** [comment]
If you think there's any historical value to it (but i don't think there is?)

**Comment by joerg1985** [comment]
I agree, this is nothing historical.

**Comment by chabala** [comment]
Seems I'm a little late to the party here. I was just thinking 'surely someone has already made Hamcrest matchers for working with Selenium', and found the Lift artifact. Then I spent longer trying to find out 'what is Selenium Lift?', and eventually found this issue, and #12263.

Obviously I'll always have the existing artifact in Maven to use, but if I were to advocate for the code to return from being deleted, I'd love to see a 'just the matchers' artifact with minimal dependencies beyond Hamcrest & Selenium.

**Pull request merged**
