### PR TITLE
[java] Self-signed certificate should not require certificate file

### PR DESCRIPTION
**Pull request by pujagani**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

When using Grid with `--self-signed-https` option, it throws an error that "`You must provide a certificate via --https-certificate when using --https `".  It is not required when using self-signed. The error occurred during the check at the step 
https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/security/SecretOptions.java#L44. 

The easiest solution was to remove the check however that might not be the right solution since I do not have the context of why it was added here and if/why registration secret is required for this case too.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — APPROVED** [review]

**Comment by VietND96** [comment]
@pujagani, I am just aware that in #13413 I added back the check `|| isSelfSigned()`. This mistake caused this fix to be reverted. Can you please recommit if this is a major impact? Thanks!

**Comment by pujagani** [comment]
Sure! Will do that. Appreciate your help! Thank you

**Comment by VietND96** [comment]
Thank you @pujagani !
I saw the recommit come to the trunk already. Can we consider releasing new jar package for the selenium grid together with the Python binding fix also? @diemol

**Comment by diemol** [comment]
Not really, is this urgent and needs a patch release?

**Comment by VietND96** [comment]
> Not really, is this urgent and needs a patch release?

I think not urgent, we can wait for `4.18.0`

**Pull request merged**
