### PR TITLE
turn on http keep alive while using ChromeDriver

### PR DESCRIPTION
**Pull request by awarecan**
need chrome driver 2.35 or above
fix #5758

- [X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

---
This change is [Reviewable](https://reviewable.io/reviews/seleniumhq/selenium/5759)

### CODE REVIEW

**Comment by bradharms** [comment]
Does this address the issue that ECONNREFUSED is reported when many concurrent instances are created?

**Comment by bradharms** [comment]
I confirmed that this does resolve the issue mentioned above.

**Comment by jdmerinor** [comment]
Thanks for providing this solution, this problem is killing my testing server now (I already changed my default timeout and port setting) and I can't wait for this to get merged :)

**Comment by lvsavova** [comment]
Is this released yet?

**Comment by lvsavova** [comment]
is this fixed for the Java binding?

**Pull request merged**
