### PR TITLE
[py] moved all pytest configuration settings from `pytest.ini` file to `pyproject.toml`

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
### **User description**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Moved all Pytest settings from `pytest.ini` file to `pyproject.toml`

### Motivation and Context
This avoids having to maintain a separate config file for pytest settings. All pytest configuration settings can be maintained in `pyproject.toml`

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Configuration changes

___

### **Description**
- Migrated all pytest configuration settings from `pytest.ini` to `pyproject.toml`.
- Updated Bazel build configuration to reference `pyproject.toml` instead of `pytest.ini`.
- Removed the `pytest.ini` file as it is no longer needed.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>BUILD.bazel</strong><dd><code>Update Bazel build configuration to use `pyproject.toml`</code>&nbsp; </dd></summary>
<hr>

py/BUILD.bazel

- Replaced `pytest.ini` with `pyproject.toml` in the data section.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14256/files#diff-3e8ff3a52e8e6c0b195ea328e17c50ba6d90abca1ce1624110607da20691d7a9">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pytest.ini</strong><dd><code>Remove `pytest.ini` file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/pytest.ini

- Removed the `pytest.ini` file and its contents.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14256/files#diff-3868e8b31761356967e524552b603b75fbbf7cfbdb85d8b5df1e81b553fcb080">+0/-15</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pyproject.toml</strong><dd><code>Migrate pytest settings to `pyproject.toml`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

py/pyproject.toml

<li>Added pytest configuration settings under <code>[tool.pytest.ini_options]</code>.<br> <li> Included markers for various test expectations.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium/pull/14256/files#diff-3adb340b5a499e26b04507d972c31f5cf6fc27a6d81e3f7b547bf50e90c43be3">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by diemol** [comment]
Were all tests executed? The list looks short https://github.com/SeleniumHQ/selenium/actions/runs/10141004211/job/28037337462?pr=14256#step:15:4061

**Comment by sandeepsuryaprasad** [comment]
@diemol is there any action pending from my side regarding this PR.

**Comment by diemol** [comment]
Yes, my question above. It does seem not all tests were executed. Can you please verify?

**Comment by sandeepsuryaprasad** [comment]
> Yes, my question above. It does seem not all tests were executed. Can you please verify?

All Python tests are passed. But there are some errors from .NET modules. I think this has got nothing to do with the changes that I have made.

```
(08:44:24) ERROR: Traceback (most recent call last):
	File "/home/runner/.bazel/external/rules_dotnet~/dotnet/private/transitions/tfm_transition.bzl", line 59, column 13, in _impl
		fail("Label {0} does not support the target framework: {1}".format(attr.name, incoming_tfm))
Error in fail: Label fixtures does not support the target framework: net7.0
(08:44:24) ERROR: /home/runner/work/selenium/selenium/dotnet/test/common/BUILD.bazel:35:15: Errors encountered while applying Starlark transition
(08:44:24) ERROR: /home/runner/work/selenium/selenium/dotnet/src/webdriver/BUILD.bazel: no such target '//dotnet/src/webdriver:webdriver': target 'webdriver' not declared in package 'dotnet/src/webdriver' defined by /home/runner/work/selenium/selenium/dotnet/src/webdriver/BUILD.bazel (did you mean WebDriver.cs, or IWebDriver.cs?)


(08:45:21) ERROR: /home/runner/work/selenium/selenium/dotnet/test/support/UI/BUILD.bazel:12:24: no such target '//dotnet/src/webdriver:webdriver': target 'webdriver' not declared in package 'dotnet/src/webdriver' defined by /home/runner/work/selenium/selenium/dotnet/src/webdriver/BUILD.bazel (did you mean WebDriver.cs, or IWebDriver.cs?) and referenced by '//dotnet/test/support/UI:SelectTests'

```

**Comment by diemol** [comment]
This [execution](https://github.com/SeleniumHQ/selenium/actions/runs/10321180866/job/28573458177) has around 315 python tests executed (you can search with `//py:common` and `//py:unit`). Whereas in this [execution](https://github.com/SeleniumHQ/selenium/actions/runs/10141004211/job/28037337462?pr=14256) I don't see any `//py:common` tests executed.

**Comment by sandeepsuryaprasad** [comment]
> This [execution](https://github.com/SeleniumHQ/selenium/actions/runs/10321180866/job/28573458177) has around 315 python tests executed (you can search with `//py:common` and `//py:unit`). Whereas in this [execution](https://github.com/SeleniumHQ/selenium/actions/runs/10141004211/job/28037337462?pr=14256) I don't see any `//py:common` tests executed.

Can you please re-trigger the workflow.

**Comment by sandeepsuryaprasad** [comment]
@diemol I just verified the results. All the tests have been executed and passed.

**Comment by sandeepsuryaprasad** [comment]
@diemol all test's are passing.. could you check on this one please.

**Comment by diemol** [comment]
Seems to be fine. I just want @AutomatedTester to have a look before merging.

**Review by AutomatedTester — APPROVED** [review]

**Comment by AutomatedTester** [comment]
Thanks for the PR!

**Pull request merged**
