### PR TITLE
[py] `ElementScrollBehavior` fix for ie/options 4.11.0

### LINKED ISSUE #12459: [🐛 Bug]: test/unit/selenium/webdriver/ie/test_ie_options.py::test_element_scroll_behavior fails w/ selenium-python 4.11.0
### What happened?

With `selenium-4.11.0` and git 4beab57e3f17d6f34102050dc5994e1b74c94c6b, I can reproduce the following unit test failure:

```
FAILED test/unit/selenium/webdriver/ie/test_ie_options.py::test_element_scroll_behavior - ValueError: elementScrollBehavior should be of type int
```

FWICS, the problem is that `ElementScrollBehavior` is defined as an `Enum`, while an `int` is expected. The issue can possibly be fixed by changing it to an `IntEnum` instead.

The other possibility is to change `element_scroll_behavior` to expect `Enum` but that requires more changes to the code and probably breaks backwards compatibility.

### How can we reproduce the issue?

```shell
pip install . pytest
python -m pytest -vvl test/unit
```

### Relevant log output

```shell
============================================================== FAILURES ===============================================================
____________________________________________________ test_element_scroll_behavior _____________________________________________________

opts = <selenium.webdriver.ie.options.Options object at 0x7fbde0ee1890>

    def test_element_scroll_behavior(opts):
>       opts.element_scroll_behavior = ElementScrollBehavior.BOTTOM

opts       = <selenium.webdriver.ie.options.Options object at 0x7fbde0ee1890>

test/unit/selenium/webdriver/ie/test_ie_options.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.ie.options._IeOptionsDescriptor object at 0x7fbde1100f90>
obj = <selenium.webdriver.ie.options.Options object at 0x7fbde0ee1890>, value = <ElementScrollBehavior.BOTTOM: 1>

    def __set__(self, obj, value) -> None:
        if not isinstance(value, self.expected_type):
>           raise ValueError(f"{self.name} should be of type {self.expected_type.__name__}")
E           ValueError: elementScrollBehavior should be of type int

obj        = <selenium.webdriver.ie.options.Options object at 0x7fbde0ee1890>
self       = <selenium.webdriver.ie.options._IeOptionsDescriptor object at 0x7fbde1100f90>
value      = <ElementScrollBehavior.BOTTOM: 1>

selenium/webdriver/ie/options.py:59: ValueError
```

### Operating System

Gentoo Linux

### Selenium version

Python 4.11.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by sandeepsuryaprasad**
**Thanks for contributing to Selenium!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
This fixes the issue https://github.com/SeleniumHQ/selenium/issues/12459 with `ElementScrollBehavior`

### Motivation and Context
- `ElementScrollBehavior` is an `Enum` object, but I was expecting it to be an `int`. 
-  Now I have removed `value` attribute from `ElementScrollBehavior.TOP.value` and `ElementScrollBehavior.BOTTOM.value`

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md) document.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — APPROVED** [review]

**Comment by mgorny** [comment]
Thanks for the fix but I'm afraid it doesn't solve the problem completely. For the fix to be complete, the following change is also necessary:

```diff
diff --git a/py/selenium/webdriver/ie/options.py b/py/selenium/webdriver/ie/options.py
index 34fc51f..3b0aea4 100644
--- a/py/selenium/webdriver/ie/options.py
+++ b/py/selenium/webdriver/ie/options.py
@@ -105,7 +105,7 @@ class Options(ArgOptions):
     `value`: `int` (Timeout) in milliseconds
     """
 
-    element_scroll_behavior = _IeOptionsDescriptor(ELEMENT_SCROLL_BEHAVIOR, int)
+    element_scroll_behavior = _IeOptionsDescriptor(ELEMENT_SCROLL_BEHAVIOR, Enum)
     """Gets and Sets `element_scroll_behavior`
 
     Usage
```

**Comment by diemol** [comment]
@sandeepsuryaprasad thoughts?

**Comment by sandeepsuryaprasad** [comment]
> Thanks for the fix but I'm afraid it doesn't solve the problem completely. For the fix to be complete, the following change is also necessary:
> 
> ```diff
> diff --git a/py/selenium/webdriver/ie/options.py b/py/selenium/webdriver/ie/options.py
> index 34fc51f..3b0aea4 100644
> --- a/py/selenium/webdriver/ie/options.py
> +++ b/py/selenium/webdriver/ie/options.py
> @@ -105,7 +105,7 @@ class Options(ArgOptions):
>      `value`: `int` (Timeout) in milliseconds
>      """
>  
> -    element_scroll_behavior = _IeOptionsDescriptor(ELEMENT_SCROLL_BEHAVIOR, int)
> +    element_scroll_behavior = _IeOptionsDescriptor(ELEMENT_SCROLL_BEHAVIOR, Enum)
>      """Gets and Sets `element_scroll_behavior`
>  
>      Usage
> ```

@mgorny Thank You so much for pointing this out.. I am fixing it. I am really sorry for forgetting to change the expected type .. I am fixing it right away and I will push it.

**Comment by sandeepsuryaprasad** [comment]
> @sandeepsuryaprasad thoughts?

Fixing it. Forgot to change the expected type..

**Comment by sandeepsuryaprasad** [comment]
@mgorny @diemol I have fixed this.

**Pull request merged**
