### PR TITLE
[Ruby] Fix deselecting options in <select>

### PR DESCRIPTION
**Pull request by glibas**
1. Add UnsupportedOperationError when trying
   to deselect options of non-multiseect
2. Update select_by_index, deselect_by_index to only
   select/deselect first option, since index is unique.
3. Add tests to select_spec

### CODE REVIEW

**Comment by glib-briia** [comment]
Hi @lukeis, @jimevans,

Applying the same changes as in https://github.com/SeleniumHQ/selenium/pull/1623 and https://github.com/SeleniumHQ/selenium/pull/1629 to Ruby lib. The Travis build filure seems not related to my changes. Could you please have a look?

_CLA is signed_

**Comment by glib-briia** [comment]
Hi @titusfortner ,

Just wondering if there are any news on this request, so we can finish with the issue and make select api consistent across all languages.

Thanks,
Glib

**Comment by titusfortner** [comment]
Hey sorry, I've started organizing online coding sessions with other Ruby developers to look at open Selenium issues and PRs to get more people familiar with this code base. This seemed like a really good candidate to go over with that group. We're organizing on the Ruby channel of the [Selenium Slack](https://seleniumhq.herokuapp.com/). I'd hoped to do one last week, but it got pushed off to [next week](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=ZmZpZzE2c3FqcGZiOGJudGs5NzNkNzI2cWMgd2F0aXJvcmdAbQ&tmsrc=watirorg%40gmail.com).

I know @lukeis  has been making us release every week lately, but I think we'll be safe to get this fixed up next week. Thanks again for the submission. :)

**Comment by glib-briia** [comment]
Hi,
Thank you for the info, I would definitely be interested in participation in your sessions. Looking forward to it!

**Comment by p0deje** [comment]
Merged in https://github.com/SeleniumHQ/selenium/commit/1e9d89fbd78c74364cfa2ce28600209d3a44acc1

**Pull request closed without merging**
